# RT-Thread building script for JerryScript RT port

from building import *

cwd = GetCurrentDir()
src = [cwd + '/port.c']
src += [cwd + '/jerry_util.c']
src += [cwd + '/jerry_console.c']
src += [cwd + '/jerry_utf8.c']
CPPPATH = [cwd]

group = DefineGroup('JerryScriptPort', src, depend = ['BUILD_USING_RTK_GUI'], CPPPATH = CPPPATH)

Return('group')
