#Import('rt_config')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

src += ['fal.c']
src += ['fal_flash.c']
src += ['fal_partition.c']

CPPPATH = ['../inc']

group = DefineGroup('fal', src, depend = [''], CPPPATH = CPPPATH)

Return('group')