#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   A1_BIN                                  (void *)(resource_root + 0x00000b38)
#define   A2_BIN                                  (void *)(resource_root + 0x00008b78)
#define   A3_BIN                                  (void *)(resource_root + 0x00010bb8)
#define   A4_BIN                                  (void *)(resource_root + 0x00018bf8)
#define   A5_BIN                                  (void *)(resource_root + 0x00020c38)
#define   A6_BIN                                  (void *)(resource_root + 0x00028c78)
#define   B1_BIN                                  (void *)(resource_root + 0x00030cb8)
#define   B1_RLE_BIN                              (void *)(resource_root + 0x0003a7f8)
#define   B2_BIN                                  (void *)(resource_root + 0x00042078)
#define   B2_RLE_BIN                              (void *)(resource_root + 0x0004bbb8)
#define   B3_BIN                                  (void *)(resource_root + 0x000518f8)
#define   B3_RLE_BIN                              (void *)(resource_root + 0x0005b438)
#define   B4_BIN                                  (void *)(resource_root + 0x0005dfb8)
#define   B4_RLE_BIN                              (void *)(resource_root + 0x00067af8)
#define   B5_BIN                                  (void *)(resource_root + 0x0006ad78)
#define   B5_RLE_BIN                              (void *)(resource_root + 0x000748b8)
#define   B6_BIN                                  (void *)(resource_root + 0x000768b8)
#define   B6_RLE_BIN                              (void *)(resource_root + 0x000803f8)
#define   OVAL_BIN                                (void *)(resource_root + 0x000827f8)
#define   CLOCK_BASE_BIN                          (void *)(resource_root + 0x00082ab8)
#define   ICON_ANSWER_BIN                         (void *)(resource_root + 0x00086778)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(resource_root + 0x00087678)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x00088378)
#define   ICON_BACKSPACE_BIN                      (void *)(resource_root + 0x00088638)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(resource_root + 0x00088cf8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(resource_root + 0x00089ab8)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(resource_root + 0x0008a878)
#define   ICON_BUDS_OFF_BIN                       (void *)(resource_root + 0x0008b638)
#define   ICON_BUDS_ON_BIN                        (void *)(resource_root + 0x0008c538)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(resource_root + 0x0008d3f8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(resource_root + 0x0008e2f8)
#define   ICON_BUTTON_ON_BIN                      (void *)(resource_root + 0x0008ea38)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x0008f3b8)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(resource_root + 0x00090eb8)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(resource_root + 0x00091d38)
#define   ICON_CALL_HISTORY_BIN                   (void *)(resource_root + 0x00092bf8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(resource_root + 0x00093ab8)
#define   ICON_CALL_TOUCH_BIN                     (void *)(resource_root + 0x000949b8)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(resource_root + 0x000963b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(resource_root + 0x000964b8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(resource_root + 0x000965b8)
#define   ICON_CALLER_BIN                         (void *)(resource_root + 0x00096678)
#define   ICON_CALLER_LARGE_BIN                   (void *)(resource_root + 0x000984b8)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x0009b478)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(resource_root + 0x0009beb8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(resource_root + 0x0009c8f8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(resource_root + 0x0009ca38)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(resource_root + 0x0009cfb8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(resource_root + 0x0009d6b8)
#define   ICON_CONFIRM_BIN                        (void *)(resource_root + 0x0009de78)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(resource_root + 0x0009e838)
#define   ICON_CONTACTCS_BIN                      (void *)(resource_root + 0x0009f1f8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(resource_root + 0x000a0c38)
#define   ICON_DIAL_0_BIN                         (void *)(resource_root + 0x000a2538)
#define   ICON_DIAL_1_BIN                         (void *)(resource_root + 0x000a2ab8)
#define   ICON_DIAL_2_BIN                         (void *)(resource_root + 0x000a2ef8)
#define   ICON_DIAL_3_BIN                         (void *)(resource_root + 0x000a3338)
#define   ICON_DIAL_4_BIN                         (void *)(resource_root + 0x000a3778)
#define   ICON_DIAL_5_BIN                         (void *)(resource_root + 0x000a3bb8)
#define   ICON_DIAL_6_BIN                         (void *)(resource_root + 0x000a3ff8)
#define   ICON_DIAL_7_BIN                         (void *)(resource_root + 0x000a44f8)
#define   ICON_DIAL_8_BIN                         (void *)(resource_root + 0x000a4978)
#define   ICON_DIAL_9_BIN                         (void *)(resource_root + 0x000a4eb8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(resource_root + 0x000a5478)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(resource_root + 0x000a5b78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(resource_root + 0x000a6278)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(resource_root + 0x000a66b8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(resource_root + 0x000a6af8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(resource_root + 0x000a7078)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(resource_root + 0x000a74b8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(resource_root + 0x000a79b8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(resource_root + 0x000a8138)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(resource_root + 0x000a8678)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x000a8c38)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(resource_root + 0x000a96b8)
#define   ICON_FAIL_BIN                           (void *)(resource_root + 0x000aa178)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(resource_root + 0x000ab3b8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(resource_root + 0x000ab9f8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(resource_root + 0x000ac038)
#define   ICON_FOLDER_BIN                         (void *)(resource_root + 0x000ac678)
#define   ICON_HANGUP_BIN                         (void *)(resource_root + 0x000ac838)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(resource_root + 0x000ad878)
#define   ICON_LOADING_BIN                        (void *)(resource_root + 0x000ae638)
#define   ICON_MENU_BIN                           (void *)(resource_root + 0x000aeef8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(resource_root + 0x000af7f8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(resource_root + 0x000b01f8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(resource_root + 0x000b0bb8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(resource_root + 0x000b16f8)
#define   ICON_MORE_OFF_BIN                       (void *)(resource_root + 0x000b21b8)
#define   ICON_MORE_ON_BIN                        (void *)(resource_root + 0x000b2bf8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(resource_root + 0x000b3638)
#define   ICON_PHONE_OFF_BIN                      (void *)(resource_root + 0x000b4078)
#define   ICON_PHONE_ON_BIN                       (void *)(resource_root + 0x000b4bb8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(resource_root + 0x000b56b8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(resource_root + 0x000b61f8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(resource_root + 0x000b6378)
#define   ICON_PROCESS_NODE_BIN                   (void *)(resource_root + 0x000b64b8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(resource_root + 0x000b68b8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(resource_root + 0x000b6b78)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(resource_root + 0x000b7838)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(resource_root + 0x000b8538)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(resource_root + 0x000bb6b8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(resource_root + 0x000be738)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(resource_root + 0x000c17b8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(resource_root + 0x000c19b8)
#define   ICON_RECORD_START_BIN                   (void *)(resource_root + 0x000c4938)
#define   ICON_RECORD_STOP_BIN                    (void *)(resource_root + 0x000c7778)
#define   ICON_SEEKBAR_BIN                        (void *)(resource_root + 0x000c9f78)
#define   ICON_SEEKBAR1_BIN                       (void *)(resource_root + 0x000ca5f8)
#define   ICON_SEEKBAR2_BIN                       (void *)(resource_root + 0x000ca778)
#define   ICON_SONG_BUDS_BIN                      (void *)(resource_root + 0x000cadb8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(resource_root + 0x000cb1b8)
#define   ICON_SONG_NEXT_BIN                      (void *)(resource_root + 0x000cb5f8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(resource_root + 0x000cbcf8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(resource_root + 0x000cc3f8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(resource_root + 0x000ccd78)
#define   ICON_SONG_PHONE_BIN                     (void *)(resource_root + 0x000cd6f8)
#define   ICON_SONG_PLAY_BIN                      (void *)(resource_root + 0x000cda38)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(resource_root + 0x000ce278)
#define   ICON_SONG_PREV_BIN                      (void *)(resource_root + 0x000ceab8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(resource_root + 0x000cf178)
#define   ICON_SONG_SPK_BIN                       (void *)(resource_root + 0x000cf838)
#define   ICON_SUCCESS_BIN                        (void *)(resource_root + 0x000cfbb8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(resource_root + 0x000d0ff8)
#define   ICON_SWITCH_ON_BIN                      (void *)(resource_root + 0x000d17b8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(resource_root + 0x000d1fb8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(resource_root + 0x000d24b8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(resource_root + 0x000d29b8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(resource_root + 0x000d2ef8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(resource_root + 0x000d3338)
#define   ICON_TRASH_BIN                          (void *)(resource_root + 0x000d39f8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(resource_root + 0x000d41f8)
#define   ICON_UP_SLIDE_BIN                       (void *)(resource_root + 0x000d49f8)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x000d54f8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(resource_root + 0x000d5838)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(resource_root + 0x000d59b8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(resource_root + 0x000d5ab8)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(resource_root + 0x000d5b78)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(resource_root + 0x000d5c78)
#define   ICON_VOLUME_CALL_BIN                    (void *)(resource_root + 0x000d5db8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(resource_root + 0x000d66f8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(resource_root + 0x000d6f38)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(resource_root + 0x000d74b8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(resource_root + 0x000d7a38)
#define   ICON_VOLUME_UP_BIN                      (void *)(resource_root + 0x000d7eb8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(resource_root + 0x000d85f8)
#define   PATH2_BIN                               (void *)(resource_root + 0x000d8d38)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(resource_root + 0x000d8e38)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(resource_root + 0x000d8ff8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(resource_root + 0x000d9078)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(resource_root + 0x000d9138)
#define   RECT1_BIN                               (void *)(resource_root + 0x000d92f8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(resource_root + 0x000d97f8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(resource_root + 0x000da9f8)
#define   WATCH_BASE_GREY_BIN                     (void *)(resource_root + 0x000dc578)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(resource_root + 0x000deff8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(resource_root + 0x000e19f8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(resource_root + 0x000e2f78)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(resource_root + 0x000e33b8)
#define   BUTTON_CAL_BLK_BIN                      (void *)(resource_root + 0x000e3878)
#define   BUTTON_CAL_BLK_LONG_BIN                 (void *)(resource_root + 0x000e6178)
#define   BUTTON_CAL_DEL_BIN                      (void *)(resource_root + 0x000eb578)
#define   BUTTON_CAL_GRAY_BIN                     (void *)(resource_root + 0x000ebcb8)
#define   BUTTON_CAL_GRAY_LONG_BIN                (void *)(resource_root + 0x000ee5b8)
#define   BUTTON_CAL_ORG_BIN                      (void *)(resource_root + 0x000f39b8)
#define   BUTTON_CAL_YELLOW_BIN                   (void *)(resource_root + 0x000f62b8)
#define   HAND_BIN                                (void *)(resource_root + 0x000f8bf8)
#define   TICKMARK_BIN                            (void *)(resource_root + 0x000f91b8)
#define   BACK14_BIN                              (void *)(resource_root + 0x00101ef8)
#define   BACK15_BIN                              (void *)(resource_root + 0x0012c0f8)
#define   KEHUZHOUQI_BIN                          (void *)(resource_root + 0x00157fb8)
#define   RECT12_BIN                              (void *)(resource_root + 0x00159138)
#define   RECT13_BIN                              (void *)(resource_root + 0x001598f8)
#define   RECT14_BIN                              (void *)(resource_root + 0x0015a3f8)
#define   RECT15_BIN                              (void *)(resource_root + 0x0015af78)
#define   ARIAL_SIZE48_BITS4_FONT_BIN             (void *)(resource_root + 0x0015b7b8)
#define   ARIALBD_SIZE16_BITS4_FONT_BIN           (void *)(resource_root + 0x00181b38)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x001a4cf8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(resource_root + 0x001d7b78)
#define   SIMKAI_SIZE32_BITS2_FONT_BIN            (void *)(resource_root + 0x004bb538)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(resource_root + 0x00a379f8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(resource_root + 0x00a3bf38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(resource_root + 0x00a3de38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(resource_root + 0x00a415b8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(resource_root + 0x00a45b38)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(resource_root + 0x00a47ab8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(resource_root + 0x00a4a1f8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(resource_root + 0x00a63638)
#define   FRUIT_NINJA_GAMEOVER_BIN                (void *)(resource_root + 0x00a6aef8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(resource_root + 0x00a76c38)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(resource_root + 0x00a798f8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(resource_root + 0x00a7b6b8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(resource_root + 0x00a7d338)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(resource_root + 0x00a823f8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(resource_root + 0x00a861b8)
#define   HEARTRATE04_BIN                         (void *)(resource_root + 0x00a89678)
#define   HEARTRATE08_BIN                         (void *)(resource_root + 0x00a91678)
#define   HEARTRATE12_BIN                         (void *)(resource_root + 0x00a99938)
#define   HEARTRATE16_BIN                         (void *)(resource_root + 0x00aa1af8)
#define   HEARTRATE20_BIN                         (void *)(resource_root + 0x00aa9af8)
#define   HEARTRATE24_BIN                         (void *)(resource_root + 0x00ab1c78)
#define   HEARTRATE28_BIN                         (void *)(resource_root + 0x00ab9e78)
#define   HEARTRATE32_BIN                         (void *)(resource_root + 0x00ac2278)
#define   HEARTRATE36_BIN                         (void *)(resource_root + 0x00acabf8)
#define   HEARTRATE40_BIN                         (void *)(resource_root + 0x00ad3ab8)
#define   HEARTRATE44_BIN                         (void *)(resource_root + 0x00adca78)
#define   HEARTRATE48_BIN                         (void *)(resource_root + 0x00ae59f8)
#define   I4500009_BIN                            (void *)(resource_root + 0x00aee8b8)
#define   I4500011_BIN                            (void *)(resource_root + 0x00af02f8)
#define   I4500015_BIN                            (void *)(resource_root + 0x00af19b8)
#define   I4500020_BIN                            (void *)(resource_root + 0x00af3438)
#define   I4500028_BIN                            (void *)(resource_root + 0x00af52b8)
#define   I4500034_BIN                            (void *)(resource_root + 0x00af6bb8)
#define   I4500035_BIN                            (void *)(resource_root + 0x00af8878)
#define   I4500037_BIN                            (void *)(resource_root + 0x00af9ff8)
#define   I4500040_BIN                            (void *)(resource_root + 0x00afc2f8)
#define   I4500042_BIN                            (void *)(resource_root + 0x00afddf8)
#define   I4500047_BIN                            (void *)(resource_root + 0x00affdb8)
#define   I4500049_BIN                            (void *)(resource_root + 0x00b013f8)
#define   I4500052_BIN                            (void *)(resource_root + 0x00b02d78)
#define   I4500064_BIN                            (void *)(resource_root + 0x00b04878)
#define   RESIZE_PY                               (void *)(resource_root + 0x00b05f78)
#define   BUTTERFLY_ANTENNA_BIN                   (void *)(resource_root + 0x00b07078)
#define   BUTTERFLY_BODYHALF_BIN                  (void *)(resource_root + 0x00b079b8)
#define   BUTTERFLY_SWINGDOWN_BIN                 (void *)(resource_root + 0x00b088f8)
#define   BUTTERFLY_SWINGUP_BIN                   (void *)(resource_root + 0x00b11938)
#define   BUTTERFLY_DOT0_BIN                      (void *)(resource_root + 0x00b1a978)
#define   BUTTERFLY_DOT1_BIN                      (void *)(resource_root + 0x00b1d9b8)
#define   COMMON_FIXED_BIN                        (void *)(resource_root + 0x00b1e5f8)
#define   COMMON_FONT32_BIN                       (void *)(resource_root + 0x00b1f8f8)
#define   COMMON_FONT96_BIN                       (void *)(resource_root + 0x00b2fe38)
#define   COMMON_UNFIXED_BIN                      (void *)(resource_root + 0x00b47e78)
#define   DCLOCK_BACKGROUND_BIN                   (void *)(resource_root + 0x00b49178)
#define   DCLOCK_BACKGROUND_SHADOW_BIN            (void *)(resource_root + 0x00b591b8)
#define   DCLOCK_BATTERY_BIN                      (void *)(resource_root + 0x00b691f8)
#define   DCLOCK_BG_0_BIN                         (void *)(resource_root + 0x00b6d138)
#define   DCLOCK_BG_1_BIN                         (void *)(resource_root + 0x00b71c78)
#define   DCLOCK_BG_2_BIN                         (void *)(resource_root + 0x00b767b8)
#define   DCLOCK_BG_3_BIN                         (void *)(resource_root + 0x00b7b2f8)
#define   DCLOCK_BG_4_BIN                         (void *)(resource_root + 0x00b7fe38)
#define   DCLOCK_BG_5_BIN                         (void *)(resource_root + 0x00b84978)
#define   DCLOCK_BG_6_BIN                         (void *)(resource_root + 0x00b894b8)
#define   DCLOCK_BG_7_BIN                         (void *)(resource_root + 0x00b8dff8)
#define   DCLOCK_BG_8_BIN                         (void *)(resource_root + 0x00b92b38)
#define   DCLOCK_BG_9_BIN                         (void *)(resource_root + 0x00b97678)
#define   DCLOCK_BG_WEEK0_BIN                     (void *)(resource_root + 0x00b9c1b8)
#define   DCLOCK_BG_WEEK1_BIN                     (void *)(resource_root + 0x00ba0cf8)
#define   DCLOCK_BG_WEEK2_BIN                     (void *)(resource_root + 0x00ba5838)
#define   DCLOCK_BG_WEEK3_BIN                     (void *)(resource_root + 0x00baa378)
#define   DCLOCK_BG_WEEK4_BIN                     (void *)(resource_root + 0x00baeeb8)
#define   DCLOCK_BG_WEEK5_BIN                     (void *)(resource_root + 0x00bb39f8)
#define   DCLOCK_BG_WEEK6_BIN                     (void *)(resource_root + 0x00bb8538)
#define   DCLOCK_DATE_BIN                         (void *)(resource_root + 0x00bbd078)
#define   DCLOCK_FG_0_BIN                         (void *)(resource_root + 0x00bc0fb8)
#define   DCLOCK_FG_1_BIN                         (void *)(resource_root + 0x00bc5af8)
#define   DCLOCK_FG_2_BIN                         (void *)(resource_root + 0x00bca638)
#define   DCLOCK_FG_3_BIN                         (void *)(resource_root + 0x00bcf178)
#define   DCLOCK_FG_4_BIN                         (void *)(resource_root + 0x00bd3cb8)
#define   DCLOCK_FG_5_BIN                         (void *)(resource_root + 0x00bd87f8)
#define   DCLOCK_FG_6_BIN                         (void *)(resource_root + 0x00bdd338)
#define   DCLOCK_FG_7_BIN                         (void *)(resource_root + 0x00be1e78)
#define   DCLOCK_FG_8_BIN                         (void *)(resource_root + 0x00be69b8)
#define   DCLOCK_FG_9_BIN                         (void *)(resource_root + 0x00beb4f8)
#define   DCLOCK_FG_WEEK0_BIN                     (void *)(resource_root + 0x00bf0038)
#define   DCLOCK_FG_WEEK1_BIN                     (void *)(resource_root + 0x00bf4b78)
#define   DCLOCK_FG_WEEK2_BIN                     (void *)(resource_root + 0x00bf96b8)
#define   DCLOCK_FG_WEEK3_BIN                     (void *)(resource_root + 0x00bfe1f8)
#define   DCLOCK_FG_WEEK4_BIN                     (void *)(resource_root + 0x00c02d38)
#define   DCLOCK_FG_WEEK5_BIN                     (void *)(resource_root + 0x00c07878)
#define   DCLOCK_FG_WEEK6_BIN                     (void *)(resource_root + 0x00c0c3b8)
#define   DCLOCK_STEPS_BIN                        (void *)(resource_root + 0x00c10ef8)
#define   DCLOCK_TIME_BIN                         (void *)(resource_root + 0x00c14e38)
#define   DCLOCK_BTY_BIN                          (void *)(resource_root + 0x00c18d78)
#define   EBOX_FACE0_BIN                          (void *)(resource_root + 0x00c18e78)
#define   EBOX_LIGHT0_BIN                         (void *)(resource_root + 0x00c24eb8)
#define   EBOX_LIGHT1_BIN                         (void *)(resource_root + 0x00c27ef8)
#define   FLOWERFALL_BACKGROUND_BIN               (void *)(resource_root + 0x00c29f38)
#define   FLOWERFALL_BRANCH01_BIN                 (void *)(resource_root + 0x00c93ff8)
#define   FLOWERFALL_BRANCH02_BIN                 (void *)(resource_root + 0x00ccaef8)
#define   FLOWERFALL_DOT01_BIN                    (void *)(resource_root + 0x00cdabf8)
#define   FLOWERFALL_DOT02_BIN                    (void *)(resource_root + 0x00cdb838)
#define   FLOWERFALL_LEAF01_BIN                   (void *)(resource_root + 0x00cdc478)
#define   FLOWERFALL_LEAF02_BIN                   (void *)(resource_root + 0x00cdd0b8)
#define   FLOWERFALL_LEAF03_BIN                   (void *)(resource_root + 0x00cddcf8)
#define   FLOWERFALL_LEAF04_BIN                   (void *)(resource_root + 0x00cde938)
#define   FLOWERFALL_LEAF05_BIN                   (void *)(resource_root + 0x00cdf578)
#define   FLOWERFALL_LEAF06_BIN                   (void *)(resource_root + 0x00ce01b8)
#define   NOTIFICATIONS_ENVELOPE_BIN              (void *)(resource_root + 0x00ce0df8)
#define   NOTIFICATIONS_ENVELOPEBG_BIN            (void *)(resource_root + 0x00d0bb78)
#define   NOTIFICATIONS_FLAPCLOSE_BIN             (void *)(resource_root + 0x00d14738)
#define   NOTIFICATIONS_FLAPOPEN_BIN              (void *)(resource_root + 0x00d25e78)
#define   NOTIFICATIONS_LETTERBG_BIN              (void *)(resource_root + 0x00d369b8)
#define   PRSIM_ACTIVITYGOAL_BIN                  (void *)(resource_root + 0x00d628f8)
#define   PRSIM_ALIPAY_BIN                        (void *)(resource_root + 0x00d7eb38)
#define   PRSIM_BACKBOARD_BIN                     (void *)(resource_root + 0x00d9ad78)
#define   PRSIM_CLOCK_BIN                         (void *)(resource_root + 0x00db6fb8)
#define   PRSIM_HEARTRATE_BIN                     (void *)(resource_root + 0x00dd31f8)
#define   PRSIM_SIDE_BIN                          (void *)(resource_root + 0x00def438)
#define   PRSIM_SLEEP_BIN                         (void *)(resource_root + 0x00df0078)
#define   PRSIM_WEATHER_BIN                       (void *)(resource_root + 0x00e0c2b8)
#define   TRANS_LIGHT_BIN                         (void *)(resource_root + 0x00e284f8)
#define   TRANS_SIDE_BIN                          (void *)(resource_root + 0x00ebf4b8)
#define   WINDMILL_BACKGROUND_BIN                 (void *)(resource_root + 0x00ec5f78)
#define   WINDMILL_BUBBLE_BIN                     (void *)(resource_root + 0x00f30038)
#define   WINDMILL_FACE_BIN                       (void *)(resource_root + 0x00f36c78)
#define   WINDMILL_FACEBLUE_BIN                   (void *)(resource_root + 0x00f39fb8)
#define   WINDMILL_FACEBLUE_SHADOW_BIN            (void *)(resource_root + 0x00f3cff8)
#define   WINDMILL_FACEGREEN_BIN                  (void *)(resource_root + 0x00f40038)
#define   WINDMILL_FACEGREEN_SHADOW_BIN           (void *)(resource_root + 0x00f43078)
#define   WINDMILL_FACERED_BIN                    (void *)(resource_root + 0x00f460b8)
#define   WINDMILL_FACERED_SHADOW_BIN             (void *)(resource_root + 0x00f490f8)
#define   WINDMILL_FACEYELLOW_BIN                 (void *)(resource_root + 0x00f4c138)
#define   WINDMILL_FACEYELLOW_SHADOW_BIN          (void *)(resource_root + 0x00f4f178)
#define   WINDMILL_NAIL_BIN                       (void *)(resource_root + 0x00f521b8)
#define   WINDMILL_STICK_BIN                      (void *)(resource_root + 0x00f52df8)
#define   SOCCER_ACTIVITIES_BIN                   (void *)(resource_root + 0x00f53a38)
#define   SOCCER_ALARM_BIN                        (void *)(resource_root + 0x00f58578)
#define   SOCCER_ALIPAY_BIN                       (void *)(resource_root + 0x00f5d0b8)
#define   SOCCER_BOARD_BIN                        (void *)(resource_root + 0x00f61bf8)
#define   SOCCER_CARDS_BIN                        (void *)(resource_root + 0x00f6dc38)
#define   SOCCER_COMPASS_BIN                      (void *)(resource_root + 0x00f72778)
#define   SOCCER_COUNTDOWN_BIN                    (void *)(resource_root + 0x00f772b8)
#define   SOCCER_FINDPHONE_BIN                    (void *)(resource_root + 0x00f7bdf8)
#define   SOCCER_GOAL_BIN                         (void *)(resource_root + 0x00f80938)
#define   SOCCER_HEARTRATE_BIN                    (void *)(resource_root + 0x00f85478)
#define   SOCCER_HOME_BIN                         (void *)(resource_root + 0x00f89fb8)
#define   SOCCER_MUSIC_BIN                        (void *)(resource_root + 0x00f8eaf8)
#define   SOCCER_SCHEDULE_BIN                     (void *)(resource_root + 0x00f93638)
#define   SOCCER_SETTINGS_BIN                     (void *)(resource_root + 0x00f98178)
#define   SOCCER_SLEEP_BIN                        (void *)(resource_root + 0x00f9ccb8)
#define   SOCCER_SPO2_BIN                         (void *)(resource_root + 0x00fa17f8)
#define   SOCCER_SPORTS_BIN                       (void *)(resource_root + 0x00fa6338)
#define   SOCCER_STAR_BIN                         (void *)(resource_root + 0x00faae78)
#define   SOCCER_STOPWATCH_BIN                    (void *)(resource_root + 0x00faceb8)
#define   SOCCER_STRESS_BIN                       (void *)(resource_root + 0x00fb19f8)
#define   SOCCER_TEMPERATURE_BIN                  (void *)(resource_root + 0x00fb6538)
#define   SOCCER_WEATHER_BIN                      (void *)(resource_root + 0x00fbb078)
#define   TEXT0_BIN                               (void *)(resource_root + 0x00fbfcb8)
#define   TEXT1_BIN                               (void *)(resource_root + 0x00fc0178)
#define   TEXT2_BIN                               (void *)(resource_root + 0x00fc0338)
#define   TEXT3_BIN                               (void *)(resource_root + 0x00fc07f8)
#define   TEXT4_BIN                               (void *)(resource_root + 0x00fc0c78)
#define   TEXT5_BIN                               (void *)(resource_root + 0x00fc1138)
#define   TEXT6_BIN                               (void *)(resource_root + 0x00fc15b8)
#define   TEXT7_BIN                               (void *)(resource_root + 0x00fc19f8)
#define   TEXT8_BIN                               (void *)(resource_root + 0x00fc1e78)
#define   TEXT9_BIN                               (void *)(resource_root + 0x00fc2338)
#define   TEXTAM_BIN                              (void *)(resource_root + 0x00fc2778)
#define   TEXTDIAN_BIN                            (void *)(resource_root + 0x00fc3578)
#define   TEXTMAOHAO_BIN                          (void *)(resource_root + 0x00fc35f8)
#define   TEXTPM_BIN                              (void *)(resource_root + 0x00fc36f8)
#define   TEXTXIEGANG_BIN                         (void *)(resource_root + 0x00fc42f8)
#define   PATH04_BIN                              (void *)(resource_root + 0x00fc47f8)
#define   PATH05_BIN                              (void *)(resource_root + 0x00fc4b78)
#define   PATH07_BIN                              (void *)(resource_root + 0x00fc5078)
#define   PATH08_BIN                              (void *)(resource_root + 0x00fc57b8)
#define   PATH09_BIN                              (void *)(resource_root + 0x00fc5f38)
#define   PATH11_BIN                              (void *)(resource_root + 0x00fc66f8)
#define   PATH12_BIN                              (void *)(resource_root + 0x00fc6ef8)
#define   PATH14_BIN                              (void *)(resource_root + 0x00fc7738)
#define   PATH15_BIN                              (void *)(resource_root + 0x00fc7f78)
#define   PATH16_BIN                              (void *)(resource_root + 0x00fc87f8)
#define   PATH18_BIN                              (void *)(resource_root + 0x00fc9078)
#define   PATH19_BIN                              (void *)(resource_root + 0x00fc98f8)
#define   PATH20_BIN                              (void *)(resource_root + 0x00fca1b8)
#define   PATH22_BIN                              (void *)(resource_root + 0x00fcaa78)
#define   PATH23_BIN                              (void *)(resource_root + 0x00fcb338)
#define   PATH24_BIN                              (void *)(resource_root + 0x00fcbc38)
#define   PATH25_BIN                              (void *)(resource_root + 0x00fcc538)
#define   BAR1_BIN                                (void *)(resource_root + 0x00fccf78)
#define   BAR10_BIN                               (void *)(resource_root + 0x00fceef8)
#define   BAR13_BIN                               (void *)(resource_root + 0x00fd0e78)
#define   BAR16_BIN                               (void *)(resource_root + 0x00fd2df8)
#define   BAR19_BIN                               (void *)(resource_root + 0x00fd4d78)
#define   BAR22_BIN                               (void *)(resource_root + 0x00fd6cf8)
#define   BAR25_BIN                               (void *)(resource_root + 0x00fd8c78)
#define   BAR28_BIN                               (void *)(resource_root + 0x00fdabf8)
#define   BAR31_BIN                               (void *)(resource_root + 0x00fdcb78)
#define   BAR34_BIN                               (void *)(resource_root + 0x00fdeaf8)
#define   BAR38_BIN                               (void *)(resource_root + 0x00fe0a78)
#define   BAR39_BIN                               (void *)(resource_root + 0x00fe29f8)
#define   BAR4_BIN                                (void *)(resource_root + 0x00fe4978)
#define   BAR40_BIN                               (void *)(resource_root + 0x00fe68f8)
#define   BAR41_BIN                               (void *)(resource_root + 0x00fe8878)
#define   BAR42_BIN                               (void *)(resource_root + 0x00fea7f8)
#define   BAR43_BIN                               (void *)(resource_root + 0x00fec778)
#define   BAR7_BIN                                (void *)(resource_root + 0x00fee6f8)
#define   BARS1_BIN                               (void *)(resource_root + 0x00ff0678)
#define   BARS2_BIN                               (void *)(resource_root + 0x00ff25f8)
#define   BARS3_BIN                               (void *)(resource_root + 0x00ff4578)
#define   BATTERY_BIN                             (void *)(resource_root + 0x00ff6538)
#define   BATTERYHL_BIN                           (void *)(resource_root + 0x00ff7ff8)
#define   BLUETOOTH_BIN                           (void *)(resource_root + 0x00ff9af8)
#define   BLUETOOTHHL_BIN                         (void *)(resource_root + 0x00ffc078)
#define   MYDEVICE_BIN                            (void *)(resource_root + 0x00ffe5f8)
#define   MYDEVICEHL_BIN                          (void *)(resource_root + 0x01000538)
#define   PAUSEBUTTON_BIN                         (void *)(resource_root + 0x010024f8)
#define   STARTBUTTON_BIN                         (void *)(resource_root + 0x010152f8)
#define   STOPBUTTON_BIN                          (void *)(resource_root + 0x010280f8)
#define   STOPWATCHMASK_BIN                       (void *)(resource_root + 0x0103aef8)
#define   VOLUME_BIN                              (void *)(resource_root + 0x01046838)
#define   VOLUME2_BIN                             (void *)(resource_root + 0x01049178)
#define   VOLUMEBACK_BIN                          (void *)(resource_root + 0x010497b8)
#define   VOLUMEBACK2_BIN                         (void *)(resource_root + 0x0104bff8)

#else
#define   A1_BIN                                  (void *)(0x04400b38)
#define   A2_BIN                                  (void *)(0x04408b78)
#define   A3_BIN                                  (void *)(0x04410bb8)
#define   A4_BIN                                  (void *)(0x04418bf8)
#define   A5_BIN                                  (void *)(0x04420c38)
#define   A6_BIN                                  (void *)(0x04428c78)
#define   B1_BIN                                  (void *)(0x04430cb8)
#define   B1_RLE_BIN                              (void *)(0x0443a7f8)
#define   B2_BIN                                  (void *)(0x04442078)
#define   B2_RLE_BIN                              (void *)(0x0444bbb8)
#define   B3_BIN                                  (void *)(0x044518f8)
#define   B3_RLE_BIN                              (void *)(0x0445b438)
#define   B4_BIN                                  (void *)(0x0445dfb8)
#define   B4_RLE_BIN                              (void *)(0x04467af8)
#define   B5_BIN                                  (void *)(0x0446ad78)
#define   B5_RLE_BIN                              (void *)(0x044748b8)
#define   B6_BIN                                  (void *)(0x044768b8)
#define   B6_RLE_BIN                              (void *)(0x044803f8)
#define   OVAL_BIN                                (void *)(0x044827f8)
#define   CLOCK_BASE_BIN                          (void *)(0x04482ab8)
#define   ICON_ANSWER_BIN                         (void *)(0x04486778)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(0x04487678)
#define   ICON_BACK_BIN                           (void *)(0x04488378)
#define   ICON_BACKSPACE_BIN                      (void *)(0x04488638)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(0x04488cf8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(0x04489ab8)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(0x0448a878)
#define   ICON_BUDS_OFF_BIN                       (void *)(0x0448b638)
#define   ICON_BUDS_ON_BIN                        (void *)(0x0448c538)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(0x0448d3f8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(0x0448e2f8)
#define   ICON_BUTTON_ON_BIN                      (void *)(0x0448ea38)
#define   ICON_CALL_BIN                           (void *)(0x0448f3b8)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(0x04490eb8)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(0x04491d38)
#define   ICON_CALL_HISTORY_BIN                   (void *)(0x04492bf8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(0x04493ab8)
#define   ICON_CALL_TOUCH_BIN                     (void *)(0x044949b8)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(0x044963b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(0x044964b8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(0x044965b8)
#define   ICON_CALLER_BIN                         (void *)(0x04496678)
#define   ICON_CALLER_LARGE_BIN                   (void *)(0x044984b8)
#define   ICON_CANCEL_BIN                         (void *)(0x0449b478)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(0x0449beb8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(0x0449c8f8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(0x0449ca38)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(0x0449cfb8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(0x0449d6b8)
#define   ICON_CONFIRM_BIN                        (void *)(0x0449de78)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(0x0449e838)
#define   ICON_CONTACTCS_BIN                      (void *)(0x0449f1f8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(0x044a0c38)
#define   ICON_DIAL_0_BIN                         (void *)(0x044a2538)
#define   ICON_DIAL_1_BIN                         (void *)(0x044a2ab8)
#define   ICON_DIAL_2_BIN                         (void *)(0x044a2ef8)
#define   ICON_DIAL_3_BIN                         (void *)(0x044a3338)
#define   ICON_DIAL_4_BIN                         (void *)(0x044a3778)
#define   ICON_DIAL_5_BIN                         (void *)(0x044a3bb8)
#define   ICON_DIAL_6_BIN                         (void *)(0x044a3ff8)
#define   ICON_DIAL_7_BIN                         (void *)(0x044a44f8)
#define   ICON_DIAL_8_BIN                         (void *)(0x044a4978)
#define   ICON_DIAL_9_BIN                         (void *)(0x044a4eb8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(0x044a5478)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(0x044a5b78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(0x044a6278)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(0x044a66b8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(0x044a6af8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(0x044a7078)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(0x044a74b8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(0x044a79b8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(0x044a8138)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(0x044a8678)
#define   ICON_DISCONNECT_BIN                     (void *)(0x044a8c38)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(0x044a96b8)
#define   ICON_FAIL_BIN                           (void *)(0x044aa178)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(0x044ab3b8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(0x044ab9f8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(0x044ac038)
#define   ICON_FOLDER_BIN                         (void *)(0x044ac678)
#define   ICON_HANGUP_BIN                         (void *)(0x044ac838)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(0x044ad878)
#define   ICON_LOADING_BIN                        (void *)(0x044ae638)
#define   ICON_MENU_BIN                           (void *)(0x044aeef8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(0x044af7f8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(0x044b01f8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(0x044b0bb8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(0x044b16f8)
#define   ICON_MORE_OFF_BIN                       (void *)(0x044b21b8)
#define   ICON_MORE_ON_BIN                        (void *)(0x044b2bf8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(0x044b3638)
#define   ICON_PHONE_OFF_BIN                      (void *)(0x044b4078)
#define   ICON_PHONE_ON_BIN                       (void *)(0x044b4bb8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(0x044b56b8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(0x044b61f8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(0x044b6378)
#define   ICON_PROCESS_NODE_BIN                   (void *)(0x044b64b8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(0x044b68b8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(0x044b6b78)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(0x044b7838)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(0x044b8538)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(0x044bb6b8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(0x044be738)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(0x044c17b8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(0x044c19b8)
#define   ICON_RECORD_START_BIN                   (void *)(0x044c4938)
#define   ICON_RECORD_STOP_BIN                    (void *)(0x044c7778)
#define   ICON_SEEKBAR_BIN                        (void *)(0x044c9f78)
#define   ICON_SEEKBAR1_BIN                       (void *)(0x044ca5f8)
#define   ICON_SEEKBAR2_BIN                       (void *)(0x044ca778)
#define   ICON_SONG_BUDS_BIN                      (void *)(0x044cadb8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(0x044cb1b8)
#define   ICON_SONG_NEXT_BIN                      (void *)(0x044cb5f8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(0x044cbcf8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(0x044cc3f8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(0x044ccd78)
#define   ICON_SONG_PHONE_BIN                     (void *)(0x044cd6f8)
#define   ICON_SONG_PLAY_BIN                      (void *)(0x044cda38)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(0x044ce278)
#define   ICON_SONG_PREV_BIN                      (void *)(0x044ceab8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(0x044cf178)
#define   ICON_SONG_SPK_BIN                       (void *)(0x044cf838)
#define   ICON_SUCCESS_BIN                        (void *)(0x044cfbb8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(0x044d0ff8)
#define   ICON_SWITCH_ON_BIN                      (void *)(0x044d17b8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(0x044d1fb8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(0x044d24b8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(0x044d29b8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(0x044d2ef8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(0x044d3338)
#define   ICON_TRASH_BIN                          (void *)(0x044d39f8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(0x044d41f8)
#define   ICON_UP_SLIDE_BIN                       (void *)(0x044d49f8)
#define   ICON_VOLUME_BIN                         (void *)(0x044d54f8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(0x044d5838)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(0x044d59b8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(0x044d5ab8)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(0x044d5b78)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(0x044d5c78)
#define   ICON_VOLUME_CALL_BIN                    (void *)(0x044d5db8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(0x044d66f8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(0x044d6f38)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(0x044d74b8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(0x044d7a38)
#define   ICON_VOLUME_UP_BIN                      (void *)(0x044d7eb8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(0x044d85f8)
#define   PATH2_BIN                               (void *)(0x044d8d38)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(0x044d8e38)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(0x044d8ff8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(0x044d9078)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(0x044d9138)
#define   RECT1_BIN                               (void *)(0x044d92f8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(0x044d97f8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(0x044da9f8)
#define   WATCH_BASE_GREY_BIN                     (void *)(0x044dc578)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(0x044deff8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(0x044e19f8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(0x044e2f78)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(0x044e33b8)
#define   BUTTON_CAL_BLK_BIN                      (void *)(0x044e3878)
#define   BUTTON_CAL_BLK_LONG_BIN                 (void *)(0x044e6178)
#define   BUTTON_CAL_DEL_BIN                      (void *)(0x044eb578)
#define   BUTTON_CAL_GRAY_BIN                     (void *)(0x044ebcb8)
#define   BUTTON_CAL_GRAY_LONG_BIN                (void *)(0x044ee5b8)
#define   BUTTON_CAL_ORG_BIN                      (void *)(0x044f39b8)
#define   BUTTON_CAL_YELLOW_BIN                   (void *)(0x044f62b8)
#define   HAND_BIN                                (void *)(0x044f8bf8)
#define   TICKMARK_BIN                            (void *)(0x044f91b8)
#define   BACK14_BIN                              (void *)(0x04501ef8)
#define   BACK15_BIN                              (void *)(0x0452c0f8)
#define   KEHUZHOUQI_BIN                          (void *)(0x04557fb8)
#define   RECT12_BIN                              (void *)(0x04559138)
#define   RECT13_BIN                              (void *)(0x045598f8)
#define   RECT14_BIN                              (void *)(0x0455a3f8)
#define   RECT15_BIN                              (void *)(0x0455af78)
#define   ARIAL_SIZE48_BITS4_FONT_BIN             (void *)(0x0455b7b8)
#define   ARIALBD_SIZE16_BITS4_FONT_BIN           (void *)(0x04581b38)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x045a4cf8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(0x045d7b78)
#define   SIMKAI_SIZE32_BITS2_FONT_BIN            (void *)(0x048bb538)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(0x04e379f8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(0x04e3bf38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(0x04e3de38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(0x04e415b8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(0x04e45b38)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(0x04e47ab8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(0x04e4a1f8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(0x04e63638)
#define   FRUIT_NINJA_GAMEOVER_BIN                (void *)(0x04e6aef8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(0x04e76c38)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(0x04e798f8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(0x04e7b6b8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(0x04e7d338)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(0x04e823f8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(0x04e861b8)
#define   HEARTRATE04_BIN                         (void *)(0x04e89678)
#define   HEARTRATE08_BIN                         (void *)(0x04e91678)
#define   HEARTRATE12_BIN                         (void *)(0x04e99938)
#define   HEARTRATE16_BIN                         (void *)(0x04ea1af8)
#define   HEARTRATE20_BIN                         (void *)(0x04ea9af8)
#define   HEARTRATE24_BIN                         (void *)(0x04eb1c78)
#define   HEARTRATE28_BIN                         (void *)(0x04eb9e78)
#define   HEARTRATE32_BIN                         (void *)(0x04ec2278)
#define   HEARTRATE36_BIN                         (void *)(0x04ecabf8)
#define   HEARTRATE40_BIN                         (void *)(0x04ed3ab8)
#define   HEARTRATE44_BIN                         (void *)(0x04edca78)
#define   HEARTRATE48_BIN                         (void *)(0x04ee59f8)
#define   I4500009_BIN                            (void *)(0x04eee8b8)
#define   I4500011_BIN                            (void *)(0x04ef02f8)
#define   I4500015_BIN                            (void *)(0x04ef19b8)
#define   I4500020_BIN                            (void *)(0x04ef3438)
#define   I4500028_BIN                            (void *)(0x04ef52b8)
#define   I4500034_BIN                            (void *)(0x04ef6bb8)
#define   I4500035_BIN                            (void *)(0x04ef8878)
#define   I4500037_BIN                            (void *)(0x04ef9ff8)
#define   I4500040_BIN                            (void *)(0x04efc2f8)
#define   I4500042_BIN                            (void *)(0x04efddf8)
#define   I4500047_BIN                            (void *)(0x04effdb8)
#define   I4500049_BIN                            (void *)(0x04f013f8)
#define   I4500052_BIN                            (void *)(0x04f02d78)
#define   I4500064_BIN                            (void *)(0x04f04878)
#define   RESIZE_PY                               (void *)(0x04f05f78)
#define   BUTTERFLY_ANTENNA_BIN                   (void *)(0x04f07078)
#define   BUTTERFLY_BODYHALF_BIN                  (void *)(0x04f079b8)
#define   BUTTERFLY_SWINGDOWN_BIN                 (void *)(0x04f088f8)
#define   BUTTERFLY_SWINGUP_BIN                   (void *)(0x04f11938)
#define   BUTTERFLY_DOT0_BIN                      (void *)(0x04f1a978)
#define   BUTTERFLY_DOT1_BIN                      (void *)(0x04f1d9b8)
#define   COMMON_FIXED_BIN                        (void *)(0x04f1e5f8)
#define   COMMON_FONT32_BIN                       (void *)(0x04f1f8f8)
#define   COMMON_FONT96_BIN                       (void *)(0x04f2fe38)
#define   COMMON_UNFIXED_BIN                      (void *)(0x04f47e78)
#define   DCLOCK_BACKGROUND_BIN                   (void *)(0x04f49178)
#define   DCLOCK_BACKGROUND_SHADOW_BIN            (void *)(0x04f591b8)
#define   DCLOCK_BATTERY_BIN                      (void *)(0x04f691f8)
#define   DCLOCK_BG_0_BIN                         (void *)(0x04f6d138)
#define   DCLOCK_BG_1_BIN                         (void *)(0x04f71c78)
#define   DCLOCK_BG_2_BIN                         (void *)(0x04f767b8)
#define   DCLOCK_BG_3_BIN                         (void *)(0x04f7b2f8)
#define   DCLOCK_BG_4_BIN                         (void *)(0x04f7fe38)
#define   DCLOCK_BG_5_BIN                         (void *)(0x04f84978)
#define   DCLOCK_BG_6_BIN                         (void *)(0x04f894b8)
#define   DCLOCK_BG_7_BIN                         (void *)(0x04f8dff8)
#define   DCLOCK_BG_8_BIN                         (void *)(0x04f92b38)
#define   DCLOCK_BG_9_BIN                         (void *)(0x04f97678)
#define   DCLOCK_BG_WEEK0_BIN                     (void *)(0x04f9c1b8)
#define   DCLOCK_BG_WEEK1_BIN                     (void *)(0x04fa0cf8)
#define   DCLOCK_BG_WEEK2_BIN                     (void *)(0x04fa5838)
#define   DCLOCK_BG_WEEK3_BIN                     (void *)(0x04faa378)
#define   DCLOCK_BG_WEEK4_BIN                     (void *)(0x04faeeb8)
#define   DCLOCK_BG_WEEK5_BIN                     (void *)(0x04fb39f8)
#define   DCLOCK_BG_WEEK6_BIN                     (void *)(0x04fb8538)
#define   DCLOCK_DATE_BIN                         (void *)(0x04fbd078)
#define   DCLOCK_FG_0_BIN                         (void *)(0x04fc0fb8)
#define   DCLOCK_FG_1_BIN                         (void *)(0x04fc5af8)
#define   DCLOCK_FG_2_BIN                         (void *)(0x04fca638)
#define   DCLOCK_FG_3_BIN                         (void *)(0x04fcf178)
#define   DCLOCK_FG_4_BIN                         (void *)(0x04fd3cb8)
#define   DCLOCK_FG_5_BIN                         (void *)(0x04fd87f8)
#define   DCLOCK_FG_6_BIN                         (void *)(0x04fdd338)
#define   DCLOCK_FG_7_BIN                         (void *)(0x04fe1e78)
#define   DCLOCK_FG_8_BIN                         (void *)(0x04fe69b8)
#define   DCLOCK_FG_9_BIN                         (void *)(0x04feb4f8)
#define   DCLOCK_FG_WEEK0_BIN                     (void *)(0x04ff0038)
#define   DCLOCK_FG_WEEK1_BIN                     (void *)(0x04ff4b78)
#define   DCLOCK_FG_WEEK2_BIN                     (void *)(0x04ff96b8)
#define   DCLOCK_FG_WEEK3_BIN                     (void *)(0x04ffe1f8)
#define   DCLOCK_FG_WEEK4_BIN                     (void *)(0x05002d38)
#define   DCLOCK_FG_WEEK5_BIN                     (void *)(0x05007878)
#define   DCLOCK_FG_WEEK6_BIN                     (void *)(0x0500c3b8)
#define   DCLOCK_STEPS_BIN                        (void *)(0x05010ef8)
#define   DCLOCK_TIME_BIN                         (void *)(0x05014e38)
#define   DCLOCK_BTY_BIN                          (void *)(0x05018d78)
#define   EBOX_FACE0_BIN                          (void *)(0x05018e78)
#define   EBOX_LIGHT0_BIN                         (void *)(0x05024eb8)
#define   EBOX_LIGHT1_BIN                         (void *)(0x05027ef8)
#define   FLOWERFALL_BACKGROUND_BIN               (void *)(0x05029f38)
#define   FLOWERFALL_BRANCH01_BIN                 (void *)(0x05093ff8)
#define   FLOWERFALL_BRANCH02_BIN                 (void *)(0x050caef8)
#define   FLOWERFALL_DOT01_BIN                    (void *)(0x050dabf8)
#define   FLOWERFALL_DOT02_BIN                    (void *)(0x050db838)
#define   FLOWERFALL_LEAF01_BIN                   (void *)(0x050dc478)
#define   FLOWERFALL_LEAF02_BIN                   (void *)(0x050dd0b8)
#define   FLOWERFALL_LEAF03_BIN                   (void *)(0x050ddcf8)
#define   FLOWERFALL_LEAF04_BIN                   (void *)(0x050de938)
#define   FLOWERFALL_LEAF05_BIN                   (void *)(0x050df578)
#define   FLOWERFALL_LEAF06_BIN                   (void *)(0x050e01b8)
#define   NOTIFICATIONS_ENVELOPE_BIN              (void *)(0x050e0df8)
#define   NOTIFICATIONS_ENVELOPEBG_BIN            (void *)(0x0510bb78)
#define   NOTIFICATIONS_FLAPCLOSE_BIN             (void *)(0x05114738)
#define   NOTIFICATIONS_FLAPOPEN_BIN              (void *)(0x05125e78)
#define   NOTIFICATIONS_LETTERBG_BIN              (void *)(0x051369b8)
#define   PRSIM_ACTIVITYGOAL_BIN                  (void *)(0x051628f8)
#define   PRSIM_ALIPAY_BIN                        (void *)(0x0517eb38)
#define   PRSIM_BACKBOARD_BIN                     (void *)(0x0519ad78)
#define   PRSIM_CLOCK_BIN                         (void *)(0x051b6fb8)
#define   PRSIM_HEARTRATE_BIN                     (void *)(0x051d31f8)
#define   PRSIM_SIDE_BIN                          (void *)(0x051ef438)
#define   PRSIM_SLEEP_BIN                         (void *)(0x051f0078)
#define   PRSIM_WEATHER_BIN                       (void *)(0x0520c2b8)
#define   TRANS_LIGHT_BIN                         (void *)(0x052284f8)
#define   TRANS_SIDE_BIN                          (void *)(0x052bf4b8)
#define   WINDMILL_BACKGROUND_BIN                 (void *)(0x052c5f78)
#define   WINDMILL_BUBBLE_BIN                     (void *)(0x05330038)
#define   WINDMILL_FACE_BIN                       (void *)(0x05336c78)
#define   WINDMILL_FACEBLUE_BIN                   (void *)(0x05339fb8)
#define   WINDMILL_FACEBLUE_SHADOW_BIN            (void *)(0x0533cff8)
#define   WINDMILL_FACEGREEN_BIN                  (void *)(0x05340038)
#define   WINDMILL_FACEGREEN_SHADOW_BIN           (void *)(0x05343078)
#define   WINDMILL_FACERED_BIN                    (void *)(0x053460b8)
#define   WINDMILL_FACERED_SHADOW_BIN             (void *)(0x053490f8)
#define   WINDMILL_FACEYELLOW_BIN                 (void *)(0x0534c138)
#define   WINDMILL_FACEYELLOW_SHADOW_BIN          (void *)(0x0534f178)
#define   WINDMILL_NAIL_BIN                       (void *)(0x053521b8)
#define   WINDMILL_STICK_BIN                      (void *)(0x05352df8)
#define   SOCCER_ACTIVITIES_BIN                   (void *)(0x05353a38)
#define   SOCCER_ALARM_BIN                        (void *)(0x05358578)
#define   SOCCER_ALIPAY_BIN                       (void *)(0x0535d0b8)
#define   SOCCER_BOARD_BIN                        (void *)(0x05361bf8)
#define   SOCCER_CARDS_BIN                        (void *)(0x0536dc38)
#define   SOCCER_COMPASS_BIN                      (void *)(0x05372778)
#define   SOCCER_COUNTDOWN_BIN                    (void *)(0x053772b8)
#define   SOCCER_FINDPHONE_BIN                    (void *)(0x0537bdf8)
#define   SOCCER_GOAL_BIN                         (void *)(0x05380938)
#define   SOCCER_HEARTRATE_BIN                    (void *)(0x05385478)
#define   SOCCER_HOME_BIN                         (void *)(0x05389fb8)
#define   SOCCER_MUSIC_BIN                        (void *)(0x0538eaf8)
#define   SOCCER_SCHEDULE_BIN                     (void *)(0x05393638)
#define   SOCCER_SETTINGS_BIN                     (void *)(0x05398178)
#define   SOCCER_SLEEP_BIN                        (void *)(0x0539ccb8)
#define   SOCCER_SPO2_BIN                         (void *)(0x053a17f8)
#define   SOCCER_SPORTS_BIN                       (void *)(0x053a6338)
#define   SOCCER_STAR_BIN                         (void *)(0x053aae78)
#define   SOCCER_STOPWATCH_BIN                    (void *)(0x053aceb8)
#define   SOCCER_STRESS_BIN                       (void *)(0x053b19f8)
#define   SOCCER_TEMPERATURE_BIN                  (void *)(0x053b6538)
#define   SOCCER_WEATHER_BIN                      (void *)(0x053bb078)
#define   TEXT0_BIN                               (void *)(0x053bfcb8)
#define   TEXT1_BIN                               (void *)(0x053c0178)
#define   TEXT2_BIN                               (void *)(0x053c0338)
#define   TEXT3_BIN                               (void *)(0x053c07f8)
#define   TEXT4_BIN                               (void *)(0x053c0c78)
#define   TEXT5_BIN                               (void *)(0x053c1138)
#define   TEXT6_BIN                               (void *)(0x053c15b8)
#define   TEXT7_BIN                               (void *)(0x053c19f8)
#define   TEXT8_BIN                               (void *)(0x053c1e78)
#define   TEXT9_BIN                               (void *)(0x053c2338)
#define   TEXTAM_BIN                              (void *)(0x053c2778)
#define   TEXTDIAN_BIN                            (void *)(0x053c3578)
#define   TEXTMAOHAO_BIN                          (void *)(0x053c35f8)
#define   TEXTPM_BIN                              (void *)(0x053c36f8)
#define   TEXTXIEGANG_BIN                         (void *)(0x053c42f8)
#define   PATH04_BIN                              (void *)(0x053c47f8)
#define   PATH05_BIN                              (void *)(0x053c4b78)
#define   PATH07_BIN                              (void *)(0x053c5078)
#define   PATH08_BIN                              (void *)(0x053c57b8)
#define   PATH09_BIN                              (void *)(0x053c5f38)
#define   PATH11_BIN                              (void *)(0x053c66f8)
#define   PATH12_BIN                              (void *)(0x053c6ef8)
#define   PATH14_BIN                              (void *)(0x053c7738)
#define   PATH15_BIN                              (void *)(0x053c7f78)
#define   PATH16_BIN                              (void *)(0x053c87f8)
#define   PATH18_BIN                              (void *)(0x053c9078)
#define   PATH19_BIN                              (void *)(0x053c98f8)
#define   PATH20_BIN                              (void *)(0x053ca1b8)
#define   PATH22_BIN                              (void *)(0x053caa78)
#define   PATH23_BIN                              (void *)(0x053cb338)
#define   PATH24_BIN                              (void *)(0x053cbc38)
#define   PATH25_BIN                              (void *)(0x053cc538)
#define   BAR1_BIN                                (void *)(0x053ccf78)
#define   BAR10_BIN                               (void *)(0x053ceef8)
#define   BAR13_BIN                               (void *)(0x053d0e78)
#define   BAR16_BIN                               (void *)(0x053d2df8)
#define   BAR19_BIN                               (void *)(0x053d4d78)
#define   BAR22_BIN                               (void *)(0x053d6cf8)
#define   BAR25_BIN                               (void *)(0x053d8c78)
#define   BAR28_BIN                               (void *)(0x053dabf8)
#define   BAR31_BIN                               (void *)(0x053dcb78)
#define   BAR34_BIN                               (void *)(0x053deaf8)
#define   BAR38_BIN                               (void *)(0x053e0a78)
#define   BAR39_BIN                               (void *)(0x053e29f8)
#define   BAR4_BIN                                (void *)(0x053e4978)
#define   BAR40_BIN                               (void *)(0x053e68f8)
#define   BAR41_BIN                               (void *)(0x053e8878)
#define   BAR42_BIN                               (void *)(0x053ea7f8)
#define   BAR43_BIN                               (void *)(0x053ec778)
#define   BAR7_BIN                                (void *)(0x053ee6f8)
#define   BARS1_BIN                               (void *)(0x053f0678)
#define   BARS2_BIN                               (void *)(0x053f25f8)
#define   BARS3_BIN                               (void *)(0x053f4578)
#define   BATTERY_BIN                             (void *)(0x053f6538)
#define   BATTERYHL_BIN                           (void *)(0x053f7ff8)
#define   BLUETOOTH_BIN                           (void *)(0x053f9af8)
#define   BLUETOOTHHL_BIN                         (void *)(0x053fc078)
#define   MYDEVICE_BIN                            (void *)(0x053fe5f8)
#define   MYDEVICEHL_BIN                          (void *)(0x05400538)
#define   PAUSEBUTTON_BIN                         (void *)(0x054024f8)
#define   STARTBUTTON_BIN                         (void *)(0x054152f8)
#define   STOPBUTTON_BIN                          (void *)(0x054280f8)
#define   STOPWATCHMASK_BIN                       (void *)(0x0543aef8)
#define   VOLUME_BIN                              (void *)(0x05446838)
#define   VOLUME2_BIN                             (void *)(0x05449178)
#define   VOLUMEBACK_BIN                          (void *)(0x054497b8)
#define   VOLUMEBACK2_BIN                         (void *)(0x0544bff8)

#endif
