#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   A1_BIN                                  (void *)(resource_root + 0x00000af8)
#define   A2_BIN                                  (void *)(resource_root + 0x00008b38)
#define   A3_BIN                                  (void *)(resource_root + 0x00010b78)
#define   A4_BIN                                  (void *)(resource_root + 0x00018bb8)
#define   A5_BIN                                  (void *)(resource_root + 0x00020bf8)
#define   A6_BIN                                  (void *)(resource_root + 0x00028c38)
#define   B1_BIN                                  (void *)(resource_root + 0x00030c78)
#define   B1_RLE_BIN                              (void *)(resource_root + 0x0003a7b8)
#define   B2_BIN                                  (void *)(resource_root + 0x00042038)
#define   B2_RLE_BIN                              (void *)(resource_root + 0x0004bb78)
#define   B3_BIN                                  (void *)(resource_root + 0x000518b8)
#define   B3_RLE_BIN                              (void *)(resource_root + 0x0005b3f8)
#define   B4_BIN                                  (void *)(resource_root + 0x0005df78)
#define   B4_RLE_BIN                              (void *)(resource_root + 0x00067ab8)
#define   B5_BIN                                  (void *)(resource_root + 0x0006ad38)
#define   B5_RLE_BIN                              (void *)(resource_root + 0x00074878)
#define   B6_BIN                                  (void *)(resource_root + 0x00076878)
#define   B6_RLE_BIN                              (void *)(resource_root + 0x000803b8)
#define   OVAL_BIN                                (void *)(resource_root + 0x000827b8)
#define   CLOCK_BASE_BIN                          (void *)(resource_root + 0x00082a78)
#define   ICON_ANSWER_BIN                         (void *)(resource_root + 0x00086738)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(resource_root + 0x00087638)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x00088338)
#define   ICON_BACKSPACE_BIN                      (void *)(resource_root + 0x000885f8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(resource_root + 0x00088cb8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(resource_root + 0x00089a78)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(resource_root + 0x0008a838)
#define   ICON_BUDS_OFF_BIN                       (void *)(resource_root + 0x0008b5f8)
#define   ICON_BUDS_ON_BIN                        (void *)(resource_root + 0x0008c4f8)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(resource_root + 0x0008d3b8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(resource_root + 0x0008e2b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(resource_root + 0x0008e9f8)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x0008f378)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(resource_root + 0x00090e78)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(resource_root + 0x00091cf8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(resource_root + 0x00092bb8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(resource_root + 0x00093a78)
#define   ICON_CALL_TOUCH_BIN                     (void *)(resource_root + 0x00094978)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(resource_root + 0x00096378)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(resource_root + 0x00096478)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(resource_root + 0x00096578)
#define   ICON_CALLER_BIN                         (void *)(resource_root + 0x00096638)
#define   ICON_CALLER_LARGE_BIN                   (void *)(resource_root + 0x00098478)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x0009b438)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(resource_root + 0x0009be78)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(resource_root + 0x0009c8b8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(resource_root + 0x0009c9f8)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(resource_root + 0x0009cf78)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(resource_root + 0x0009d678)
#define   ICON_CONFIRM_BIN                        (void *)(resource_root + 0x0009de38)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(resource_root + 0x0009e7f8)
#define   ICON_CONTACTCS_BIN                      (void *)(resource_root + 0x0009f1b8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(resource_root + 0x000a0bf8)
#define   ICON_DIAL_0_BIN                         (void *)(resource_root + 0x000a24f8)
#define   ICON_DIAL_1_BIN                         (void *)(resource_root + 0x000a2a78)
#define   ICON_DIAL_2_BIN                         (void *)(resource_root + 0x000a2eb8)
#define   ICON_DIAL_3_BIN                         (void *)(resource_root + 0x000a32f8)
#define   ICON_DIAL_4_BIN                         (void *)(resource_root + 0x000a3738)
#define   ICON_DIAL_5_BIN                         (void *)(resource_root + 0x000a3b78)
#define   ICON_DIAL_6_BIN                         (void *)(resource_root + 0x000a3fb8)
#define   ICON_DIAL_7_BIN                         (void *)(resource_root + 0x000a44b8)
#define   ICON_DIAL_8_BIN                         (void *)(resource_root + 0x000a4938)
#define   ICON_DIAL_9_BIN                         (void *)(resource_root + 0x000a4e78)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(resource_root + 0x000a5438)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(resource_root + 0x000a5b38)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(resource_root + 0x000a6238)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(resource_root + 0x000a6678)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(resource_root + 0x000a6ab8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(resource_root + 0x000a7038)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(resource_root + 0x000a7478)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(resource_root + 0x000a7978)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(resource_root + 0x000a80f8)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(resource_root + 0x000a8638)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x000a8bf8)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(resource_root + 0x000a9678)
#define   ICON_FAIL_BIN                           (void *)(resource_root + 0x000aa138)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(resource_root + 0x000ab378)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(resource_root + 0x000ab9b8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(resource_root + 0x000abff8)
#define   ICON_FOLDER_BIN                         (void *)(resource_root + 0x000ac638)
#define   ICON_HANGUP_BIN                         (void *)(resource_root + 0x000ac7f8)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(resource_root + 0x000ad838)
#define   ICON_LOADING_BIN                        (void *)(resource_root + 0x000ae5f8)
#define   ICON_MENU_BIN                           (void *)(resource_root + 0x000aeeb8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(resource_root + 0x000af7b8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(resource_root + 0x000b01b8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(resource_root + 0x000b0b78)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(resource_root + 0x000b16b8)
#define   ICON_MORE_OFF_BIN                       (void *)(resource_root + 0x000b2178)
#define   ICON_MORE_ON_BIN                        (void *)(resource_root + 0x000b2bb8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(resource_root + 0x000b35f8)
#define   ICON_PHONE_OFF_BIN                      (void *)(resource_root + 0x000b4038)
#define   ICON_PHONE_ON_BIN                       (void *)(resource_root + 0x000b4b78)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(resource_root + 0x000b5678)
#define   ICON_PROCESS_BAR_BIN                    (void *)(resource_root + 0x000b61b8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(resource_root + 0x000b6338)
#define   ICON_PROCESS_NODE_BIN                   (void *)(resource_root + 0x000b6478)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(resource_root + 0x000b6878)
#define   ICON_RECORD_DELETE_BIN                  (void *)(resource_root + 0x000b6b38)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(resource_root + 0x000b77f8)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(resource_root + 0x000b84f8)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(resource_root + 0x000bb678)
#define   ICON_RECORD_PLAY_BIN                    (void *)(resource_root + 0x000be6f8)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(resource_root + 0x000c1778)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(resource_root + 0x000c1978)
#define   ICON_RECORD_START_BIN                   (void *)(resource_root + 0x000c48f8)
#define   ICON_RECORD_STOP_BIN                    (void *)(resource_root + 0x000c7738)
#define   ICON_SEEKBAR_BIN                        (void *)(resource_root + 0x000c9f38)
#define   ICON_SEEKBAR1_BIN                       (void *)(resource_root + 0x000ca5b8)
#define   ICON_SEEKBAR2_BIN                       (void *)(resource_root + 0x000ca738)
#define   ICON_SONG_BUDS_BIN                      (void *)(resource_root + 0x000cad78)
#define   ICON_SONG_LOCAL_BIN                     (void *)(resource_root + 0x000cb178)
#define   ICON_SONG_NEXT_BIN                      (void *)(resource_root + 0x000cb5b8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(resource_root + 0x000cbcb8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(resource_root + 0x000cc3b8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(resource_root + 0x000ccd38)
#define   ICON_SONG_PHONE_BIN                     (void *)(resource_root + 0x000cd6b8)
#define   ICON_SONG_PLAY_BIN                      (void *)(resource_root + 0x000cd9f8)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(resource_root + 0x000ce238)
#define   ICON_SONG_PREV_BIN                      (void *)(resource_root + 0x000cea78)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(resource_root + 0x000cf138)
#define   ICON_SONG_SPK_BIN                       (void *)(resource_root + 0x000cf7f8)
#define   ICON_SUCCESS_BIN                        (void *)(resource_root + 0x000cfb78)
#define   ICON_SWITCH_OFF_BIN                     (void *)(resource_root + 0x000d0fb8)
#define   ICON_SWITCH_ON_BIN                      (void *)(resource_root + 0x000d1778)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(resource_root + 0x000d1f78)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(resource_root + 0x000d2478)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(resource_root + 0x000d2978)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(resource_root + 0x000d2eb8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(resource_root + 0x000d32f8)
#define   ICON_TRASH_BIN                          (void *)(resource_root + 0x000d39b8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(resource_root + 0x000d41b8)
#define   ICON_UP_SLIDE_BIN                       (void *)(resource_root + 0x000d49b8)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x000d54b8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(resource_root + 0x000d57f8)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(resource_root + 0x000d5978)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(resource_root + 0x000d5a78)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(resource_root + 0x000d5b38)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(resource_root + 0x000d5c38)
#define   ICON_VOLUME_CALL_BIN                    (void *)(resource_root + 0x000d5d78)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(resource_root + 0x000d66b8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(resource_root + 0x000d6ef8)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(resource_root + 0x000d7478)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(resource_root + 0x000d79f8)
#define   ICON_VOLUME_UP_BIN                      (void *)(resource_root + 0x000d7e78)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(resource_root + 0x000d85b8)
#define   PATH2_BIN                               (void *)(resource_root + 0x000d8cf8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(resource_root + 0x000d8df8)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(resource_root + 0x000d8fb8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(resource_root + 0x000d9038)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(resource_root + 0x000d90f8)
#define   RECT1_BIN                               (void *)(resource_root + 0x000d92b8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(resource_root + 0x000d97b8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(resource_root + 0x000da9b8)
#define   WATCH_BASE_GREY_BIN                     (void *)(resource_root + 0x000dc538)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(resource_root + 0x000defb8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(resource_root + 0x000e19b8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(resource_root + 0x000e2f38)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(resource_root + 0x000e3378)
#define   HAND_BIN                                (void *)(resource_root + 0x000e37b8)
#define   TICKMARK_BIN                            (void *)(resource_root + 0x000e3d78)
#define   BACK14_BIN                              (void *)(resource_root + 0x000ecab8)
#define   BACK15_BIN                              (void *)(resource_root + 0x00116cb8)
#define   KEHUZHOUQI_BIN                          (void *)(resource_root + 0x00142b78)
#define   RECT12_BIN                              (void *)(resource_root + 0x00143cf8)
#define   RECT13_BIN                              (void *)(resource_root + 0x001444b8)
#define   RECT14_BIN                              (void *)(resource_root + 0x00144fb8)
#define   RECT15_BIN                              (void *)(resource_root + 0x00145b38)
#define   ARIAL_SIZE48_BITS4_FONT_BIN             (void *)(resource_root + 0x00146338)
#define   ARIALBD_SIZE16_BITS4_FONT_BIN           (void *)(resource_root + 0x0016c6b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(resource_root + 0x0018f878)
#define   SIMKAI_SIZE32_BITS2_FONT_BIN            (void *)(resource_root + 0x00473238)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(resource_root + 0x009ef6f8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(resource_root + 0x009f3c38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(resource_root + 0x009f5b38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(resource_root + 0x009f92b8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(resource_root + 0x009fd838)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(resource_root + 0x009ff7b8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(resource_root + 0x00a01ef8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(resource_root + 0x00a1b338)
#define   FRUIT_NINJA_GAMEOVER_BIN                (void *)(resource_root + 0x00a22bf8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(resource_root + 0x00a2e938)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(resource_root + 0x00a315f8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(resource_root + 0x00a333b8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(resource_root + 0x00a35038)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(resource_root + 0x00a3a0f8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(resource_root + 0x00a3deb8)
#define   HEARTRATE04_BIN                         (void *)(resource_root + 0x00a41378)
#define   HEARTRATE08_BIN                         (void *)(resource_root + 0x00a49378)
#define   HEARTRATE12_BIN                         (void *)(resource_root + 0x00a51638)
#define   HEARTRATE16_BIN                         (void *)(resource_root + 0x00a597f8)
#define   HEARTRATE20_BIN                         (void *)(resource_root + 0x00a617f8)
#define   HEARTRATE24_BIN                         (void *)(resource_root + 0x00a69978)
#define   HEARTRATE28_BIN                         (void *)(resource_root + 0x00a71b78)
#define   HEARTRATE32_BIN                         (void *)(resource_root + 0x00a79f78)
#define   HEARTRATE36_BIN                         (void *)(resource_root + 0x00a828f8)
#define   HEARTRATE40_BIN                         (void *)(resource_root + 0x00a8b7b8)
#define   HEARTRATE44_BIN                         (void *)(resource_root + 0x00a94778)
#define   HEARTRATE48_BIN                         (void *)(resource_root + 0x00a9d6f8)
#define   I4500009_BIN                            (void *)(resource_root + 0x00aa65b8)
#define   I4500011_BIN                            (void *)(resource_root + 0x00aa7ff8)
#define   I4500015_BIN                            (void *)(resource_root + 0x00aa96b8)
#define   I4500020_BIN                            (void *)(resource_root + 0x00aab138)
#define   I4500028_BIN                            (void *)(resource_root + 0x00aacfb8)
#define   I4500034_BIN                            (void *)(resource_root + 0x00aae8b8)
#define   I4500035_BIN                            (void *)(resource_root + 0x00ab0578)
#define   I4500037_BIN                            (void *)(resource_root + 0x00ab1cf8)
#define   I4500040_BIN                            (void *)(resource_root + 0x00ab3ff8)
#define   I4500042_BIN                            (void *)(resource_root + 0x00ab5af8)
#define   I4500047_BIN                            (void *)(resource_root + 0x00ab7ab8)
#define   I4500049_BIN                            (void *)(resource_root + 0x00ab90f8)
#define   I4500052_BIN                            (void *)(resource_root + 0x00abaa78)
#define   I4500064_BIN                            (void *)(resource_root + 0x00abc578)
#define   RESIZE_PY                               (void *)(resource_root + 0x00abdc78)
#define   BUTTERFLY_ANTENNA_BIN                   (void *)(resource_root + 0x00abed78)
#define   BUTTERFLY_BODYHALF_BIN                  (void *)(resource_root + 0x00abf6b8)
#define   BUTTERFLY_SWINGDOWN_BIN                 (void *)(resource_root + 0x00ac05f8)
#define   BUTTERFLY_SWINGUP_BIN                   (void *)(resource_root + 0x00ac9638)
#define   BUTTERFLY_DOT0_BIN                      (void *)(resource_root + 0x00ad2678)
#define   BUTTERFLY_DOT1_BIN                      (void *)(resource_root + 0x00ad56b8)
#define   COMMON_FIXED_BIN                        (void *)(resource_root + 0x00ad62f8)
#define   COMMON_FONT32_BIN                       (void *)(resource_root + 0x00ad75f8)
#define   COMMON_FONT96_BIN                       (void *)(resource_root + 0x00ae7b38)
#define   COMMON_UNFIXED_BIN                      (void *)(resource_root + 0x00affb78)
#define   DCLOCK_BACKGROUND_BIN                   (void *)(resource_root + 0x00b00e78)
#define   DCLOCK_BACKGROUND_SHADOW_BIN            (void *)(resource_root + 0x00b10eb8)
#define   DCLOCK_BATTERY_BIN                      (void *)(resource_root + 0x00b20ef8)
#define   DCLOCK_BG_0_BIN                         (void *)(resource_root + 0x00b24e38)
#define   DCLOCK_BG_1_BIN                         (void *)(resource_root + 0x00b29978)
#define   DCLOCK_BG_2_BIN                         (void *)(resource_root + 0x00b2e4b8)
#define   DCLOCK_BG_3_BIN                         (void *)(resource_root + 0x00b32ff8)
#define   DCLOCK_BG_4_BIN                         (void *)(resource_root + 0x00b37b38)
#define   DCLOCK_BG_5_BIN                         (void *)(resource_root + 0x00b3c678)
#define   DCLOCK_BG_6_BIN                         (void *)(resource_root + 0x00b411b8)
#define   DCLOCK_BG_7_BIN                         (void *)(resource_root + 0x00b45cf8)
#define   DCLOCK_BG_8_BIN                         (void *)(resource_root + 0x00b4a838)
#define   DCLOCK_BG_9_BIN                         (void *)(resource_root + 0x00b4f378)
#define   DCLOCK_BG_WEEK0_BIN                     (void *)(resource_root + 0x00b53eb8)
#define   DCLOCK_BG_WEEK1_BIN                     (void *)(resource_root + 0x00b589f8)
#define   DCLOCK_BG_WEEK2_BIN                     (void *)(resource_root + 0x00b5d538)
#define   DCLOCK_BG_WEEK3_BIN                     (void *)(resource_root + 0x00b62078)
#define   DCLOCK_BG_WEEK4_BIN                     (void *)(resource_root + 0x00b66bb8)
#define   DCLOCK_BG_WEEK5_BIN                     (void *)(resource_root + 0x00b6b6f8)
#define   DCLOCK_BG_WEEK6_BIN                     (void *)(resource_root + 0x00b70238)
#define   DCLOCK_DATE_BIN                         (void *)(resource_root + 0x00b74d78)
#define   DCLOCK_FG_0_BIN                         (void *)(resource_root + 0x00b78cb8)
#define   DCLOCK_FG_1_BIN                         (void *)(resource_root + 0x00b7d7f8)
#define   DCLOCK_FG_2_BIN                         (void *)(resource_root + 0x00b82338)
#define   DCLOCK_FG_3_BIN                         (void *)(resource_root + 0x00b86e78)
#define   DCLOCK_FG_4_BIN                         (void *)(resource_root + 0x00b8b9b8)
#define   DCLOCK_FG_5_BIN                         (void *)(resource_root + 0x00b904f8)
#define   DCLOCK_FG_6_BIN                         (void *)(resource_root + 0x00b95038)
#define   DCLOCK_FG_7_BIN                         (void *)(resource_root + 0x00b99b78)
#define   DCLOCK_FG_8_BIN                         (void *)(resource_root + 0x00b9e6b8)
#define   DCLOCK_FG_9_BIN                         (void *)(resource_root + 0x00ba31f8)
#define   DCLOCK_FG_WEEK0_BIN                     (void *)(resource_root + 0x00ba7d38)
#define   DCLOCK_FG_WEEK1_BIN                     (void *)(resource_root + 0x00bac878)
#define   DCLOCK_FG_WEEK2_BIN                     (void *)(resource_root + 0x00bb13b8)
#define   DCLOCK_FG_WEEK3_BIN                     (void *)(resource_root + 0x00bb5ef8)
#define   DCLOCK_FG_WEEK4_BIN                     (void *)(resource_root + 0x00bbaa38)
#define   DCLOCK_FG_WEEK5_BIN                     (void *)(resource_root + 0x00bbf578)
#define   DCLOCK_FG_WEEK6_BIN                     (void *)(resource_root + 0x00bc40b8)
#define   DCLOCK_STEPS_BIN                        (void *)(resource_root + 0x00bc8bf8)
#define   DCLOCK_TIME_BIN                         (void *)(resource_root + 0x00bccb38)
#define   DCLOCK_BTY_BIN                          (void *)(resource_root + 0x00bd0a78)
#define   EBOX_FACE0_BIN                          (void *)(resource_root + 0x00bd0b78)
#define   EBOX_LIGHT0_BIN                         (void *)(resource_root + 0x00bdcbb8)
#define   EBOX_LIGHT1_BIN                         (void *)(resource_root + 0x00bdfbf8)
#define   FLOWERFALL_BACKGROUND_BIN               (void *)(resource_root + 0x00be1c38)
#define   FLOWERFALL_BRANCH01_BIN                 (void *)(resource_root + 0x00c4bcf8)
#define   FLOWERFALL_BRANCH02_BIN                 (void *)(resource_root + 0x00c82bf8)
#define   FLOWERFALL_DOT01_BIN                    (void *)(resource_root + 0x00c928f8)
#define   FLOWERFALL_DOT02_BIN                    (void *)(resource_root + 0x00c93538)
#define   FLOWERFALL_LEAF01_BIN                   (void *)(resource_root + 0x00c94178)
#define   FLOWERFALL_LEAF02_BIN                   (void *)(resource_root + 0x00c94db8)
#define   FLOWERFALL_LEAF03_BIN                   (void *)(resource_root + 0x00c959f8)
#define   FLOWERFALL_LEAF04_BIN                   (void *)(resource_root + 0x00c96638)
#define   FLOWERFALL_LEAF05_BIN                   (void *)(resource_root + 0x00c97278)
#define   FLOWERFALL_LEAF06_BIN                   (void *)(resource_root + 0x00c97eb8)
#define   NOTIFICATIONS_ENVELOPE_BIN              (void *)(resource_root + 0x00c98af8)
#define   NOTIFICATIONS_ENVELOPEBG_BIN            (void *)(resource_root + 0x00cc3878)
#define   NOTIFICATIONS_FLAPCLOSE_BIN             (void *)(resource_root + 0x00ccc438)
#define   NOTIFICATIONS_FLAPOPEN_BIN              (void *)(resource_root + 0x00cddb78)
#define   NOTIFICATIONS_LETTERBG_BIN              (void *)(resource_root + 0x00cee6b8)
#define   PRSIM_ACTIVITYGOAL_BIN                  (void *)(resource_root + 0x00d1a5f8)
#define   PRSIM_ALIPAY_BIN                        (void *)(resource_root + 0x00d36838)
#define   PRSIM_BACKBOARD_BIN                     (void *)(resource_root + 0x00d52a78)
#define   PRSIM_CLOCK_BIN                         (void *)(resource_root + 0x00d6ecb8)
#define   PRSIM_HEARTRATE_BIN                     (void *)(resource_root + 0x00d8aef8)
#define   PRSIM_SIDE_BIN                          (void *)(resource_root + 0x00da7138)
#define   PRSIM_SLEEP_BIN                         (void *)(resource_root + 0x00da7d78)
#define   PRSIM_WEATHER_BIN                       (void *)(resource_root + 0x00dc3fb8)
#define   TRANS_LIGHT_BIN                         (void *)(resource_root + 0x00de01f8)
#define   TRANS_SIDE_BIN                          (void *)(resource_root + 0x00e771b8)
#define   WINDMILL_BACKGROUND_BIN                 (void *)(resource_root + 0x00e7dc78)
#define   WINDMILL_BUBBLE_BIN                     (void *)(resource_root + 0x00ee7d38)
#define   WINDMILL_FACE_BIN                       (void *)(resource_root + 0x00eee978)
#define   WINDMILL_FACEBLUE_BIN                   (void *)(resource_root + 0x00ef1cb8)
#define   WINDMILL_FACEBLUE_SHADOW_BIN            (void *)(resource_root + 0x00ef4cf8)
#define   WINDMILL_FACEGREEN_BIN                  (void *)(resource_root + 0x00ef7d38)
#define   WINDMILL_FACEGREEN_SHADOW_BIN           (void *)(resource_root + 0x00efad78)
#define   WINDMILL_FACERED_BIN                    (void *)(resource_root + 0x00efddb8)
#define   WINDMILL_FACERED_SHADOW_BIN             (void *)(resource_root + 0x00f00df8)
#define   WINDMILL_FACEYELLOW_BIN                 (void *)(resource_root + 0x00f03e38)
#define   WINDMILL_FACEYELLOW_SHADOW_BIN          (void *)(resource_root + 0x00f06e78)
#define   WINDMILL_NAIL_BIN                       (void *)(resource_root + 0x00f09eb8)
#define   WINDMILL_STICK_BIN                      (void *)(resource_root + 0x00f0aaf8)
#define   SOCCER_ACTIVITIES_BIN                   (void *)(resource_root + 0x00f0b738)
#define   SOCCER_ALARM_BIN                        (void *)(resource_root + 0x00f10278)
#define   SOCCER_ALIPAY_BIN                       (void *)(resource_root + 0x00f14db8)
#define   SOCCER_BOARD_BIN                        (void *)(resource_root + 0x00f198f8)
#define   SOCCER_CARDS_BIN                        (void *)(resource_root + 0x00f25938)
#define   SOCCER_COMPASS_BIN                      (void *)(resource_root + 0x00f2a478)
#define   SOCCER_COUNTDOWN_BIN                    (void *)(resource_root + 0x00f2efb8)
#define   SOCCER_FINDPHONE_BIN                    (void *)(resource_root + 0x00f33af8)
#define   SOCCER_GOAL_BIN                         (void *)(resource_root + 0x00f38638)
#define   SOCCER_HEARTRATE_BIN                    (void *)(resource_root + 0x00f3d178)
#define   SOCCER_HOME_BIN                         (void *)(resource_root + 0x00f41cb8)
#define   SOCCER_MUSIC_BIN                        (void *)(resource_root + 0x00f467f8)
#define   SOCCER_SCHEDULE_BIN                     (void *)(resource_root + 0x00f4b338)
#define   SOCCER_SETTINGS_BIN                     (void *)(resource_root + 0x00f4fe78)
#define   SOCCER_SLEEP_BIN                        (void *)(resource_root + 0x00f549b8)
#define   SOCCER_SPO2_BIN                         (void *)(resource_root + 0x00f594f8)
#define   SOCCER_SPORTS_BIN                       (void *)(resource_root + 0x00f5e038)
#define   SOCCER_STAR_BIN                         (void *)(resource_root + 0x00f62b78)
#define   SOCCER_STOPWATCH_BIN                    (void *)(resource_root + 0x00f64bb8)
#define   SOCCER_STRESS_BIN                       (void *)(resource_root + 0x00f696f8)
#define   SOCCER_TEMPERATURE_BIN                  (void *)(resource_root + 0x00f6e238)
#define   SOCCER_WEATHER_BIN                      (void *)(resource_root + 0x00f72d78)
#define   TEXT0_BIN                               (void *)(resource_root + 0x00f779b8)
#define   TEXT1_BIN                               (void *)(resource_root + 0x00f77cb8)
#define   TEXT2_BIN                               (void *)(resource_root + 0x00f77db8)
#define   TEXT3_BIN                               (void *)(resource_root + 0x00f78078)
#define   TEXT4_BIN                               (void *)(resource_root + 0x00f782b8)
#define   TEXT5_BIN                               (void *)(resource_root + 0x00f784b8)
#define   TEXT6_BIN                               (void *)(resource_root + 0x00f78738)
#define   TEXT7_BIN                               (void *)(resource_root + 0x00f78a78)
#define   TEXT8_BIN                               (void *)(resource_root + 0x00f78c78)
#define   TEXT9_BIN                               (void *)(resource_root + 0x00f78fb8)
#define   TEXTAM_BIN                              (void *)(resource_root + 0x00f792f8)
#define   TEXTDIAN_BIN                            (void *)(resource_root + 0x00f79938)
#define   TEXTMAOHAO_BIN                          (void *)(resource_root + 0x00f799f8)
#define   TEXTPM_BIN                              (void *)(resource_root + 0x00f79b78)
#define   TEXTXIEGANG_BIN                         (void *)(resource_root + 0x00f7a138)
#define   PATH04_BIN                              (void *)(resource_root + 0x00f7a4f8)
#define   PATH05_BIN                              (void *)(resource_root + 0x00f7a878)
#define   PATH07_BIN                              (void *)(resource_root + 0x00f7ad78)
#define   PATH08_BIN                              (void *)(resource_root + 0x00f7b4b8)
#define   PATH09_BIN                              (void *)(resource_root + 0x00f7bc38)
#define   PATH11_BIN                              (void *)(resource_root + 0x00f7c3f8)
#define   PATH12_BIN                              (void *)(resource_root + 0x00f7cbf8)
#define   PATH14_BIN                              (void *)(resource_root + 0x00f7d438)
#define   PATH15_BIN                              (void *)(resource_root + 0x00f7dc78)
#define   PATH16_BIN                              (void *)(resource_root + 0x00f7e4f8)
#define   PATH18_BIN                              (void *)(resource_root + 0x00f7ed78)
#define   PATH19_BIN                              (void *)(resource_root + 0x00f7f5f8)
#define   PATH20_BIN                              (void *)(resource_root + 0x00f7feb8)
#define   PATH22_BIN                              (void *)(resource_root + 0x00f80778)
#define   PATH23_BIN                              (void *)(resource_root + 0x00f81038)
#define   PATH24_BIN                              (void *)(resource_root + 0x00f81938)
#define   PATH25_BIN                              (void *)(resource_root + 0x00f82238)
#define   BAR1_BIN                                (void *)(resource_root + 0x00f82c78)
#define   BAR10_BIN                               (void *)(resource_root + 0x00f84bf8)
#define   BAR13_BIN                               (void *)(resource_root + 0x00f86b78)
#define   BAR16_BIN                               (void *)(resource_root + 0x00f88af8)
#define   BAR19_BIN                               (void *)(resource_root + 0x00f8aa78)
#define   BAR22_BIN                               (void *)(resource_root + 0x00f8c9f8)
#define   BAR25_BIN                               (void *)(resource_root + 0x00f8e978)
#define   BAR28_BIN                               (void *)(resource_root + 0x00f908f8)
#define   BAR31_BIN                               (void *)(resource_root + 0x00f92878)
#define   BAR34_BIN                               (void *)(resource_root + 0x00f947f8)
#define   BAR38_BIN                               (void *)(resource_root + 0x00f96778)
#define   BAR39_BIN                               (void *)(resource_root + 0x00f986f8)
#define   BAR4_BIN                                (void *)(resource_root + 0x00f9a678)
#define   BAR40_BIN                               (void *)(resource_root + 0x00f9c5f8)
#define   BAR41_BIN                               (void *)(resource_root + 0x00f9e578)
#define   BAR42_BIN                               (void *)(resource_root + 0x00fa04f8)
#define   BAR43_BIN                               (void *)(resource_root + 0x00fa2478)
#define   BAR7_BIN                                (void *)(resource_root + 0x00fa43f8)
#define   BARS1_BIN                               (void *)(resource_root + 0x00fa6378)
#define   BARS2_BIN                               (void *)(resource_root + 0x00fa82f8)
#define   BARS3_BIN                               (void *)(resource_root + 0x00faa278)
#define   BATTERY_BIN                             (void *)(resource_root + 0x00fac238)
#define   BATTERYHL_BIN                           (void *)(resource_root + 0x00fadcf8)
#define   BLUETOOTH_BIN                           (void *)(resource_root + 0x00faf7f8)
#define   BLUETOOTHHL_BIN                         (void *)(resource_root + 0x00fb1d78)
#define   MYDEVICE_BIN                            (void *)(resource_root + 0x00fb42f8)
#define   MYDEVICEHL_BIN                          (void *)(resource_root + 0x00fb6238)
#define   STOPWATCH_BIN                           (void *)(resource_root + 0x00fb81b8)
#define   VOLUME_BIN                              (void *)(resource_root + 0x0102b178)
#define   VOLUME2_BIN                             (void *)(resource_root + 0x0102dab8)
#define   VOLUMEBACK_BIN                          (void *)(resource_root + 0x0102e0f8)
#define   VOLUMEBACK2_BIN                         (void *)(resource_root + 0x01030938)

#else
#define   A1_BIN                                  (void *)(0x04400af8)
#define   A2_BIN                                  (void *)(0x04408b38)
#define   A3_BIN                                  (void *)(0x04410b78)
#define   A4_BIN                                  (void *)(0x04418bb8)
#define   A5_BIN                                  (void *)(0x04420bf8)
#define   A6_BIN                                  (void *)(0x04428c38)
#define   B1_BIN                                  (void *)(0x04430c78)
#define   B1_RLE_BIN                              (void *)(0x0443a7b8)
#define   B2_BIN                                  (void *)(0x04442038)
#define   B2_RLE_BIN                              (void *)(0x0444bb78)
#define   B3_BIN                                  (void *)(0x044518b8)
#define   B3_RLE_BIN                              (void *)(0x0445b3f8)
#define   B4_BIN                                  (void *)(0x0445df78)
#define   B4_RLE_BIN                              (void *)(0x04467ab8)
#define   B5_BIN                                  (void *)(0x0446ad38)
#define   B5_RLE_BIN                              (void *)(0x04474878)
#define   B6_BIN                                  (void *)(0x04476878)
#define   B6_RLE_BIN                              (void *)(0x044803b8)
#define   OVAL_BIN                                (void *)(0x044827b8)
#define   CLOCK_BASE_BIN                          (void *)(0x04482a78)
#define   ICON_ANSWER_BIN                         (void *)(0x04486738)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(0x04487638)
#define   ICON_BACK_BIN                           (void *)(0x04488338)
#define   ICON_BACKSPACE_BIN                      (void *)(0x044885f8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(0x04488cb8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(0x04489a78)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(0x0448a838)
#define   ICON_BUDS_OFF_BIN                       (void *)(0x0448b5f8)
#define   ICON_BUDS_ON_BIN                        (void *)(0x0448c4f8)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(0x0448d3b8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(0x0448e2b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(0x0448e9f8)
#define   ICON_CALL_BIN                           (void *)(0x0448f378)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(0x04490e78)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(0x04491cf8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(0x04492bb8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(0x04493a78)
#define   ICON_CALL_TOUCH_BIN                     (void *)(0x04494978)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(0x04496378)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(0x04496478)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(0x04496578)
#define   ICON_CALLER_BIN                         (void *)(0x04496638)
#define   ICON_CALLER_LARGE_BIN                   (void *)(0x04498478)
#define   ICON_CANCEL_BIN                         (void *)(0x0449b438)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(0x0449be78)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(0x0449c8b8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(0x0449c9f8)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(0x0449cf78)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(0x0449d678)
#define   ICON_CONFIRM_BIN                        (void *)(0x0449de38)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(0x0449e7f8)
#define   ICON_CONTACTCS_BIN                      (void *)(0x0449f1b8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(0x044a0bf8)
#define   ICON_DIAL_0_BIN                         (void *)(0x044a24f8)
#define   ICON_DIAL_1_BIN                         (void *)(0x044a2a78)
#define   ICON_DIAL_2_BIN                         (void *)(0x044a2eb8)
#define   ICON_DIAL_3_BIN                         (void *)(0x044a32f8)
#define   ICON_DIAL_4_BIN                         (void *)(0x044a3738)
#define   ICON_DIAL_5_BIN                         (void *)(0x044a3b78)
#define   ICON_DIAL_6_BIN                         (void *)(0x044a3fb8)
#define   ICON_DIAL_7_BIN                         (void *)(0x044a44b8)
#define   ICON_DIAL_8_BIN                         (void *)(0x044a4938)
#define   ICON_DIAL_9_BIN                         (void *)(0x044a4e78)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(0x044a5438)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(0x044a5b38)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(0x044a6238)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(0x044a6678)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(0x044a6ab8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(0x044a7038)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(0x044a7478)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(0x044a7978)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(0x044a80f8)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(0x044a8638)
#define   ICON_DISCONNECT_BIN                     (void *)(0x044a8bf8)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(0x044a9678)
#define   ICON_FAIL_BIN                           (void *)(0x044aa138)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(0x044ab378)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(0x044ab9b8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(0x044abff8)
#define   ICON_FOLDER_BIN                         (void *)(0x044ac638)
#define   ICON_HANGUP_BIN                         (void *)(0x044ac7f8)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(0x044ad838)
#define   ICON_LOADING_BIN                        (void *)(0x044ae5f8)
#define   ICON_MENU_BIN                           (void *)(0x044aeeb8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(0x044af7b8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(0x044b01b8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(0x044b0b78)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(0x044b16b8)
#define   ICON_MORE_OFF_BIN                       (void *)(0x044b2178)
#define   ICON_MORE_ON_BIN                        (void *)(0x044b2bb8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(0x044b35f8)
#define   ICON_PHONE_OFF_BIN                      (void *)(0x044b4038)
#define   ICON_PHONE_ON_BIN                       (void *)(0x044b4b78)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(0x044b5678)
#define   ICON_PROCESS_BAR_BIN                    (void *)(0x044b61b8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(0x044b6338)
#define   ICON_PROCESS_NODE_BIN                   (void *)(0x044b6478)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(0x044b6878)
#define   ICON_RECORD_DELETE_BIN                  (void *)(0x044b6b38)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(0x044b77f8)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(0x044b84f8)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(0x044bb678)
#define   ICON_RECORD_PLAY_BIN                    (void *)(0x044be6f8)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(0x044c1778)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(0x044c1978)
#define   ICON_RECORD_START_BIN                   (void *)(0x044c48f8)
#define   ICON_RECORD_STOP_BIN                    (void *)(0x044c7738)
#define   ICON_SEEKBAR_BIN                        (void *)(0x044c9f38)
#define   ICON_SEEKBAR1_BIN                       (void *)(0x044ca5b8)
#define   ICON_SEEKBAR2_BIN                       (void *)(0x044ca738)
#define   ICON_SONG_BUDS_BIN                      (void *)(0x044cad78)
#define   ICON_SONG_LOCAL_BIN                     (void *)(0x044cb178)
#define   ICON_SONG_NEXT_BIN                      (void *)(0x044cb5b8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(0x044cbcb8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(0x044cc3b8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(0x044ccd38)
#define   ICON_SONG_PHONE_BIN                     (void *)(0x044cd6b8)
#define   ICON_SONG_PLAY_BIN                      (void *)(0x044cd9f8)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(0x044ce238)
#define   ICON_SONG_PREV_BIN                      (void *)(0x044cea78)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(0x044cf138)
#define   ICON_SONG_SPK_BIN                       (void *)(0x044cf7f8)
#define   ICON_SUCCESS_BIN                        (void *)(0x044cfb78)
#define   ICON_SWITCH_OFF_BIN                     (void *)(0x044d0fb8)
#define   ICON_SWITCH_ON_BIN                      (void *)(0x044d1778)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(0x044d1f78)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(0x044d2478)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(0x044d2978)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(0x044d2eb8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(0x044d32f8)
#define   ICON_TRASH_BIN                          (void *)(0x044d39b8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(0x044d41b8)
#define   ICON_UP_SLIDE_BIN                       (void *)(0x044d49b8)
#define   ICON_VOLUME_BIN                         (void *)(0x044d54b8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(0x044d57f8)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(0x044d5978)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(0x044d5a78)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(0x044d5b38)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(0x044d5c38)
#define   ICON_VOLUME_CALL_BIN                    (void *)(0x044d5d78)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(0x044d66b8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(0x044d6ef8)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(0x044d7478)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(0x044d79f8)
#define   ICON_VOLUME_UP_BIN                      (void *)(0x044d7e78)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(0x044d85b8)
#define   PATH2_BIN                               (void *)(0x044d8cf8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(0x044d8df8)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(0x044d8fb8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(0x044d9038)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(0x044d90f8)
#define   RECT1_BIN                               (void *)(0x044d92b8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(0x044d97b8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(0x044da9b8)
#define   WATCH_BASE_GREY_BIN                     (void *)(0x044dc538)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(0x044defb8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(0x044e19b8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(0x044e2f38)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(0x044e3378)
#define   HAND_BIN                                (void *)(0x044e37b8)
#define   TICKMARK_BIN                            (void *)(0x044e3d78)
#define   BACK14_BIN                              (void *)(0x044ecab8)
#define   BACK15_BIN                              (void *)(0x04516cb8)
#define   KEHUZHOUQI_BIN                          (void *)(0x04542b78)
#define   RECT12_BIN                              (void *)(0x04543cf8)
#define   RECT13_BIN                              (void *)(0x045444b8)
#define   RECT14_BIN                              (void *)(0x04544fb8)
#define   RECT15_BIN                              (void *)(0x04545b38)
#define   ARIAL_SIZE48_BITS4_FONT_BIN             (void *)(0x04546338)
#define   ARIALBD_SIZE16_BITS4_FONT_BIN           (void *)(0x0456c6b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(0x0458f878)
#define   SIMKAI_SIZE32_BITS2_FONT_BIN            (void *)(0x04873238)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(0x04def6f8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(0x04df3c38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(0x04df5b38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(0x04df92b8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(0x04dfd838)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(0x04dff7b8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(0x04e01ef8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(0x04e1b338)
#define   FRUIT_NINJA_GAMEOVER_BIN                (void *)(0x04e22bf8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(0x04e2e938)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(0x04e315f8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(0x04e333b8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(0x04e35038)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(0x04e3a0f8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(0x04e3deb8)
#define   HEARTRATE04_BIN                         (void *)(0x04e41378)
#define   HEARTRATE08_BIN                         (void *)(0x04e49378)
#define   HEARTRATE12_BIN                         (void *)(0x04e51638)
#define   HEARTRATE16_BIN                         (void *)(0x04e597f8)
#define   HEARTRATE20_BIN                         (void *)(0x04e617f8)
#define   HEARTRATE24_BIN                         (void *)(0x04e69978)
#define   HEARTRATE28_BIN                         (void *)(0x04e71b78)
#define   HEARTRATE32_BIN                         (void *)(0x04e79f78)
#define   HEARTRATE36_BIN                         (void *)(0x04e828f8)
#define   HEARTRATE40_BIN                         (void *)(0x04e8b7b8)
#define   HEARTRATE44_BIN                         (void *)(0x04e94778)
#define   HEARTRATE48_BIN                         (void *)(0x04e9d6f8)
#define   I4500009_BIN                            (void *)(0x04ea65b8)
#define   I4500011_BIN                            (void *)(0x04ea7ff8)
#define   I4500015_BIN                            (void *)(0x04ea96b8)
#define   I4500020_BIN                            (void *)(0x04eab138)
#define   I4500028_BIN                            (void *)(0x04eacfb8)
#define   I4500034_BIN                            (void *)(0x04eae8b8)
#define   I4500035_BIN                            (void *)(0x04eb0578)
#define   I4500037_BIN                            (void *)(0x04eb1cf8)
#define   I4500040_BIN                            (void *)(0x04eb3ff8)
#define   I4500042_BIN                            (void *)(0x04eb5af8)
#define   I4500047_BIN                            (void *)(0x04eb7ab8)
#define   I4500049_BIN                            (void *)(0x04eb90f8)
#define   I4500052_BIN                            (void *)(0x04ebaa78)
#define   I4500064_BIN                            (void *)(0x04ebc578)
#define   RESIZE_PY                               (void *)(0x04ebdc78)
#define   BUTTERFLY_ANTENNA_BIN                   (void *)(0x04ebed78)
#define   BUTTERFLY_BODYHALF_BIN                  (void *)(0x04ebf6b8)
#define   BUTTERFLY_SWINGDOWN_BIN                 (void *)(0x04ec05f8)
#define   BUTTERFLY_SWINGUP_BIN                   (void *)(0x04ec9638)
#define   BUTTERFLY_DOT0_BIN                      (void *)(0x04ed2678)
#define   BUTTERFLY_DOT1_BIN                      (void *)(0x04ed56b8)
#define   COMMON_FIXED_BIN                        (void *)(0x04ed62f8)
#define   COMMON_FONT32_BIN                       (void *)(0x04ed75f8)
#define   COMMON_FONT96_BIN                       (void *)(0x04ee7b38)
#define   COMMON_UNFIXED_BIN                      (void *)(0x04effb78)
#define   DCLOCK_BACKGROUND_BIN                   (void *)(0x04f00e78)
#define   DCLOCK_BACKGROUND_SHADOW_BIN            (void *)(0x04f10eb8)
#define   DCLOCK_BATTERY_BIN                      (void *)(0x04f20ef8)
#define   DCLOCK_BG_0_BIN                         (void *)(0x04f24e38)
#define   DCLOCK_BG_1_BIN                         (void *)(0x04f29978)
#define   DCLOCK_BG_2_BIN                         (void *)(0x04f2e4b8)
#define   DCLOCK_BG_3_BIN                         (void *)(0x04f32ff8)
#define   DCLOCK_BG_4_BIN                         (void *)(0x04f37b38)
#define   DCLOCK_BG_5_BIN                         (void *)(0x04f3c678)
#define   DCLOCK_BG_6_BIN                         (void *)(0x04f411b8)
#define   DCLOCK_BG_7_BIN                         (void *)(0x04f45cf8)
#define   DCLOCK_BG_8_BIN                         (void *)(0x04f4a838)
#define   DCLOCK_BG_9_BIN                         (void *)(0x04f4f378)
#define   DCLOCK_BG_WEEK0_BIN                     (void *)(0x04f53eb8)
#define   DCLOCK_BG_WEEK1_BIN                     (void *)(0x04f589f8)
#define   DCLOCK_BG_WEEK2_BIN                     (void *)(0x04f5d538)
#define   DCLOCK_BG_WEEK3_BIN                     (void *)(0x04f62078)
#define   DCLOCK_BG_WEEK4_BIN                     (void *)(0x04f66bb8)
#define   DCLOCK_BG_WEEK5_BIN                     (void *)(0x04f6b6f8)
#define   DCLOCK_BG_WEEK6_BIN                     (void *)(0x04f70238)
#define   DCLOCK_DATE_BIN                         (void *)(0x04f74d78)
#define   DCLOCK_FG_0_BIN                         (void *)(0x04f78cb8)
#define   DCLOCK_FG_1_BIN                         (void *)(0x04f7d7f8)
#define   DCLOCK_FG_2_BIN                         (void *)(0x04f82338)
#define   DCLOCK_FG_3_BIN                         (void *)(0x04f86e78)
#define   DCLOCK_FG_4_BIN                         (void *)(0x04f8b9b8)
#define   DCLOCK_FG_5_BIN                         (void *)(0x04f904f8)
#define   DCLOCK_FG_6_BIN                         (void *)(0x04f95038)
#define   DCLOCK_FG_7_BIN                         (void *)(0x04f99b78)
#define   DCLOCK_FG_8_BIN                         (void *)(0x04f9e6b8)
#define   DCLOCK_FG_9_BIN                         (void *)(0x04fa31f8)
#define   DCLOCK_FG_WEEK0_BIN                     (void *)(0x04fa7d38)
#define   DCLOCK_FG_WEEK1_BIN                     (void *)(0x04fac878)
#define   DCLOCK_FG_WEEK2_BIN                     (void *)(0x04fb13b8)
#define   DCLOCK_FG_WEEK3_BIN                     (void *)(0x04fb5ef8)
#define   DCLOCK_FG_WEEK4_BIN                     (void *)(0x04fbaa38)
#define   DCLOCK_FG_WEEK5_BIN                     (void *)(0x04fbf578)
#define   DCLOCK_FG_WEEK6_BIN                     (void *)(0x04fc40b8)
#define   DCLOCK_STEPS_BIN                        (void *)(0x04fc8bf8)
#define   DCLOCK_TIME_BIN                         (void *)(0x04fccb38)
#define   DCLOCK_BTY_BIN                          (void *)(0x04fd0a78)
#define   EBOX_FACE0_BIN                          (void *)(0x04fd0b78)
#define   EBOX_LIGHT0_BIN                         (void *)(0x04fdcbb8)
#define   EBOX_LIGHT1_BIN                         (void *)(0x04fdfbf8)
#define   FLOWERFALL_BACKGROUND_BIN               (void *)(0x04fe1c38)
#define   FLOWERFALL_BRANCH01_BIN                 (void *)(0x0504bcf8)
#define   FLOWERFALL_BRANCH02_BIN                 (void *)(0x05082bf8)
#define   FLOWERFALL_DOT01_BIN                    (void *)(0x050928f8)
#define   FLOWERFALL_DOT02_BIN                    (void *)(0x05093538)
#define   FLOWERFALL_LEAF01_BIN                   (void *)(0x05094178)
#define   FLOWERFALL_LEAF02_BIN                   (void *)(0x05094db8)
#define   FLOWERFALL_LEAF03_BIN                   (void *)(0x050959f8)
#define   FLOWERFALL_LEAF04_BIN                   (void *)(0x05096638)
#define   FLOWERFALL_LEAF05_BIN                   (void *)(0x05097278)
#define   FLOWERFALL_LEAF06_BIN                   (void *)(0x05097eb8)
#define   NOTIFICATIONS_ENVELOPE_BIN              (void *)(0x05098af8)
#define   NOTIFICATIONS_ENVELOPEBG_BIN            (void *)(0x050c3878)
#define   NOTIFICATIONS_FLAPCLOSE_BIN             (void *)(0x050cc438)
#define   NOTIFICATIONS_FLAPOPEN_BIN              (void *)(0x050ddb78)
#define   NOTIFICATIONS_LETTERBG_BIN              (void *)(0x050ee6b8)
#define   PRSIM_ACTIVITYGOAL_BIN                  (void *)(0x0511a5f8)
#define   PRSIM_ALIPAY_BIN                        (void *)(0x05136838)
#define   PRSIM_BACKBOARD_BIN                     (void *)(0x05152a78)
#define   PRSIM_CLOCK_BIN                         (void *)(0x0516ecb8)
#define   PRSIM_HEARTRATE_BIN                     (void *)(0x0518aef8)
#define   PRSIM_SIDE_BIN                          (void *)(0x051a7138)
#define   PRSIM_SLEEP_BIN                         (void *)(0x051a7d78)
#define   PRSIM_WEATHER_BIN                       (void *)(0x051c3fb8)
#define   TRANS_LIGHT_BIN                         (void *)(0x051e01f8)
#define   TRANS_SIDE_BIN                          (void *)(0x052771b8)
#define   WINDMILL_BACKGROUND_BIN                 (void *)(0x0527dc78)
#define   WINDMILL_BUBBLE_BIN                     (void *)(0x052e7d38)
#define   WINDMILL_FACE_BIN                       (void *)(0x052ee978)
#define   WINDMILL_FACEBLUE_BIN                   (void *)(0x052f1cb8)
#define   WINDMILL_FACEBLUE_SHADOW_BIN            (void *)(0x052f4cf8)
#define   WINDMILL_FACEGREEN_BIN                  (void *)(0x052f7d38)
#define   WINDMILL_FACEGREEN_SHADOW_BIN           (void *)(0x052fad78)
#define   WINDMILL_FACERED_BIN                    (void *)(0x052fddb8)
#define   WINDMILL_FACERED_SHADOW_BIN             (void *)(0x05300df8)
#define   WINDMILL_FACEYELLOW_BIN                 (void *)(0x05303e38)
#define   WINDMILL_FACEYELLOW_SHADOW_BIN          (void *)(0x05306e78)
#define   WINDMILL_NAIL_BIN                       (void *)(0x05309eb8)
#define   WINDMILL_STICK_BIN                      (void *)(0x0530aaf8)
#define   SOCCER_ACTIVITIES_BIN                   (void *)(0x0530b738)
#define   SOCCER_ALARM_BIN                        (void *)(0x05310278)
#define   SOCCER_ALIPAY_BIN                       (void *)(0x05314db8)
#define   SOCCER_BOARD_BIN                        (void *)(0x053198f8)
#define   SOCCER_CARDS_BIN                        (void *)(0x05325938)
#define   SOCCER_COMPASS_BIN                      (void *)(0x0532a478)
#define   SOCCER_COUNTDOWN_BIN                    (void *)(0x0532efb8)
#define   SOCCER_FINDPHONE_BIN                    (void *)(0x05333af8)
#define   SOCCER_GOAL_BIN                         (void *)(0x05338638)
#define   SOCCER_HEARTRATE_BIN                    (void *)(0x0533d178)
#define   SOCCER_HOME_BIN                         (void *)(0x05341cb8)
#define   SOCCER_MUSIC_BIN                        (void *)(0x053467f8)
#define   SOCCER_SCHEDULE_BIN                     (void *)(0x0534b338)
#define   SOCCER_SETTINGS_BIN                     (void *)(0x0534fe78)
#define   SOCCER_SLEEP_BIN                        (void *)(0x053549b8)
#define   SOCCER_SPO2_BIN                         (void *)(0x053594f8)
#define   SOCCER_SPORTS_BIN                       (void *)(0x0535e038)
#define   SOCCER_STAR_BIN                         (void *)(0x05362b78)
#define   SOCCER_STOPWATCH_BIN                    (void *)(0x05364bb8)
#define   SOCCER_STRESS_BIN                       (void *)(0x053696f8)
#define   SOCCER_TEMPERATURE_BIN                  (void *)(0x0536e238)
#define   SOCCER_WEATHER_BIN                      (void *)(0x05372d78)
#define   TEXT0_BIN                               (void *)(0x053779b8)
#define   TEXT1_BIN                               (void *)(0x05377cb8)
#define   TEXT2_BIN                               (void *)(0x05377db8)
#define   TEXT3_BIN                               (void *)(0x05378078)
#define   TEXT4_BIN                               (void *)(0x053782b8)
#define   TEXT5_BIN                               (void *)(0x053784b8)
#define   TEXT6_BIN                               (void *)(0x05378738)
#define   TEXT7_BIN                               (void *)(0x05378a78)
#define   TEXT8_BIN                               (void *)(0x05378c78)
#define   TEXT9_BIN                               (void *)(0x05378fb8)
#define   TEXTAM_BIN                              (void *)(0x053792f8)
#define   TEXTDIAN_BIN                            (void *)(0x05379938)
#define   TEXTMAOHAO_BIN                          (void *)(0x053799f8)
#define   TEXTPM_BIN                              (void *)(0x05379b78)
#define   TEXTXIEGANG_BIN                         (void *)(0x0537a138)
#define   PATH04_BIN                              (void *)(0x0537a4f8)
#define   PATH05_BIN                              (void *)(0x0537a878)
#define   PATH07_BIN                              (void *)(0x0537ad78)
#define   PATH08_BIN                              (void *)(0x0537b4b8)
#define   PATH09_BIN                              (void *)(0x0537bc38)
#define   PATH11_BIN                              (void *)(0x0537c3f8)
#define   PATH12_BIN                              (void *)(0x0537cbf8)
#define   PATH14_BIN                              (void *)(0x0537d438)
#define   PATH15_BIN                              (void *)(0x0537dc78)
#define   PATH16_BIN                              (void *)(0x0537e4f8)
#define   PATH18_BIN                              (void *)(0x0537ed78)
#define   PATH19_BIN                              (void *)(0x0537f5f8)
#define   PATH20_BIN                              (void *)(0x0537feb8)
#define   PATH22_BIN                              (void *)(0x05380778)
#define   PATH23_BIN                              (void *)(0x05381038)
#define   PATH24_BIN                              (void *)(0x05381938)
#define   PATH25_BIN                              (void *)(0x05382238)
#define   BAR1_BIN                                (void *)(0x05382c78)
#define   BAR10_BIN                               (void *)(0x05384bf8)
#define   BAR13_BIN                               (void *)(0x05386b78)
#define   BAR16_BIN                               (void *)(0x05388af8)
#define   BAR19_BIN                               (void *)(0x0538aa78)
#define   BAR22_BIN                               (void *)(0x0538c9f8)
#define   BAR25_BIN                               (void *)(0x0538e978)
#define   BAR28_BIN                               (void *)(0x053908f8)
#define   BAR31_BIN                               (void *)(0x05392878)
#define   BAR34_BIN                               (void *)(0x053947f8)
#define   BAR38_BIN                               (void *)(0x05396778)
#define   BAR39_BIN                               (void *)(0x053986f8)
#define   BAR4_BIN                                (void *)(0x0539a678)
#define   BAR40_BIN                               (void *)(0x0539c5f8)
#define   BAR41_BIN                               (void *)(0x0539e578)
#define   BAR42_BIN                               (void *)(0x053a04f8)
#define   BAR43_BIN                               (void *)(0x053a2478)
#define   BAR7_BIN                                (void *)(0x053a43f8)
#define   BARS1_BIN                               (void *)(0x053a6378)
#define   BARS2_BIN                               (void *)(0x053a82f8)
#define   BARS3_BIN                               (void *)(0x053aa278)
#define   BATTERY_BIN                             (void *)(0x053ac238)
#define   BATTERYHL_BIN                           (void *)(0x053adcf8)
#define   BLUETOOTH_BIN                           (void *)(0x053af7f8)
#define   BLUETOOTHHL_BIN                         (void *)(0x053b1d78)
#define   MYDEVICE_BIN                            (void *)(0x053b42f8)
#define   MYDEVICEHL_BIN                          (void *)(0x053b6238)
#define   STOPWATCH_BIN                           (void *)(0x053b81b8)
#define   VOLUME_BIN                              (void *)(0x0542b178)
#define   VOLUME2_BIN                             (void *)(0x0542dab8)
#define   VOLUMEBACK_BIN                          (void *)(0x0542e0f8)
#define   VOLUMEBACK2_BIN                         (void *)(0x05430938)

#endif
