from building import *
import sys

cwd = GetCurrentDir()

src = []
libs = ['']

if sys.platform == 'win32':
    libs += ['glew32','glew32s']
    libpath = [cwd]
    libpath += [cwd + '/glew-2.1.0/lib/Release/x64']
    include = [cwd]        
    include += [cwd + '/glew-2.1.0/include']
    include += [cwd + '/glew-2.1.0/include/GL']
else:  # Linux/WSL - use system GLEW
    libs += ['GLEW']
    libpath = []
    include = []


group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = include, LIBS = libs, LIBPATH = libpath)

Return('group')
