from building import *

cwd = GetCurrentDir()

src = []
libs = ['']
libs += ['glew32','glew32s']


libpath = [cwd]
libpath += [cwd + '/glew-2.1.0/lib/Release/x64']


include = [cwd]        
include += [cwd + '/glew-2.1.0/include']
include += [cwd + '/glew-2.1.0/include/GL']


group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = include, LIBS = libs, LIBPATH = libpath)

Return('group')
