# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
SrcRemove(src,'app_calculator.c')

if not GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    SrcRemove(src,'app_lvgl.c')
if not GetDepend('CONFIG_REALTEK_BUILD_PAINTER_ENGINE'):
    SrcRemove(src,'app_px.c')

CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_hongkong']
print(CPPPATH)

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_448_368_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_448_368_DEMO']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_448_368_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
