# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
if not GetDepend('BUILD_USING_LVGL_GUI'):
    SrcRemove(src,'app_lvgl.c')
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_hongkong']
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['BUILD_USING_RTK_GUI_448_368_DEMO'], CPPPATH = CPPPATH)

Return('group')
