# for module compiling
import os
Import('TOOL_ROOT')


from building import *

cwd = GetCurrentDir()




src = Glob('*.c')
inc = ['']


CPPDEFINES = []



objs = DefineGroup('rtk_gui', src, depend = [''], CPPPATH = inc, CPPDEFINES = CPPDEFINES)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
