# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


src += ['draw_img.c']
src += ['gui_matrix.c']
src += ['draw_font.c']
src += ['font_mem.c']
src += ['font_stb.c']
src += ['acc_sw.c']
src += ['acc_init.c']
src += ['acc_sw_blend.c']
src += ['acc_sw_rle.c']
src += ['acc_sw_bypass.c']
src += ['acc_sw_filter.c']
src += ['acc_sw_bypass_matrix.c']
src += ['acc_sw_filter_matrix.c']
# src += ['acc_sw_rle_bypass.c']
# src += ['acc_sw_rle_filter.c']
# src += ['acc_sw_rle_bypass_matrix.c']
# src += ['acc_sw_rle_filter_matrix.c']

if GetDepend(['BUILD_USING_VG_LITE']):
    src += ['acc_vg_lite.c']

if GetDepend(['BUILD_USING_RTK_PPE']):
    src += ['acc_rtk_ppe.c']

CPPPATH = [cwd]

group = DefineGroup('rtk_gui', src, depend = ['BUILD_USING_RTK_GUI'], CPPPATH = CPPPATH)

Return('group')
