# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


src += ['draw_img.c']
src += ['gui_matrix.c']
src += ['draw_font.c']
src += ['font_mem.c']
src += ['font_stb.c']
src += ['acc_sw.c']
src += ['acc_init.c']
if GetDepend(['BUILD_USING_SCRIPT_AS_A_APP']):
    src += ['ezhtml.c']
    src += ['ezjs.c']
    src += ['frontend_launcher.c']

if GetDepend(['BUILD_USING_VG_LITE']):
    src += ['acc_vg_lite.c']

if GetDepend(['BUILD_USING_RTK_PPE']):
    src += ['acc_rtk_ppe.c']

CPPPATH = [cwd]

group = DefineGroup('rtk_gui', src, depend = ['BUILD_USING_RTK_GUI'], CPPPATH = CPPPATH)

Return('group')
