import os
import sys
import menu_config
from SCons.Script import *

TOOL_ROOT="./scons-tool"

sys.path = sys.path + [os.path.join(TOOL_ROOT, '')]
try:
    from building import *
except:
    print('Cannot found Scons tool root directory, please check TOOL_ROOT')
    exit(-1)

TARGET = 'gui.' + 'exe'

#env = Environment(tools = ['mingw'],
#    AS = menu_config.AS, ASFLAGS = menu_config.AFLAGS,
#    CC = menu_config.CC, CCFLAGS = menu_config.CFLAGS,
#    AR = menu_config.AR, ARFLAGS = '-rc',
#    CXX = menu_config.CXX, CXXFLAGS = menu_config.CXXFLAGS,
#    LINK = menu_config.LINK, LINKFLAGS = menu_config.LFLAGS)

env = Environment(tools = ['mingw'],
                  CC=menu_config.CC, CCFLAGS = menu_config.CFLAGS,
                  LINKFLAGS = menu_config.LFLAGS)

#env.PrependENVPath('PATH', menu_config.EXEC_PATH)
env.Append(LIBS = ['mingw32'])




GUI_ENGINE = os.path.abspath('./../gui_engine/')
LVGL_ROOT = os.path.abspath('./../lvgl/')

Export('TOOL_ROOT')
Export('GUI_ENGINE')
Export('LVGL_ROOT')


print('TOOL ROOT = ' + TOOL_ROOT)
print('RTK GUI ENGINE ROOT = ' + GUI_ENGINE)
print('LVGL ROOT = ' + LVGL_ROOT)

# prepare building environment
objs = PrepareBuilding(env, TOOL_ROOT, has_libcpu=False)


# include app
objs.extend(SConscript(os.path.join(GUI_ENGINE, 'SConscript')))
objs.extend(SConscript(os.path.join(LVGL_ROOT, 'SConscript')))

# bsp_vdir = 'build'

# make a building
DoBuilding(TARGET, objs)
