# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

group = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_EXAMPLE_MENU_CELLULAR_WIDGET'):
    src += ['example_gui_menu_cellular.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
    
Return('group')

