# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')


CPPPATH = [cwd]

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_DEMO']

group = DefineGroup('gui_demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
