# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

group = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_REAL_BASE'):
    src += ['app_ui_realgui_base.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_PAINTENGINE'):
    src += ['app_ui_paintengine.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_DEMO_APP'):
    src += ['app_ui_lvgl.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_ARM2D_DEMO_APP'):
    src += ['app_ui_arm2d.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')

