

from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

if GetDepend(['NT35510_480800_DBIB']):
    src += ['nt35510_480800_dbib.c']
if GetDepend(['SH8601A_454454_QSPI']):
    src += ['sh8601a_454454_qspi.c']
if GetDepend(['SH8601A_454454_MIPI_CMD']):
    src += ['SH8601A_454454_mipi_cmd.c']
if GetDepend(['SH8601A_454454_MIPI_VIDEO']):
    src += ['sh8601a_454454_mipi_video.c']
if GetDepend(['OTM8009A_480800_MIPI_CMD']):
    src += ['otm8009a_480800_mipi_cmd.c']
if GetDepend(['OTM8009A_480800_MIPI_VIDEO']):
    src += ['otm8009a_480800_mipi_video.c']
if GetDepend(['ST7701S_360640_RGB']):
    src += ['st7701s_360640_rgb.c']
if GetDepend(['ST7701S_480480_MIPI_VIDEO']):
    src += ['ST7701S_480480_mipi_video.c']

CPPPATH = [cwd]

group = DefineGroup('lcd_low_driver', src, depend = [''], CPPPATH = CPPPATH)
# print(src)
# print(group)

Return('group')