# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

objs = DefineGroup('realgui/input', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('objs')
