/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_FITNESS_PB_H_INCLUDED
#define PB_WEAR_FITNESS_PB_H_INCLUDED
#include <pb.h>

#include "wear_common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _GpsAccuracy
{
    GpsAccuracy_GPS_LOW = 0,
    GpsAccuracy_GPS_MEDIUM = 1,
    GpsAccuracy_GPS_HIGH = 2,
    GpsAccuracy_GPS_UNKNOWN = 10
} GpsAccuracy;
#define _GpsAccuracy_MIN GpsAccuracy_GPS_LOW
#define _GpsAccuracy_MAX GpsAccuracy_GPS_UNKNOWN
#define _GpsAccuracy_ARRAYSIZE ((GpsAccuracy)(GpsAccuracy_GPS_UNKNOWN+1))

typedef enum _GYMCapability
{
    GYMCapability_GYM_SAVE_DATA = 1,
    GYMCapability_GYM_RECEIVE_ASSIST = 2
} GYMCapability;
#define _GYMCapability_MIN GYMCapability_GYM_SAVE_DATA
#define _GYMCapability_MAX GYMCapability_GYM_RECEIVE_ASSIST
#define _GYMCapability_ARRAYSIZE ((GYMCapability)(GYMCapability_GYM_RECEIVE_ASSIST+1))

typedef enum _Fitness_FitnessID
{
    Fitness_FitnessID_SET_USER_PROFILE = 0,
    Fitness_FitnessID_GET_TODAY_FITNESS_IDS = 1,
    Fitness_FitnessID_GET_HISTORY_FITNESS_IDS = 2,
    Fitness_FitnessID_REQUEST_FITNESS_IDS = 3,
    Fitness_FitnessID_REQUEST_FITNESS_ID = 4,
    Fitness_FitnessID_CONFIRM_FITNESS_ID = 5,
    Fitness_FitnessID_GET_REMAINING_SPORT_DATA = 6,
    Fitness_FitnessID_GET_BLOOD_OXYGEN_MONITOR = 8,
    Fitness_FitnessID_SET_BLOOD_OXYGEN_MONITOR = 9,
    Fitness_FitnessID_GET_HEART_RATE_MONITOR = 10,
    Fitness_FitnessID_SET_HEART_RATE_MONITOR = 11,
    Fitness_FitnessID_GET_SEDENTARY_REMINDER = 12,
    Fitness_FitnessID_SET_SEDENTARY_REMINDER = 13,
    Fitness_FitnessID_GET_PRESSURE_MONITOR = 14,
    Fitness_FitnessID_SET_PRESSURE_MONITOR = 15,
    Fitness_FitnessID_START_PRESSURE_CALIBRATE = 23,
    Fitness_FitnessID_STOP_PRESSURE_CALIBRATE = 24,
    Fitness_FitnessID_COMPLETE_PRESSURE_CALIBRATE = 25,
    Fitness_FitnessID_SPORT_REQUEST = 26,
    Fitness_FitnessID_PHONE_SPORT_DATA = 27,
    Fitness_FitnessID_WEAR_SPORT_DATA = 28,
    Fitness_FitnessID_GET_SPORT_STATUS = 29,
    Fitness_FitnessID_SPORT_PRE_REQUEST = 30,
    Fitness_FitnessID_ECG_REQUEST = 32,
    Fitness_FitnessID_REPORT_ECG_DATA = 33,
    Fitness_FitnessID_REPORT_ECG_STATUS = 34,
    Fitness_FitnessID_REQUEST_WOMEN_HEALTH = 37,
    Fitness_FitnessID_SYNC_WOMEN_HEALTH = 38,
    Fitness_FitnessID_SET_WOMEN_HEALTH_FORCAST = 39,
    Fitness_FitnessID_SET_WOMEN_HEALTH_REMINDER = 40,
    Fitness_FitnessID_SYNC_SLEEP_RESULT = 41,
    Fitness_FitnessID_GET_GOAL_STATUS = 42,
    Fitness_FitnessID_SET_GOAL_STATUS = 43,
    Fitness_FitnessID_GET_BASIC_DATA = 44,
    Fitness_FitnessID_REGISTER_BASIC_DATA_REPORT = 45,
    Fitness_FitnessID_UNREGISTER_BASIC_DATA_REPORT = 46,
    Fitness_FitnessID_REPORT_BASIC_DATA = 47,
    Fitness_FitnessID_SYNC_VITALITY_DATA = 51,
    Fitness_FitnessID_SYNC_BEST_SPORT_DATA = 52,
    Fitness_FitnessID_PHONE_SPORT_DATA_V2D = 48,
    Fitness_FitnessID_PHONE_SPORT_DATA_V2A = 49,
    Fitness_FitnessID_WEAR_SPORT_DATA_V2A = 50,
    Fitness_FitnessID_GYM_REQUEST = 64,
    Fitness_FitnessID_GYM_ASSIST = 65,
    Fitness_FitnessID_GYM_DATA = 66,
    Fitness_FitnessID_GET_GYM_SETTINGS = 67,
    Fitness_FitnessID_SET_GYM_SETTINGS = 68
} Fitness_FitnessID;
#define _Fitness_FitnessID_MIN Fitness_FitnessID_SET_USER_PROFILE
#define _Fitness_FitnessID_MAX Fitness_FitnessID_SET_GYM_SETTINGS
#define _Fitness_FitnessID_ARRAYSIZE ((Fitness_FitnessID)(Fitness_FitnessID_SET_GYM_SETTINGS+1))

typedef enum _BloodOxygenMonitor_Mode
{
    BloodOxygenMonitor_Mode_OFF = 0,
    BloodOxygenMonitor_Mode_SLEEP_ON = 1,
    BloodOxygenMonitor_Mode_ALL_DAY_ON = 2
} BloodOxygenMonitor_Mode;
#define _BloodOxygenMonitor_Mode_MIN BloodOxygenMonitor_Mode_OFF
#define _BloodOxygenMonitor_Mode_MAX BloodOxygenMonitor_Mode_ALL_DAY_ON
#define _BloodOxygenMonitor_Mode_ARRAYSIZE ((BloodOxygenMonitor_Mode)(BloodOxygenMonitor_Mode_ALL_DAY_ON+1))

typedef enum _HeartRateMonitor_Mode
{
    HeartRateMonitor_Mode_AUTO = 0,
    HeartRateMonitor_Mode_OFF = 1
} HeartRateMonitor_Mode;
#define _HeartRateMonitor_Mode_MIN HeartRateMonitor_Mode_AUTO
#define _HeartRateMonitor_Mode_MAX HeartRateMonitor_Mode_OFF
#define _HeartRateMonitor_Mode_ARRAYSIZE ((HeartRateMonitor_Mode)(HeartRateMonitor_Mode_OFF+1))

typedef enum _PressureCalibrate_Code
{
    PressureCalibrate_Code_OK = 0,
    PressureCalibrate_Code_NOT_WEARING = 1,
    PressureCalibrate_Code_IN_SPORT = 2,
    PressureCalibrate_Code_NOT_IN_CALIBRATING = 3,
    PressureCalibrate_Code_UNKNOWN = 10
} PressureCalibrate_Code;
#define _PressureCalibrate_Code_MIN PressureCalibrate_Code_OK
#define _PressureCalibrate_Code_MAX PressureCalibrate_Code_UNKNOWN
#define _PressureCalibrate_Code_ARRAYSIZE ((PressureCalibrate_Code)(PressureCalibrate_Code_UNKNOWN+1))

typedef enum _Goal_Type
{
    Goal_Type_STEP = 1,
    Goal_Type_CALORIE = 2,
    Goal_Type_INTENSITY = 3,
    Goal_Type_STAND = 4
} Goal_Type;
#define _Goal_Type_MIN Goal_Type_STEP
#define _Goal_Type_MAX Goal_Type_STAND
#define _Goal_Type_ARRAYSIZE ((Goal_Type)(Goal_Type_STAND+1))

typedef enum _SportResponse_Code
{
    SportResponse_Code_OK = 0,
    SportResponse_Code_BUSY = 1,
    SportResponse_Code_TYPE_NOT_MATCH = 2,
    SportResponse_Code_NO_PERMISSION = 3,
    SportResponse_Code_SPORT_NOT_SUPPORT = 4,
    SportResponse_Code_LACK_OF_ACCURACY = 5,
    SportResponse_Code_CHARGING = 6,
    SportResponse_Code_LOW_BATTERY = 7,
    SportResponse_Code_VERSION_NOT_SUPPORT = 8,
    SportResponse_Code_UNKNOWN = 10
} SportResponse_Code;
#define _SportResponse_Code_MIN SportResponse_Code_OK
#define _SportResponse_Code_MAX SportResponse_Code_UNKNOWN
#define _SportResponse_Code_ARRAYSIZE ((SportResponse_Code)(SportResponse_Code_UNKNOWN+1))

typedef enum _GYMSetting_Key
{
    GYMSetting_Key_CHILD_LOCK = 0,
    GYMSetting_Key_SAFETY_LOCK = 1,
    GYMSetting_Key_DEVICE_LOCK = 2,
    GYMSetting_Key_DEVICE_IN_DEBUG_MODE = 3,
    GYMSetting_Key_SPEED_UP_LIMIT = 4
} GYMSetting_Key;
#define _GYMSetting_Key_MIN GYMSetting_Key_CHILD_LOCK
#define _GYMSetting_Key_MAX GYMSetting_Key_SPEED_UP_LIMIT
#define _GYMSetting_Key_ARRAYSIZE ((GYMSetting_Key)(GYMSetting_Key_SPEED_UP_LIMIT+1))

typedef enum _GYMResponse_Code
{
    GYMResponse_Code_OK = 0,
    GYMResponse_Code_BUSY = 1,
    GYMResponse_Code_TYPE_NOT_MATCH = 2,
    GYMResponse_Code_SPORT_NOT_SUPPORT = 3,
    GYMResponse_Code_LOW_BATTERY = 4,
    GYMResponse_Code_CHILD_LOCK = 5,
    GYMResponse_Code_SAFETY_LOCK = 6,
    GYMResponse_Code_DEVICE_LOCK = 7,
    GYMResponse_Code_DEVICE_IN_DEBUG_MODE = 8,
    GYMResponse_Code_DEVICE_IN_OTA = 9,
    GYMResponse_Code_UNKNOWN = 16
} GYMResponse_Code;
#define _GYMResponse_Code_MIN GYMResponse_Code_OK
#define _GYMResponse_Code_MAX GYMResponse_Code_UNKNOWN
#define _GYMResponse_Code_ARRAYSIZE ((GYMResponse_Code)(GYMResponse_Code_UNKNOWN+1))

typedef enum _ECGRequest_Type
{
    ECGRequest_Type_HANDHELD = 0,
    ECGRequest_Type_FITTING = 1
} ECGRequest_Type;
#define _ECGRequest_Type_MIN ECGRequest_Type_HANDHELD
#define _ECGRequest_Type_MAX ECGRequest_Type_FITTING
#define _ECGRequest_Type_ARRAYSIZE ((ECGRequest_Type)(ECGRequest_Type_FITTING+1))

typedef enum _ECGRequest_State
{
    ECGRequest_State_START = 0,
    ECGRequest_State_STOP = 1
} ECGRequest_State;
#define _ECGRequest_State_MIN ECGRequest_State_START
#define _ECGRequest_State_MAX ECGRequest_State_STOP
#define _ECGRequest_State_ARRAYSIZE ((ECGRequest_State)(ECGRequest_State_STOP+1))

typedef enum _ECGResponse_Code
{
    ECGResponse_Code_READY = 0,
    ECGResponse_Code_BUSY = 1,
    ECGResponse_Code_FALL_OFF = 2,
    ECGResponse_Code_IN_SPORT = 3,
    ECGResponse_Code_CHARGING = 4,
    ECGResponse_Code_FAIL = 10
} ECGResponse_Code;
#define _ECGResponse_Code_MIN ECGResponse_Code_READY
#define _ECGResponse_Code_MAX ECGResponse_Code_FAIL
#define _ECGResponse_Code_ARRAYSIZE ((ECGResponse_Code)(ECGResponse_Code_FAIL+1))

typedef enum _ECGStatus_Status
{
    ECGStatus_Status_FALL_OFF = 0,
    ECGStatus_Status_WEAR_ON = 1
} ECGStatus_Status;
#define _ECGStatus_Status_MIN ECGStatus_Status_FALL_OFF
#define _ECGStatus_Status_MAX ECGStatus_Status_WEAR_ON
#define _ECGStatus_Status_ARRAYSIZE ((ECGStatus_Status)(ECGStatus_Status_WEAR_ON+1))

typedef enum _WomenHealth_Type
{
    WomenHealth_Type_NORMAL = 0,
    WomenHealth_Type_MENSTRUATION = 1,
    WomenHealth_Type_OVULATION = 2,
    WomenHealth_Type_EASY_PREGNANCY = 3
} WomenHealth_Type;
#define _WomenHealth_Type_MIN WomenHealth_Type_NORMAL
#define _WomenHealth_Type_MAX WomenHealth_Type_EASY_PREGNANCY
#define _WomenHealth_Type_ARRAYSIZE ((WomenHealth_Type)(WomenHealth_Type_EASY_PREGNANCY+1))

/* Struct definitions */
typedef struct _BestSportData_List
{
    pb_size_t sport_data_list_count;
    struct _BestSportData *sport_data_list;
    /* @@protoc_insertion_point(struct:BestSportData_List) */
} BestSportData_List;

typedef struct _GYMSetting_List
{
    pb_size_t list_count;
    struct _GYMSetting *list;
    /* @@protoc_insertion_point(struct:GYMSetting_List) */
} GYMSetting_List;

typedef struct _Goal_Status
{
    pb_size_t current_goals_count;
    struct _Goal *current_goals;
    pb_size_t supported_goals_count;
    struct _Goal *supported_goals;
    /* @@protoc_insertion_point(struct:Goal_Status) */
} Goal_Status;

typedef struct _PressureCalibrate
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:PressureCalibrate) */
} PressureCalibrate;

typedef struct _RemainingSportData_List
{
    pb_size_t list_count;
    struct _RemainingSportData *list;
    /* @@protoc_insertion_point(struct:RemainingSportData_List) */
} RemainingSportData_List;

typedef struct _SleepResult
{
    pb_size_t section_list_count;
    struct _SleepResult_Section *section_list;
    /* @@protoc_insertion_point(struct:SleepResult) */
} SleepResult;

typedef struct _VitalityData
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:VitalityData) */
} VitalityData;

typedef struct _WomenHealth_Reminder_List
{
    pb_size_t list_count;
    struct _WomenHealth_Reminder *list;
    /* @@protoc_insertion_point(struct:WomenHealth_Reminder_List) */
} WomenHealth_Reminder_List;

typedef struct _BasicData
{
    uint32_t steps;
    uint16_t calories;
    bool has_distance;
    uint32_t distance;
    bool has_heart_rate;
    uint8_t heart_rate;
    bool has_intensity;
    uint16_t intensity;
    bool has_valid_stand;
    uint8_t valid_stand;
    /* @@protoc_insertion_point(struct:BasicData) */
} BasicData;

typedef struct _BestSportData
{
    SportType sport_type;
    uint32_t duration;
    bool has_distance;
    uint32_t distance;
    /* @@protoc_insertion_point(struct:BestSportData) */
} BestSportData;

typedef struct _ECGData
{
    pb_bytes_array_t *sampling_data;
    bool has_heart_rate;
    uint8_t heart_rate;
    /* @@protoc_insertion_point(struct:ECGData) */
} ECGData;

typedef struct _ECGRequest
{
    ECGRequest_Type type;
    ECGRequest_State state;
    bool has_expected_duration;
    uint8_t expected_duration;
    /* @@protoc_insertion_point(struct:ECGRequest) */
} ECGRequest;

typedef struct _ECGResponse
{
    ECGResponse_Code code;
    /* @@protoc_insertion_point(struct:ECGResponse) */
} ECGResponse;

typedef struct _ECGStatus
{
    ECGStatus_Status status;
    /* @@protoc_insertion_point(struct:ECGStatus) */
} ECGStatus;

typedef struct _GYMAssist
{
    bool has_heart_rate;
    uint8_t heart_rate;
    bool has_adjust_speed;
    float adjust_speed;
    bool has_adjust_pace;
    uint32_t adjust_pace;
    bool has_adjust_resistance_level;
    uint8_t adjust_resistance_level;
    /* @@protoc_insertion_point(struct:GYMAssist) */
} GYMAssist;

typedef struct _GYMData
{
    uint32_t duration;
    bool has_calories;
    uint16_t calories;
    bool has_heart_rate;
    uint8_t heart_rate;
    bool has_distance;
    uint32_t distance;
    bool has_steps;
    uint32_t steps;
    bool has_step_frequency;
    uint16_t step_frequency;
    bool has_current_pace;
    uint32_t current_pace;
    bool has_speed;
    float speed;
    bool has_current_rpm;
    uint8_t current_rpm;
    bool has_revolution_count;
    uint32_t revolution_count;
    bool has_current_power;
    uint16_t current_power;
    bool has_current_resistance_level;
    uint8_t current_resistance_level;
    bool has_jump_count;
    uint32_t jump_count;
    bool has_jump_height;
    uint32_t jump_height;
    bool has_stumble_count;
    uint16_t stumble_count;
    /* @@protoc_insertion_point(struct:GYMData) */
} GYMData;

typedef struct _GYMSetting
{
    GYMSetting_Key key;
    int16_t value;
    /* @@protoc_insertion_point(struct:GYMSetting) */
} GYMSetting;

typedef struct _Goal
{
    Goal_Type type;
    /* @@protoc_insertion_point(struct:Goal) */
} Goal;

typedef struct _HeartRateMonitor_AssistSleep
{
    bool on;
    /* @@protoc_insertion_point(struct:HeartRateMonitor_AssistSleep) */
} HeartRateMonitor_AssistSleep;

typedef struct _PhoneSportData
{
    uint32_t distance;
    uint32_t pace;
    GpsAccuracy gps_accuracy;
    /* @@protoc_insertion_point(struct:PhoneSportData) */
} PhoneSportData;

typedef struct _PhoneSportDataV2A
{
    uint32_t duration;
    uint8_t heart_rate;
    uint16_t calories;
    bool has_distance;
    uint32_t distance;
    bool has_current_pace;
    uint32_t current_pace;
    bool has_average_pace;
    uint32_t average_pace;
    bool has_steps;
    uint32_t steps;
    bool has_stride;
    uint16_t stride;
    bool has_stride_frequency;
    uint16_t stride_frequency;
    bool has_rise;
    float rise;
    bool has_decline;
    float decline;
    bool has_reminder_kilometre_duration;
    uint32_t reminder_kilometre_duration;
    bool has_reminder_kilometre_pace;
    uint32_t reminder_kilometre_pace;
    bool has_reminder_pace;
    uint32_t reminder_pace;
    bool has_reminder_heart_rate;
    uint8_t reminder_heart_rate;
    /* @@protoc_insertion_point(struct:PhoneSportDataV2A) */
} PhoneSportDataV2A;

typedef struct _PhoneSportDataV2D
{
    GpsAccuracy gps_accuracy;
    uint32_t timestamp;
    double longitude;
    double latitude;
    bool has_altitude;
    double altitude;
    bool has_speed;
    float speed;
    bool has_bearing;
    float bearing;
    bool has_horizontal_accuracy;
    float horizontal_accuracy;
    bool has_vertical_accuracy;
    float vertical_accuracy;
    /* @@protoc_insertion_point(struct:PhoneSportDataV2D) */
} PhoneSportDataV2D;

typedef struct _PressureCalibrate_CalibrationResult
{
    PressureCalibrate_Code code;
    bool has_current_pressure;
    uint8_t current_pressure;
    /* @@protoc_insertion_point(struct:PressureCalibrate_CalibrationResult) */
} PressureCalibrate_CalibrationResult;

typedef struct _PressureCalibrate_EvaluationResult
{
    uint8_t value;
    /* @@protoc_insertion_point(struct:PressureCalibrate_EvaluationResult) */
} PressureCalibrate_EvaluationResult;

typedef struct _PressureCalibrate_Response
{
    PressureCalibrate_Code code;
    bool has_need_collect_time;
    uint16_t need_collect_time;
    /* @@protoc_insertion_point(struct:PressureCalibrate_Response) */
} PressureCalibrate_Response;

typedef struct _RemainingSportData
{
    pb_bytes_array_t *ids;
    bool has_sport_course_type;
    uint8_t sport_course_type;
    bool has_cloud_course_id;
    uint64_t cloud_course_id;
    bool has_duration;
    uint32_t duration;
    bool has_distance;
    uint32_t distance;
    /* @@protoc_insertion_point(struct:RemainingSportData) */
} RemainingSportData;

typedef struct _SedentaryReminder
{
    bool on;
    Time start_time;
    Time end_time;
    bool no_disturb_in_launch_break;
    bool has_stretch_guide;
    OptionalSwitcher stretch_guide;
    bool has_launch_break_start_time;
    Time launch_break_start_time;
    bool has_launch_break_end_time;
    Time launch_break_end_time;
    /* @@protoc_insertion_point(struct:SedentaryReminder) */
} SedentaryReminder;

typedef struct _SleepResult_Section
{
    Timezone timezone;
    uint32_t valid_sleep_time;
    uint32_t sleep_timestamp;
    uint32_t wakeup_timestamp;
    uint8_t average_heart_rate;
    uint8_t average_blood_oxygen;
    /* @@protoc_insertion_point(struct:SleepResult_Section) */
} SleepResult_Section;

typedef struct _SportCourse
{
    uint8_t sport_course_type;
    bool has_cloud_course_id;
    uint64_t cloud_course_id;
    char *course_name;
    /* @@protoc_insertion_point(struct:SportCourse) */
} SportCourse;

typedef struct _SportPreRequest
{
    SportType sport_type;
    uint8_t support_versions;
    bool has_main_sport_type;
    SportType main_sport_type;
    /* @@protoc_insertion_point(struct:SportPreRequest) */
} SportPreRequest;

typedef struct _SportPreResponse
{
    SportResponse_Code code;
    uint8_t select_version;
    bool has_gps_accuracy;
    GpsAccuracy gps_accuracy;
    /* @@protoc_insertion_point(struct:SportPreResponse) */
} SportPreResponse;

typedef struct _SportTarget
{
    SportTargetType type;
    uint32_t value;
    /* @@protoc_insertion_point(struct:SportTarget) */
} SportTarget;

typedef struct _SyncParam
{
    uint8_t reason;
    /* @@protoc_insertion_point(struct:SyncParam) */
} SyncParam;

typedef struct _UserProfile
{
    bool has_height;
    uint16_t height;
    bool has_weight;
    float weight;
    bool has_birth;
    uint32_t birth;
    bool has_sex;
    Sex sex;
    bool has_max_hr;
    uint16_t max_hr;
    bool has_goal_calorie;
    uint16_t goal_calorie;
    bool has_goal_step;
    uint16_t goal_step;
    bool has_maximal_met;
    float maximal_met;
    bool has_goal_valid_stand;
    uint8_t goal_valid_stand;
    bool has_goal_sleep;
    uint16_t goal_sleep;
    bool has_goal_intensity;
    uint16_t goal_intensity;
    /* @@protoc_insertion_point(struct:UserProfile) */
} UserProfile;

typedef struct _VitalityData_Item
{
    Goal_Type type;
    uint32_t total;
    bool has_interval;
    uint8_t interval;
    pb_size_t detail_count;
    uint32_t *detail;
    /* @@protoc_insertion_point(struct:VitalityData_Item) */
} VitalityData_Item;

typedef struct _VitalityData_List
{
    bool has_timestamp;
    uint32_t timestamp;
    pb_size_t list_count;
    struct _VitalityData_Item *list;
    /* @@protoc_insertion_point(struct:VitalityData_List) */
} VitalityData_List;

typedef struct _WarningOption
{
    bool warning;
    uint16_t warning_value;
    /* @@protoc_insertion_point(struct:WarningOption) */
} WarningOption;

typedef struct _WearSportData
{
    uint32_t steps;
    uint16_t calories;
    uint8_t heart_rate;
    bool has_max_heart_rate;
    uint8_t max_heart_rate;
    bool has_min_heart_rate;
    uint8_t min_heart_rate;
    /* @@protoc_insertion_point(struct:WearSportData) */
} WearSportData;

typedef struct _WearSportDataV2A
{
    uint8_t heart_rate;
    uint16_t calories;
    bool has_steps;
    uint32_t steps;
    bool has_distance;
    uint32_t distance;
    /* @@protoc_insertion_point(struct:WearSportDataV2A) */
} WearSportDataV2A;

typedef struct _WomenHealth_Data
{
    WomenHealth_Type type;
    bool forcast;
    /* @@protoc_insertion_point(struct:WomenHealth_Data) */
} WomenHealth_Data;

typedef struct _WomenHealth_Data_List
{
    uint32_t timestamp;
    Timezone timezone;
    pb_size_t list_count;
    struct _WomenHealth_Data *list;
    bool has_last_timestamp;
    uint32_t last_timestamp;
    bool has_last_days;
    uint8_t last_days;
    bool has_next_timestamp;
    uint32_t next_timestamp;
    bool has_next_type;
    WomenHealth_Type next_type;
    /* @@protoc_insertion_point(struct:WomenHealth_Data_List) */
} WomenHealth_Data_List;

typedef struct _WomenHealth_Reminder
{
    WomenHealth_Type type;
    uint8_t advanced_days;
    /* @@protoc_insertion_point(struct:WomenHealth_Reminder) */
} WomenHealth_Reminder;

typedef struct _BloodOxygenMonitor
{
    bool support_all_day;
    BloodOxygenMonitor_Mode mode;
    bool has_frequency;
    uint8_t frequency;
    bool has_warning_non_sleep;
    WarningOption warning_non_sleep;
    /* @@protoc_insertion_point(struct:BloodOxygenMonitor) */
} BloodOxygenMonitor;

typedef struct _GYMRequest
{
    uint32_t timestamp;
    Timezone timezone;
    SportType sport_type;
    SportState state;
    pb_size_t sport_target_list_count;
    struct _SportTarget *sport_target_list;
    bool has_sport_course;
    SportCourse sport_course;
    bool has_gym_capability;
    uint8_t gym_capability;
    pb_bytes_array_t *ids;
    bool has_main_sport_type;
    SportType main_sport_type;
    /* @@protoc_insertion_point(struct:GYMRequest) */
} GYMRequest;

typedef struct _HeartRateMonitor
{
    HeartRateMonitor_Mode mode;
    uint8_t frequency;
    bool warning;
    uint16_t warning_value;
    bool has_assit_sleep;
    HeartRateMonitor_AssistSleep assit_sleep;
    bool has_warning_sport;
    WarningOption warning_sport;
    bool has_support_intelligent_monitor;
    bool support_intelligent_monitor;
    bool has_warning_low;
    WarningOption warning_low;
    bool has_sleep_breathe_quality;
    OptionalSwitcher sleep_breathe_quality;
    bool has_abnormal_cardiac;
    OptionalSwitcher abnormal_cardiac;
    /* @@protoc_insertion_point(struct:HeartRateMonitor) */
} HeartRateMonitor;

typedef struct _PressureMonitor
{
    bool on;
    bool has_warning_non_sleep;
    WarningOption warning_non_sleep;
    /* @@protoc_insertion_point(struct:PressureMonitor) */
} PressureMonitor;

typedef struct _SportRequest
{
    uint32_t timestamp;
    Timezone timezone;
    SportType sport_type;
    SportState state;
    pb_bytes_array_t *ids;
    bool has_support_versions;
    uint8_t support_versions;
    pb_size_t sport_target_list_count;
    struct _SportTarget *sport_target_list;
    bool has_sport_course;
    SportCourse sport_course;
    bool has_main_sport_type;
    SportType main_sport_type;
    /* @@protoc_insertion_point(struct:SportRequest) */
} SportRequest;

typedef struct _SportStatus
{
    SportType sport_type;
    bool has_timestamp;
    uint32_t timestamp;
    bool has_timezone;
    Timezone timezone;
    bool has_duration;
    uint32_t duration;
    bool has_paused;
    bool paused;
    bool has_standalone;
    bool standalone;
    bool has_select_version;
    uint8_t select_version;
    bool has_app_launched;
    bool app_launched;
    pb_size_t sport_target_list_count;
    struct _SportTarget *sport_target_list;
    bool has_sport_course;
    SportCourse sport_course;
    bool has_main_sport_type;
    SportType main_sport_type;
    /* @@protoc_insertion_point(struct:SportStatus) */
} SportStatus;

typedef struct _WomenHealth
{
    bool enabled;
    bool has_forcast_on;
    bool forcast_on;
    bool has_reminder_list;
    WomenHealth_Reminder_List reminder_list;
    bool has_data_list;
    WomenHealth_Data_List data_list;
    /* @@protoc_insertion_point(struct:WomenHealth) */
} WomenHealth;

typedef struct _GYMResponse
{
    GYMResponse_Code code;
    bool has_gym_capability;
    uint8_t gym_capability;
    pb_bytes_array_t *ids;
    bool has_sport_status;
    SportStatus sport_status;
    /* @@protoc_insertion_point(struct:GYMResponse) */
} GYMResponse;

typedef struct _SportResponse
{
    SportResponse_Code code;
    pb_bytes_array_t *ids;
    bool has_sport_status;
    SportStatus sport_status;
    bool has_gps_accuracy;
    GpsAccuracy gps_accuracy;
    bool has_select_version;
    uint8_t select_version;
    /* @@protoc_insertion_point(struct:SportResponse) */
} SportResponse;

typedef struct _Fitness
{
    pb_size_t which_payload;
    union
    {
        UserProfile user_profile;
        pb_bytes_array_t *ids;
        pb_bytes_array_t *id;
        RemainingSportData_List remaining_sport_data_list;
        SyncParam sync_param;
        BloodOxygenMonitor blood_oxygen_monitor;
        HeartRateMonitor heart_rate_monitor;
        SedentaryReminder sedentary_reminder;
        PressureMonitor pressure_monitor;
        PressureCalibrate_Response pressur_calibrate_response;
        PressureCalibrate_EvaluationResult evaluation_result;
        PressureCalibrate_CalibrationResult calibration_result;
        SportRequest sport_request;
        SportResponse sport_response;
        PhoneSportData phone_sport_data;
        WearSportData wear_sport_data;
        SportStatus sport_status;
        SportPreRequest sport_pre_request;
        SportPreResponse sport_pre_response;
        ECGRequest ecg_request;
        ECGResponse ecg_response;
        ECGData ecg_data;
        ECGStatus ecg_status;
        WomenHealth women_health;
        bool forcast_on;
        WomenHealth_Reminder_List reminder_list;
        SleepResult sleep_result;
        Goal_Status goal_status;
        BasicData basic_data;
        PhoneSportDataV2D phone_sport_data_v2d;
        PhoneSportDataV2A phone_sport_data_v2a;
        WearSportDataV2A wear_sport_data_v2a;
        VitalityData_List vitality_data_list;
        BestSportData_List sport_data_list;
        GYMRequest gym_request;
        GYMResponse gym_response;
        GYMAssist gym_assist;
        GYMData gym_data;
        GYMSetting_List gym_setting_list;
    } payload;
    /* @@protoc_insertion_point(struct:Fitness) */
} Fitness;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Fitness_init_default                     {0, {UserProfile_init_default}}
#define UserProfile_init_default                 {false, 0, false, 0, false, 0, false, _Sex_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define SyncParam_init_default                   {0}
#define RemainingSportData_init_default          {NULL, false, 0, false, 0, false, 0, false, 0}
#define RemainingSportData_List_init_default     {0, NULL}
#define WarningOption_init_default               {0, 0}
#define BloodOxygenMonitor_init_default          {0, _BloodOxygenMonitor_Mode_MIN, false, 0, false, WarningOption_init_default}
#define HeartRateMonitor_init_default            {_HeartRateMonitor_Mode_MIN, 0, 0, 0, false, HeartRateMonitor_AssistSleep_init_default, false, WarningOption_init_default, false, 0, false, WarningOption_init_default, false, _OptionalSwitcher_MIN, false, _OptionalSwitcher_MIN}
#define HeartRateMonitor_AssistSleep_init_default {0}
#define SedentaryReminder_init_default           {0, Time_init_default, Time_init_default, 0, false, _OptionalSwitcher_MIN, false, Time_init_default, false, Time_init_default}
#define PressureMonitor_init_default             {0, false, WarningOption_init_default}
#define PressureCalibrate_init_default           {0}
#define PressureCalibrate_Response_init_default  {_PressureCalibrate_Code_MIN, false, 0}
#define PressureCalibrate_EvaluationResult_init_default {0}
#define PressureCalibrate_CalibrationResult_init_default {_PressureCalibrate_Code_MIN, false, 0}
#define SleepResult_init_default                 {0, NULL}
#define SleepResult_Section_init_default         {Timezone_init_default, 0, 0, 0, 0, 0}
#define Goal_init_default                        {_Goal_Type_MIN}
#define Goal_Status_init_default                 {0, NULL, 0, NULL}
#define BasicData_init_default                   {0, 0, false, 0, false, 0, false, 0, false, 0}
#define VitalityData_init_default                {0}
#define VitalityData_Item_init_default           {_Goal_Type_MIN, 0, false, 0, 0, NULL}
#define VitalityData_List_init_default           {false, 0, 0, NULL}
#define BestSportData_init_default               {_SportType_MIN, 0, false, 0}
#define BestSportData_List_init_default          {0, NULL}
#define SportTarget_init_default                 {_SportTargetType_MIN, 0}
#define SportCourse_init_default                 {0, false, 0, NULL}
#define SportStatus_init_default                 {_SportType_MIN, false, 0, false, Timezone_init_default, false, 0, false, 0, false, 0, false, 0, false, 0, 0, NULL, false, SportCourse_init_default, false, _SportType_MIN}
#define SportPreRequest_init_default             {_SportType_MIN, 0, false, _SportType_MIN}
#define SportPreResponse_init_default            {_SportResponse_Code_MIN, 0, false, _GpsAccuracy_MIN}
#define SportRequest_init_default                {0, Timezone_init_default, _SportType_MIN, _SportState_MIN, NULL, false, 0, 0, NULL, false, SportCourse_init_default, false, _SportType_MIN}
#define SportResponse_init_default               {_SportResponse_Code_MIN, NULL, false, SportStatus_init_default, false, _GpsAccuracy_MIN, false, 0}
#define PhoneSportData_init_default              {0, 0, _GpsAccuracy_MIN}
#define WearSportData_init_default               {0, 0, 0, false, 0, false, 0}
#define PhoneSportDataV2D_init_default           {_GpsAccuracy_MIN, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define PhoneSportDataV2A_init_default           {0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define WearSportDataV2A_init_default            {0, 0, false, 0, false, 0}
#define GYMSetting_init_default                  {_GYMSetting_Key_MIN, 0}
#define GYMSetting_List_init_default             {0, NULL}
#define GYMRequest_init_default                  {0, Timezone_init_default, _SportType_MIN, _SportState_MIN, 0, NULL, false, SportCourse_init_default, false, 0, NULL, false, _SportType_MIN}
#define GYMResponse_init_default                 {_GYMResponse_Code_MIN, false, 0, NULL, false, SportStatus_init_default}
#define GYMAssist_init_default                   {false, 0, false, 0, false, 0, false, 0}
#define GYMData_init_default                     {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ECGRequest_init_default                  {_ECGRequest_Type_MIN, _ECGRequest_State_MIN, false, 0}
#define ECGResponse_init_default                 {_ECGResponse_Code_MIN}
#define ECGData_init_default                     {NULL, false, 0}
#define ECGStatus_init_default                   {_ECGStatus_Status_MIN}
#define WomenHealth_init_default                 {0, false, 0, false, WomenHealth_Reminder_List_init_default, false, WomenHealth_Data_List_init_default}
#define WomenHealth_Reminder_init_default        {_WomenHealth_Type_MIN, 0}
#define WomenHealth_Reminder_List_init_default   {0, NULL}
#define WomenHealth_Data_init_default            {_WomenHealth_Type_MIN, 0}
#define WomenHealth_Data_List_init_default       {0, Timezone_init_default, 0, NULL, false, 0, false, 0, false, 0, false, _WomenHealth_Type_MIN}
#define Fitness_init_zero                        {0, {UserProfile_init_zero}}
#define UserProfile_init_zero                    {false, 0, false, 0, false, 0, false, _Sex_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define SyncParam_init_zero                      {0}
#define RemainingSportData_init_zero             {NULL, false, 0, false, 0, false, 0, false, 0}
#define RemainingSportData_List_init_zero        {0, NULL}
#define WarningOption_init_zero                  {0, 0}
#define BloodOxygenMonitor_init_zero             {0, _BloodOxygenMonitor_Mode_MIN, false, 0, false, WarningOption_init_zero}
#define HeartRateMonitor_init_zero               {_HeartRateMonitor_Mode_MIN, 0, 0, 0, false, HeartRateMonitor_AssistSleep_init_zero, false, WarningOption_init_zero, false, 0, false, WarningOption_init_zero, false, _OptionalSwitcher_MIN, false, _OptionalSwitcher_MIN}
#define HeartRateMonitor_AssistSleep_init_zero   {0}
#define SedentaryReminder_init_zero              {0, Time_init_zero, Time_init_zero, 0, false, _OptionalSwitcher_MIN, false, Time_init_zero, false, Time_init_zero}
#define PressureMonitor_init_zero                {0, false, WarningOption_init_zero}
#define PressureCalibrate_init_zero              {0}
#define PressureCalibrate_Response_init_zero     {_PressureCalibrate_Code_MIN, false, 0}
#define PressureCalibrate_EvaluationResult_init_zero {0}
#define PressureCalibrate_CalibrationResult_init_zero {_PressureCalibrate_Code_MIN, false, 0}
#define SleepResult_init_zero                    {0, NULL}
#define SleepResult_Section_init_zero            {Timezone_init_zero, 0, 0, 0, 0, 0}
#define Goal_init_zero                           {_Goal_Type_MIN}
#define Goal_Status_init_zero                    {0, NULL, 0, NULL}
#define BasicData_init_zero                      {0, 0, false, 0, false, 0, false, 0, false, 0}
#define VitalityData_init_zero                   {0}
#define VitalityData_Item_init_zero              {_Goal_Type_MIN, 0, false, 0, 0, NULL}
#define VitalityData_List_init_zero              {false, 0, 0, NULL}
#define BestSportData_init_zero                  {_SportType_MIN, 0, false, 0}
#define BestSportData_List_init_zero             {0, NULL}
#define SportTarget_init_zero                    {_SportTargetType_MIN, 0}
#define SportCourse_init_zero                    {0, false, 0, NULL}
#define SportStatus_init_zero                    {_SportType_MIN, false, 0, false, Timezone_init_zero, false, 0, false, 0, false, 0, false, 0, false, 0, 0, NULL, false, SportCourse_init_zero, false, _SportType_MIN}
#define SportPreRequest_init_zero                {_SportType_MIN, 0, false, _SportType_MIN}
#define SportPreResponse_init_zero               {_SportResponse_Code_MIN, 0, false, _GpsAccuracy_MIN}
#define SportRequest_init_zero                   {0, Timezone_init_zero, _SportType_MIN, _SportState_MIN, NULL, false, 0, 0, NULL, false, SportCourse_init_zero, false, _SportType_MIN}
#define SportResponse_init_zero                  {_SportResponse_Code_MIN, NULL, false, SportStatus_init_zero, false, _GpsAccuracy_MIN, false, 0}
#define PhoneSportData_init_zero                 {0, 0, _GpsAccuracy_MIN}
#define WearSportData_init_zero                  {0, 0, 0, false, 0, false, 0}
#define PhoneSportDataV2D_init_zero              {_GpsAccuracy_MIN, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define PhoneSportDataV2A_init_zero              {0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define WearSportDataV2A_init_zero               {0, 0, false, 0, false, 0}
#define GYMSetting_init_zero                     {_GYMSetting_Key_MIN, 0}
#define GYMSetting_List_init_zero                {0, NULL}
#define GYMRequest_init_zero                     {0, Timezone_init_zero, _SportType_MIN, _SportState_MIN, 0, NULL, false, SportCourse_init_zero, false, 0, NULL, false, _SportType_MIN}
#define GYMResponse_init_zero                    {_GYMResponse_Code_MIN, false, 0, NULL, false, SportStatus_init_zero}
#define GYMAssist_init_zero                      {false, 0, false, 0, false, 0, false, 0}
#define GYMData_init_zero                        {0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ECGRequest_init_zero                     {_ECGRequest_Type_MIN, _ECGRequest_State_MIN, false, 0}
#define ECGResponse_init_zero                    {_ECGResponse_Code_MIN}
#define ECGData_init_zero                        {NULL, false, 0}
#define ECGStatus_init_zero                      {_ECGStatus_Status_MIN}
#define WomenHealth_init_zero                    {0, false, 0, false, WomenHealth_Reminder_List_init_zero, false, WomenHealth_Data_List_init_zero}
#define WomenHealth_Reminder_init_zero           {_WomenHealth_Type_MIN, 0}
#define WomenHealth_Reminder_List_init_zero      {0, NULL}
#define WomenHealth_Data_init_zero               {_WomenHealth_Type_MIN, 0}
#define WomenHealth_Data_List_init_zero          {0, Timezone_init_zero, 0, NULL, false, 0, false, 0, false, 0, false, _WomenHealth_Type_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define BestSportData_List_sport_data_list_tag   1
#define GYMSetting_List_list_tag                 1
#define Goal_Status_current_goals_tag            1
#define Goal_Status_supported_goals_tag          2
#define RemainingSportData_List_list_tag         1
#define SleepResult_section_list_tag             1
#define WomenHealth_Reminder_List_list_tag       1
#define BasicData_steps_tag                      1
#define BasicData_calories_tag                   2
#define BasicData_distance_tag                   3
#define BasicData_heart_rate_tag                 4
#define BasicData_intensity_tag                  5
#define BasicData_valid_stand_tag                6
#define BestSportData_sport_type_tag             1
#define BestSportData_duration_tag               2
#define BestSportData_distance_tag               3
#define ECGData_sampling_data_tag                1
#define ECGData_heart_rate_tag                   2
#define ECGRequest_type_tag                      1
#define ECGRequest_state_tag                     2
#define ECGRequest_expected_duration_tag         3
#define ECGResponse_code_tag                     1
#define ECGStatus_status_tag                     1
#define GYMAssist_heart_rate_tag                 1
#define GYMAssist_adjust_speed_tag               2
#define GYMAssist_adjust_pace_tag                3
#define GYMAssist_adjust_resistance_level_tag    4
#define GYMData_duration_tag                     1
#define GYMData_calories_tag                     2
#define GYMData_heart_rate_tag                   3
#define GYMData_distance_tag                     4
#define GYMData_steps_tag                        5
#define GYMData_step_frequency_tag               6
#define GYMData_current_pace_tag                 7
#define GYMData_speed_tag                        8
#define GYMData_current_rpm_tag                  9
#define GYMData_revolution_count_tag             10
#define GYMData_current_power_tag                11
#define GYMData_current_resistance_level_tag     12
#define GYMData_jump_count_tag                   13
#define GYMData_jump_height_tag                  14
#define GYMData_stumble_count_tag                15
#define GYMSetting_key_tag                       1
#define GYMSetting_value_tag                     2
#define Goal_type_tag                            1
#define HeartRateMonitor_AssistSleep_on_tag      1
#define PhoneSportData_distance_tag              1
#define PhoneSportData_pace_tag                  2
#define PhoneSportData_gps_accuracy_tag          3
#define PhoneSportDataV2A_duration_tag           1
#define PhoneSportDataV2A_heart_rate_tag         2
#define PhoneSportDataV2A_calories_tag           3
#define PhoneSportDataV2A_distance_tag           4
#define PhoneSportDataV2A_current_pace_tag       5
#define PhoneSportDataV2A_average_pace_tag       6
#define PhoneSportDataV2A_steps_tag              7
#define PhoneSportDataV2A_stride_tag             8
#define PhoneSportDataV2A_stride_frequency_tag   9
#define PhoneSportDataV2A_rise_tag               10
#define PhoneSportDataV2A_decline_tag            11
#define PhoneSportDataV2A_reminder_kilometre_duration_tag 12
#define PhoneSportDataV2A_reminder_kilometre_pace_tag 13
#define PhoneSportDataV2A_reminder_pace_tag      14
#define PhoneSportDataV2A_reminder_heart_rate_tag 15
#define PhoneSportDataV2D_gps_accuracy_tag       1
#define PhoneSportDataV2D_timestamp_tag          2
#define PhoneSportDataV2D_longitude_tag          3
#define PhoneSportDataV2D_latitude_tag           4
#define PhoneSportDataV2D_altitude_tag           5
#define PhoneSportDataV2D_speed_tag              6
#define PhoneSportDataV2D_bearing_tag            7
#define PhoneSportDataV2D_horizontal_accuracy_tag 8
#define PhoneSportDataV2D_vertical_accuracy_tag  9
#define PressureCalibrate_CalibrationResult_code_tag 1
#define PressureCalibrate_CalibrationResult_current_pressure_tag 2
#define PressureCalibrate_EvaluationResult_value_tag 1
#define PressureCalibrate_Response_code_tag      1
#define PressureCalibrate_Response_need_collect_time_tag 2
#define RemainingSportData_ids_tag               1
#define RemainingSportData_sport_course_type_tag 2
#define RemainingSportData_cloud_course_id_tag   3
#define RemainingSportData_duration_tag          4
#define RemainingSportData_distance_tag          5
#define SedentaryReminder_on_tag                 1
#define SedentaryReminder_start_time_tag         2
#define SedentaryReminder_end_time_tag           3
#define SedentaryReminder_no_disturb_in_launch_break_tag 4
#define SedentaryReminder_launch_break_start_time_tag 6
#define SedentaryReminder_launch_break_end_time_tag 7
#define SedentaryReminder_stretch_guide_tag      5
#define SleepResult_Section_timezone_tag         1
#define SleepResult_Section_valid_sleep_time_tag 2
#define SleepResult_Section_sleep_timestamp_tag  3
#define SleepResult_Section_wakeup_timestamp_tag 4
#define SleepResult_Section_average_heart_rate_tag 5
#define SleepResult_Section_average_blood_oxygen_tag 6
#define SportCourse_sport_course_type_tag        1
#define SportCourse_cloud_course_id_tag          2
#define SportCourse_course_name_tag              3
#define SportPreRequest_sport_type_tag           1
#define SportPreRequest_main_sport_type_tag      3
#define SportPreRequest_support_versions_tag     2
#define SportPreResponse_code_tag                1
#define SportPreResponse_select_version_tag      2
#define SportPreResponse_gps_accuracy_tag        3
#define SportTarget_type_tag                     1
#define SportTarget_value_tag                    2
#define SyncParam_reason_tag                     1
#define UserProfile_height_tag                   1
#define UserProfile_weight_tag                   2
#define UserProfile_birth_tag                    3
#define UserProfile_sex_tag                      4
#define UserProfile_max_hr_tag                   5
#define UserProfile_goal_calorie_tag             6
#define UserProfile_goal_step_tag                7
#define UserProfile_maximal_met_tag              8
#define UserProfile_goal_valid_stand_tag         9
#define UserProfile_goal_sleep_tag               10
#define UserProfile_goal_intensity_tag           11
#define VitalityData_Item_type_tag               1
#define VitalityData_Item_total_tag              2
#define VitalityData_Item_interval_tag           3
#define VitalityData_Item_detail_tag             4
#define VitalityData_List_timestamp_tag          1
#define VitalityData_List_list_tag               2
#define WarningOption_warning_tag                1
#define WarningOption_warning_value_tag          2
#define WearSportData_steps_tag                  1
#define WearSportData_calories_tag               2
#define WearSportData_heart_rate_tag             3
#define WearSportData_max_heart_rate_tag         4
#define WearSportData_min_heart_rate_tag         5
#define WearSportDataV2A_heart_rate_tag          1
#define WearSportDataV2A_calories_tag            2
#define WearSportDataV2A_steps_tag               3
#define WearSportDataV2A_distance_tag            4
#define WomenHealth_Data_type_tag                1
#define WomenHealth_Data_forcast_tag             2
#define WomenHealth_Data_List_timestamp_tag      1
#define WomenHealth_Data_List_timezone_tag       2
#define WomenHealth_Data_List_list_tag           3
#define WomenHealth_Data_List_last_timestamp_tag 4
#define WomenHealth_Data_List_last_days_tag      5
#define WomenHealth_Data_List_next_timestamp_tag 6
#define WomenHealth_Data_List_next_type_tag      7
#define WomenHealth_Reminder_type_tag            1
#define WomenHealth_Reminder_advanced_days_tag   2
#define BloodOxygenMonitor_support_all_day_tag   1
#define BloodOxygenMonitor_mode_tag              2
#define BloodOxygenMonitor_frequency_tag         3
#define BloodOxygenMonitor_warning_non_sleep_tag 4
#define GYMRequest_timestamp_tag                 1
#define GYMRequest_timezone_tag                  2
#define GYMRequest_sport_type_tag                3
#define GYMRequest_main_sport_type_tag           9
#define GYMRequest_state_tag                     4
#define GYMRequest_sport_target_list_tag         5
#define GYMRequest_sport_course_tag              6
#define GYMRequest_gym_capability_tag            7
#define GYMRequest_ids_tag                       8
#define HeartRateMonitor_mode_tag                1
#define HeartRateMonitor_frequency_tag           2
#define HeartRateMonitor_support_intelligent_monitor_tag 7
#define HeartRateMonitor_warning_tag             3
#define HeartRateMonitor_warning_value_tag       4
#define HeartRateMonitor_warning_low_tag         8
#define HeartRateMonitor_abnormal_cardiac_tag    10
#define HeartRateMonitor_assit_sleep_tag         5
#define HeartRateMonitor_sleep_breathe_quality_tag 9
#define HeartRateMonitor_warning_sport_tag       6
#define PressureMonitor_on_tag                   1
#define PressureMonitor_warning_non_sleep_tag    2
#define SportRequest_timestamp_tag               1
#define SportRequest_timezone_tag                2
#define SportRequest_sport_type_tag              3
#define SportRequest_main_sport_type_tag         9
#define SportRequest_state_tag                   4
#define SportRequest_ids_tag                     5
#define SportRequest_support_versions_tag        6
#define SportRequest_sport_target_list_tag       7
#define SportRequest_sport_course_tag            8
#define SportStatus_sport_type_tag               1
#define SportStatus_main_sport_type_tag          11
#define SportStatus_timestamp_tag                2
#define SportStatus_timezone_tag                 3
#define SportStatus_duration_tag                 4
#define SportStatus_paused_tag                   5
#define SportStatus_standalone_tag               6
#define SportStatus_select_version_tag           7
#define SportStatus_app_launched_tag             8
#define SportStatus_sport_target_list_tag        9
#define SportStatus_sport_course_tag             10
#define WomenHealth_enabled_tag                  1
#define WomenHealth_forcast_on_tag               2
#define WomenHealth_reminder_list_tag            3
#define WomenHealth_data_list_tag                4
#define GYMResponse_code_tag                     1
#define GYMResponse_gym_capability_tag           2
#define GYMResponse_ids_tag                      3
#define GYMResponse_sport_status_tag             4
#define SportResponse_code_tag                   1
#define SportResponse_ids_tag                    2
#define SportResponse_sport_status_tag           3
#define SportResponse_gps_accuracy_tag           4
#define SportResponse_select_version_tag         5
#define Fitness_user_profile_tag                 1
#define Fitness_ids_tag                          2
#define Fitness_id_tag                           3
#define Fitness_remaining_sport_data_list_tag    4
#define Fitness_sync_param_tag                   5
#define Fitness_blood_oxygen_monitor_tag         7
#define Fitness_heart_rate_monitor_tag           8
#define Fitness_sedentary_reminder_tag           9
#define Fitness_pressure_monitor_tag             10
#define Fitness_pressur_calibrate_response_tag   17
#define Fitness_evaluation_result_tag            18
#define Fitness_calibration_result_tag           19
#define Fitness_sport_request_tag                20
#define Fitness_sport_response_tag               21
#define Fitness_phone_sport_data_tag             22
#define Fitness_wear_sport_data_tag              23
#define Fitness_sport_status_tag                 24
#define Fitness_sport_pre_request_tag            25
#define Fitness_sport_pre_response_tag           26
#define Fitness_ecg_request_tag                  27
#define Fitness_ecg_response_tag                 28
#define Fitness_ecg_data_tag                     29
#define Fitness_ecg_status_tag                   30
#define Fitness_women_health_tag                 34
#define Fitness_forcast_on_tag                   35
#define Fitness_reminder_list_tag                36
#define Fitness_sleep_result_tag                 37
#define Fitness_goal_status_tag                  38
#define Fitness_basic_data_tag                   39
#define Fitness_phone_sport_data_v2d_tag         40
#define Fitness_phone_sport_data_v2a_tag         41
#define Fitness_wear_sport_data_v2a_tag          42
#define Fitness_vitality_data_list_tag           43
#define Fitness_sport_data_list_tag              44
#define Fitness_gym_request_tag                  50
#define Fitness_gym_response_tag                 51
#define Fitness_gym_assist_tag                   52
#define Fitness_gym_data_tag                     53
#define Fitness_gym_setting_list_tag             54

/* Struct field encoding specification for nanopb */
extern const pb_field_t Fitness_fields[40];
extern const pb_field_t UserProfile_fields[12];
extern const pb_field_t SyncParam_fields[2];
extern const pb_field_t RemainingSportData_fields[6];
extern const pb_field_t RemainingSportData_List_fields[2];
extern const pb_field_t WarningOption_fields[3];
extern const pb_field_t BloodOxygenMonitor_fields[5];
extern const pb_field_t HeartRateMonitor_fields[11];
extern const pb_field_t HeartRateMonitor_AssistSleep_fields[2];
extern const pb_field_t SedentaryReminder_fields[8];
extern const pb_field_t PressureMonitor_fields[3];
extern const pb_field_t PressureCalibrate_fields[1];
extern const pb_field_t PressureCalibrate_Response_fields[3];
extern const pb_field_t PressureCalibrate_EvaluationResult_fields[2];
extern const pb_field_t PressureCalibrate_CalibrationResult_fields[3];
extern const pb_field_t SleepResult_fields[2];
extern const pb_field_t SleepResult_Section_fields[7];
extern const pb_field_t Goal_fields[2];
extern const pb_field_t Goal_Status_fields[3];
extern const pb_field_t BasicData_fields[7];
extern const pb_field_t VitalityData_fields[1];
extern const pb_field_t VitalityData_Item_fields[5];
extern const pb_field_t VitalityData_List_fields[3];
extern const pb_field_t BestSportData_fields[4];
extern const pb_field_t BestSportData_List_fields[2];
extern const pb_field_t SportTarget_fields[3];
extern const pb_field_t SportCourse_fields[4];
extern const pb_field_t SportStatus_fields[12];
extern const pb_field_t SportPreRequest_fields[4];
extern const pb_field_t SportPreResponse_fields[4];
extern const pb_field_t SportRequest_fields[10];
extern const pb_field_t SportResponse_fields[6];
extern const pb_field_t PhoneSportData_fields[4];
extern const pb_field_t WearSportData_fields[6];
extern const pb_field_t PhoneSportDataV2D_fields[10];
extern const pb_field_t PhoneSportDataV2A_fields[16];
extern const pb_field_t WearSportDataV2A_fields[5];
extern const pb_field_t GYMSetting_fields[3];
extern const pb_field_t GYMSetting_List_fields[2];
extern const pb_field_t GYMRequest_fields[10];
extern const pb_field_t GYMResponse_fields[5];
extern const pb_field_t GYMAssist_fields[5];
extern const pb_field_t GYMData_fields[16];
extern const pb_field_t ECGRequest_fields[4];
extern const pb_field_t ECGResponse_fields[2];
extern const pb_field_t ECGData_fields[3];
extern const pb_field_t ECGStatus_fields[2];
extern const pb_field_t WomenHealth_fields[5];
extern const pb_field_t WomenHealth_Reminder_fields[3];
extern const pb_field_t WomenHealth_Reminder_List_fields[2];
extern const pb_field_t WomenHealth_Data_fields[3];
extern const pb_field_t WomenHealth_Data_List_fields[8];

/* Maximum encoded size of messages (where known) */
/* Fitness_size depends on runtime parameters */
#define UserProfile_size                         60
#define SyncParam_size                           6
/* RemainingSportData_size depends on runtime parameters */
/* RemainingSportData_List_size depends on runtime parameters */
#define WarningOption_size                       8
#define BloodOxygenMonitor_size                  20
#define HeartRateMonitor_size                    46
#define HeartRateMonitor_AssistSleep_size        2
#define SedentaryReminder_size                   110
#define PressureMonitor_size                     12
#define PressureCalibrate_size                   0
#define PressureCalibrate_Response_size          8
#define PressureCalibrate_EvaluationResult_size  6
#define PressureCalibrate_CalibrationResult_size 8
/* SleepResult_size depends on runtime parameters */
#define SleepResult_Section_size                 (36 + Timezone_size)
#define Goal_size                                2
/* Goal_Status_size depends on runtime parameters */
#define BasicData_size                           36
#define VitalityData_size                        0
/* VitalityData_Item_size depends on runtime parameters */
/* VitalityData_List_size depends on runtime parameters */
#define BestSportData_size                       15
/* BestSportData_List_size depends on runtime parameters */
#define SportTarget_size                         8
/* SportCourse_size depends on runtime parameters */
/* SportStatus_size depends on runtime parameters */
#define SportPreRequest_size                     12
#define SportPreResponse_size                    10
/* SportRequest_size depends on runtime parameters */
/* SportResponse_size depends on runtime parameters */
#define PhoneSportData_size                      14
#define WearSportData_size                       30
#define PhoneSportDataV2D_size                   55
#define PhoneSportDataV2A_size                   88
#define WearSportDataV2A_size                    24
#define GYMSetting_size                          8
/* GYMSetting_List_size depends on runtime parameters */
/* GYMRequest_size depends on runtime parameters */
/* GYMResponse_size depends on runtime parameters */
#define GYMAssist_size                           23
#define GYMData_size                             89
#define ECGRequest_size                          10
#define ECGResponse_size                         2
/* ECGData_size depends on runtime parameters */
#define ECGStatus_size                           2
/* WomenHealth_size depends on runtime parameters */
#define WomenHealth_Reminder_size                8
/* WomenHealth_Reminder_List_size depends on runtime parameters */
#define WomenHealth_Data_size                    4
/* WomenHealth_Data_List_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_FITNESS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
