/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_PB_H_INCLUDED
#define PB_WEAR_PB_H_INCLUDED
#include <pb.h>

#include "wear_common.pb.h"

#include "wear_account.pb.h"

#include "wear_system.pb.h"

#include "wear_watch_face.pb.h"

#include "wear_nfc.pb.h"

#include "wear_notification.pb.h"

#include "wear_fitness.pb.h"

#include "wear_lpa.pb.h"

#include "wear_weather.pb.h"

#include "wear_stock.pb.h"

#include "wear_calendar.pb.h"

#include "wear_factory.pb.h"

#include "wear_aivs.pb.h"

#include "wear_market.pb.h"

#include "wear_gnss.pb.h"

#include "wear_clock.pb.h"

#include "wear_media.pb.h"

#include "wear_alexa.pb.h"

#include "wear_thirdparty_app.pb.h"

#include "wear_contact.pb.h"

#include "wear_mass.pb.h"

#include "wear_interconnection.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _WearPacket_Type
{
    WearPacket_Type_OTHER = 0,
    WearPacket_Type_ACCOUNT = 1,
    WearPacket_Type_SYSTEM = 2,
    WearPacket_Type_WATCH_FACE = 4,
    WearPacket_Type_NFC = 5,
    WearPacket_Type_NOTIFICATION = 7,
    WearPacket_Type_FITNESS = 8,
    WearPacket_Type_LPA = 9,
    WearPacket_Type_WEATHER = 10,
    WearPacket_Type_STOCK = 11,
    WearPacket_Type_CALENDAR = 12,
    WearPacket_Type_FACTORY = 13,
    WearPacket_Type_AIVS = 14,
    WearPacket_Type_MARKET = 15,
    WearPacket_Type_GNSS = 16,
    WearPacket_Type_CLOCK = 17,
    WearPacket_Type_MEDIA = 18,
    WearPacket_Type_ALEXA = 19,
    WearPacket_Type_THIRDPARTY_APP = 20,
    WearPacket_Type_CONTACT = 21,
    WearPacket_Type_MASS = 22,
    WearPacket_Type_INTERCONNECTION = 23
} WearPacket_Type;
#define _WearPacket_Type_MIN WearPacket_Type_OTHER
#define _WearPacket_Type_MAX WearPacket_Type_INTERCONNECTION
#define _WearPacket_Type_ARRAYSIZE ((WearPacket_Type)(WearPacket_Type_INTERCONNECTION+1))

/* Struct definitions */
typedef struct _WearPacket
{
    WearPacket_Type type;
    uint8_t id;
    pb_size_t which_payload;
    union
    {
        Account account;
        System system;
        WatchFace watch_face;
        Nfc nfc;
        Notification notification;
        Fitness fitness;
        Lpa lpa;
        Weather weather;
        Stock stock;
        Calendar calendar;
        Factory factory;
        Aivs aivs;
        Market market;
        Gnss gnss;
        Clock clock;
        Media media;
        Alexa alexa;
        ThirdpartyApp thirdparty_app;
        Contact contact;
        Mass mass;
        Interconnection interconnection;
        ErrorCode error_code;
    } payload;
    /* @@protoc_insertion_point(struct:WearPacket) */
} WearPacket;

/* Default values for struct fields */

/* Initializer values for message structs */
#define WearPacket_init_default                  {_WearPacket_Type_MIN, 0, 0, {Account_init_default}}
#define WearPacket_init_zero                     {_WearPacket_Type_MIN, 0, 0, {Account_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define WearPacket_account_tag                   3
#define WearPacket_system_tag                    4
#define WearPacket_watch_face_tag                6
#define WearPacket_nfc_tag                       7
#define WearPacket_notification_tag              9
#define WearPacket_fitness_tag                   10
#define WearPacket_lpa_tag                       11
#define WearPacket_weather_tag                   12
#define WearPacket_stock_tag                     13
#define WearPacket_calendar_tag                  14
#define WearPacket_factory_tag                   15
#define WearPacket_aivs_tag                      16
#define WearPacket_market_tag                    17
#define WearPacket_gnss_tag                      18
#define WearPacket_clock_tag                     19
#define WearPacket_media_tag                     20
#define WearPacket_alexa_tag                     21
#define WearPacket_thirdparty_app_tag            22
#define WearPacket_contact_tag                   23
#define WearPacket_mass_tag                      24
#define WearPacket_interconnection_tag           25
#define WearPacket_error_code_tag                100
#define WearPacket_type_tag                      1
#define WearPacket_id_tag                        2

/* Struct field encoding specification for nanopb */
extern const pb_field_t WearPacket_fields[25];

/* Maximum encoded size of messages (where known) */
#define WearPacket_size                          (13 + sizeof(union{char f0[4]; char f3[Account_size]; char f4[System_size]; char f6[WatchFace_size]; char f7[Nfc_size]; char f9[Notification_size]; char f10[Fitness_size]; char f11[Lpa_size]; char f12[Weather_size]; char f13[Stock_size]; char f14[Calendar_size]; char f15[Factory_size]; char f16[Aivs_size]; char f17[Market_size]; char f18[Gnss_size]; char f19[Clock_size]; char f20[Media_size]; char f21[Alexa_size]; char f22[ThirdpartyApp_size]; char f23[Contact_size]; char f24[Mass_size]; char f25[Interconnection_size];}))

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
