/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_ACCOUNT_PB_H_INCLUDED
#define PB_WEAR_ACCOUNT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _VerifyMode
{
    VerifyMode_SERVER_PSK = 1,
    VerifyMode_APP_LOCAL = 2
} VerifyMode;
#define _VerifyMode_MIN VerifyMode_SERVER_PSK
#define _VerifyMode_MAX VerifyMode_APP_LOCAL
#define _VerifyMode_ARRAYSIZE ((VerifyMode)(VerifyMode_APP_LOCAL+1))

typedef enum _OOBMode
{
    OOBMode_NO_OOB = 0,
    OOBMode_NUMERIC_COMPARISON = 1,
    OOBMode_DYNAMIC_CODE = 2,
    OOBMode_BUTTON_CONFIRM = 3
} OOBMode;
#define _OOBMode_MIN OOBMode_NO_OOB
#define _OOBMode_MAX OOBMode_BUTTON_CONFIRM
#define _OOBMode_ARRAYSIZE ((OOBMode)(OOBMode_BUTTON_CONFIRM+1))

typedef enum _Account_AccountID
{
    Account_AccountID_BIND_STATUS = 0,
    Account_AccountID_BIND_START = 1,
    Account_AccountID_BIND_RESULT = 2,
    Account_AccountID_LOGIN_STATUS = 3,
    Account_AccountID_LOGIN_START = 4,
    Account_AccountID_ACCOUNT_VERIFY = 5,
    Account_AccountID_BOND_APPLY = 16,
    Account_AccountID_BIND_START_V2 = 17,
    Account_AccountID_BIND_VERIFY = 18,
    Account_AccountID_BIND_CONFIRM = 19,
    Account_AccountID_BIND_RESULT_V2 = 25,
    Account_AccountID_AUTH_VERIFY = 26,
    Account_AccountID_AUTH_CONFIRM = 27
} Account_AccountID;
#define _Account_AccountID_MIN Account_AccountID_BIND_STATUS
#define _Account_AccountID_MAX Account_AccountID_AUTH_CONFIRM
#define _Account_AccountID_ARRAYSIZE ((Account_AccountID)(Account_AccountID_AUTH_CONFIRM+1))

typedef enum _Account_ErrorCode
{
    Account_ErrorCode_NO_ERROR = 0,
    Account_ErrorCode_HAVE_BOUND = 1,
    Account_ErrorCode_INFO_MISSING = 2,
    Account_ErrorCode_INVALID_PARAM = 3,
    Account_ErrorCode_NO_BOUND = 4,
    Account_ErrorCode_SERVER_ERROR = 5,
    Account_ErrorCode_CANCEL = 6,
    Account_ErrorCode_VERIFY_ERROR = 7,
    Account_ErrorCode_STATE_NOT_MATCH = 8,
    Account_ErrorCode_USER_CHANGED = 9,
    Account_ErrorCode_UNKNOWN = 100
} Account_ErrorCode;
#define _Account_ErrorCode_MIN Account_ErrorCode_NO_ERROR
#define _Account_ErrorCode_MAX Account_ErrorCode_UNKNOWN
#define _Account_ErrorCode_ARRAYSIZE ((Account_ErrorCode)(Account_ErrorCode_UNKNOWN+1))

typedef enum _CompanionDevice_DeviceType
{
    CompanionDevice_DeviceType_ANDROID = 0,
    CompanionDevice_DeviceType_IOS = 1
} CompanionDevice_DeviceType;
#define _CompanionDevice_DeviceType_MIN CompanionDevice_DeviceType_ANDROID
#define _CompanionDevice_DeviceType_MAX CompanionDevice_DeviceType_IOS
#define _CompanionDevice_DeviceType_ARRAYSIZE ((CompanionDevice_DeviceType)(CompanionDevice_DeviceType_IOS+1))

typedef enum _BondReply_Status
{
    BondReply_Status_NOT_SUPPORT = 1,
    BondReply_Status_BOND_SUCCESS = 2,
    BondReply_Status_BOND_FAIL = 3
} BondReply_Status;
#define _BondReply_Status_MIN BondReply_Status_NOT_SUPPORT
#define _BondReply_Status_MAX BondReply_Status_BOND_FAIL
#define _BondReply_Status_ARRAYSIZE ((BondReply_Status)(BondReply_Status_BOND_FAIL+1))

/* Struct definitions */
typedef struct _Auth
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:Auth) */
} Auth;

typedef struct _Auth_AppConfirm
{
    pb_bytes_array_t *app_sign;
    pb_bytes_array_t *encrypt_companion_device;
    /* @@protoc_insertion_point(struct:Auth_AppConfirm) */
} Auth_AppConfirm;

typedef struct _Auth_DeviceVerify
{
    pb_bytes_array_t *device_random;
    pb_bytes_array_t *device_sign;
    /* @@protoc_insertion_point(struct:Auth_DeviceVerify) */
} Auth_DeviceVerify;

typedef struct _BindInfo
{
    char *bind_key;
    char *did;
    char *model;
    char *mac;
    char *sign;
    char *serial_number;
    /* @@protoc_insertion_point(struct:BindInfo) */
} BindInfo;

typedef struct _BindLocal
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:BindLocal) */
} BindLocal;

typedef struct _BindLocal_AppConfirm
{
    pb_bytes_array_t *app_random;
    pb_bytes_array_t *app_sign;
    /* @@protoc_insertion_point(struct:BindLocal_AppConfirm) */
} BindLocal_AppConfirm;

typedef struct _BindLocal_AppVerify
{
    char *app_device_id;
    pb_bytes_array_t *app_public_key;
    /* @@protoc_insertion_point(struct:BindLocal_AppVerify) */
} BindLocal_AppVerify;

typedef struct _BindLocal_DeviceVerify
{
    pb_bytes_array_t *device_public_key;
    pb_bytes_array_t *device_random;
    pb_bytes_array_t *device_sign;
    /* @@protoc_insertion_point(struct:BindLocal_DeviceVerify) */
} BindLocal_DeviceVerify;

typedef struct _BindPsk
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:BindPsk) */
} BindPsk;

typedef struct _BindPsk_AppConfirm
{
    pb_bytes_array_t *app_random;
    pb_bytes_array_t *app_sign;
    pb_bytes_array_t *bind_key;
    /* @@protoc_insertion_point(struct:BindPsk_AppConfirm) */
} BindPsk_AppConfirm;

typedef struct _BindPsk_DeviceConfirm
{
    pb_bytes_array_t *device_random;
    pb_bytes_array_t *device_sign;
    pb_bytes_array_t *bind_sign;
    /* @@protoc_insertion_point(struct:BindPsk_DeviceConfirm) */
} BindPsk_DeviceConfirm;

typedef struct _BindPsk_DeviceVerify
{
    pb_bytes_array_t *device_public_key;
    pb_bytes_array_t *device_sign;
    /* @@protoc_insertion_point(struct:BindPsk_DeviceVerify) */
} BindPsk_DeviceVerify;

typedef struct _BindPsk_ServerVerify
{
    pb_bytes_array_t *server_public_key;
    pb_bytes_array_t *server_sign;
    pb_bytes_array_t *server_random;
    /* @@protoc_insertion_point(struct:BindPsk_ServerVerify) */
} BindPsk_ServerVerify;

typedef struct _BindResultV2
{
    pb_bytes_array_t *encrypt_result_info;
    /* @@protoc_insertion_point(struct:BindResultV2) */
} BindResultV2;

typedef struct _BondApply
{
    pb_bytes_array_t *hash_user_id;
    /* @@protoc_insertion_point(struct:BondApply) */
} BondApply;

typedef struct _Auth_AppVerify
{
    pb_bytes_array_t *app_random;
    char *app_device_id;
    bool has_check_dynamic_code;
    bool check_dynamic_code;
    /* @@protoc_insertion_point(struct:Auth_AppVerify) */
} Auth_AppVerify;

typedef struct _Auth_DeviceConfirm
{
    bool confirm_result;
    bool has_device_capability;
    uint32_t device_capability;
    /* @@protoc_insertion_point(struct:Auth_DeviceConfirm) */
} Auth_DeviceConfirm;

typedef struct _BindInfoV2
{
    VerifyMode verify_mode;
    char *serial_number;
    char *mac;
    char *model;
    OOBMode oob_mode;
    pb_bytes_array_t *device_random;
    char *did;
    /* @@protoc_insertion_point(struct:BindInfoV2) */
} BindInfoV2;

typedef struct _BindLocal_DeviceConfirm
{
    bool confirm_result;
    /* @@protoc_insertion_point(struct:BindLocal_DeviceConfirm) */
} BindLocal_DeviceConfirm;

typedef struct _BindStartV2
{
    bool check_dynamic_code;
    pb_bytes_array_t *hash_user_id;
    /* @@protoc_insertion_point(struct:BindStartV2) */
} BindStartV2;

typedef struct _BondReply
{
    BondReply_Status status;
    /* @@protoc_insertion_point(struct:BondReply) */
} BondReply;

typedef struct _CompanionDevice
{
    CompanionDevice_DeviceType device_type;
    bool has_system_version;
    float system_version;
    char *device_name;
    bool has_app_capability;
    uint32_t app_capability;
    /* @@protoc_insertion_point(struct:CompanionDevice) */
} CompanionDevice;

typedef struct _BindLocal_ResultInfo
{
    char *user_id;
    CompanionDevice companion_device;
    /* @@protoc_insertion_point(struct:BindLocal_ResultInfo) */
} BindLocal_ResultInfo;

typedef struct _BindPsk_ResultInfo
{
    char *user_id;
    bool has_companion_device;
    CompanionDevice companion_device;
    /* @@protoc_insertion_point(struct:BindPsk_ResultInfo) */
} BindPsk_ResultInfo;

typedef struct _BindResult
{
    char *user_id;
    char *token;
    bool has_companion_device;
    CompanionDevice companion_device;
    /* @@protoc_insertion_point(struct:BindResult) */
} BindResult;

typedef struct _Account
{
    pb_size_t which_payload;
    union
    {
        bool bind_status;
        char *bind_key;
        Account_ErrorCode error_code;
        BindInfo bind_info;
        BindResult bind_result;
        bool login_status;
        char *verify_key;
        bool verify_result;
        BondApply bond_apply;
        BondReply bond_reply;
        BindStartV2 bind_start_v2;
        BindInfoV2 bind_info_v2;
        BindPsk_ServerVerify psk_server_verify;
        BindPsk_DeviceVerify psk_device_verify;
        BindPsk_AppConfirm psk_app_confirm;
        BindPsk_DeviceConfirm psk_device_confirm;
        BindLocal_AppVerify local_app_verify;
        BindLocal_DeviceVerify local_device_verify;
        BindLocal_AppConfirm local_app_confirm;
        BindLocal_DeviceConfirm local_device_confirm;
        BindResultV2 bind_result_v2;
        Auth_AppVerify auth_app_verify;
        Auth_DeviceVerify auth_device_verify;
        Auth_AppConfirm auth_app_confirm;
        Auth_DeviceConfirm auth_device_confirm;
    } payload;
    /* @@protoc_insertion_point(struct:Account) */
} Account;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Account_init_default                     {0, {0}}
#define BindInfo_init_default                    {NULL, NULL, NULL, NULL, NULL, NULL}
#define BindResult_init_default                  {NULL, NULL, false, CompanionDevice_init_default}
#define CompanionDevice_init_default             {_CompanionDevice_DeviceType_MIN, false, 0, NULL, false, 0}
#define BondApply_init_default                   {NULL}
#define BondReply_init_default                   {_BondReply_Status_MIN}
#define BindStartV2_init_default                 {0, NULL}
#define BindInfoV2_init_default                  {_VerifyMode_MIN, NULL, NULL, NULL, _OOBMode_MIN, NULL, NULL}
#define BindPsk_init_default                     {0}
#define BindPsk_ServerVerify_init_default        {NULL, NULL, NULL}
#define BindPsk_DeviceVerify_init_default        {NULL, NULL}
#define BindPsk_AppConfirm_init_default          {NULL, NULL, NULL}
#define BindPsk_DeviceConfirm_init_default       {NULL, NULL, NULL}
#define BindPsk_ResultInfo_init_default          {NULL, false, CompanionDevice_init_default}
#define BindLocal_init_default                   {0}
#define BindLocal_AppVerify_init_default         {NULL, NULL}
#define BindLocal_DeviceVerify_init_default      {NULL, NULL, NULL}
#define BindLocal_AppConfirm_init_default        {NULL, NULL}
#define BindLocal_DeviceConfirm_init_default     {0}
#define BindLocal_ResultInfo_init_default        {NULL, CompanionDevice_init_default}
#define BindResultV2_init_default                {NULL}
#define Auth_init_default                        {0}
#define Auth_AppVerify_init_default              {NULL, NULL, false, 0}
#define Auth_DeviceVerify_init_default           {NULL, NULL}
#define Auth_AppConfirm_init_default             {NULL, NULL}
#define Auth_DeviceConfirm_init_default          {0, false, 0}
#define Account_init_zero                        {0, {0}}
#define BindInfo_init_zero                       {NULL, NULL, NULL, NULL, NULL, NULL}
#define BindResult_init_zero                     {NULL, NULL, false, CompanionDevice_init_zero}
#define CompanionDevice_init_zero                {_CompanionDevice_DeviceType_MIN, false, 0, NULL, false, 0}
#define BondApply_init_zero                      {NULL}
#define BondReply_init_zero                      {_BondReply_Status_MIN}
#define BindStartV2_init_zero                    {0, NULL}
#define BindInfoV2_init_zero                     {_VerifyMode_MIN, NULL, NULL, NULL, _OOBMode_MIN, NULL, NULL}
#define BindPsk_init_zero                        {0}
#define BindPsk_ServerVerify_init_zero           {NULL, NULL, NULL}
#define BindPsk_DeviceVerify_init_zero           {NULL, NULL}
#define BindPsk_AppConfirm_init_zero             {NULL, NULL, NULL}
#define BindPsk_DeviceConfirm_init_zero          {NULL, NULL, NULL}
#define BindPsk_ResultInfo_init_zero             {NULL, false, CompanionDevice_init_zero}
#define BindLocal_init_zero                      {0}
#define BindLocal_AppVerify_init_zero            {NULL, NULL}
#define BindLocal_DeviceVerify_init_zero         {NULL, NULL, NULL}
#define BindLocal_AppConfirm_init_zero           {NULL, NULL}
#define BindLocal_DeviceConfirm_init_zero        {0}
#define BindLocal_ResultInfo_init_zero           {NULL, CompanionDevice_init_zero}
#define BindResultV2_init_zero                   {NULL}
#define Auth_init_zero                           {0}
#define Auth_AppVerify_init_zero                 {NULL, NULL, false, 0}
#define Auth_DeviceVerify_init_zero              {NULL, NULL}
#define Auth_AppConfirm_init_zero                {NULL, NULL}
#define Auth_DeviceConfirm_init_zero             {0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Auth_AppConfirm_app_sign_tag             1
#define Auth_AppConfirm_encrypt_companion_device_tag 2
#define Auth_DeviceVerify_device_random_tag      1
#define Auth_DeviceVerify_device_sign_tag        2
#define BindInfo_bind_key_tag                    1
#define BindInfo_did_tag                         2
#define BindInfo_model_tag                       3
#define BindInfo_mac_tag                         4
#define BindInfo_sign_tag                        5
#define BindInfo_serial_number_tag               6
#define BindLocal_AppConfirm_app_random_tag      1
#define BindLocal_AppConfirm_app_sign_tag        2
#define BindLocal_AppVerify_app_device_id_tag    1
#define BindLocal_AppVerify_app_public_key_tag   2
#define BindLocal_DeviceVerify_device_public_key_tag 1
#define BindLocal_DeviceVerify_device_random_tag 2
#define BindLocal_DeviceVerify_device_sign_tag   3
#define BindPsk_AppConfirm_app_random_tag        1
#define BindPsk_AppConfirm_app_sign_tag          2
#define BindPsk_AppConfirm_bind_key_tag          3
#define BindPsk_DeviceConfirm_device_random_tag  1
#define BindPsk_DeviceConfirm_device_sign_tag    2
#define BindPsk_DeviceConfirm_bind_sign_tag      3
#define BindPsk_DeviceVerify_device_public_key_tag 1
#define BindPsk_DeviceVerify_device_sign_tag     2
#define BindPsk_ServerVerify_server_public_key_tag 1
#define BindPsk_ServerVerify_server_sign_tag     2
#define BindPsk_ServerVerify_server_random_tag   3
#define BindResultV2_encrypt_result_info_tag     1
#define BondApply_hash_user_id_tag               1
#define Auth_AppVerify_app_random_tag            1
#define Auth_AppVerify_app_device_id_tag         2
#define Auth_AppVerify_check_dynamic_code_tag    3
#define Auth_DeviceConfirm_confirm_result_tag    1
#define Auth_DeviceConfirm_device_capability_tag 2
#define BindInfoV2_verify_mode_tag               1
#define BindInfoV2_serial_number_tag             2
#define BindInfoV2_mac_tag                       3
#define BindInfoV2_model_tag                     4
#define BindInfoV2_oob_mode_tag                  5
#define BindInfoV2_device_random_tag             6
#define BindInfoV2_did_tag                       7
#define BindLocal_DeviceConfirm_confirm_result_tag 1
#define BindStartV2_check_dynamic_code_tag       1
#define BindStartV2_hash_user_id_tag             2
#define BondReply_status_tag                     1
#define CompanionDevice_device_type_tag          1
#define CompanionDevice_system_version_tag       2
#define CompanionDevice_device_name_tag          3
#define CompanionDevice_app_capability_tag       4
#define BindLocal_ResultInfo_user_id_tag         1
#define BindLocal_ResultInfo_companion_device_tag 2
#define BindPsk_ResultInfo_user_id_tag           1
#define BindPsk_ResultInfo_companion_device_tag  2
#define BindResult_user_id_tag                   1
#define BindResult_token_tag                     2
#define BindResult_companion_device_tag          3
#define Account_bind_status_tag                  1
#define Account_bind_key_tag                     2
#define Account_error_code_tag                   3
#define Account_bind_info_tag                    4
#define Account_bind_result_tag                  5
#define Account_login_status_tag                 6
#define Account_verify_key_tag                   7
#define Account_verify_result_tag                8
#define Account_bond_apply_tag                   9
#define Account_bond_reply_tag                   10
#define Account_bind_start_v2_tag                11
#define Account_bind_info_v2_tag                 12
#define Account_psk_server_verify_tag            13
#define Account_psk_device_verify_tag            14
#define Account_psk_app_confirm_tag              15
#define Account_psk_device_confirm_tag           16
#define Account_local_app_verify_tag             17
#define Account_local_device_verify_tag          18
#define Account_local_app_confirm_tag            19
#define Account_local_device_confirm_tag         20
#define Account_bind_result_v2_tag               29
#define Account_auth_app_verify_tag              30
#define Account_auth_device_verify_tag           31
#define Account_auth_app_confirm_tag             32
#define Account_auth_device_confirm_tag          33

/* Struct field encoding specification for nanopb */
extern const pb_field_t Account_fields[26];
extern const pb_field_t BindInfo_fields[7];
extern const pb_field_t BindResult_fields[4];
extern const pb_field_t CompanionDevice_fields[5];
extern const pb_field_t BondApply_fields[2];
extern const pb_field_t BondReply_fields[2];
extern const pb_field_t BindStartV2_fields[3];
extern const pb_field_t BindInfoV2_fields[8];
extern const pb_field_t BindPsk_fields[1];
extern const pb_field_t BindPsk_ServerVerify_fields[4];
extern const pb_field_t BindPsk_DeviceVerify_fields[3];
extern const pb_field_t BindPsk_AppConfirm_fields[4];
extern const pb_field_t BindPsk_DeviceConfirm_fields[4];
extern const pb_field_t BindPsk_ResultInfo_fields[3];
extern const pb_field_t BindLocal_fields[1];
extern const pb_field_t BindLocal_AppVerify_fields[3];
extern const pb_field_t BindLocal_DeviceVerify_fields[4];
extern const pb_field_t BindLocal_AppConfirm_fields[3];
extern const pb_field_t BindLocal_DeviceConfirm_fields[2];
extern const pb_field_t BindLocal_ResultInfo_fields[3];
extern const pb_field_t BindResultV2_fields[2];
extern const pb_field_t Auth_fields[1];
extern const pb_field_t Auth_AppVerify_fields[4];
extern const pb_field_t Auth_DeviceVerify_fields[3];
extern const pb_field_t Auth_AppConfirm_fields[3];
extern const pb_field_t Auth_DeviceConfirm_fields[3];

/* Maximum encoded size of messages (where known) */
/* Account_size depends on runtime parameters */
/* BindInfo_size depends on runtime parameters */
/* BindResult_size depends on runtime parameters */
/* CompanionDevice_size depends on runtime parameters */
/* BondApply_size depends on runtime parameters */
#define BondReply_size                           2
/* BindStartV2_size depends on runtime parameters */
/* BindInfoV2_size depends on runtime parameters */
#define BindPsk_size                             0
/* BindPsk_ServerVerify_size depends on runtime parameters */
/* BindPsk_DeviceVerify_size depends on runtime parameters */
/* BindPsk_AppConfirm_size depends on runtime parameters */
/* BindPsk_DeviceConfirm_size depends on runtime parameters */
/* BindPsk_ResultInfo_size depends on runtime parameters */
#define BindLocal_size                           0
/* BindLocal_AppVerify_size depends on runtime parameters */
/* BindLocal_DeviceVerify_size depends on runtime parameters */
/* BindLocal_AppConfirm_size depends on runtime parameters */
#define BindLocal_DeviceConfirm_size             2
/* BindLocal_ResultInfo_size depends on runtime parameters */
/* BindResultV2_size depends on runtime parameters */
#define Auth_size                                0
/* Auth_AppVerify_size depends on runtime parameters */
/* Auth_DeviceVerify_size depends on runtime parameters */
/* Auth_AppConfirm_size depends on runtime parameters */
#define Auth_DeviceConfirm_size                  8

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_ACCOUNT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
