/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_NOTIFICATION_PB_H_INCLUDED
#define PB_WEAR_NOTIFICATION_PB_H_INCLUDED
#include <pb.h>

#include "wear_common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _CallType
{
    CallType_NOTHING = 0,
    CallType_INCOMING_CALL = 1,
    CallType_MISSED_CALL = 2,
    CallType_OUTGOING_CALL = 3
} CallType;
#define _CallType_MIN CallType_NOTHING
#define _CallType_MAX CallType_OUTGOING_CALL
#define _CallType_ARRAYSIZE ((CallType)(CallType_OUTGOING_CALL+1))

typedef enum _ReplyResult
{
    ReplyResult_REPLY_SUCCESS = 0,
    ReplyResult_TARGET_NOT_SUPPORT = 1,
    ReplyResult_NOTIFY_NOT_FOUND = 2,
    ReplyResult_NO_REPLY_PERMISSION = 3,
    ReplyResult_REPLY_FAIL = 4
} ReplyResult;
#define _ReplyResult_MIN ReplyResult_REPLY_SUCCESS
#define _ReplyResult_MAX ReplyResult_REPLY_FAIL
#define _ReplyResult_ARRAYSIZE ((ReplyResult)(ReplyResult_REPLY_FAIL+1))

typedef enum _Notification_NotificationID
{
    Notification_NotificationID_ADD_NOTIFY = 0,
    Notification_NotificationID_REMOVE_NOTIFY = 1,
    Notification_NotificationID_OPEN_NOTIFY = 8,
    Notification_NotificationID_HANG_UP = 2,
    Notification_NotificationID_INCOMING_CALL_MUTE = 5,
    Notification_NotificationID_GET_APP_LIST = 3,
    Notification_NotificationID_SET_APP = 4,
    Notification_NotificationID_GET_AUTO_SCREEN = 6,
    Notification_NotificationID_SET_AUTO_SCREEN = 7,
    Notification_NotificationID_GET_REPLY_MSG = 9,
    Notification_NotificationID_ADD_REPLY_MSG = 10,
    Notification_NotificationID_REMOVE_REPLY_MSG = 11,
    Notification_NotificationID_UPDATE_REPLY_MSG = 12,
    Notification_NotificationID_REPLY_MSG_REQUEST = 13,
    Notification_NotificationID_REPLY_MSG_RESULT = 14,
    Notification_NotificationID_PREPARE_APP_ICON = 15,
    Notification_NotificationID_APP_ICON_APPLY = 16
} Notification_NotificationID;
#define _Notification_NotificationID_MIN Notification_NotificationID_ADD_NOTIFY
#define _Notification_NotificationID_MAX Notification_NotificationID_APP_ICON_APPLY
#define _Notification_NotificationID_ARRAYSIZE ((Notification_NotificationID)(Notification_NotificationID_APP_ICON_APPLY+1))

typedef enum _ReplyMsg_Target
{
    ReplyMsg_Target_SMS = 1,
    ReplyMsg_Target_WECHAT = 2
} ReplyMsg_Target;
#define _ReplyMsg_Target_MIN ReplyMsg_Target_SMS
#define _ReplyMsg_Target_MAX ReplyMsg_Target_WECHAT
#define _ReplyMsg_Target_ARRAYSIZE ((ReplyMsg_Target)(ReplyMsg_Target_WECHAT+1))

typedef enum _ReplyMsg_Result
{
    ReplyMsg_Result_SUCCESS = 0,
    ReplyMsg_Result_EXCEED_LIMIT = 1,
    ReplyMsg_Result_INVALID_ID = 2,
    ReplyMsg_Result_FAIL = 10
} ReplyMsg_Result;
#define _ReplyMsg_Result_MIN ReplyMsg_Result_SUCCESS
#define _ReplyMsg_Result_MAX ReplyMsg_Result_FAIL
#define _ReplyMsg_Result_ARRAYSIZE ((ReplyMsg_Result)(ReplyMsg_Result_FAIL+1))

typedef enum _AppInfo_Type
{
    AppInfo_Type_NOTIFICATION = 0,
    AppInfo_Type_CALL = 1,
    AppInfo_Type_WECHAT = 2,
    AppInfo_Type_QQ = 3,
    AppInfo_Type_ALIPAY = 4,
    AppInfo_Type_OTHER = 5,
    AppInfo_Type_SMS = 6,
    AppInfo_Type_MAIL = 7,
    AppInfo_Type_WEIBO = 8,
    AppInfo_Type_TAOBAO = 9,
    AppInfo_Type_TIKTOK = 10,
    AppInfo_Type_DINGDING = 11,
    AppInfo_Type_MIHOME = 12,
    AppInfo_Type_XIAOHONGSHU = 13,
    AppInfo_Type_PINDUODUO = 14,
    AppInfo_Type_KUAISHOU = 15,
    AppInfo_Type_QQMUSIC = 16,
    AppInfo_Type_DIDI = 17,
    AppInfo_Type_BAIDUMAP = 18,
    AppInfo_Type_GAODEMAP = 19,
    AppInfo_Type_CLOUDMUSIC = 20,
    AppInfo_Type_KUGOU = 21,
    AppInfo_Type_BAIDU = 22,
    AppInfo_Type_QQMAIL = 23,
    AppInfo_Type_QQZONE = 24,
    AppInfo_Type_TENCENTNEWS = 25,
    AppInfo_Type_TOUTIAO = 26,
    AppInfo_Type_WEWORK = 27,
    AppInfo_Type_MEITUAN = 28,
    AppInfo_Type_KEEP = 29,
    AppInfo_Type_YOUKU = 30,
    AppInfo_Type_QQLIVE = 31,
    AppInfo_Type_IQIYI = 32,
    AppInfo_Type_BILIBILI = 33,
    AppInfo_Type_TIKTOKLITE = 34,
    AppInfo_Type_KUSISHOULITE = 35,
    AppInfo_Type_XIMALAYA = 36,
    AppInfo_Type_WEISHI = 37,
    AppInfo_Type_DIANPING = 38,
    AppInfo_Type_MEITUANWM = 39,
    AppInfo_Type_ELEME = 40,
    AppInfo_Type_ZHIHU = 41,
    AppInfo_Type_XIANYU = 42,
    AppInfo_Type_TAOBAOLITE = 43,
    AppInfo_Type_JD = 44,
    AppInfo_Type_DEWU = 45,
    AppInfo_Type_TMALL = 46,
    AppInfo_Type_SUNING = 47,
    AppInfo_Type_TICKET12306 = 48,
    AppInfo_Type_CCB = 49,
    AppInfo_Type_UNIONPAY = 50,
    AppInfo_Type_CMB = 51,
    AppInfo_Type_JDJR = 52,
    AppInfo_Type_CB = 53,
    AppInfo_Type_ICBC = 54,
    AppInfo_Type_ZSSH = 55,
    AppInfo_Type_ABC = 56,
    AppInfo_Type_JTBANK = 57,
    AppInfo_Type_WEREAD = 58,
    AppInfo_Type_SHUQI = 59,
    AppInfo_Type_QQBROWSER = 60,
    AppInfo_Type_UCBROWSER = 61,
    AppInfo_Type_SOUL = 62,
    AppInfo_Type_MOMO = 63,
    AppInfo_Type_TANTAN = 64,
    AppInfo_Type_DOUBAN = 65,
    AppInfo_Type_TIEBA = 66,
    AppInfo_Type_WUBA = 67,
    AppInfo_Type_WHATSAPP = 68,
    AppInfo_Type_VIBER = 69,
    AppInfo_Type_SNAPCHAT = 70,
    AppInfo_Type_SKYPE = 71,
    AppInfo_Type_TELEGRAM = 72,
    AppInfo_Type_FBMESSENGER = 73,
    AppInfo_Type_DISCORD = 74,
    AppInfo_Type_KAKAO = 75,
    AppInfo_Type_VKONTAKTE = 76,
    AppInfo_Type_LINE = 77,
    AppInfo_Type_TWITTER = 78,
    AppInfo_Type_GMAIL = 79,
    AppInfo_Type_OUTLOOK = 80,
    AppInfo_Type_FB = 81,
    AppInfo_Type_NAVER = 82,
    AppInfo_Type_HANGOUT = 83,
    AppInfo_Type_BIP = 84,
    AppInfo_Type_OK = 85,
    AppInfo_Type_SHARECHAT = 86,
    AppInfo_Type_MAMBA = 87,
    AppInfo_Type_INSTAGRAM = 88,
    AppInfo_Type_YOUTUBE = 89
} AppInfo_Type;
#define _AppInfo_Type_MIN AppInfo_Type_NOTIFICATION
#define _AppInfo_Type_MAX AppInfo_Type_YOUTUBE
#define _AppInfo_Type_ARRAYSIZE ((AppInfo_Type)(AppInfo_Type_YOUTUBE+1))

/* Struct definitions */
typedef struct _AppIconApply
{
    char *package_name;
    /* @@protoc_insertion_point(struct:AppIconApply) */
} AppIconApply;

typedef struct _AppInfo_List
{
    pb_size_t list_count;
    struct _AppInfo *list;
    /* @@protoc_insertion_point(struct:AppInfo_List) */
} AppInfo_List;

typedef struct _NotifyData_List
{
    pb_size_t list_count;
    struct _NotifyData *list;
    /* @@protoc_insertion_point(struct:NotifyData_List) */
} NotifyData_List;

typedef struct _NotifyId_List
{
    pb_size_t list_count;
    struct _NotifyId *list;
    /* @@protoc_insertion_point(struct:NotifyId_List) */
} NotifyId_List;

typedef struct _PrepareAppIcon
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:PrepareAppIcon) */
} PrepareAppIcon;

typedef struct _AppInfo
{
    uint8_t app_type;
    bool enable;
    /* @@protoc_insertion_point(struct:AppInfo) */
} AppInfo;

typedef struct _NotifyData
{
    char *app_id;
    char *app_name;
    char *title;
    char *sub_title;
    char *text;
    char *date;
    uint32_t uid;
    bool has_call_type;
    CallType call_type;
    char *app_group;
    char *call_number;
    bool has_support_reply;
    bool support_reply;
    char *key;
    bool has_support_open;
    bool support_open;
    /* @@protoc_insertion_point(struct:NotifyData) */
} NotifyData;

typedef struct _NotifyId
{
    uint32_t uid;
    char *app_id;
    char *app_group;
    char *key;
    /* @@protoc_insertion_point(struct:NotifyId) */
} NotifyId;

typedef struct _PrepareAppIcon_Request
{
    char *package_name;
    bool has_support_compress_mode;
    uint8_t support_compress_mode;
    /* @@protoc_insertion_point(struct:PrepareAppIcon_Request) */
} PrepareAppIcon_Request;

typedef struct _PrepareAppIcon_Response
{
    PrepareStatus prepare_status;
    bool has_support_image_format;
    ImageFormat support_image_format;
    bool has_expected_max_size;
    uint16_t expected_max_size;
    bool has_select_compress_mode;
    uint8_t select_compress_mode;
    bool has_expected_slice_length;
    uint32_t expected_slice_length;
    /* @@protoc_insertion_point(struct:PrepareAppIcon_Response) */
} PrepareAppIcon_Response;

typedef struct _ReplyMsg
{
    ReplyMsg_Target target;
    pb_size_t contents_count;
    char **contents;
    bool has_support_max_numbers;
    uint8_t support_max_numbers;
    /* @@protoc_insertion_point(struct:ReplyMsg) */
} ReplyMsg;

typedef struct _ReplyMsg_Removal
{
    ReplyMsg_Target target;
    pb_size_t id_count;
    uint32_t *id;
    /* @@protoc_insertion_point(struct:ReplyMsg_Removal) */
} ReplyMsg_Removal;

typedef struct _ReplyRequest
{
    ReplyMsg_Target target;
    char *contents;
    bool need_result;
    pb_size_t which_data;
    union
    {
        char *phone_number;
        NotifyId notify_id;
    } data;
    /* @@protoc_insertion_point(struct:ReplyRequest) */
} ReplyRequest;

typedef struct _Notification
{
    pb_size_t which_payload;
    union
    {
        NotifyData data;
        NotifyId id;
        NotifyData_List data_list;
        NotifyId_List id_list;
        AppInfo app_info;
        AppInfo_List app_info_list;
        bool enable_auto_screen;
        ReplyMsg_Target reply_msg_target;
        ReplyMsg reply_msg;
        ReplyMsg_Removal reply_msg_removal;
        ReplyMsg_Result reply_msg_result;
        ReplyRequest reply_request;
        ReplyResult reply_result;
        PrepareAppIcon_Request app_icon_request;
        PrepareAppIcon_Response app_icon_response;
        AppIconApply app_icon_apply;
    } payload;
    /* @@protoc_insertion_point(struct:Notification) */
} Notification;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Notification_init_default                {0, {NotifyData_init_default}}
#define NotifyData_init_default                  {NULL, NULL, NULL, NULL, NULL, NULL, 0, false, _CallType_MIN, NULL, NULL, false, 0, NULL, false, 0}
#define NotifyData_List_init_default             {0, NULL}
#define NotifyId_init_default                    {0, NULL, NULL, NULL}
#define NotifyId_List_init_default               {0, NULL}
#define ReplyMsg_init_default                    {_ReplyMsg_Target_MIN, 0, NULL, false, 0}
#define ReplyMsg_Removal_init_default            {_ReplyMsg_Target_MIN, 0, NULL}
#define ReplyRequest_init_default                {_ReplyMsg_Target_MIN, NULL, 0, 0, {NULL}}
#define PrepareAppIcon_init_default              {0}
#define PrepareAppIcon_Request_init_default      {NULL, false, 0}
#define PrepareAppIcon_Response_init_default     {_PrepareStatus_MIN, false, _ImageFormat_MIN, false, 0, false, 0, false, 0}
#define AppIconApply_init_default                {NULL}
#define AppInfo_init_default                     {0, 0}
#define AppInfo_List_init_default                {0, NULL}
#define Notification_init_zero                   {0, {NotifyData_init_zero}}
#define NotifyData_init_zero                     {NULL, NULL, NULL, NULL, NULL, NULL, 0, false, _CallType_MIN, NULL, NULL, false, 0, NULL, false, 0}
#define NotifyData_List_init_zero                {0, NULL}
#define NotifyId_init_zero                       {0, NULL, NULL, NULL}
#define NotifyId_List_init_zero                  {0, NULL}
#define ReplyMsg_init_zero                       {_ReplyMsg_Target_MIN, 0, NULL, false, 0}
#define ReplyMsg_Removal_init_zero               {_ReplyMsg_Target_MIN, 0, NULL}
#define ReplyRequest_init_zero                   {_ReplyMsg_Target_MIN, NULL, 0, 0, {NULL}}
#define PrepareAppIcon_init_zero                 {0}
#define PrepareAppIcon_Request_init_zero         {NULL, false, 0}
#define PrepareAppIcon_Response_init_zero        {_PrepareStatus_MIN, false, _ImageFormat_MIN, false, 0, false, 0, false, 0}
#define AppIconApply_init_zero                   {NULL}
#define AppInfo_init_zero                        {0, 0}
#define AppInfo_List_init_zero                   {0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define AppIconApply_package_name_tag            1
#define AppInfo_List_list_tag                    1
#define NotifyData_List_list_tag                 1
#define NotifyId_List_list_tag                   1
#define AppInfo_app_type_tag                     1
#define AppInfo_enable_tag                       2
#define NotifyData_app_id_tag                    1
#define NotifyData_app_name_tag                  2
#define NotifyData_title_tag                     3
#define NotifyData_sub_title_tag                 4
#define NotifyData_text_tag                      5
#define NotifyData_date_tag                      6
#define NotifyData_uid_tag                       7
#define NotifyData_app_group_tag                 9
#define NotifyData_key_tag                       12
#define NotifyData_call_type_tag                 8
#define NotifyData_call_number_tag               10
#define NotifyData_support_reply_tag             11
#define NotifyData_support_open_tag              13
#define NotifyId_uid_tag                         1
#define NotifyId_app_id_tag                      2
#define NotifyId_app_group_tag                   3
#define NotifyId_key_tag                         4
#define PrepareAppIcon_Request_package_name_tag  1
#define PrepareAppIcon_Request_support_compress_mode_tag 2
#define PrepareAppIcon_Response_prepare_status_tag 1
#define PrepareAppIcon_Response_support_image_format_tag 2
#define PrepareAppIcon_Response_expected_max_size_tag 3
#define PrepareAppIcon_Response_select_compress_mode_tag 4
#define PrepareAppIcon_Response_expected_slice_length_tag 5
#define ReplyMsg_target_tag                      1
#define ReplyMsg_contents_tag                    2
#define ReplyMsg_support_max_numbers_tag         3
#define ReplyMsg_Removal_target_tag              1
#define ReplyMsg_Removal_id_tag                  2
#define ReplyRequest_phone_number_tag            4
#define ReplyRequest_notify_id_tag               5
#define ReplyRequest_target_tag                  1
#define ReplyRequest_contents_tag                2
#define ReplyRequest_need_result_tag             3
#define Notification_data_tag                    1
#define Notification_id_tag                      2
#define Notification_data_list_tag               3
#define Notification_id_list_tag                 4
#define Notification_app_info_tag                5
#define Notification_app_info_list_tag           6
#define Notification_enable_auto_screen_tag      7
#define Notification_reply_msg_target_tag        8
#define Notification_reply_msg_tag               9
#define Notification_reply_msg_removal_tag       10
#define Notification_reply_msg_result_tag        11
#define Notification_reply_request_tag           12
#define Notification_reply_result_tag            13
#define Notification_app_icon_request_tag        14
#define Notification_app_icon_response_tag       15
#define Notification_app_icon_apply_tag          16

/* Struct field encoding specification for nanopb */
extern const pb_field_t Notification_fields[17];
extern const pb_field_t NotifyData_fields[14];
extern const pb_field_t NotifyData_List_fields[2];
extern const pb_field_t NotifyId_fields[5];
extern const pb_field_t NotifyId_List_fields[2];
extern const pb_field_t ReplyMsg_fields[4];
extern const pb_field_t ReplyMsg_Removal_fields[3];
extern const pb_field_t ReplyRequest_fields[6];
extern const pb_field_t PrepareAppIcon_fields[1];
extern const pb_field_t PrepareAppIcon_Request_fields[3];
extern const pb_field_t PrepareAppIcon_Response_fields[6];
extern const pb_field_t AppIconApply_fields[2];
extern const pb_field_t AppInfo_fields[3];
extern const pb_field_t AppInfo_List_fields[2];

/* Maximum encoded size of messages (where known) */
/* Notification_size depends on runtime parameters */
/* NotifyData_size depends on runtime parameters */
/* NotifyData_List_size depends on runtime parameters */
/* NotifyId_size depends on runtime parameters */
/* NotifyId_List_size depends on runtime parameters */
/* ReplyMsg_size depends on runtime parameters */
/* ReplyMsg_Removal_size depends on runtime parameters */
/* ReplyRequest_size depends on runtime parameters */
#define PrepareAppIcon_size                      0
/* PrepareAppIcon_Request_size depends on runtime parameters */
#define PrepareAppIcon_Response_size             23
/* AppIconApply_size depends on runtime parameters */
#define AppInfo_size                             8
/* AppInfo_List_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_NOTIFICATION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
