/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_MARKET_PB_H_INCLUDED
#define PB_WEAR_MARKET_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ApkType
{
    ApkType_APP = 0,
    ApkType_WATCH_FACE = 1
} ApkType;
#define _ApkType_MIN ApkType_APP
#define _ApkType_MAX ApkType_WATCH_FACE
#define _ApkType_ARRAYSIZE ((ApkType)(ApkType_WATCH_FACE+1))

typedef enum _InstallCode
{
    InstallCode_VERSION_DOWNGRADE = 0,
    InstallCode_LATEST_VERSION = 1,
    InstallCode_APK_NOT_FOUND = 2,
    InstallCode_WAITING_DOWNLOAD = 3,
    InstallCode_DOWNLOADING = 4,
    InstallCode_DOWNLOAD_FAILED = 5,
    InstallCode_INSTALLING = 6,
    InstallCode_INSTALL_SUCCESS = 7,
    InstallCode_INSTALL_FAILED = 8,
    InstallCode_CANCELLED = 9
} InstallCode;
#define _InstallCode_MIN InstallCode_VERSION_DOWNGRADE
#define _InstallCode_MAX InstallCode_CANCELLED
#define _InstallCode_ARRAYSIZE ((InstallCode)(InstallCode_CANCELLED+1))

typedef enum _Market_MarketID
{
    Market_MarketID_TRY_INSTALL_APK = 0,
    Market_MarketID_TRY_INSTALL_APKS = 1,
    Market_MarketID_REPORT_INSTALL_PROGRESS = 2,
    Market_MarketID_TRY_INSTALL_APK_NEW = 3,
    Market_MarketID_TRY_INSTALL_APKS_NEW = 4
} Market_MarketID;
#define _Market_MarketID_MIN Market_MarketID_TRY_INSTALL_APK
#define _Market_MarketID_MAX Market_MarketID_TRY_INSTALL_APKS_NEW
#define _Market_MarketID_ARRAYSIZE ((Market_MarketID)(Market_MarketID_TRY_INSTALL_APKS_NEW+1))

/* Struct definitions */
typedef struct _Apk_List
{
    pb_size_t list_count;
    struct _Apk *list;
    /* @@protoc_insertion_point(struct:Apk_List) */
} Apk_List;

typedef struct _ApkInfo
{
    char *package_name;
    char *package_hash;
    uint64_t version_code;
    /* @@protoc_insertion_point(struct:ApkInfo) */
} ApkInfo;

typedef struct _InstallProgress
{
    InstallCode code;
    char *package_name;
    bool has_download_progress;
    uint8_t download_progress;
    /* @@protoc_insertion_point(struct:InstallProgress) */
} InstallProgress;

typedef struct _Apk
{
    ApkType type;
    pb_size_t which_payload;
    union
    {
        char *package_name;
        char *url;
        ApkInfo apk_info;
    } payload;
    /* @@protoc_insertion_point(struct:Apk) */
} Apk;

typedef struct _Market
{
    pb_size_t which_payload;
    union
    {
        Apk apk;
        Apk_List apk_list;
        InstallProgress install_progress;
    } payload;
    /* @@protoc_insertion_point(struct:Market) */
} Market;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Market_init_default                      {0, {Apk_init_default}}
#define Apk_init_default                         {_ApkType_MIN, 0, {NULL}}
#define Apk_List_init_default                    {0, NULL}
#define ApkInfo_init_default                     {NULL, NULL, 0}
#define InstallProgress_init_default             {_InstallCode_MIN, NULL, false, 0}
#define Market_init_zero                         {0, {Apk_init_zero}}
#define Apk_init_zero                            {_ApkType_MIN, 0, {NULL}}
#define Apk_List_init_zero                       {0, NULL}
#define ApkInfo_init_zero                        {NULL, NULL, 0}
#define InstallProgress_init_zero                {_InstallCode_MIN, NULL, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Apk_List_list_tag                        1
#define ApkInfo_package_name_tag                 1
#define ApkInfo_package_hash_tag                 2
#define ApkInfo_version_code_tag                 3
#define InstallProgress_code_tag                 1
#define InstallProgress_package_name_tag         2
#define InstallProgress_download_progress_tag    3
#define Apk_package_name_tag                     2
#define Apk_url_tag                              3
#define Apk_apk_info_tag                         4
#define Apk_type_tag                             1
#define Market_apk_tag                           1
#define Market_apk_list_tag                      2
#define Market_install_progress_tag              3

/* Struct field encoding specification for nanopb */
extern const pb_field_t Market_fields[4];
extern const pb_field_t Apk_fields[5];
extern const pb_field_t Apk_List_fields[2];
extern const pb_field_t ApkInfo_fields[4];
extern const pb_field_t InstallProgress_fields[4];

/* Maximum encoded size of messages (where known) */
/* Market_size depends on runtime parameters */
/* Apk_size depends on runtime parameters */
/* Apk_List_size depends on runtime parameters */
/* ApkInfo_size depends on runtime parameters */
/* InstallProgress_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_MARKET_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
