/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_THIRDPARTY_APP_PB_H_INCLUDED
#define PB_WEAR_THIRDPARTY_APP_PB_H_INCLUDED
#include <pb.h>

#include "wear_common.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ThirdpartyApp_ThirdpartyAppID
{
    ThirdpartyApp_ThirdpartyAppID_GET_INSTALLED_LIST = 0,
    ThirdpartyApp_ThirdpartyAppID_PREPARE_INSTALL_APP = 1,
    ThirdpartyApp_ThirdpartyAppID_REPORT_INSTALL_RESULT = 2,
    ThirdpartyApp_ThirdpartyAppID_REMOVE_APP = 3,
    ThirdpartyApp_ThirdpartyAppID_LAUNCH_APP = 4,
    ThirdpartyApp_ThirdpartyAppID_SYNC_PERMISSION_INFO = 5,
    ThirdpartyApp_ThirdpartyAppID_REQUEST_PHONE_APP_STATUS = 6,
    ThirdpartyApp_ThirdpartyAppID_SYNC_PHONE_APP_STATUS = 7,
    ThirdpartyApp_ThirdpartyAppID_SEND_PHONE_MESSAGE = 8,
    ThirdpartyApp_ThirdpartyAppID_SEND_WEAR_MESSAGE = 9
} ThirdpartyApp_ThirdpartyAppID;
#define _ThirdpartyApp_ThirdpartyAppID_MIN ThirdpartyApp_ThirdpartyAppID_GET_INSTALLED_LIST
#define _ThirdpartyApp_ThirdpartyAppID_MAX ThirdpartyApp_ThirdpartyAppID_SEND_WEAR_MESSAGE
#define _ThirdpartyApp_ThirdpartyAppID_ARRAYSIZE ((ThirdpartyApp_ThirdpartyAppID)(ThirdpartyApp_ThirdpartyAppID_SEND_WEAR_MESSAGE+1))

typedef enum _AppInstaller_Result_Code
{
    AppInstaller_Result_Code_INSTALL_SUCCESS = 0,
    AppInstaller_Result_Code_INSTALL_FAILED = 1,
    AppInstaller_Result_Code_VERIFY_FAILED = 2
} AppInstaller_Result_Code;
#define _AppInstaller_Result_Code_MIN AppInstaller_Result_Code_INSTALL_SUCCESS
#define _AppInstaller_Result_Code_MAX AppInstaller_Result_Code_VERIFY_FAILED
#define _AppInstaller_Result_Code_ARRAYSIZE ((AppInstaller_Result_Code)(AppInstaller_Result_Code_VERIFY_FAILED+1))

typedef enum _PermissionInfo_Permission
{
    PermissionInfo_Permission_DEVICE_STATUS = 1,
    PermissionInfo_Permission_USER_STATUS = 2,
    PermissionInfo_Permission_BODY_SENSOR = 3,
    PermissionInfo_Permission_MOTION_SENSOR = 4,
    PermissionInfo_Permission_NOTIFY = 5
} PermissionInfo_Permission;
#define _PermissionInfo_Permission_MIN PermissionInfo_Permission_DEVICE_STATUS
#define _PermissionInfo_Permission_MAX PermissionInfo_Permission_NOTIFY
#define _PermissionInfo_Permission_ARRAYSIZE ((PermissionInfo_Permission)(PermissionInfo_Permission_NOTIFY+1))

typedef enum _PhoneAppStatus_Status
{
    PhoneAppStatus_Status_CONNECTED = 1,
    PhoneAppStatus_Status_DISCONNECTED = 2,
    PhoneAppStatus_Status_UNINSTALLED = 3
} PhoneAppStatus_Status;
#define _PhoneAppStatus_Status_MIN PhoneAppStatus_Status_CONNECTED
#define _PhoneAppStatus_Status_MAX PhoneAppStatus_Status_UNINSTALLED
#define _PhoneAppStatus_Status_ARRAYSIZE ((PhoneAppStatus_Status)(PhoneAppStatus_Status_UNINSTALLED+1))

/* Struct definitions */
typedef struct _AppInstaller
{
    char dummy_field;
    /* @@protoc_insertion_point(struct:AppInstaller) */
} AppInstaller;

typedef struct _AppItem_List
{
    pb_size_t list_count;
    struct _AppItem *list;
    /* @@protoc_insertion_point(struct:AppItem_List) */
} AppItem_List;

typedef struct _BasicInfo
{
    char *package_name;
    pb_bytes_array_t *fingerprint;
    /* @@protoc_insertion_point(struct:BasicInfo) */
} BasicInfo;

typedef struct _PermissionInfo_List
{
    pb_size_t list_count;
    struct _PermissionInfo *list;
    /* @@protoc_insertion_point(struct:PermissionInfo_List) */
} PermissionInfo_List;

typedef struct _AppInstaller_Request
{
    char *package_name;
    uint32_t version_code;
    uint32_t package_size;
    /* @@protoc_insertion_point(struct:AppInstaller_Request) */
} AppInstaller_Request;

typedef struct _AppInstaller_Response
{
    PrepareStatus prepare_status;
    bool has_expected_slice_length;
    uint32_t expected_slice_length;
    /* @@protoc_insertion_point(struct:AppInstaller_Response) */
} AppInstaller_Response;

typedef struct _AppItem
{
    char *package_name;
    pb_bytes_array_t *fingerprint;
    uint32_t version_code;
    bool can_remove;
    char *app_name;
    /* @@protoc_insertion_point(struct:AppItem) */
} AppItem;

typedef struct _LaunchInfo
{
    BasicInfo basic_info;
    char *uri;
    /* @@protoc_insertion_point(struct:LaunchInfo) */
} LaunchInfo;

typedef struct _MessageContent
{
    BasicInfo basic_info;
    pb_bytes_array_t *content;
    /* @@protoc_insertion_point(struct:MessageContent) */
} MessageContent;

typedef struct _PermissionInfo
{
    BasicInfo basic_info;
    pb_size_t grant_permissions_count;
    PermissionInfo_Permission *grant_permissions;
    /* @@protoc_insertion_point(struct:PermissionInfo) */
} PermissionInfo;

typedef struct _PhoneAppStatus
{
    BasicInfo basic_info;
    PhoneAppStatus_Status status;
    /* @@protoc_insertion_point(struct:PhoneAppStatus) */
} PhoneAppStatus;

typedef struct _AppInstaller_Result
{
    AppInstaller_Result_Code code;
    pb_size_t which_payload;
    union
    {
        char *package_name;
        AppItem app_item;
    } payload;
    /* @@protoc_insertion_point(struct:AppInstaller_Result) */
} AppInstaller_Result;

typedef struct _ThirdpartyApp
{
    pb_size_t which_payload;
    union
    {
        AppItem_List app_item_list;
        AppInstaller_Request install_request;
        AppInstaller_Response install_response;
        AppInstaller_Result install_result;
        BasicInfo basic_info;
        LaunchInfo launch_info;
        PermissionInfo_List permission_info_list;
        PhoneAppStatus app_status;
        MessageContent message_content;
    } payload;
    /* @@protoc_insertion_point(struct:ThirdpartyApp) */
} ThirdpartyApp;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ThirdpartyApp_init_default               {0, {AppItem_List_init_default}}
#define AppItem_init_default                     {NULL, NULL, 0, 0, NULL}
#define AppItem_List_init_default                {0, NULL}
#define AppInstaller_init_default                {0}
#define AppInstaller_Request_init_default        {NULL, 0, 0}
#define AppInstaller_Response_init_default       {_PrepareStatus_MIN, false, 0}
#define AppInstaller_Result_init_default         {_AppInstaller_Result_Code_MIN, 0, {NULL}}
#define BasicInfo_init_default                   {NULL, NULL}
#define LaunchInfo_init_default                  {BasicInfo_init_default, NULL}
#define PermissionInfo_init_default              {BasicInfo_init_default, 0, NULL}
#define PermissionInfo_List_init_default         {0, NULL}
#define PhoneAppStatus_init_default              {BasicInfo_init_default, _PhoneAppStatus_Status_MIN}
#define MessageContent_init_default              {BasicInfo_init_default, NULL}
#define ThirdpartyApp_init_zero                  {0, {AppItem_List_init_zero}}
#define AppItem_init_zero                        {NULL, NULL, 0, 0, NULL}
#define AppItem_List_init_zero                   {0, NULL}
#define AppInstaller_init_zero                   {0}
#define AppInstaller_Request_init_zero           {NULL, 0, 0}
#define AppInstaller_Response_init_zero          {_PrepareStatus_MIN, false, 0}
#define AppInstaller_Result_init_zero            {_AppInstaller_Result_Code_MIN, 0, {NULL}}
#define BasicInfo_init_zero                      {NULL, NULL}
#define LaunchInfo_init_zero                     {BasicInfo_init_zero, NULL}
#define PermissionInfo_init_zero                 {BasicInfo_init_zero, 0, NULL}
#define PermissionInfo_List_init_zero            {0, NULL}
#define PhoneAppStatus_init_zero                 {BasicInfo_init_zero, _PhoneAppStatus_Status_MIN}
#define MessageContent_init_zero                 {BasicInfo_init_zero, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define AppItem_List_list_tag                    1
#define BasicInfo_package_name_tag               1
#define BasicInfo_fingerprint_tag                2
#define PermissionInfo_List_list_tag             1
#define AppInstaller_Request_package_name_tag    1
#define AppInstaller_Request_version_code_tag    2
#define AppInstaller_Request_package_size_tag    3
#define AppInstaller_Response_prepare_status_tag 1
#define AppInstaller_Response_expected_slice_length_tag 2
#define AppItem_package_name_tag                 1
#define AppItem_fingerprint_tag                  2
#define AppItem_version_code_tag                 3
#define AppItem_can_remove_tag                   4
#define AppItem_app_name_tag                     5
#define LaunchInfo_basic_info_tag                1
#define LaunchInfo_uri_tag                       2
#define MessageContent_basic_info_tag            1
#define MessageContent_content_tag               2
#define PermissionInfo_basic_info_tag            1
#define PermissionInfo_grant_permissions_tag     2
#define PhoneAppStatus_basic_info_tag            1
#define PhoneAppStatus_status_tag                2
#define AppInstaller_Result_package_name_tag     2
#define AppInstaller_Result_app_item_tag         3
#define AppInstaller_Result_code_tag             1
#define ThirdpartyApp_app_item_list_tag          1
#define ThirdpartyApp_install_request_tag        2
#define ThirdpartyApp_install_response_tag       3
#define ThirdpartyApp_install_result_tag         4
#define ThirdpartyApp_basic_info_tag             5
#define ThirdpartyApp_launch_info_tag            6
#define ThirdpartyApp_permission_info_list_tag   7
#define ThirdpartyApp_app_status_tag             8
#define ThirdpartyApp_message_content_tag        9

/* Struct field encoding specification for nanopb */
extern const pb_field_t ThirdpartyApp_fields[10];
extern const pb_field_t AppItem_fields[6];
extern const pb_field_t AppItem_List_fields[2];
extern const pb_field_t AppInstaller_fields[1];
extern const pb_field_t AppInstaller_Request_fields[4];
extern const pb_field_t AppInstaller_Response_fields[3];
extern const pb_field_t AppInstaller_Result_fields[4];
extern const pb_field_t BasicInfo_fields[3];
extern const pb_field_t LaunchInfo_fields[3];
extern const pb_field_t PermissionInfo_fields[3];
extern const pb_field_t PermissionInfo_List_fields[2];
extern const pb_field_t PhoneAppStatus_fields[3];
extern const pb_field_t MessageContent_fields[3];

/* Maximum encoded size of messages (where known) */
/* ThirdpartyApp_size depends on runtime parameters */
/* AppItem_size depends on runtime parameters */
/* AppItem_List_size depends on runtime parameters */
#define AppInstaller_size                        0
/* AppInstaller_Request_size depends on runtime parameters */
#define AppInstaller_Response_size               9
/* AppInstaller_Result_size depends on runtime parameters */
/* BasicInfo_size depends on runtime parameters */
/* LaunchInfo_size depends on runtime parameters */
/* PermissionInfo_size depends on runtime parameters */
/* PermissionInfo_List_size depends on runtime parameters */
/* PhoneAppStatus_size depends on runtime parameters */
/* MessageContent_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_THIRDPARTY_APP_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
