/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_ALEXA_PB_H_INCLUDED
#define PB_WEAR_ALEXA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _AlexaResultType
{
    AlexaResultType_ALEXA_START_LISTENING = 0,
    AlexaResultType_ALEXA_END_LISTENING = 1,
    AlexaResultType_ALEXA_AUTH_STATUS = 3,
    AlexaResultType_ALEXA_ERROR_NETWORK = 80,
    AlexaResultType_ALEXA_ERROR_AUTH = 81,
    AlexaResultType_ALEXA_ERROR_CONTENT_TOO_LONG = 82,
    AlexaResultType_ALEXA_ERROR_UNRECOGNIZABLE_SPEECH = 83,
    AlexaResultType_ALEXA_ERROR_UNSUPPORTED_AREA = 84,
    AlexaResultType_ALEXA_ERROR_IOS_DEVICE_NOT_SUPPORT = 85,
    AlexaResultType_ALEXA_ERROR_ANDROID_DEVICE_NOT_SUPPORT = 86,
    AlexaResultType_ALEXA_ERROR_PLAY_NOT_SUPPORT = 87,
    AlexaResultType_ALEXA_TEMPLATE_GENERAL = 257,
    AlexaResultType_ALEXA_TEMPLATE_WEATHER = 258,
    AlexaResultType_ALEXA_TEMPLATE_LISTS = 259,
    AlexaResultType_ALEXA_ALERTS_SETALERT = 260,
    AlexaResultType_ALEXA_ALERTS_DELETEALERTS = 261,
    AlexaResultType_ALEXA_SPEECHSYNTHESIZER_SPEAK = 262,
    AlexaResultType_ALEXA_SPEECHRECOGNIZER_EXPECTSPEECH = 263,
    AlexaResultType_ALEXA_NOTIFICATIONS_SETINDICATOR = 264,
    AlexaResultType_ALEXA_NOTIFICATIONS_CLEARINDICATOR = 265
} AlexaResultType;
#define _AlexaResultType_MIN AlexaResultType_ALEXA_START_LISTENING
#define _AlexaResultType_MAX AlexaResultType_ALEXA_NOTIFICATIONS_CLEARINDICATOR
#define _AlexaResultType_ARRAYSIZE ((AlexaResultType)(AlexaResultType_ALEXA_NOTIFICATIONS_CLEARINDICATOR+1))

typedef enum _AlexaAlertType
{
    AlexaAlertType_ALEXA_AlertType_UNKNOWN = -1,
    AlexaAlertType_ALEXA_ALARM = 0,
    AlexaAlertType_ALEXA_REMINDER = 1,
    AlexaAlertType_ALEXA_TIMER = 2
} AlexaAlertType;
#define _AlexaAlertType_MIN AlexaAlertType_ALEXA_AlertType_UNKNOWN
#define _AlexaAlertType_MAX AlexaAlertType_ALEXA_TIMER
#define _AlexaAlertType_ARRAYSIZE ((AlexaAlertType)(AlexaAlertType_ALEXA_TIMER+1))

typedef enum _AlexaAuthStatus
{
    AlexaAuthStatus_ALEXA_AUTH = 0,
    AlexaAuthStatus_ALEXA_NO_AUTH = 1
} AlexaAuthStatus;
#define _AlexaAuthStatus_MIN AlexaAuthStatus_ALEXA_AUTH
#define _AlexaAuthStatus_MAX AlexaAuthStatus_ALEXA_NO_AUTH
#define _AlexaAuthStatus_ARRAYSIZE ((AlexaAuthStatus)(AlexaAuthStatus_ALEXA_NO_AUTH+1))

typedef enum _Alexa_AlexaID
{
    Alexa_AlexaID_SYNC_INSTRUCTION_LIST = 0,
    Alexa_AlexaID_SET_CONFIG = 1,
    Alexa_AlexaID_GET_CONFIG = 2,
    Alexa_AlexaID_REPORT_QUIET_MODE = 3
} Alexa_AlexaID;
#define _Alexa_AlexaID_MIN Alexa_AlexaID_SYNC_INSTRUCTION_LIST
#define _Alexa_AlexaID_MAX Alexa_AlexaID_REPORT_QUIET_MODE
#define _Alexa_AlexaID_ARRAYSIZE ((Alexa_AlexaID)(Alexa_AlexaID_REPORT_QUIET_MODE+1))

/* Struct definitions */
typedef struct _AlexaAlertsDeleteAlert
{
    char *token;
    /* @@protoc_insertion_point(struct:AlexaAlertsDeleteAlert) */
} AlexaAlertsDeleteAlert;

typedef struct _AlexaAlertsDeleteAlert_List
{
    pb_size_t list_count;
    struct _AlexaAlertsDeleteAlert *list;
    /* @@protoc_insertion_point(struct:AlexaAlertsDeleteAlert_List) */
} AlexaAlertsDeleteAlert_List;

typedef struct _AlexaConfig
{
    char *client_id;
    char *refresh_token;
    char *language;
    /* @@protoc_insertion_point(struct:AlexaConfig) */
} AlexaConfig;

typedef struct _AlexaInstruction_List
{
    pb_size_t list_count;
    struct _AlexaInstruction *list;
    /* @@protoc_insertion_point(struct:AlexaInstruction_List) */
} AlexaInstruction_List;

typedef struct _AlexaListsItem
{
    char *left;
    char *right;
    /* @@protoc_insertion_point(struct:AlexaListsItem) */
} AlexaListsItem;

typedef struct _AlexaListsItem_List
{
    pb_size_t list_count;
    struct _AlexaListsItem *list;
    /* @@protoc_insertion_point(struct:AlexaListsItem_List) */
} AlexaListsItem_List;

typedef struct _AlexaSpeechSynthesizerSpeak
{
    char *text;
    /* @@protoc_insertion_point(struct:AlexaSpeechSynthesizerSpeak) */
} AlexaSpeechSynthesizerSpeak;

typedef struct _AlexaTitle
{
    char *main_title;
    char *sub_title;
    /* @@protoc_insertion_point(struct:AlexaTitle) */
} AlexaTitle;

typedef struct _AlexaWeatherItem_List
{
    pb_size_t list_count;
    struct _AlexaWeatherItem *list;
    /* @@protoc_insertion_point(struct:AlexaWeatherItem_List) */
} AlexaWeatherItem_List;

typedef struct _AlexaAlertsSetAlert
{
    char *token;
    AlexaAlertType type;
    char *scheduledTime;
    char *label;
    /* @@protoc_insertion_point(struct:AlexaAlertsSetAlert) */
} AlexaAlertsSetAlert;

typedef struct _AlexaNotificationsSetIndicator
{
    bool playAudioIndicator;
    bool persistVisualIndicator;
    /* @@protoc_insertion_point(struct:AlexaNotificationsSetIndicator) */
} AlexaNotificationsSetIndicator;

typedef struct _AlexaQuietMode
{
    bool on;
    /* @@protoc_insertion_point(struct:AlexaQuietMode) */
} AlexaQuietMode;

typedef struct _AlexaTemplateGeneral
{
    AlexaTitle title;
    char *text;
    /* @@protoc_insertion_point(struct:AlexaTemplateGeneral) */
} AlexaTemplateGeneral;

typedef struct _AlexaTemplateLists
{
    AlexaTitle title;
    AlexaListsItem_List items;
    bool exceed_max_items;
    /* @@protoc_insertion_point(struct:AlexaTemplateLists) */
} AlexaTemplateLists;

typedef struct _AlexaTemplateWeather
{
    AlexaTitle title;
    char *current_weather;
    char *description;
    char *high_temperature;
    char *low_temperature;
    char *image;
    AlexaWeatherItem_List weatherForecast;
    int32_t weather_code;
    /* @@protoc_insertion_point(struct:AlexaTemplateWeather) */
} AlexaTemplateWeather;

typedef struct _AlexaWeatherItem
{
    char *date;
    char *weekday;
    char *high_temperature;
    char *low_temperature;
    char *image;
    int32_t weather_code;
    /* @@protoc_insertion_point(struct:AlexaWeatherItem) */
} AlexaWeatherItem;

typedef struct _Alexa
{
    pb_size_t which_payload;
    union
    {
        AlexaInstruction_List instruction_list;
        AlexaConfig config;
        AlexaQuietMode quiet_mode;
    } payload;
    /* @@protoc_insertion_point(struct:Alexa) */
} Alexa;

typedef struct _AlexaInstruction
{
    AlexaResultType result_type;
    bool has_template_general;
    AlexaTemplateGeneral template_general;
    bool has_template_weather;
    AlexaTemplateWeather template_weather;
    bool has_template_lists;
    AlexaTemplateLists template_lists;
    bool has_alerts_setalert;
    AlexaAlertsSetAlert alerts_setalert;
    bool has_speechsynthesizer_speak;
    AlexaSpeechSynthesizerSpeak speechsynthesizer_speak;
    bool has_auth_status;
    AlexaAuthStatus auth_status;
    bool has_alerts_deletealerts;
    AlexaAlertsDeleteAlert_List alerts_deletealerts;
    bool has_notifications_setindicator;
    AlexaNotificationsSetIndicator notifications_setindicator;
    /* @@protoc_insertion_point(struct:AlexaInstruction) */
} AlexaInstruction;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Alexa_init_default                       {0, {AlexaInstruction_List_init_default}}
#define AlexaConfig_init_default                 {NULL, NULL, NULL}
#define AlexaQuietMode_init_default              {0}
#define AlexaInstruction_init_default            {_AlexaResultType_MIN, false, AlexaTemplateGeneral_init_default, false, AlexaTemplateWeather_init_default, false, AlexaTemplateLists_init_default, false, AlexaAlertsSetAlert_init_default, false, AlexaSpeechSynthesizerSpeak_init_default, false, _AlexaAuthStatus_MIN, false, AlexaAlertsDeleteAlert_List_init_default, false, AlexaNotificationsSetIndicator_init_default}
#define AlexaInstruction_List_init_default       {0, NULL}
#define AlexaTemplateGeneral_init_default        {AlexaTitle_init_default, NULL}
#define AlexaTemplateWeather_init_default        {AlexaTitle_init_default, NULL, NULL, NULL, NULL, NULL, AlexaWeatherItem_List_init_default, 0}
#define AlexaWeatherItem_init_default            {NULL, NULL, NULL, NULL, NULL, 0}
#define AlexaWeatherItem_List_init_default       {0, NULL}
#define AlexaTemplateLists_init_default          {AlexaTitle_init_default, AlexaListsItem_List_init_default, 0}
#define AlexaListsItem_init_default              {NULL, NULL}
#define AlexaListsItem_List_init_default         {0, NULL}
#define AlexaAlertsSetAlert_init_default         {NULL, _AlexaAlertType_MIN, NULL, NULL}
#define AlexaAlertsDeleteAlert_init_default      {NULL}
#define AlexaAlertsDeleteAlert_List_init_default {0, NULL}
#define AlexaSpeechSynthesizerSpeak_init_default {NULL}
#define AlexaTitle_init_default                  {NULL, NULL}
#define AlexaNotificationsSetIndicator_init_default {0, 0}
#define Alexa_init_zero                          {0, {AlexaInstruction_List_init_zero}}
#define AlexaConfig_init_zero                    {NULL, NULL, NULL}
#define AlexaQuietMode_init_zero                 {0}
#define AlexaInstruction_init_zero               {_AlexaResultType_MIN, false, AlexaTemplateGeneral_init_zero, false, AlexaTemplateWeather_init_zero, false, AlexaTemplateLists_init_zero, false, AlexaAlertsSetAlert_init_zero, false, AlexaSpeechSynthesizerSpeak_init_zero, false, _AlexaAuthStatus_MIN, false, AlexaAlertsDeleteAlert_List_init_zero, false, AlexaNotificationsSetIndicator_init_zero}
#define AlexaInstruction_List_init_zero          {0, NULL}
#define AlexaTemplateGeneral_init_zero           {AlexaTitle_init_zero, NULL}
#define AlexaTemplateWeather_init_zero           {AlexaTitle_init_zero, NULL, NULL, NULL, NULL, NULL, AlexaWeatherItem_List_init_zero, 0}
#define AlexaWeatherItem_init_zero               {NULL, NULL, NULL, NULL, NULL, 0}
#define AlexaWeatherItem_List_init_zero          {0, NULL}
#define AlexaTemplateLists_init_zero             {AlexaTitle_init_zero, AlexaListsItem_List_init_zero, 0}
#define AlexaListsItem_init_zero                 {NULL, NULL}
#define AlexaListsItem_List_init_zero            {0, NULL}
#define AlexaAlertsSetAlert_init_zero            {NULL, _AlexaAlertType_MIN, NULL, NULL}
#define AlexaAlertsDeleteAlert_init_zero         {NULL}
#define AlexaAlertsDeleteAlert_List_init_zero    {0, NULL}
#define AlexaSpeechSynthesizerSpeak_init_zero    {NULL}
#define AlexaTitle_init_zero                     {NULL, NULL}
#define AlexaNotificationsSetIndicator_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AlexaAlertsDeleteAlert_token_tag         1
#define AlexaAlertsDeleteAlert_List_list_tag     1
#define AlexaConfig_client_id_tag                1
#define AlexaConfig_refresh_token_tag            2
#define AlexaConfig_language_tag                 3
#define AlexaInstruction_List_list_tag           1
#define AlexaListsItem_left_tag                  1
#define AlexaListsItem_right_tag                 2
#define AlexaListsItem_List_list_tag             1
#define AlexaSpeechSynthesizerSpeak_text_tag     1
#define AlexaTitle_main_title_tag                1
#define AlexaTitle_sub_title_tag                 2
#define AlexaWeatherItem_List_list_tag           1
#define AlexaAlertsSetAlert_token_tag            1
#define AlexaAlertsSetAlert_type_tag             2
#define AlexaAlertsSetAlert_scheduledTime_tag    3
#define AlexaAlertsSetAlert_label_tag            4
#define AlexaNotificationsSetIndicator_playAudioIndicator_tag 1
#define AlexaNotificationsSetIndicator_persistVisualIndicator_tag 2
#define AlexaQuietMode_on_tag                    1
#define AlexaTemplateGeneral_title_tag           1
#define AlexaTemplateGeneral_text_tag            2
#define AlexaTemplateLists_title_tag             1
#define AlexaTemplateLists_items_tag             2
#define AlexaTemplateLists_exceed_max_items_tag  3
#define AlexaTemplateWeather_title_tag           1
#define AlexaTemplateWeather_current_weather_tag 2
#define AlexaTemplateWeather_description_tag     3
#define AlexaTemplateWeather_high_temperature_tag 4
#define AlexaTemplateWeather_low_temperature_tag 5
#define AlexaTemplateWeather_image_tag           6
#define AlexaTemplateWeather_weatherForecast_tag 7
#define AlexaTemplateWeather_weather_code_tag    8
#define AlexaWeatherItem_date_tag                1
#define AlexaWeatherItem_weekday_tag             2
#define AlexaWeatherItem_high_temperature_tag    3
#define AlexaWeatherItem_low_temperature_tag     4
#define AlexaWeatherItem_image_tag               5
#define AlexaWeatherItem_weather_code_tag        6
#define Alexa_instruction_list_tag               1
#define Alexa_config_tag                         2
#define Alexa_quiet_mode_tag                     3
#define AlexaInstruction_result_type_tag         1
#define AlexaInstruction_template_general_tag    2
#define AlexaInstruction_template_weather_tag    3
#define AlexaInstruction_template_lists_tag      4
#define AlexaInstruction_alerts_setalert_tag     5
#define AlexaInstruction_speechsynthesizer_speak_tag 6
#define AlexaInstruction_auth_status_tag         7
#define AlexaInstruction_alerts_deletealerts_tag 12
#define AlexaInstruction_notifications_setindicator_tag 13

/* Struct field encoding specification for nanopb */
extern const pb_field_t Alexa_fields[4];
extern const pb_field_t AlexaConfig_fields[4];
extern const pb_field_t AlexaQuietMode_fields[2];
extern const pb_field_t AlexaInstruction_fields[10];
extern const pb_field_t AlexaInstruction_List_fields[2];
extern const pb_field_t AlexaTemplateGeneral_fields[3];
extern const pb_field_t AlexaTemplateWeather_fields[9];
extern const pb_field_t AlexaWeatherItem_fields[7];
extern const pb_field_t AlexaWeatherItem_List_fields[2];
extern const pb_field_t AlexaTemplateLists_fields[4];
extern const pb_field_t AlexaListsItem_fields[3];
extern const pb_field_t AlexaListsItem_List_fields[2];
extern const pb_field_t AlexaAlertsSetAlert_fields[5];
extern const pb_field_t AlexaAlertsDeleteAlert_fields[2];
extern const pb_field_t AlexaAlertsDeleteAlert_List_fields[2];
extern const pb_field_t AlexaSpeechSynthesizerSpeak_fields[2];
extern const pb_field_t AlexaTitle_fields[3];
extern const pb_field_t AlexaNotificationsSetIndicator_fields[3];

/* Maximum encoded size of messages (where known) */
/* Alexa_size depends on runtime parameters */
/* AlexaConfig_size depends on runtime parameters */
#define AlexaQuietMode_size                      2
/* AlexaInstruction_size depends on runtime parameters */
/* AlexaInstruction_List_size depends on runtime parameters */
/* AlexaTemplateGeneral_size depends on runtime parameters */
/* AlexaTemplateWeather_size depends on runtime parameters */
/* AlexaWeatherItem_size depends on runtime parameters */
/* AlexaWeatherItem_List_size depends on runtime parameters */
/* AlexaTemplateLists_size depends on runtime parameters */
/* AlexaListsItem_size depends on runtime parameters */
/* AlexaListsItem_List_size depends on runtime parameters */
/* AlexaAlertsSetAlert_size depends on runtime parameters */
/* AlexaAlertsDeleteAlert_size depends on runtime parameters */
/* AlexaAlertsDeleteAlert_List_size depends on runtime parameters */
/* AlexaSpeechSynthesizerSpeak_size depends on runtime parameters */
/* AlexaTitle_size depends on runtime parameters */
#define AlexaNotificationsSetIndicator_size      4

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_ALEXA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
