/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.6 at Fri Jun 10 15:10:20 2022. */

#ifndef PB_WEAR_AIVS_PB_H_INCLUDED
#define PB_WEAR_AIVS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ResultType
{
    ResultType_START_LISTENING = 0,
    ResultType_END_LISTENING = 1,
    ResultType_RECOGNIZE_RESULT = 2,
    ResultType_STOP_CAPTURE = 3,
    ResultType_DIALOG_FINISH = 4,
    ResultType_SYSTEM_TRUNCATIONNOTIFICATION = 5,
    ResultType_ERROR_NETWORK = 80,
    ResultType_ERROR_AUTH = 81,
    ResultType_ERROR_TOO_MANY_DEVICES = 82,
    ResultType_ERROR_CONTENT_TOO_LONG = 83,
    ResultType_AIVS_ERROR_ASR_TIMEOUT = 112,
    ResultType_AIVS_ERROR_TTS_TIMEOUT = 113,
    ResultType_TEMPLATE_TOAST = 256,
    ResultType_TEMPLATE_GENERAL = 257,
    ResultType_TEMPLATE_GENERAL2 = 258,
    ResultType_TEMPLATE_WEATHER = 259,
    ResultType_TEMPLATE_PLAYINFO = 260,
    ResultType_TEMPLATE_LISTS = 261,
    ResultType_TEMPLATE_SWITCHPANEL = 262,
    ResultType_ALERTS_SETALERT = 263,
    ResultType_SPEECHSYNTHESIZER_SPEAK = 264,
    ResultType_SPEECHRECOGNIZER_EXPECTSPEECH = 265,
    ResultType_LAUNCHER_LAUNCHAPP = 266,
    ResultType_TEMPLATE_SWITCHPANELLIST = 267,
    ResultType_BRIGHTNESSCONTROLLER_ADJUSTBRIGHTNESS = 268,
    ResultType_SYSTEM_SETPROPERTY = 269,
    ResultType_APPLICATION_OPERATE = 270,
    ResultType_ALERTS_DELIVERALERTINTENTION = 271,
    ResultType_ALERTS_STOPALERT = 272,
    ResultType_PLAYBACKCONTROLLER = 273,
    ResultType_PLAYBACKCONTROLLER_STOP = 274,
    ResultType_PLAYBACKCONTROLLER_PLAY = 275,
    ResultType_PLAYBACKCONTROLLER_PAUSE = 276,
    ResultType_PLAYBACKCONTROLLER_NEXT = 277,
    ResultType_PLAYBACKCONTROLLER_PREV = 278,
    ResultType_PLAYBACKCONTROLLER_CONTINUEPLAYING = 279,
    ResultType_SPEAKER_SETMUTE = 280,
    ResultType_SPEAKER_SETVOLUME = 281,
    ResultType_SPEAKER_AJUSTVOLUME = 282,
    ResultType_TEMPLATE_DEVICELIST = 283,
    ResultType_EXECUTE_DEVICESKILL = 284,
    ResultType_SHOW_CONTACTS = 285,
    ResultType_MAKE_CALL = 286
} ResultType;
#define _ResultType_MIN ResultType_START_LISTENING
#define _ResultType_MAX ResultType_MAKE_CALL
#define _ResultType_ARRAYSIZE ((ResultType)(ResultType_MAKE_CALL+1))

typedef enum _ApplictionOp
{
    ApplictionOp_ApplictionOp_UNKNOWN = -1,
    ApplictionOp_ApplictionOp_OPEN = 0,
    ApplictionOp_ApplictionOp_INSTALL = 1,
    ApplictionOp_ApplictionOp_UNINSTALL = 2,
    ApplictionOp_ApplictionOp_CLOSE = 3,
    ApplictionOp_ApplictionOp_SEARCH = 4
} ApplictionOp;
#define _ApplictionOp_MIN ApplictionOp_ApplictionOp_UNKNOWN
#define _ApplictionOp_MAX ApplictionOp_ApplictionOp_SEARCH
#define _ApplictionOp_ARRAYSIZE ((ApplictionOp)(ApplictionOp_ApplictionOp_SEARCH+1))

typedef enum _PlayInfoType
{
    PlayInfoType_PIT_UNKNOWN = -1,
    PlayInfoType_JOKE = 0,
    PlayInfoType_POEM = 1,
    PlayInfoType_MUSIC = 2,
    PlayInfoType_STATION = 3,
    PlayInfoType_VOICE_NEWS = 4,
    PlayInfoType_SOUND = 5,
    PlayInfoType_TRANSLATION = 6
} PlayInfoType;
#define _PlayInfoType_MIN PlayInfoType_PIT_UNKNOWN
#define _PlayInfoType_MAX PlayInfoType_TRANSLATION
#define _PlayInfoType_ARRAYSIZE ((PlayInfoType)(PlayInfoType_TRANSLATION+1))

typedef enum _SwitchPanelType
{
    SwitchPanelType_SwitchPanelType_UNKNOWN = -1,
    SwitchPanelType_DEFAULT = 0,
    SwitchPanelType_COUNTDOWN = 1
} SwitchPanelType;
#define _SwitchPanelType_MIN SwitchPanelType_SwitchPanelType_UNKNOWN
#define _SwitchPanelType_MAX SwitchPanelType_COUNTDOWN
#define _SwitchPanelType_ARRAYSIZE ((SwitchPanelType)(SwitchPanelType_COUNTDOWN+1))

typedef enum _AlertType
{
    AlertType_AlertType_UNKNOWN = -1,
    AlertType_ALARM = 0,
    AlertType_REMINDER = 1,
    AlertType_TIMER = 2
} AlertType;
#define _AlertType_MIN AlertType_AlertType_UNKNOWN
#define _AlertType_MAX AlertType_TIMER
#define _AlertType_ARRAYSIZE ((AlertType)(AlertType_TIMER+1))

typedef enum _AlertCircleType
{
    AlertCircleType_AlertCircleType_UNKNOWN = -1,
    AlertCircleType_ONCE = 0,
    AlertCircleType_EVERYDAY = 1,
    AlertCircleType_WORKDAY = 2,
    AlertCircleType_MONDAY_TO_FRIDAY = 3,
    AlertCircleType_HOLIDAY = 4,
    AlertCircleType_WEEKEND = 5,
    AlertCircleType_WEEKLY = 6,
    AlertCircleType_MONTHLY = 7,
    AlertCircleType_YEARLY = 8
} AlertCircleType;
#define _AlertCircleType_MIN AlertCircleType_AlertCircleType_UNKNOWN
#define _AlertCircleType_MAX AlertCircleType_YEARLY
#define _AlertCircleType_ARRAYSIZE ((AlertCircleType)(AlertCircleType_YEARLY+1))

typedef enum _AlertOperation
{
    AlertOperation_AlertOperation_UNKNOWN = -1,
    AlertOperation_OPEN = 0,
    AlertOperation_CLOSE = 1,
    AlertOperation_PAUSE = 2,
    AlertOperation_PROCEED = 3,
    AlertOperation_QUERY = 4,
    AlertOperation_DELETE = 5
} AlertOperation;
#define _AlertOperation_MIN AlertOperation_AlertOperation_UNKNOWN
#define _AlertOperation_MAX AlertOperation_DELETE
#define _AlertOperation_ARRAYSIZE ((AlertOperation)(AlertOperation_DELETE+1))

typedef enum _AlertFilterType
{
    AlertFilterType_ALERTFILTER_UNKNOWN = -1,
    AlertFilterType_ALERTFILTER_RECENTLY_SET = 0,
    AlertFilterType_ALERTFILTER_RECENTLY_CALL = 1,
    AlertFilterType_ALERTFILTER_ON_STATUS = 2,
    AlertFilterType_ALERTFILTER_OFF_STATUS = 3
} AlertFilterType;
#define _AlertFilterType_MIN AlertFilterType_ALERTFILTER_UNKNOWN
#define _AlertFilterType_MAX AlertFilterType_ALERTFILTER_OFF_STATUS
#define _AlertFilterType_ARRAYSIZE ((AlertFilterType)(AlertFilterType_ALERTFILTER_OFF_STATUS+1))

typedef enum _AlertTimeType
{
    AlertTimeType_ALERTTIME_UNKNOWN = -1,
    AlertTimeType_ALERTTIME_DATETIME = 0,
    AlertTimeType_ALERTTIME_DURATION = 1,
    AlertTimeType_ALERTTIME_OFFSET = 2,
    AlertTimeType_ALERTTIME_INDETER_DATETIME = 3
} AlertTimeType;
#define _AlertTimeType_MIN AlertTimeType_ALERTTIME_UNKNOWN
#define _AlertTimeType_MAX AlertTimeType_ALERTTIME_INDETER_DATETIME
#define _AlertTimeType_ARRAYSIZE ((AlertTimeType)(AlertTimeType_ALERTTIME_INDETER_DATETIME+1))

typedef enum _MediaErrorType
{
    MediaErrorType_Media_ERROR_OK = 0,
    MediaErrorType_Media_ERROR_UNSUPPORT_SYSTEM = 1,
    MediaErrorType_Media_ERROR_NO_PERMISSION = 2,
    MediaErrorType_Media_ERROR_NO_MUSIC = 3,
    MediaErrorType_Media_ERROR_ALREADY_PLAYING_ON_PLAY = 4,
    MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_PAUSE = 5,
    MediaErrorType_Media_ERROR_ALREADY_MAX_ON_RAISE_VOLUME = 6,
    MediaErrorType_Media_ERROR_ALREADY_MIN_ON_LOWER_VOLUME = 7,
    MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_ADJUST_VOLUME = 8,
    MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_SET_VOLUME = 9,
    MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_SET_MUTE = 10
} MediaErrorType;
#define _MediaErrorType_MIN MediaErrorType_Media_ERROR_OK
#define _MediaErrorType_MAX MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_SET_MUTE
#define _MediaErrorType_ARRAYSIZE ((MediaErrorType)(MediaErrorType_Media_ERROR_ALREADY_PAUSED_ON_SET_MUTE+1))

typedef enum _SpeakerVolumeType
{
    SpeakerVolumeType_Speaker_VOLUME_UNKNOWN = -1,
    SpeakerVolumeType_Speaker_VOLUME_MEDIA = 0,
    SpeakerVolumeType_Speaker_VOLUME_RING = 1,
    SpeakerVolumeType_Speaker_VOLUME_NOTIFICATION = 2,
    SpeakerVolumeType_Speaker_VOLUME_VOICE_ASSISTANT = 3,
    SpeakerVolumeType_Speaker_VOLUME_ALARM = 4
} SpeakerVolumeType;
#define _SpeakerVolumeType_MIN SpeakerVolumeType_Speaker_VOLUME_UNKNOWN
#define _SpeakerVolumeType_MAX SpeakerVolumeType_Speaker_VOLUME_ALARM
#define _SpeakerVolumeType_ARRAYSIZE ((SpeakerVolumeType)(SpeakerVolumeType_Speaker_VOLUME_ALARM+1))

typedef enum _SpeakerUnitDef
{
    SpeakerUnitDef_Speaker_UNIT_UNKNOWN = -1,
    SpeakerUnitDef_Speaker_UNIT_PERCENT = 0,
    SpeakerUnitDef_Speaker_UNIT_ABSOLUTE = 1
} SpeakerUnitDef;
#define _SpeakerUnitDef_MIN SpeakerUnitDef_Speaker_UNIT_UNKNOWN
#define _SpeakerUnitDef_MAX SpeakerUnitDef_Speaker_UNIT_ABSOLUTE
#define _SpeakerUnitDef_ARRAYSIZE ((SpeakerUnitDef)(SpeakerUnitDef_Speaker_UNIT_ABSOLUTE+1))

typedef enum _Aivs_AivsID
{
    Aivs_AivsID_SYNC_INSTRUCTION_LIST = 0,
    Aivs_AivsID_GET_CONFIG = 1,
    Aivs_AivsID_SET_CONFIG = 2
} Aivs_AivsID;
#define _Aivs_AivsID_MIN Aivs_AivsID_SYNC_INSTRUCTION_LIST
#define _Aivs_AivsID_MAX Aivs_AivsID_SET_CONFIG
#define _Aivs_AivsID_ARRAYSIZE ((Aivs_AivsID)(Aivs_AivsID_SET_CONFIG+1))

typedef enum _ShowContacts_Code
{
    ShowContacts_Code_OK = 0,
    ShowContacts_Code_NO_PERMISSION = 1
} ShowContacts_Code;
#define _ShowContacts_Code_MIN ShowContacts_Code_OK
#define _ShowContacts_Code_MAX ShowContacts_Code_NO_PERMISSION
#define _ShowContacts_Code_ARRAYSIZE ((ShowContacts_Code)(ShowContacts_Code_NO_PERMISSION+1))

/* Struct definitions */
typedef struct _AbstractItem
{
    char *k;
    char *v;
    /* @@protoc_insertion_point(struct:AbstractItem) */
} AbstractItem;

typedef struct _AbstractItem_List
{
    pb_size_t list_count;
    struct _AbstractItem *list;
    /* @@protoc_insertion_point(struct:AbstractItem_List) */
} AbstractItem_List;

typedef struct _AivsInstruction_List
{
    pb_size_t list_count;
    struct _AivsInstruction *list;
    /* @@protoc_insertion_point(struct:AivsInstruction_List) */
} AivsInstruction_List;

typedef struct _AndroidIntent
{
    char *pkg_name;
    char *uri;
    /* @@protoc_insertion_point(struct:AndroidIntent) */
} AndroidIntent;

typedef struct _DeviceItem_List
{
    pb_size_t list_count;
    struct _DeviceItem *list;
    /* @@protoc_insertion_point(struct:DeviceItem_List) */
} DeviceItem_List;

typedef struct _ListsItem_List
{
    pb_size_t list_count;
    struct _ListsItem *list;
    /* @@protoc_insertion_point(struct:ListsItem_List) */
} ListsItem_List;

typedef struct _PlayInfoItem_List
{
    pb_size_t list_count;
    struct _PlayInfoItem *list;
    /* @@protoc_insertion_point(struct:PlayInfoItem_List) */
} PlayInfoItem_List;

typedef struct _RichText
{
    char *text;
    char *color;
    char *bg_color;
    /* @@protoc_insertion_point(struct:RichText) */
} RichText;

typedef struct _RichText_List
{
    pb_size_t list_count;
    struct _RichText *list;
    /* @@protoc_insertion_point(struct:RichText_List) */
} RichText_List;

typedef struct _ShowContacts_ContactData
{
    char *name;
    char *number;
    /* @@protoc_insertion_point(struct:ShowContacts_ContactData) */
} ShowContacts_ContactData;

typedef struct _SpeechRecognizeResultItem
{
    char *text;
    /* @@protoc_insertion_point(struct:SpeechRecognizeResultItem) */
} SpeechRecognizeResultItem;

typedef struct _SpeechRecognizeResultItem_List
{
    pb_size_t list_count;
    struct _SpeechRecognizeResultItem *list;
    /* @@protoc_insertion_point(struct:SpeechRecognizeResultItem_List) */
} SpeechRecognizeResultItem_List;

typedef struct _SpeechSynthesizerSpeak
{
    char *text;
    /* @@protoc_insertion_point(struct:SpeechSynthesizerSpeak) */
} SpeechSynthesizerSpeak;

typedef struct _SwitchItem_List
{
    pb_size_t list_count;
    struct _SwitchItem *list;
    /* @@protoc_insertion_point(struct:SwitchItem_List) */
} SwitchItem_List;

typedef struct _SystemSetProperty
{
    char *name;
    char *value;
    /* @@protoc_insertion_point(struct:SystemSetProperty) */
} SystemSetProperty;

typedef struct _TemplateToast
{
    char *text;
    /* @@protoc_insertion_point(struct:TemplateToast) */
} TemplateToast;

typedef struct _Title
{
    char *main_title;
    char *sub_title;
    /* @@protoc_insertion_point(struct:Title) */
} Title;

typedef struct _WeatherCode
{
    char *current;
    char *from;
    char *to;
    /* @@protoc_insertion_point(struct:WeatherCode) */
} WeatherCode;

typedef struct _WeatherItem_List
{
    pb_size_t list_count;
    struct _WeatherItem *list;
    /* @@protoc_insertion_point(struct:WeatherItem_List) */
} WeatherItem_List;

typedef struct _WeatherWindDirection
{
    char *text;
    char *current;
    char *from;
    char *to;
    /* @@protoc_insertion_point(struct:WeatherWindDirection) */
} WeatherWindDirection;

typedef struct _WeatherWindSpeed
{
    char *text;
    char *current;
    char *from;
    char *to;
    /* @@protoc_insertion_point(struct:WeatherWindSpeed) */
} WeatherWindSpeed;

typedef struct _AivsConfig
{
    bool enable_tts;
    /* @@protoc_insertion_point(struct:AivsConfig) */
} AivsConfig;

typedef struct _AlertDateTime
{
    char *value;
    int64_t timestamp;
    /* @@protoc_insertion_point(struct:AlertDateTime) */
} AlertDateTime;

typedef struct _AlertsSetAlert
{
    char *id;
    AlertType type;
    char *datetime;
    bool has_circle;
    AlertCircleType circle;
    char *circle_extra;
    char *offset;
    /* @@protoc_insertion_point(struct:AlertsSetAlert) */
} AlertsSetAlert;

typedef struct _ApplicationOperate
{
    ApplictionOp operation;
    char *keyword;
    char *app_pkg_name;
    /* @@protoc_insertion_point(struct:ApplicationOperate) */
} ApplicationOperate;

typedef struct _BrightnessControllerAjustBrightness
{
    int32_t brightness_delta;
    /* @@protoc_insertion_point(struct:BrightnessControllerAjustBrightness) */
} BrightnessControllerAjustBrightness;

typedef struct _DeviceItem
{
    Title title;
    /* @@protoc_insertion_point(struct:DeviceItem) */
} DeviceItem;

typedef struct _ExecuteDeviceSkill
{
    AndroidIntent intent;
    /* @@protoc_insertion_point(struct:ExecuteDeviceSkill) */
} ExecuteDeviceSkill;

typedef struct _LauncherLaunchApp
{
    AndroidIntent intent;
    /* @@protoc_insertion_point(struct:LauncherLaunchApp) */
} LauncherLaunchApp;

typedef struct _ListsItem
{
    Title title;
    char *text;
    char *skill_description;
    /* @@protoc_insertion_point(struct:ListsItem) */
} ListsItem;

typedef struct _PlayInfoItem
{
    Title title;
    bool has_duration_in_ms;
    uint32_t duration_in_ms;
    char *text;
    /* @@protoc_insertion_point(struct:PlayInfoItem) */
} PlayInfoItem;

typedef struct _ShowContacts
{
    ShowContacts_Code code;
    pb_size_t list_count;
    struct _ShowContacts_ContactData *list;
    /* @@protoc_insertion_point(struct:ShowContacts) */
} ShowContacts;

typedef struct _SpeakerAjustVolume
{
    int32_t volume_delta;
    SpeakerVolumeType type;
    SpeakerUnitDef unit;
    /* @@protoc_insertion_point(struct:SpeakerAjustVolume) */
} SpeakerAjustVolume;

typedef struct _SpeakerSetMute
{
    bool mute;
    /* @@protoc_insertion_point(struct:SpeakerSetMute) */
} SpeakerSetMute;

typedef struct _SpeakerSetVolume
{
    int32_t volume;
    SpeakerVolumeType type;
    SpeakerUnitDef unit;
    bool has_once;
    bool once;
    /* @@protoc_insertion_point(struct:SpeakerSetVolume) */
} SpeakerSetVolume;

typedef struct _SpeechRecognizeResult
{
    bool is_final;
    SpeechRecognizeResultItem_List results;
    /* @@protoc_insertion_point(struct:SpeechRecognizeResult) */
} SpeechRecognizeResult;

typedef struct _SwitchItem
{
    Title title;
    char *status;
    /* @@protoc_insertion_point(struct:SwitchItem) */
} SwitchItem;

typedef struct _TemplateDeviceList
{
    DeviceItem_List items;
    bool exceed_max_items;
    bool show_index;
    /* @@protoc_insertion_point(struct:TemplateDeviceList) */
} TemplateDeviceList;

typedef struct _TemplateGeneral
{
    Title title;
    char *text;
    bool has_results;
    AbstractItem_List results;
    char *skill_description;
    /* @@protoc_insertion_point(struct:TemplateGeneral) */
} TemplateGeneral;

typedef struct _TemplateGeneral2
{
    RichText main_title;
    RichText_List sub_titles;
    RichText_List texts;
    char *skill_description;
    /* @@protoc_insertion_point(struct:TemplateGeneral2) */
} TemplateGeneral2;

typedef struct _TemplateLists
{
    char *skill_description;
    ListsItem_List items;
    bool has_title;
    Title title;
    /* @@protoc_insertion_point(struct:TemplateLists) */
} TemplateLists;

typedef struct _TemplatePlayInfo
{
    PlayInfoItem_List items;
    PlayInfoType type;
    char *skill_description;
    /* @@protoc_insertion_point(struct:TemplatePlayInfo) */
} TemplatePlayInfo;

typedef struct _TemplateSwitchPanel
{
    Title title;
    char *skill_description;
    char *status;
    bool has_type;
    SwitchPanelType type;
    /* @@protoc_insertion_point(struct:TemplateSwitchPanel) */
} TemplateSwitchPanel;

typedef struct _TemplateSwitchPanelList
{
    SwitchItem_List titles;
    char *skill_description;
    bool has_type;
    SwitchPanelType type;
    bool has_items;
    SwitchItem_List items;
    /* @@protoc_insertion_point(struct:TemplateSwitchPanelList) */
} TemplateSwitchPanelList;

typedef struct _TemplateWeather
{
    WeatherItem_List weather;
    char *skill_description;
    /* @@protoc_insertion_point(struct:TemplateWeather) */
} TemplateWeather;

typedef struct _WeatherWind
{
    bool has_direction;
    WeatherWindDirection direction;
    bool has_speed;
    WeatherWindSpeed speed;
    /* @@protoc_insertion_point(struct:WeatherWind) */
} WeatherWind;

typedef struct _Aivs
{
    pb_size_t which_payload;
    union
    {
        AivsInstruction_List instruction_list;
        AivsConfig aivs_config;
    } payload;
    /* @@protoc_insertion_point(struct:Aivs) */
} Aivs;

typedef struct _AlertTimeInfo
{
    AlertTimeType type;
    char *token;
    bool has_datetime;
    AlertDateTime datetime;
    bool has_start_datetime;
    AlertDateTime start_datetime;
    bool has_end_datetime;
    AlertDateTime end_datetime;
    /* @@protoc_insertion_point(struct:AlertTimeInfo) */
} AlertTimeInfo;

typedef struct _WeatherItem
{
    char *date;
    char *location;
    char *aqi;
    char *current_temperature;
    char *high_temperature;
    char *low_temperature;
    char *icon_description;
    bool has_weather_code;
    WeatherCode weather_code;
    bool has_wind;
    WeatherWind wind;
    char *weekday;
    /* @@protoc_insertion_point(struct:WeatherItem) */
} WeatherItem;

typedef struct _AlertsDeliverAlertIntention
{
    AlertType type;
    AlertOperation operation;
    bool operate_all;
    bool has_circle;
    AlertCircleType circle;
    char *circle_extra;
    char *event;
    bool has_filter_type;
    AlertFilterType filter_type;
    bool has_time;
    AlertTimeInfo time;
    /* @@protoc_insertion_point(struct:AlertsDeliverAlertIntention) */
} AlertsDeliverAlertIntention;

typedef struct _AivsInstruction
{
    ResultType result_type;
    bool has_recognize_result;
    SpeechRecognizeResult recognize_result;
    bool has_template_toast;
    TemplateToast template_toast;
    bool has_template_general;
    TemplateGeneral template_general;
    bool has_template_general2;
    TemplateGeneral2 template_general2;
    bool has_template_weather;
    TemplateWeather template_weather;
    bool has_template_playinfo;
    TemplatePlayInfo template_playinfo;
    bool has_template_lists;
    TemplateLists template_lists;
    bool has_template_switchpanel;
    TemplateSwitchPanel template_switchpanel;
    bool has_alerts_setalert;
    AlertsSetAlert alerts_setalert;
    bool has_speechsynthesizer_speak;
    SpeechSynthesizerSpeak speechsynthesizer_speak;
    uint8_t session_id;
    bool has_laucher_lauchapp;
    LauncherLaunchApp laucher_lauchapp;
    bool has_template_switchpanellist;
    TemplateSwitchPanelList template_switchpanellist;
    bool has_brightnesscontroller_ajustbrightness;
    BrightnessControllerAjustBrightness brightnesscontroller_ajustbrightness;
    bool has_system_setproperty;
    SystemSetProperty system_setproperty;
    bool has_application_operate;
    ApplicationOperate application_operate;
    bool has_alerts_deliveralertintention;
    AlertsDeliverAlertIntention alerts_deliveralertintention;
    bool has_media_errortype;
    MediaErrorType media_errortype;
    bool has_speaker_setmute;
    SpeakerSetMute speaker_setmute;
    bool has_speaker_setvolume;
    SpeakerSetVolume speaker_setvolume;
    bool has_speaker_ajustvolume;
    SpeakerAjustVolume speaker_ajustvolume;
    bool has_template_devicelist;
    TemplateDeviceList template_devicelist;
    bool has_execute_deviceskill;
    ExecuteDeviceSkill execute_deviceskill;
    bool has_show_contacts;
    ShowContacts show_contacts;
    bool has_contact_data;
    ShowContacts_ContactData contact_data;
    /* @@protoc_insertion_point(struct:AivsInstruction) */
} AivsInstruction;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Aivs_init_default                        {0, {AivsInstruction_List_init_default}}
#define AivsConfig_init_default                  {0}
#define AivsInstruction_init_default             {_ResultType_MIN, false, SpeechRecognizeResult_init_default, false, TemplateToast_init_default, false, TemplateGeneral_init_default, false, TemplateGeneral2_init_default, false, TemplateWeather_init_default, false, TemplatePlayInfo_init_default, false, TemplateLists_init_default, false, TemplateSwitchPanel_init_default, false, AlertsSetAlert_init_default, false, SpeechSynthesizerSpeak_init_default, 0, false, LauncherLaunchApp_init_default, false, TemplateSwitchPanelList_init_default, false, BrightnessControllerAjustBrightness_init_default, false, SystemSetProperty_init_default, false, ApplicationOperate_init_default, false, AlertsDeliverAlertIntention_init_default, false, _MediaErrorType_MIN, false, SpeakerSetMute_init_default, false, SpeakerSetVolume_init_default, false, SpeakerAjustVolume_init_default, false, TemplateDeviceList_init_default, false, ExecuteDeviceSkill_init_default, false, ShowContacts_init_default, false, ShowContacts_ContactData_init_default}
#define AivsInstruction_List_init_default        {0, NULL}
#define SpeechRecognizeResult_init_default       {0, SpeechRecognizeResultItem_List_init_default}
#define TemplateToast_init_default               {NULL}
#define TemplateGeneral_init_default             {Title_init_default, NULL, false, AbstractItem_List_init_default, NULL}
#define TemplateGeneral2_init_default            {RichText_init_default, RichText_List_init_default, RichText_List_init_default, NULL}
#define TemplateWeather_init_default             {WeatherItem_List_init_default, NULL}
#define TemplatePlayInfo_init_default            {PlayInfoItem_List_init_default, _PlayInfoType_MIN, NULL}
#define TemplateLists_init_default               {NULL, ListsItem_List_init_default, false, Title_init_default}
#define TemplateSwitchPanel_init_default         {Title_init_default, NULL, NULL, false, _SwitchPanelType_MIN}
#define TemplateSwitchPanelList_init_default     {SwitchItem_List_init_default, NULL, false, _SwitchPanelType_MIN, false, SwitchItem_List_init_default}
#define SwitchItem_init_default                  {Title_init_default, NULL}
#define SwitchItem_List_init_default             {0, NULL}
#define AlertsSetAlert_init_default              {NULL, _AlertType_MIN, NULL, false, _AlertCircleType_MIN, NULL, NULL}
#define AlertsDeliverAlertIntention_init_default {_AlertType_MIN, _AlertOperation_MIN, 0, false, _AlertCircleType_MIN, NULL, NULL, false, _AlertFilterType_MIN, false, AlertTimeInfo_init_default}
#define SpeechSynthesizerSpeak_init_default      {NULL}
#define SpeechRecognizeResultItem_init_default   {NULL}
#define SpeechRecognizeResultItem_List_init_default {0, NULL}
#define SystemSetProperty_init_default           {NULL, NULL}
#define LauncherLaunchApp_init_default           {AndroidIntent_init_default}
#define ExecuteDeviceSkill_init_default          {AndroidIntent_init_default}
#define BrightnessControllerAjustBrightness_init_default {0}
#define ApplicationOperate_init_default          {_ApplictionOp_MIN, NULL, NULL}
#define AndroidIntent_init_default               {NULL, NULL}
#define AbstractItem_init_default                {NULL, NULL}
#define AbstractItem_List_init_default           {0, NULL}
#define Title_init_default                       {NULL, NULL}
#define RichText_init_default                    {NULL, NULL, NULL}
#define RichText_List_init_default               {0, NULL}
#define WeatherItem_init_default                 {NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, WeatherCode_init_default, false, WeatherWind_init_default, NULL}
#define WeatherItem_List_init_default            {0, NULL}
#define WeatherCode_init_default                 {NULL, NULL, NULL}
#define WeatherWind_init_default                 {false, WeatherWindDirection_init_default, false, WeatherWindSpeed_init_default}
#define WeatherWindDirection_init_default        {NULL, NULL, NULL, NULL}
#define WeatherWindSpeed_init_default            {NULL, NULL, NULL, NULL}
#define PlayInfoItem_init_default                {Title_init_default, false, 0, NULL}
#define PlayInfoItem_List_init_default           {0, NULL}
#define ListsItem_init_default                   {Title_init_default, NULL, NULL}
#define ListsItem_List_init_default              {0, NULL}
#define AlertTimeInfo_init_default               {_AlertTimeType_MIN, NULL, false, AlertDateTime_init_default, false, AlertDateTime_init_default, false, AlertDateTime_init_default}
#define AlertDateTime_init_default               {NULL, 0}
#define SpeakerSetMute_init_default              {0}
#define SpeakerSetVolume_init_default            {0, _SpeakerVolumeType_MIN, _SpeakerUnitDef_MIN, false, 0}
#define SpeakerAjustVolume_init_default          {0, _SpeakerVolumeType_MIN, _SpeakerUnitDef_MIN}
#define TemplateDeviceList_init_default          {DeviceItem_List_init_default, 0, 0}
#define DeviceItem_init_default                  {Title_init_default}
#define DeviceItem_List_init_default             {0, NULL}
#define ShowContacts_init_default                {_ShowContacts_Code_MIN, 0, NULL}
#define ShowContacts_ContactData_init_default    {NULL, NULL}
#define Aivs_init_zero                           {0, {AivsInstruction_List_init_zero}}
#define AivsConfig_init_zero                     {0}
#define AivsInstruction_init_zero                {_ResultType_MIN, false, SpeechRecognizeResult_init_zero, false, TemplateToast_init_zero, false, TemplateGeneral_init_zero, false, TemplateGeneral2_init_zero, false, TemplateWeather_init_zero, false, TemplatePlayInfo_init_zero, false, TemplateLists_init_zero, false, TemplateSwitchPanel_init_zero, false, AlertsSetAlert_init_zero, false, SpeechSynthesizerSpeak_init_zero, 0, false, LauncherLaunchApp_init_zero, false, TemplateSwitchPanelList_init_zero, false, BrightnessControllerAjustBrightness_init_zero, false, SystemSetProperty_init_zero, false, ApplicationOperate_init_zero, false, AlertsDeliverAlertIntention_init_zero, false, _MediaErrorType_MIN, false, SpeakerSetMute_init_zero, false, SpeakerSetVolume_init_zero, false, SpeakerAjustVolume_init_zero, false, TemplateDeviceList_init_zero, false, ExecuteDeviceSkill_init_zero, false, ShowContacts_init_zero, false, ShowContacts_ContactData_init_zero}
#define AivsInstruction_List_init_zero           {0, NULL}
#define SpeechRecognizeResult_init_zero          {0, SpeechRecognizeResultItem_List_init_zero}
#define TemplateToast_init_zero                  {NULL}
#define TemplateGeneral_init_zero                {Title_init_zero, NULL, false, AbstractItem_List_init_zero, NULL}
#define TemplateGeneral2_init_zero               {RichText_init_zero, RichText_List_init_zero, RichText_List_init_zero, NULL}
#define TemplateWeather_init_zero                {WeatherItem_List_init_zero, NULL}
#define TemplatePlayInfo_init_zero               {PlayInfoItem_List_init_zero, _PlayInfoType_MIN, NULL}
#define TemplateLists_init_zero                  {NULL, ListsItem_List_init_zero, false, Title_init_zero}
#define TemplateSwitchPanel_init_zero            {Title_init_zero, NULL, NULL, false, _SwitchPanelType_MIN}
#define TemplateSwitchPanelList_init_zero        {SwitchItem_List_init_zero, NULL, false, _SwitchPanelType_MIN, false, SwitchItem_List_init_zero}
#define SwitchItem_init_zero                     {Title_init_zero, NULL}
#define SwitchItem_List_init_zero                {0, NULL}
#define AlertsSetAlert_init_zero                 {NULL, _AlertType_MIN, NULL, false, _AlertCircleType_MIN, NULL, NULL}
#define AlertsDeliverAlertIntention_init_zero    {_AlertType_MIN, _AlertOperation_MIN, 0, false, _AlertCircleType_MIN, NULL, NULL, false, _AlertFilterType_MIN, false, AlertTimeInfo_init_zero}
#define SpeechSynthesizerSpeak_init_zero         {NULL}
#define SpeechRecognizeResultItem_init_zero      {NULL}
#define SpeechRecognizeResultItem_List_init_zero {0, NULL}
#define SystemSetProperty_init_zero              {NULL, NULL}
#define LauncherLaunchApp_init_zero              {AndroidIntent_init_zero}
#define ExecuteDeviceSkill_init_zero             {AndroidIntent_init_zero}
#define BrightnessControllerAjustBrightness_init_zero {0}
#define ApplicationOperate_init_zero             {_ApplictionOp_MIN, NULL, NULL}
#define AndroidIntent_init_zero                  {NULL, NULL}
#define AbstractItem_init_zero                   {NULL, NULL}
#define AbstractItem_List_init_zero              {0, NULL}
#define Title_init_zero                          {NULL, NULL}
#define RichText_init_zero                       {NULL, NULL, NULL}
#define RichText_List_init_zero                  {0, NULL}
#define WeatherItem_init_zero                    {NULL, NULL, NULL, NULL, NULL, NULL, NULL, false, WeatherCode_init_zero, false, WeatherWind_init_zero, NULL}
#define WeatherItem_List_init_zero               {0, NULL}
#define WeatherCode_init_zero                    {NULL, NULL, NULL}
#define WeatherWind_init_zero                    {false, WeatherWindDirection_init_zero, false, WeatherWindSpeed_init_zero}
#define WeatherWindDirection_init_zero           {NULL, NULL, NULL, NULL}
#define WeatherWindSpeed_init_zero               {NULL, NULL, NULL, NULL}
#define PlayInfoItem_init_zero                   {Title_init_zero, false, 0, NULL}
#define PlayInfoItem_List_init_zero              {0, NULL}
#define ListsItem_init_zero                      {Title_init_zero, NULL, NULL}
#define ListsItem_List_init_zero                 {0, NULL}
#define AlertTimeInfo_init_zero                  {_AlertTimeType_MIN, NULL, false, AlertDateTime_init_zero, false, AlertDateTime_init_zero, false, AlertDateTime_init_zero}
#define AlertDateTime_init_zero                  {NULL, 0}
#define SpeakerSetMute_init_zero                 {0}
#define SpeakerSetVolume_init_zero               {0, _SpeakerVolumeType_MIN, _SpeakerUnitDef_MIN, false, 0}
#define SpeakerAjustVolume_init_zero             {0, _SpeakerVolumeType_MIN, _SpeakerUnitDef_MIN}
#define TemplateDeviceList_init_zero             {DeviceItem_List_init_zero, 0, 0}
#define DeviceItem_init_zero                     {Title_init_zero}
#define DeviceItem_List_init_zero                {0, NULL}
#define ShowContacts_init_zero                   {_ShowContacts_Code_MIN, 0, NULL}
#define ShowContacts_ContactData_init_zero       {NULL, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define AbstractItem_k_tag                       1
#define AbstractItem_v_tag                       2
#define AbstractItem_List_list_tag               1
#define AivsInstruction_List_list_tag            1
#define AndroidIntent_pkg_name_tag               1
#define AndroidIntent_uri_tag                    2
#define DeviceItem_List_list_tag                 1
#define ListsItem_List_list_tag                  1
#define PlayInfoItem_List_list_tag               1
#define RichText_text_tag                        1
#define RichText_color_tag                       2
#define RichText_bg_color_tag                    3
#define RichText_List_list_tag                   1
#define ShowContacts_ContactData_name_tag        1
#define ShowContacts_ContactData_number_tag      2
#define SpeechRecognizeResultItem_text_tag       1
#define SpeechRecognizeResultItem_List_list_tag  1
#define SpeechSynthesizerSpeak_text_tag          1
#define SwitchItem_List_list_tag                 1
#define SystemSetProperty_name_tag               1
#define SystemSetProperty_value_tag              2
#define TemplateToast_text_tag                   1
#define Title_main_title_tag                     1
#define Title_sub_title_tag                      2
#define WeatherCode_current_tag                  1
#define WeatherCode_from_tag                     2
#define WeatherCode_to_tag                       3
#define WeatherItem_List_list_tag                1
#define WeatherWindDirection_text_tag            1
#define WeatherWindDirection_current_tag         2
#define WeatherWindDirection_from_tag            3
#define WeatherWindDirection_to_tag              4
#define WeatherWindSpeed_text_tag                1
#define WeatherWindSpeed_current_tag             2
#define WeatherWindSpeed_from_tag                3
#define WeatherWindSpeed_to_tag                  4
#define AivsConfig_enable_tts_tag                1
#define AlertDateTime_value_tag                  1
#define AlertDateTime_timestamp_tag              2
#define AlertsSetAlert_id_tag                    1
#define AlertsSetAlert_type_tag                  2
#define AlertsSetAlert_datetime_tag              3
#define AlertsSetAlert_circle_tag                4
#define AlertsSetAlert_circle_extra_tag          5
#define AlertsSetAlert_offset_tag                6
#define ApplicationOperate_operation_tag         1
#define ApplicationOperate_keyword_tag           2
#define ApplicationOperate_app_pkg_name_tag      3
#define BrightnessControllerAjustBrightness_brightness_delta_tag 1
#define DeviceItem_title_tag                     1
#define ExecuteDeviceSkill_intent_tag            1
#define LauncherLaunchApp_intent_tag             1
#define ListsItem_title_tag                      1
#define ListsItem_text_tag                       2
#define ListsItem_skill_description_tag          3
#define PlayInfoItem_title_tag                   1
#define PlayInfoItem_duration_in_ms_tag          2
#define PlayInfoItem_text_tag                    3
#define ShowContacts_code_tag                    1
#define ShowContacts_list_tag                    2
#define SpeakerAjustVolume_volume_delta_tag      1
#define SpeakerAjustVolume_type_tag              2
#define SpeakerAjustVolume_unit_tag              3
#define SpeakerSetMute_mute_tag                  1
#define SpeakerSetVolume_volume_tag              1
#define SpeakerSetVolume_type_tag                2
#define SpeakerSetVolume_unit_tag                3
#define SpeakerSetVolume_once_tag                4
#define SpeechRecognizeResult_is_final_tag       1
#define SpeechRecognizeResult_results_tag        2
#define SwitchItem_title_tag                     1
#define SwitchItem_status_tag                    2
#define TemplateDeviceList_items_tag             1
#define TemplateDeviceList_exceed_max_items_tag  2
#define TemplateDeviceList_show_index_tag        3
#define TemplateGeneral_title_tag                1
#define TemplateGeneral_text_tag                 2
#define TemplateGeneral_results_tag              3
#define TemplateGeneral_skill_description_tag    4
#define TemplateGeneral2_main_title_tag          1
#define TemplateGeneral2_sub_titles_tag          2
#define TemplateGeneral2_texts_tag               3
#define TemplateGeneral2_skill_description_tag   4
#define TemplateLists_skill_description_tag      1
#define TemplateLists_items_tag                  2
#define TemplateLists_title_tag                  3
#define TemplatePlayInfo_items_tag               1
#define TemplatePlayInfo_type_tag                2
#define TemplatePlayInfo_skill_description_tag   3
#define TemplateSwitchPanel_title_tag            1
#define TemplateSwitchPanel_skill_description_tag 2
#define TemplateSwitchPanel_status_tag           3
#define TemplateSwitchPanel_type_tag             4
#define TemplateSwitchPanelList_titles_tag       1
#define TemplateSwitchPanelList_skill_description_tag 2
#define TemplateSwitchPanelList_type_tag         3
#define TemplateSwitchPanelList_items_tag        4
#define TemplateWeather_weather_tag              1
#define TemplateWeather_skill_description_tag    2
#define WeatherWind_direction_tag                1
#define WeatherWind_speed_tag                    2
#define Aivs_instruction_list_tag                1
#define Aivs_aivs_config_tag                     2
#define AlertTimeInfo_type_tag                   1
#define AlertTimeInfo_token_tag                  2
#define AlertTimeInfo_datetime_tag               3
#define AlertTimeInfo_start_datetime_tag         4
#define AlertTimeInfo_end_datetime_tag           5
#define WeatherItem_date_tag                     1
#define WeatherItem_location_tag                 2
#define WeatherItem_aqi_tag                      3
#define WeatherItem_current_temperature_tag      4
#define WeatherItem_high_temperature_tag         5
#define WeatherItem_low_temperature_tag          6
#define WeatherItem_icon_description_tag         7
#define WeatherItem_weather_code_tag             8
#define WeatherItem_wind_tag                     9
#define WeatherItem_weekday_tag                  10
#define AlertsDeliverAlertIntention_type_tag     1
#define AlertsDeliverAlertIntention_operation_tag 2
#define AlertsDeliverAlertIntention_operate_all_tag 3
#define AlertsDeliverAlertIntention_circle_tag   4
#define AlertsDeliverAlertIntention_circle_extra_tag 5
#define AlertsDeliverAlertIntention_event_tag    6
#define AlertsDeliverAlertIntention_filter_type_tag 7
#define AlertsDeliverAlertIntention_time_tag     8
#define AivsInstruction_result_type_tag          1
#define AivsInstruction_session_id_tag           13
#define AivsInstruction_recognize_result_tag     2
#define AivsInstruction_template_toast_tag       3
#define AivsInstruction_template_general_tag     4
#define AivsInstruction_template_general2_tag    5
#define AivsInstruction_template_weather_tag     6
#define AivsInstruction_template_playinfo_tag    7
#define AivsInstruction_template_lists_tag       8
#define AivsInstruction_template_switchpanel_tag 9
#define AivsInstruction_alerts_setalert_tag      10
#define AivsInstruction_speechsynthesizer_speak_tag 11
#define AivsInstruction_laucher_lauchapp_tag     14
#define AivsInstruction_template_switchpanellist_tag 15
#define AivsInstruction_brightnesscontroller_ajustbrightness_tag 16
#define AivsInstruction_system_setproperty_tag   17
#define AivsInstruction_application_operate_tag  18
#define AivsInstruction_alerts_deliveralertintention_tag 19
#define AivsInstruction_media_errortype_tag      20
#define AivsInstruction_speaker_setmute_tag      21
#define AivsInstruction_speaker_setvolume_tag    22
#define AivsInstruction_speaker_ajustvolume_tag  23
#define AivsInstruction_template_devicelist_tag  24
#define AivsInstruction_execute_deviceskill_tag  25
#define AivsInstruction_show_contacts_tag        26
#define AivsInstruction_contact_data_tag         27

/* Struct field encoding specification for nanopb */
extern const pb_field_t Aivs_fields[3];
extern const pb_field_t AivsConfig_fields[2];
extern const pb_field_t AivsInstruction_fields[27];
extern const pb_field_t AivsInstruction_List_fields[2];
extern const pb_field_t SpeechRecognizeResult_fields[3];
extern const pb_field_t TemplateToast_fields[2];
extern const pb_field_t TemplateGeneral_fields[5];
extern const pb_field_t TemplateGeneral2_fields[5];
extern const pb_field_t TemplateWeather_fields[3];
extern const pb_field_t TemplatePlayInfo_fields[4];
extern const pb_field_t TemplateLists_fields[4];
extern const pb_field_t TemplateSwitchPanel_fields[5];
extern const pb_field_t TemplateSwitchPanelList_fields[5];
extern const pb_field_t SwitchItem_fields[3];
extern const pb_field_t SwitchItem_List_fields[2];
extern const pb_field_t AlertsSetAlert_fields[7];
extern const pb_field_t AlertsDeliverAlertIntention_fields[9];
extern const pb_field_t SpeechSynthesizerSpeak_fields[2];
extern const pb_field_t SpeechRecognizeResultItem_fields[2];
extern const pb_field_t SpeechRecognizeResultItem_List_fields[2];
extern const pb_field_t SystemSetProperty_fields[3];
extern const pb_field_t LauncherLaunchApp_fields[2];
extern const pb_field_t ExecuteDeviceSkill_fields[2];
extern const pb_field_t BrightnessControllerAjustBrightness_fields[2];
extern const pb_field_t ApplicationOperate_fields[4];
extern const pb_field_t AndroidIntent_fields[3];
extern const pb_field_t AbstractItem_fields[3];
extern const pb_field_t AbstractItem_List_fields[2];
extern const pb_field_t Title_fields[3];
extern const pb_field_t RichText_fields[4];
extern const pb_field_t RichText_List_fields[2];
extern const pb_field_t WeatherItem_fields[11];
extern const pb_field_t WeatherItem_List_fields[2];
extern const pb_field_t WeatherCode_fields[4];
extern const pb_field_t WeatherWind_fields[3];
extern const pb_field_t WeatherWindDirection_fields[5];
extern const pb_field_t WeatherWindSpeed_fields[5];
extern const pb_field_t PlayInfoItem_fields[4];
extern const pb_field_t PlayInfoItem_List_fields[2];
extern const pb_field_t ListsItem_fields[4];
extern const pb_field_t ListsItem_List_fields[2];
extern const pb_field_t AlertTimeInfo_fields[6];
extern const pb_field_t AlertDateTime_fields[3];
extern const pb_field_t SpeakerSetMute_fields[2];
extern const pb_field_t SpeakerSetVolume_fields[5];
extern const pb_field_t SpeakerAjustVolume_fields[4];
extern const pb_field_t TemplateDeviceList_fields[4];
extern const pb_field_t DeviceItem_fields[2];
extern const pb_field_t DeviceItem_List_fields[2];
extern const pb_field_t ShowContacts_fields[3];
extern const pb_field_t ShowContacts_ContactData_fields[3];

/* Maximum encoded size of messages (where known) */
/* Aivs_size depends on runtime parameters */
#define AivsConfig_size                          2
/* AivsInstruction_size depends on runtime parameters */
/* AivsInstruction_List_size depends on runtime parameters */
/* SpeechRecognizeResult_size depends on runtime parameters */
/* TemplateToast_size depends on runtime parameters */
/* TemplateGeneral_size depends on runtime parameters */
/* TemplateGeneral2_size depends on runtime parameters */
/* TemplateWeather_size depends on runtime parameters */
/* TemplatePlayInfo_size depends on runtime parameters */
/* TemplateLists_size depends on runtime parameters */
/* TemplateSwitchPanel_size depends on runtime parameters */
/* TemplateSwitchPanelList_size depends on runtime parameters */
/* SwitchItem_size depends on runtime parameters */
/* SwitchItem_List_size depends on runtime parameters */
/* AlertsSetAlert_size depends on runtime parameters */
/* AlertsDeliverAlertIntention_size depends on runtime parameters */
/* SpeechSynthesizerSpeak_size depends on runtime parameters */
/* SpeechRecognizeResultItem_size depends on runtime parameters */
/* SpeechRecognizeResultItem_List_size depends on runtime parameters */
/* SystemSetProperty_size depends on runtime parameters */
/* LauncherLaunchApp_size depends on runtime parameters */
/* ExecuteDeviceSkill_size depends on runtime parameters */
#define BrightnessControllerAjustBrightness_size 11
/* ApplicationOperate_size depends on runtime parameters */
/* AndroidIntent_size depends on runtime parameters */
/* AbstractItem_size depends on runtime parameters */
/* AbstractItem_List_size depends on runtime parameters */
/* Title_size depends on runtime parameters */
/* RichText_size depends on runtime parameters */
/* RichText_List_size depends on runtime parameters */
/* WeatherItem_size depends on runtime parameters */
/* WeatherItem_List_size depends on runtime parameters */
/* WeatherCode_size depends on runtime parameters */
/* WeatherWind_size depends on runtime parameters */
/* WeatherWindDirection_size depends on runtime parameters */
/* WeatherWindSpeed_size depends on runtime parameters */
/* PlayInfoItem_size depends on runtime parameters */
/* PlayInfoItem_List_size depends on runtime parameters */
/* ListsItem_size depends on runtime parameters */
/* ListsItem_List_size depends on runtime parameters */
/* AlertTimeInfo_size depends on runtime parameters */
/* AlertDateTime_size depends on runtime parameters */
#define SpeakerSetMute_size                      2
#define SpeakerSetVolume_size                    35
#define SpeakerAjustVolume_size                  33
/* TemplateDeviceList_size depends on runtime parameters */
/* DeviceItem_size depends on runtime parameters */
/* DeviceItem_List_size depends on runtime parameters */
/* ShowContacts_size depends on runtime parameters */
/* ShowContacts_ContactData_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define WEAR_AIVS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
