# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_BUILD_SCRIPT_AS_A_APP']):
    src += ['ezxml.c']
if GetDepend(['CONFIG_REALTEK_BUILD_WATCHFACE_UPDATE']):
    src += ['ezxml.c']


CPPPATH = [cwd]

group = DefineGroup('realgui/3rd', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH)

Return('group')
