Import('TOOL_ROOT')
#import wristband_sdk_config
from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []

# add the general drivers.
src = Split("""
""")

if GetDepend(['PRIVATE_SERVICE']):
    src += ['communicate_task.c']
    src += ['communicate_protocol.c']
    src += ['communicate_parse.c']
    src += ['communicate_parse_bond.c']
    src += ['communicate_parse_control.c']
    src += ['communicate_parse_setting.c']
    src += ['communicate_parse_health.c']
    src += ['communicate_parse_notify.c']
    src += ['communicate_parse_navigation.c']

CPPPATH = [cwd, cwd + './../Sensor_Algorithm_3.8.14']
CPPDEFINES = ['RTK_PRIVATE_SERVICE']

group = DefineGroup('communication', src, depend = ['PRIVATE_SERVICE'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')