# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd]
src = Glob('*.c')

objs = DefineGroup('misc', src, depend = [''], CPPPATH = inc)
list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
