
from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('realgui/dc', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('group')
