Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['BSP_TOUCH_GT911']):
    src += ['touch_gt911.c']
if GetDepend(['BSP_TOUCH_816S']):
    src += ['touch_816s.c']
if GetDepend(['BSP_TOUCH_ZT2717']):
    src += ['touch_zt2717.c']

CPPPATH = [cwd]

group = DefineGroup('touch_driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')