# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_800_400']
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['BUILD_USING_RTK_GUI_800_480_DEMO'], CPPPATH = CPPPATH)

Return('group')
