# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPDEFINES = []
if not GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    SrcRemove(src,'app_lvgl.c')
SrcRemove(src,'app_dashboard_480_272.c')
SrcRemove(src,'app_dashboard_800_400.c')
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_800_480']
print(CPPPATH)

if GetDepend('CONFIG_REALTEK_BUILD_GUI_800_480_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_800_480_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=800']
    CPPDEFINES += ['DRV_LCD_HIGHT=480']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_800_480_DEMO'], CPPPATH = CPPPATH)

Return('group')
