# building script for HoneyGUI

from building import *
import os

cwd = GetCurrentDir()
CPPPATH = [cwd]

objs = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HEIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_PARTICLE_DEMO'):
    src = Glob('*.c')
    objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
    
Return('objs')
