# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd, os.path.join(cwd, 'root_image'), os.path.join(cwd, '..', '..', '..', 'realgui', 'widget', 'gui_particle', 'effects')]
src = ['particle_demo.c', 'particle_launcher.c', 'example_particle.c']

if GetDepend(['CONFIG_REALTEK_BUILD_PARTICLE_DEMO']):
    CPPDEFINES = ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HEIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    objs = DefineGroup('example/widget', src, depend = [''], CPPPATH = inc, CPPDEFINES = CPPDEFINES)
    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
else:
    objs = []

Return('objs')
