# building script for HoneyGUI

from building import *
import os

cwd = GetCurrentDir()
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image']
CPPPATH += [os.path.join(cwd, '..', '..', '..', 'realgui', 'widget', 'gui_particle', 'effects')]

objs = []
CPPDEFINES = []
src = []

# Demo, launcher, example: depend on particle demo selection
if GetDepend('CONFIG_REALTEK_BUILD_PARTICLE_DEMO'):
    CPPDEFINES = ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HEIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    src += [os.path.join(cwd, f) for f in [
        'particle_demo.c',
        'particle_launcher.c',
        'example_particle.c',
    ]]

objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
