# for module compiling
import os
Import('TOOL_ROOT')
Import('WEARABLE_ROOT')

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, 
           WEARABLE_ROOT + '/example/root_image/']


src = Split("""
""")
#src = Glob('*.c')
src = ['main.c']
src += ['rtk_gui_demo.c']


CPPDEFINES = ['GUI_KEIL_SIM']
objs = DefineGroup('application', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
