# building script for HoneyGUI
from building import *

Import('env')

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += Glob('./*.cpp') 


CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image']

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_466_466_DEMO'):
    CPPDEFINES += ['DRV_LCD_WIDTH=466']
    CPPDEFINES += ['DRV_LCD_HEIGHT=466']
    CPPDEFINES += ['DRV_PIXEL_BITS=32']
    CPPDEFINES += ['DRV_LCD_CORNER_RADIUS=-1']
objs = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_466_466_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
