#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: MIT
#

set(CONFIG_REALTEK_HONEYGUI y)
set(CONFIG_REALTEK_BUILD_PINYIN y)
set(CONFIG_REALTEK_BUILD_LETTER_SHELL y)
set(CONFIG_REALTEK_BUILD_MONKEY_TEST y)
set(CONFIG_REALTEK_H264_DECODER y)
set(CONFIG_REALTEK_H264BSD y)
set(CONFIG_REALTEK_BUILD_GUI_BOX2D y)
set(CONFIG_REALTEK_BUILD_LITE3D y)
