
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('realgui/3rd', src, depend = ['CONFIG_REALTEK_BUILD_LETTER_SHELL'], CPPPATH = CPPPATH)

Return('group')
