from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
LOCAL_CCFLAGS = ''
libs = ['']
libpath = [cwd]

libs += Split('''
health_algorithm_3.8.14
''')

group = DefineGroup('algorithm', src, depend = ['MODULE_USING_RTK_ALGO'], CPPPATH = CPPPATH, LIBS = libs, LIBPATH = libpath)

Return('group')
