# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_V9'], CPPPATH = CPPPATH)

Return('group')
