# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image']
src = Split("""
""")

objs = []

CPPDEFINES = []

if GetDepend('CONFIG_REALTEK_BUILD_EXAMPLE_LITE_VIDEO_WIDGET'):

    src += ['example_lite_video.c']
    CPPDEFINES = ['DRV_LCD_WIDTH=360']
    CPPDEFINES += ['DRV_LCD_HEIGHT=360']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    CPPDEFINES += ['DRV_LCD_CORNER_RADIUS=0']

objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
