# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += Glob('./gui_main/*.c')
src += Glob('./gui_watchface/*.c')
src += Glob('./gui_player/*.c')
src += Glob('./gui_contacts/*.c')
src += Glob('./gui_common/*.c')
src += Glob('./gui_call/*.c')
src += Glob('./gui_record/*.c')
CPPPATH = [cwd]
CPPPATH += [cwd + '\\gui_common']
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['BUILD_USING_RTK_GUI_454_454_BB2PLUS_WATCH'], CPPPATH = CPPPATH)

Return('group')
