# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

group = []
CPPDEFINES = []
CPPDEFINES += ['DRV_PIXEL_BITS=16']


if GetDepend('CONFIG_REALTEK_BUILD_REAL_DOG_3D'):
    src += ['app_ui_realgui_3d_dog.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)   

if GetDepend('CONFIG_REALTEK_BUILD_REAL_EARTH_3D'):
    src += ['app_ui_realgui_3d_earth.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES) 

if GetDepend('CONFIG_REALTEK_BUILD_REAL_PIKACHU_GLTF_3D'):
    src += ['app_ui_realgui_3d_pikachu_gltf.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES) 

if GetDepend('CONFIG_REALTEK_BUILD_REAL_FLAG_GLTF_3D'):
    src += ['app_ui_realgui_3d_flag_gltf.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES) 

Return('group')
