# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

group = []
CPPDEFINES = []
CPPDEFINES += ['DRV_PIXEL_BITS=16']


if GetDepend('CONFIG_REALTEK_BUILD_REAL_BUTTERFLY_3D'):
    src += ['app_ui_realgui_3d_butterfly.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_PRISM_MIRROR_3D'):
    src += [cwd + '/prism3d/src/app_ui_realgui_3d_view_image.c']
    src += [cwd + '/prism3d/src/app_ui_realgui_3d_view_prism.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_FACE_3D'):
    src += ['app_ui_realgui_3d_face.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)   

if GetDepend('CONFIG_REALTEK_BUILD_REAL_DOG_3D'):
    src += ['app_ui_realgui_3d_dog.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)   

if GetDepend('CONFIG_REALTEK_BUILD_REAL_DISC_3D'):
    src += ['app_ui_realgui_3d_disc.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES) 
if GetDepend('CONFIG_REALTEK_BUILD_REAL_SEAWATER_3D'):
    CPPDEFINES += ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HIGHT=502']
    src += [cwd +'/SeaWaterDClock/example_gui_SeaWater.c']
    src += [cwd +'/SeaWaterDClock/gui_nanovg_wave.c']
    CPPPATH +=[cwd +'/SeaWaterDClock' ]
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)     

Return('group')
