# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd]
src = []

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_DOG_3D']):
    src += ['example_3d_dog.c']

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_EARTH_3D']):
    src += ['example_3d_earth.c']

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_DONUT_3D']):
    src += ['example_3d_donut.c']

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_PIKACHU_GLTF_3D']):
    src += ['example_3d_pikachu_gltf.c']

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_FLAG_GLTF_3D']):
    src += ['example_3d_flag_gltf.c']

if GetDepend(['CONFIG_REALTEK_BUILD_REAL_ROBOT_GLTF_3D']):
    src += ['example_3d_robot_gltf.c']

if src:
    CPPDEFINES = ['DRV_PIXEL_BITS=16']
    objs = DefineGroup('example/widget', src, depend = [''], CPPPATH = inc, CPPDEFINES = CPPDEFINES)
else:
    objs = []

Return('objs')
