from building import *
import os


src = []
inc = []
group = []

cwd = GetCurrentDir() # get current dir path



# check if .h or .hpp files exsit
def check_h_hpp_exsit(path):
    file_dirs = os.listdir(path)
    for file_dir in file_dirs:
        if os.path.splitext(file_dir)[1] in ['.h', '.hpp']:
            return True
    return False



for root, dirs, files in os.walk(cwd):
    for dir in dirs:
        current_path = os.path.join(root, dir)
        if check_h_hpp_exsit(current_path): # add .h and .hpp path
            inc = inc + [current_path]

src += [cwd + '/HoneyGUI.lib']

CPPDEFINES = ['ENABLE_HONEYGUI']

group = DefineGroup('gui', src, depend = ['CONFIG_REALTEK_BUILD_HONEYGUI_LIB'], CPPPATH = inc, CPPDEFINES = CPPDEFINES)



Return('group')
