
#ifndef GUI_VERSION_H
#define GUI_VERSION_H

#define VERSION_TAG "v1.1.0.0.RVD"
#define VERSION_BRANCH "dev"
#define VERSION_COMMIT "49902bca"
#define VERSION_BUILD_DATE "2025-03-31 11:24:54"
#define VERSION_REPO_STATUS "clean"

#endif // GUI_VERSION_H
