# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
list = os.listdir(cwd)
src = Split("""""")
CPPPATH = [cwd]

CPPDEFINES = ['ENABLE_HONEYGUI']


group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_HONEYGUI'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            if not os.path.isfile(os.path.join(path, 'SConstruct')):
                group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
