# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
list = os.listdir(cwd)
src = Split("""""")
CPPPATH = [cwd]

CPPDEFINES = ['ENABLE_HONEYGUI']

if GetDepend('CONFIG_REALTEK_BUILD_GUI_XML_DOM'):
    CPPDEFINES += ['REALTEK_BUILD_GUI_XML_DOM']
if GetDepend('CONFIG_REALTEK_BUILD_SCRIPT_AS_A_APP'):
    CPPDEFINES += ['ENABLE_RTK_GUI_SCRIPT_AS_A_APP']
if GetDepend('CONFIG_REALTEK_BUILD_VG_LITE'):
    CPPDEFINES += ['RTK_MODULE_VG_LITE']
if GetDepend('CONFIG_REALTEK_BUILD_PPE'):
    CPPDEFINES += ['RTK_MODULE_RTK_PPE']
if GetDepend('CONFIG_REALTEK_BUILD_PPEV2'):
    CPPDEFINES += ['RTK_MODULE_RTK_PPEV2']
if GetDepend('CONFIG_REALTEK_BUILD_WATCHFACE_UPDATE'):
    CPPDEFINES += ['ENABLE_RTK_GUI_WATCHFACE_UPDATE']

group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_GUI'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            if not os.path.isfile(os.path.join(path, 'SConstruct')):
                group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
