from building import *

# get current directory
cwd = GetCurrentDir()

#src = Split("""""")
src     = Glob('*.c')

libs = ['']
libpath = [cwd]

libs += Split('''
alipay_crypto
alipay_IoTpay
alipay_mbedtls
alipay_transport
alipay_transport_test
cJSON/cJSON
transport_selftest/alipay_transport_test
pretest/pretest
''')

src += ['./vendor/alipay_vendor.c']
src += ['./vendor/transport_vendor.c']
src += ['./sm/sm3.c']
src += ['./sm/sm2_test.c']

path = [cwd, 
        cwd + '/cJSON',
        cwd + '/transport_selftest',
        cwd + '/pretest',
        cwd + '/sm',
        cwd + '/vendor']

group = DefineGroup('ali_iot', src, depend = ['MODULE_ALI_IOT'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs += group

Return('objs')
