#if defined _WIN32
extern unsigned char resource_root[];

#define   ARROW_BIN                               (void *)(resource_root + 0x00000438)
#define   BAR0_BIN                                (void *)(resource_root + 0x00008478)
#define   BAR1_BIN                                (void *)(resource_root + 0x0000acb8)
#define   BAR2_BIN                                (void *)(resource_root + 0x0000d4f8)
#define   BAR3_BIN                                (void *)(resource_root + 0x0000fd38)
#define   BAR4_BIN                                (void *)(resource_root + 0x00012578)
#define   BAT_CASE_BIN                            (void *)(resource_root + 0x00014db8)
#define   BAT_L_BIN                               (void *)(resource_root + 0x000154f8)
#define   BAT_R_BIN                               (void *)(resource_root + 0x00015c38)
#define   BLUETOOTH_OFF_BIN                       (void *)(resource_root + 0x00016378)
#define   BLUETOOTH_ON_BIN                        (void *)(resource_root + 0x00016ab8)
#define   BUTTON_BIN                              (void *)(resource_root + 0x000171f8)
#define   BUTTON_ON_BIN                           (void *)(resource_root + 0x0001c778)
#define   CALL_ANSWER_BIN                         (void *)(resource_root + 0x00021cf8)
#define   CALL_ANSWER_HIGHLIGHT_BIN               (void *)(resource_root + 0x00024f38)
#define   CALL_REJECT_BIN                         (void *)(resource_root + 0x00028178)
#define   CALL_REJECT_HIGHLIGHT_BIN               (void *)(resource_root + 0x0002b3b8)
#define   CLOCK_SET_BIN                           (void *)(resource_root + 0x0002e5f8)
#define   CLOCK_SET_HIGHLIGHT_BIN                 (void *)(resource_root + 0x00033738)
#define   CONN_BIN                                (void *)(resource_root + 0x00038878)
#define   CONN_BLUE_BIN                           (void *)(resource_root + 0x0003bcf8)
#define   DISC_BIN                                (void *)(resource_root + 0x0003f138)
#define   DISC_BLUE_BIN                           (void *)(resource_root + 0x000425b8)
#define   EQ_OFF_BIN                              (void *)(resource_root + 0x000459f8)
#define   EQ_ON_BIN                               (void *)(resource_root + 0x000462b8)
#define   FLASHLIGHT_BIN                          (void *)(resource_root + 0x00046b78)
#define   FLASHLIGHT_HIGHLIGHT_BIN                (void *)(resource_root + 0x0004c038)
#define   HARMONYOS_REGULAR_SIZE24_BITS1_FONT_BIN (void *)(resource_root + 0x00051538)
#define   HARMONYOS_REGULAR_SIZE28_BITS1_FONT_BIN (void *)(resource_root + 0x0023d338)
#define   LISTEN_ANC_BIN                          (void *)(resource_root + 0x0051b178)
#define   LISTEN_ANC_HIGHLIGHT_BIN                (void *)(resource_root + 0x0051ecb8)
#define   LISTEN_APT_BIN                          (void *)(resource_root + 0x005227f8)
#define   LISTEN_APT_HIGHLIGHT_BIN                (void *)(resource_root + 0x00526338)
#define   LISTEN_OFF_BIN                          (void *)(resource_root + 0x00529e78)
#define   LISTEN_OFF_HIGHLIGHT_BIN                (void *)(resource_root + 0x0052d9b8)
#define   MIC_MUTE_BIN                            (void *)(resource_root + 0x005314f8)
#define   MIC_MUTE_HIGHLIGHT_BIN                  (void *)(resource_root + 0x00533138)
#define   MIC_UNMUTE_BIN                          (void *)(resource_root + 0x00534d78)
#define   MIC_UNMUTE_HIGHLIGHT_BIN                (void *)(resource_root + 0x005369b8)
#define   MUSIC_BACKWARD_BIN                      (void *)(resource_root + 0x005385f8)
#define   MUSIC_BACKWARD_HIGHLIGHT_BIN            (void *)(resource_root + 0x0053b838)
#define   MUSIC_FORWARD_BIN                       (void *)(resource_root + 0x0053ea78)
#define   MUSIC_FORWARD_HIGHLIGHT_BIN             (void *)(resource_root + 0x00541cb8)
#define   MUSIC_PAUSE_BIN                         (void *)(resource_root + 0x00544ef8)
#define   MUSIC_PLAY_BIN                          (void *)(resource_root + 0x00548138)
#define   OPTION_LEFT_BIN                         (void *)(resource_root + 0x0054b378)
#define   OPTION_LEFT_HIGHLIGHT_BIN               (void *)(resource_root + 0x0054e5b8)
#define   OPTION_RIGHT_BIN                        (void *)(resource_root + 0x005517f8)
#define   OPTION_RIGHT_HIGHLIGHT_BIN              (void *)(resource_root + 0x00554a38)
#define   OVERLAP_BIN                             (void *)(resource_root + 0x00557c78)
#define   SCAN_BIN                                (void *)(resource_root + 0x00567338)
#define   SCAN_BLUE_BIN                           (void *)(resource_root + 0x0056a7b8)
#define   TWS_LEFT_BIN                            (void *)(resource_root + 0x0056dbf8)
#define   TWS_LEFT_HIGHLIGHT_BIN                  (void *)(resource_root + 0x005739f8)
#define   TWS_RIGHT_BIN                           (void *)(resource_root + 0x005797b8)
#define   TWS_RIGHT_HIGHLIGHT_BIN                 (void *)(resource_root + 0x0057f5b8)
#define   VOLUME_DOWN_BIN                         (void *)(resource_root + 0x00585378)
#define   VOLUME_DOWN_HIGHLIGHT_BIN               (void *)(resource_root + 0x005885b8)
#define   VOLUME_UP_BIN                           (void *)(resource_root + 0x0058b7f8)
#define   VOLUME_UP_HIGHLIGHT_BIN                 (void *)(resource_root + 0x0058ea38)
#define   WALLPAPER1_BIN                          (void *)(resource_root + 0x00591c78)
#define   WALLPAPER1_SIZE_BIN                     (void *)(resource_root + 0x005cdf38)
#define   WALLPAPER2_BIN                          (void *)(resource_root + 0x005d7978)
#define   WALLPAPER2_SIZE_BIN                     (void *)(resource_root + 0x00613c38)
#define   WALLPAPER3_BIN                          (void *)(resource_root + 0x0061d678)
#define   WALLPAPER3_SIZE_BIN                     (void *)(resource_root + 0x00659938)

#else
#define   ARROW_BIN                               (void *)(0x00a00438)
#define   BAR0_BIN                                (void *)(0x00a08478)
#define   BAR1_BIN                                (void *)(0x00a0acb8)
#define   BAR2_BIN                                (void *)(0x00a0d4f8)
#define   BAR3_BIN                                (void *)(0x00a0fd38)
#define   BAR4_BIN                                (void *)(0x00a12578)
#define   BAT_CASE_BIN                            (void *)(0x00a14db8)
#define   BAT_L_BIN                               (void *)(0x00a154f8)
#define   BAT_R_BIN                               (void *)(0x00a15c38)
#define   BLUETOOTH_OFF_BIN                       (void *)(0x00a16378)
#define   BLUETOOTH_ON_BIN                        (void *)(0x00a16ab8)
#define   BUTTON_BIN                              (void *)(0x00a171f8)
#define   BUTTON_ON_BIN                           (void *)(0x00a1c778)
#define   CALL_ANSWER_BIN                         (void *)(0x00a21cf8)
#define   CALL_ANSWER_HIGHLIGHT_BIN               (void *)(0x00a24f38)
#define   CALL_REJECT_BIN                         (void *)(0x00a28178)
#define   CALL_REJECT_HIGHLIGHT_BIN               (void *)(0x00a2b3b8)
#define   CLOCK_SET_BIN                           (void *)(0x00a2e5f8)
#define   CLOCK_SET_HIGHLIGHT_BIN                 (void *)(0x00a33738)
#define   CONN_BIN                                (void *)(0x00a38878)
#define   CONN_BLUE_BIN                           (void *)(0x00a3bcf8)
#define   DISC_BIN                                (void *)(0x00a3f138)
#define   DISC_BLUE_BIN                           (void *)(0x00a425b8)
#define   EQ_OFF_BIN                              (void *)(0x00a459f8)
#define   EQ_ON_BIN                               (void *)(0x00a462b8)
#define   FLASHLIGHT_BIN                          (void *)(0x00a46b78)
#define   FLASHLIGHT_HIGHLIGHT_BIN                (void *)(0x00a4c038)
#define   HARMONYOS_REGULAR_SIZE24_BITS1_FONT_BIN (void *)(0x00a51538)
#define   HARMONYOS_REGULAR_SIZE28_BITS1_FONT_BIN (void *)(0x00c3d338)
#define   LISTEN_ANC_BIN                          (void *)(0x00f1b178)
#define   LISTEN_ANC_HIGHLIGHT_BIN                (void *)(0x00f1ecb8)
#define   LISTEN_APT_BIN                          (void *)(0x00f227f8)
#define   LISTEN_APT_HIGHLIGHT_BIN                (void *)(0x00f26338)
#define   LISTEN_OFF_BIN                          (void *)(0x00f29e78)
#define   LISTEN_OFF_HIGHLIGHT_BIN                (void *)(0x00f2d9b8)
#define   MIC_MUTE_BIN                            (void *)(0x00f314f8)
#define   MIC_MUTE_HIGHLIGHT_BIN                  (void *)(0x00f33138)
#define   MIC_UNMUTE_BIN                          (void *)(0x00f34d78)
#define   MIC_UNMUTE_HIGHLIGHT_BIN                (void *)(0x00f369b8)
#define   MUSIC_BACKWARD_BIN                      (void *)(0x00f385f8)
#define   MUSIC_BACKWARD_HIGHLIGHT_BIN            (void *)(0x00f3b838)
#define   MUSIC_FORWARD_BIN                       (void *)(0x00f3ea78)
#define   MUSIC_FORWARD_HIGHLIGHT_BIN             (void *)(0x00f41cb8)
#define   MUSIC_PAUSE_BIN                         (void *)(0x00f44ef8)
#define   MUSIC_PLAY_BIN                          (void *)(0x00f48138)
#define   OPTION_LEFT_BIN                         (void *)(0x00f4b378)
#define   OPTION_LEFT_HIGHLIGHT_BIN               (void *)(0x00f4e5b8)
#define   OPTION_RIGHT_BIN                        (void *)(0x00f517f8)
#define   OPTION_RIGHT_HIGHLIGHT_BIN              (void *)(0x00f54a38)
#define   OVERLAP_BIN                             (void *)(0x00f57c78)
#define   SCAN_BIN                                (void *)(0x00f67338)
#define   SCAN_BLUE_BIN                           (void *)(0x00f6a7b8)
#define   TWS_LEFT_BIN                            (void *)(0x00f6dbf8)
#define   TWS_LEFT_HIGHLIGHT_BIN                  (void *)(0x00f739f8)
#define   TWS_RIGHT_BIN                           (void *)(0x00f797b8)
#define   TWS_RIGHT_HIGHLIGHT_BIN                 (void *)(0x00f7f5b8)
#define   VOLUME_DOWN_BIN                         (void *)(0x00f85378)
#define   VOLUME_DOWN_HIGHLIGHT_BIN               (void *)(0x00f885b8)
#define   VOLUME_UP_BIN                           (void *)(0x00f8b7f8)
#define   VOLUME_UP_HIGHLIGHT_BIN                 (void *)(0x00f8ea38)
#define   WALLPAPER1_BIN                          (void *)(0x00f91c78)
#define   WALLPAPER1_SIZE_BIN                     (void *)(0x00fcdf38)
#define   WALLPAPER2_BIN                          (void *)(0x00fd7978)
#define   WALLPAPER2_SIZE_BIN                     (void *)(0x01013c38)
#define   WALLPAPER3_BIN                          (void *)(0x0101d678)
#define   WALLPAPER3_SIZE_BIN                     (void *)(0x01059938)

#endif
