# building script for HoneyGUI
from building import *
cwd = GetCurrentDir()
list = os.listdir(cwd)


src = Glob('*.c')
src += Glob('*.cpp')

inc = [cwd]

objs = DefineGroup('realgui/engine', src, depend = [''], CPPPATH = inc)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        if not os.path.isfile(os.path.join(path, 'SConstruct')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
