# building script for HoneyGUI
from building import *
import os
import menu_config

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

objs = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_REAL_LITE_CIRCLE'):
    src += ['example_lite_geometry_circle.c']
    objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
    
Return('objs')

