from building import *

# get current directory
cwd = GetCurrentDir()

#src = Split("""""")
src     = Glob('*.c')
libs = ['']
libpath = [cwd]

libs += Split('''
lib/miwear-sdk-RTL8762DK_M69_0.2.13
lib/miwear-sdk-RTL8762DK_M69-nanopb_0.2.13
''')

path = [cwd]

group = DefineGroup('miwear', src, depend = ['RTK_MI_WEAR'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

objs += group

Return('objs')
