import os
import sys
import rtk_gui_config
from SCons.Script import *

TOOL_ROOT="./scons-tool"

sys.path = sys.path + [os.path.join(TOOL_ROOT, '')]
try:
    from building import *
except:
    print('Cannot found Scons tool root directory, please check TOOL_ROOT')
    exit(-1)

TARGET = 'gui.' + 'exe'

#env = Environment(tools = ['mingw'],
#    AS = rtk_gui_config.AS, ASFLAGS = rtk_gui_config.AFLAGS,
#    CC = rtk_gui_config.CC, CCFLAGS = rtk_gui_config.CFLAGS,
#    AR = rtk_gui_config.AR, ARFLAGS = '-rc',
#    CXX = rtk_gui_config.CXX, CXXFLAGS = rtk_gui_config.CXXFLAGS,
#    LINK = rtk_gui_config.LINK, LINKFLAGS = rtk_gui_config.LFLAGS)

env = Environment(tools = ['mingw'],
                  CC=rtk_gui_config.CC, CCFLAGS = rtk_gui_config.CFLAGS,
                  LINKFLAGS = rtk_gui_config.LFLAGS)

#env.PrependENVPath('PATH', rtk_gui_config.EXEC_PATH)
env.Append(LIBS = ['mingw32'])




WEARABLE_ROOT = os.path.abspath('./../')

Export('TOOL_ROOT')
Export('WEARABLE_ROOT')


print('TOOL ROOT = ' + TOOL_ROOT)
print('RTK WEARABLE ROOT = ' + WEARABLE_ROOT)

# prepare building environment
objs = PrepareBuilding(env, TOOL_ROOT, has_libcpu=False)


# include app
objs.extend(SConscript(os.path.join(WEARABLE_ROOT, 'SConscript')))

# bsp_vdir = 'build'

# make a building
DoBuilding(TARGET, objs)
