# for module compiling
import os
Import('TOOL_ROOT')
Import('WEARABLE_ROOT')

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, 
           WEARABLE_ROOT + '/example/root_image/']



#src = Glob('*.c')
src = ['main.c']
src += ['rtk_gui_demo.c']
src += ['nanovg_test.c']

objs = DefineGroup('rtk_gui', src, depend = [''], CPPPATH = CPPPATH)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
