# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_280_456_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_280_456_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=280']
    CPPDEFINES += ['DRV_LCD_HEIGHT=456']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_280_456_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
