# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

CPPPATH = [cwd]
if GetDepend(['CONFIG_REALTEK_BUILD_SCRIPT_AS_A_APP']):
    src += Glob('./*.c')
    src += Glob('./js_ui/*.c')


group = DefineGroup('realgui/SaaA', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH)

Return('group')
