#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   A1_BIN                                  (void *)(resource_root + 0x00000a38)
#define   A2_BIN                                  (void *)(resource_root + 0x00008a78)
#define   A3_BIN                                  (void *)(resource_root + 0x00010ab8)
#define   A4_BIN                                  (void *)(resource_root + 0x00018af8)
#define   A5_BIN                                  (void *)(resource_root + 0x00020b38)
#define   A6_BIN                                  (void *)(resource_root + 0x00028b78)
#define   B1_BIN                                  (void *)(resource_root + 0x00030bb8)
#define   B1_RLE_BIN                              (void *)(resource_root + 0x0003a6f8)
#define   B2_BIN                                  (void *)(resource_root + 0x00041f78)
#define   B2_RLE_BIN                              (void *)(resource_root + 0x0004bab8)
#define   B3_BIN                                  (void *)(resource_root + 0x000517f8)
#define   B3_RLE_BIN                              (void *)(resource_root + 0x0005b338)
#define   B4_BIN                                  (void *)(resource_root + 0x0005deb8)
#define   B4_RLE_BIN                              (void *)(resource_root + 0x000679f8)
#define   B5_BIN                                  (void *)(resource_root + 0x0006ac78)
#define   B5_RLE_BIN                              (void *)(resource_root + 0x000747b8)
#define   B6_BIN                                  (void *)(resource_root + 0x000767b8)
#define   B6_RLE_BIN                              (void *)(resource_root + 0x000802f8)
#define   OVAL_BIN                                (void *)(resource_root + 0x000826f8)
#define   CLOCK_BASE_BIN                          (void *)(resource_root + 0x000829b8)
#define   ICON_ANSWER_BIN                         (void *)(resource_root + 0x00086678)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(resource_root + 0x00087578)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x00088278)
#define   ICON_BACKSPACE_BIN                      (void *)(resource_root + 0x00088538)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(resource_root + 0x00088bf8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(resource_root + 0x000899b8)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(resource_root + 0x0008a778)
#define   ICON_BUDS_OFF_BIN                       (void *)(resource_root + 0x0008b538)
#define   ICON_BUDS_ON_BIN                        (void *)(resource_root + 0x0008c438)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(resource_root + 0x0008d2f8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(resource_root + 0x0008e1f8)
#define   ICON_BUTTON_ON_BIN                      (void *)(resource_root + 0x0008e938)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x0008f2b8)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(resource_root + 0x00090db8)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(resource_root + 0x00091c38)
#define   ICON_CALL_HISTORY_BIN                   (void *)(resource_root + 0x00092af8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(resource_root + 0x000939b8)
#define   ICON_CALL_TOUCH_BIN                     (void *)(resource_root + 0x000948b8)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(resource_root + 0x000962b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(resource_root + 0x000963b8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(resource_root + 0x000964b8)
#define   ICON_CALLER_BIN                         (void *)(resource_root + 0x00096578)
#define   ICON_CALLER_LARGE_BIN                   (void *)(resource_root + 0x000983b8)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x0009b378)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(resource_root + 0x0009bdb8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(resource_root + 0x0009c7f8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(resource_root + 0x0009c938)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(resource_root + 0x0009ceb8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(resource_root + 0x0009d5b8)
#define   ICON_CONFIRM_BIN                        (void *)(resource_root + 0x0009dd78)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(resource_root + 0x0009e738)
#define   ICON_CONTACTCS_BIN                      (void *)(resource_root + 0x0009f0f8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(resource_root + 0x000a0b38)
#define   ICON_DIAL_0_BIN                         (void *)(resource_root + 0x000a2438)
#define   ICON_DIAL_1_BIN                         (void *)(resource_root + 0x000a29b8)
#define   ICON_DIAL_2_BIN                         (void *)(resource_root + 0x000a2df8)
#define   ICON_DIAL_3_BIN                         (void *)(resource_root + 0x000a3238)
#define   ICON_DIAL_4_BIN                         (void *)(resource_root + 0x000a3678)
#define   ICON_DIAL_5_BIN                         (void *)(resource_root + 0x000a3ab8)
#define   ICON_DIAL_6_BIN                         (void *)(resource_root + 0x000a3ef8)
#define   ICON_DIAL_7_BIN                         (void *)(resource_root + 0x000a43f8)
#define   ICON_DIAL_8_BIN                         (void *)(resource_root + 0x000a4878)
#define   ICON_DIAL_9_BIN                         (void *)(resource_root + 0x000a4db8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(resource_root + 0x000a5378)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(resource_root + 0x000a5a78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(resource_root + 0x000a6178)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(resource_root + 0x000a65b8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(resource_root + 0x000a69f8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(resource_root + 0x000a6f78)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(resource_root + 0x000a73b8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(resource_root + 0x000a78b8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(resource_root + 0x000a8038)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(resource_root + 0x000a8578)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x000a8b38)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(resource_root + 0x000a95b8)
#define   ICON_FAIL_BIN                           (void *)(resource_root + 0x000aa078)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(resource_root + 0x000ab2b8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(resource_root + 0x000ab8f8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(resource_root + 0x000abf38)
#define   ICON_FOLDER_BIN                         (void *)(resource_root + 0x000ac578)
#define   ICON_HANGUP_BIN                         (void *)(resource_root + 0x000ac738)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(resource_root + 0x000ad778)
#define   ICON_LOADING_BIN                        (void *)(resource_root + 0x000ae538)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(resource_root + 0x000aedf8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(resource_root + 0x000af7f8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(resource_root + 0x000b01b8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(resource_root + 0x000b0cf8)
#define   ICON_MORE_OFF_BIN                       (void *)(resource_root + 0x000b17b8)
#define   ICON_MORE_ON_BIN                        (void *)(resource_root + 0x000b21f8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(resource_root + 0x000b2c38)
#define   ICON_PHONE_OFF_BIN                      (void *)(resource_root + 0x000b3678)
#define   ICON_PHONE_ON_BIN                       (void *)(resource_root + 0x000b41b8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(resource_root + 0x000b4cb8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(resource_root + 0x000b57f8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(resource_root + 0x000b5978)
#define   ICON_PROCESS_NODE_BIN                   (void *)(resource_root + 0x000b5ab8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(resource_root + 0x000b5eb8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(resource_root + 0x000b6178)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(resource_root + 0x000b6e38)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(resource_root + 0x000b7b38)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(resource_root + 0x000bacb8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(resource_root + 0x000bdd38)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(resource_root + 0x000c0db8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(resource_root + 0x000c0fb8)
#define   ICON_RECORD_START_BIN                   (void *)(resource_root + 0x000c3f38)
#define   ICON_RECORD_STOP_BIN                    (void *)(resource_root + 0x000c6d78)
#define   ICON_SEEKBAR_BIN                        (void *)(resource_root + 0x000c9578)
#define   ICON_SEEKBAR1_BIN                       (void *)(resource_root + 0x000c9bf8)
#define   ICON_SEEKBAR2_BIN                       (void *)(resource_root + 0x000c9d78)
#define   ICON_SONG_BUDS_BIN                      (void *)(resource_root + 0x000ca3b8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(resource_root + 0x000ca7b8)
#define   ICON_SONG_NEXT_BIN                      (void *)(resource_root + 0x000cabf8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(resource_root + 0x000cb2f8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(resource_root + 0x000cb9f8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(resource_root + 0x000cc378)
#define   ICON_SONG_PHONE_BIN                     (void *)(resource_root + 0x000cccf8)
#define   ICON_SONG_PLAY_BIN                      (void *)(resource_root + 0x000cd038)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(resource_root + 0x000cd878)
#define   ICON_SONG_PREV_BIN                      (void *)(resource_root + 0x000ce0b8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(resource_root + 0x000ce778)
#define   ICON_SONG_SPK_BIN                       (void *)(resource_root + 0x000cee38)
#define   ICON_SUCCESS_BIN                        (void *)(resource_root + 0x000cf1b8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(resource_root + 0x000d05f8)
#define   ICON_SWITCH_ON_BIN                      (void *)(resource_root + 0x000d0db8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(resource_root + 0x000d15b8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(resource_root + 0x000d1ab8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(resource_root + 0x000d1fb8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(resource_root + 0x000d24f8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(resource_root + 0x000d2938)
#define   ICON_TRASH_BIN                          (void *)(resource_root + 0x000d2ff8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(resource_root + 0x000d37f8)
#define   ICON_UP_SLIDE_BIN                       (void *)(resource_root + 0x000d3ff8)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x000d4af8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(resource_root + 0x000d4e38)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(resource_root + 0x000d4fb8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(resource_root + 0x000d50b8)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(resource_root + 0x000d5178)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(resource_root + 0x000d5278)
#define   ICON_VOLUME_CALL_BIN                    (void *)(resource_root + 0x000d53b8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(resource_root + 0x000d5cf8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(resource_root + 0x000d6538)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(resource_root + 0x000d6ab8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(resource_root + 0x000d7038)
#define   ICON_VOLUME_UP_BIN                      (void *)(resource_root + 0x000d74b8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(resource_root + 0x000d7bf8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(resource_root + 0x000d8338)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(resource_root + 0x000d84f8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(resource_root + 0x000d8578)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(resource_root + 0x000d8638)
#define   WATCH_BASE_BLACK_BIN                    (void *)(resource_root + 0x000d87f8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(resource_root + 0x000d99f8)
#define   WATCH_BASE_GREY_BIN                     (void *)(resource_root + 0x000db578)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(resource_root + 0x000ddff8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(resource_root + 0x000e09f8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(resource_root + 0x000e1f78)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(resource_root + 0x000e23b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(resource_root + 0x000e27f8)

#else
#define   A1_BIN                                  (void *)(0x0238be38)
#define   A2_BIN                                  (void *)(0x02393e78)
#define   A3_BIN                                  (void *)(0x0239beb8)
#define   A4_BIN                                  (void *)(0x023a3ef8)
#define   A5_BIN                                  (void *)(0x023abf38)
#define   A6_BIN                                  (void *)(0x023b3f78)
#define   B1_BIN                                  (void *)(0x023bbfb8)
#define   B1_RLE_BIN                              (void *)(0x023c5af8)
#define   B2_BIN                                  (void *)(0x023cd378)
#define   B2_RLE_BIN                              (void *)(0x023d6eb8)
#define   B3_BIN                                  (void *)(0x023dcbf8)
#define   B3_RLE_BIN                              (void *)(0x023e6738)
#define   B4_BIN                                  (void *)(0x023e92b8)
#define   B4_RLE_BIN                              (void *)(0x023f2df8)
#define   B5_BIN                                  (void *)(0x023f6078)
#define   B5_RLE_BIN                              (void *)(0x023ffbb8)
#define   B6_BIN                                  (void *)(0x02401bb8)
#define   B6_RLE_BIN                              (void *)(0x0240b6f8)
#define   OVAL_BIN                                (void *)(0x0240daf8)
#define   CLOCK_BASE_BIN                          (void *)(0x0240ddb8)
#define   ICON_ANSWER_BIN                         (void *)(0x02411a78)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(0x02412978)
#define   ICON_BACK_BIN                           (void *)(0x02413678)
#define   ICON_BACKSPACE_BIN                      (void *)(0x02413938)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(0x02413ff8)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(0x02414db8)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(0x02415b78)
#define   ICON_BUDS_OFF_BIN                       (void *)(0x02416938)
#define   ICON_BUDS_ON_BIN                        (void *)(0x02417838)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(0x024186f8)
#define   ICON_BUTTON_OFF_BIN                     (void *)(0x024195f8)
#define   ICON_BUTTON_ON_BIN                      (void *)(0x02419d38)
#define   ICON_CALL_BIN                           (void *)(0x0241a6b8)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(0x0241c1b8)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(0x0241d038)
#define   ICON_CALL_HISTORY_BIN                   (void *)(0x0241def8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(0x0241edb8)
#define   ICON_CALL_TOUCH_BIN                     (void *)(0x0241fcb8)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(0x024216b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(0x024217b8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(0x024218b8)
#define   ICON_CALLER_BIN                         (void *)(0x02421978)
#define   ICON_CALLER_LARGE_BIN                   (void *)(0x024237b8)
#define   ICON_CANCEL_BIN                         (void *)(0x02426778)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(0x024271b8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(0x02427bf8)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(0x02427d38)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(0x024282b8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(0x024289b8)
#define   ICON_CONFIRM_BIN                        (void *)(0x02429178)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(0x02429b38)
#define   ICON_CONTACTCS_BIN                      (void *)(0x0242a4f8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(0x0242bf38)
#define   ICON_DIAL_0_BIN                         (void *)(0x0242d838)
#define   ICON_DIAL_1_BIN                         (void *)(0x0242ddb8)
#define   ICON_DIAL_2_BIN                         (void *)(0x0242e1f8)
#define   ICON_DIAL_3_BIN                         (void *)(0x0242e638)
#define   ICON_DIAL_4_BIN                         (void *)(0x0242ea78)
#define   ICON_DIAL_5_BIN                         (void *)(0x0242eeb8)
#define   ICON_DIAL_6_BIN                         (void *)(0x0242f2f8)
#define   ICON_DIAL_7_BIN                         (void *)(0x0242f7f8)
#define   ICON_DIAL_8_BIN                         (void *)(0x0242fc78)
#define   ICON_DIAL_9_BIN                         (void *)(0x024301b8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(0x02430778)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(0x02430e78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(0x02431578)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(0x024319b8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(0x02431df8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(0x02432378)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(0x024327b8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(0x02432cb8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(0x02433438)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(0x02433978)
#define   ICON_DISCONNECT_BIN                     (void *)(0x02433f38)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(0x024349b8)
#define   ICON_FAIL_BIN                           (void *)(0x02435478)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(0x024366b8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(0x02436cf8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(0x02437338)
#define   ICON_FOLDER_BIN                         (void *)(0x02437978)
#define   ICON_HANGUP_BIN                         (void *)(0x02437b38)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(0x02438b78)
#define   ICON_LOADING_BIN                        (void *)(0x02439938)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(0x0243a1f8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(0x0243abf8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(0x0243b5b8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(0x0243c0f8)
#define   ICON_MORE_OFF_BIN                       (void *)(0x0243cbb8)
#define   ICON_MORE_ON_BIN                        (void *)(0x0243d5f8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(0x0243e038)
#define   ICON_PHONE_OFF_BIN                      (void *)(0x0243ea78)
#define   ICON_PHONE_ON_BIN                       (void *)(0x0243f5b8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(0x024400b8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(0x02440bf8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(0x02440d78)
#define   ICON_PROCESS_NODE_BIN                   (void *)(0x02440eb8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(0x024412b8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(0x02441578)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(0x02442238)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(0x02442f38)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(0x024460b8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(0x02449138)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(0x0244c1b8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(0x0244c3b8)
#define   ICON_RECORD_START_BIN                   (void *)(0x0244f338)
#define   ICON_RECORD_STOP_BIN                    (void *)(0x02452178)
#define   ICON_SEEKBAR_BIN                        (void *)(0x02454978)
#define   ICON_SEEKBAR1_BIN                       (void *)(0x02454ff8)
#define   ICON_SEEKBAR2_BIN                       (void *)(0x02455178)
#define   ICON_SONG_BUDS_BIN                      (void *)(0x024557b8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(0x02455bb8)
#define   ICON_SONG_NEXT_BIN                      (void *)(0x02455ff8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(0x024566f8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(0x02456df8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(0x02457778)
#define   ICON_SONG_PHONE_BIN                     (void *)(0x024580f8)
#define   ICON_SONG_PLAY_BIN                      (void *)(0x02458438)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(0x02458c78)
#define   ICON_SONG_PREV_BIN                      (void *)(0x024594b8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(0x02459b78)
#define   ICON_SONG_SPK_BIN                       (void *)(0x0245a238)
#define   ICON_SUCCESS_BIN                        (void *)(0x0245a5b8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(0x0245b9f8)
#define   ICON_SWITCH_ON_BIN                      (void *)(0x0245c1b8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(0x0245c9b8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(0x0245ceb8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(0x0245d3b8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(0x0245d8f8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(0x0245dd38)
#define   ICON_TRASH_BIN                          (void *)(0x0245e3f8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(0x0245ebf8)
#define   ICON_UP_SLIDE_BIN                       (void *)(0x0245f3f8)
#define   ICON_VOLUME_BIN                         (void *)(0x0245fef8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(0x02460238)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(0x024603b8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(0x024604b8)
#define   ICON_VOLUME_BAR_BLUE_BIN                (void *)(0x02460578)
#define   ICON_VOLUME_BAR_PURPLE_BIN              (void *)(0x02460678)
#define   ICON_VOLUME_CALL_BIN                    (void *)(0x024607b8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(0x024610f8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(0x02461938)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(0x02461eb8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(0x02462438)
#define   ICON_VOLUME_UP_BIN                      (void *)(0x024628b8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(0x02462ff8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(0x02463738)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(0x024638f8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(0x02463978)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(0x02463a38)
#define   WATCH_BASE_BLACK_BIN                    (void *)(0x02463bf8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(0x02464df8)
#define   WATCH_BASE_GREY_BIN                     (void *)(0x02466978)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(0x024693f8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(0x0246bdf8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(0x0246d378)
#define   WATCH_BASE_MASK_GREY_BIN                (void *)(0x0246d7b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(0x0246dbf8)

#endif
