#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   OVAL_BIN                                (void *)(resource_root + 0x00000878)
#define   CLOCK_BIN                               (void *)(resource_root + 0x000010b8)
#define   ICON_ANSWER_BIN                         (void *)(resource_root + 0x00065b38)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(resource_root + 0x00068d78)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x0006bfb8)
#define   ICON_BACKSPACE_BIN                      (void *)(resource_root + 0x0006d1f8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(resource_root + 0x0006f238)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(resource_root + 0x00074078)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(resource_root + 0x00078eb8)
#define   ICON_BUDS_OFF_BIN                       (void *)(resource_root + 0x0007dcf8)
#define   ICON_BUDS_ON_BIN                        (void *)(resource_root + 0x00082b38)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(resource_root + 0x00087978)
#define   ICON_BUTTON_OFF_BIN                     (void *)(resource_root + 0x0008c7b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(resource_root + 0x0008e7f8)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x00090838)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(resource_root + 0x000a3478)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(resource_root + 0x000ae4b8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(resource_root + 0x000b94f8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(resource_root + 0x000c4538)
#define   ICON_CALL_TOUCH_BIN                     (void *)(resource_root + 0x000cf578)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(resource_root + 0x000e21b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(resource_root + 0x000e30f8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(resource_root + 0x000e32b8)
#define   ICON_CALLER_BIN                         (void *)(resource_root + 0x000e41f8)
#define   ICON_CALLER_LARGE_BIN                   (void *)(resource_root + 0x000ebc38)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x000febb8)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(resource_root + 0x001033f8)
#define   ICON_CONFIRM_BIN                        (void *)(resource_root + 0x00107c38)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(resource_root + 0x0010c478)
#define   ICON_CONTACTCS_BIN                      (void *)(resource_root + 0x00110cb8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(resource_root + 0x001238f8)
#define   ICON_DIAL_0_BIN                         (void *)(resource_root + 0x00136538)
#define   ICON_DIAL_1_BIN                         (void *)(resource_root + 0x0013af38)
#define   ICON_DIAL_2_BIN                         (void *)(resource_root + 0x0013f938)
#define   ICON_DIAL_3_BIN                         (void *)(resource_root + 0x00144338)
#define   ICON_DIAL_4_BIN                         (void *)(resource_root + 0x00148d38)
#define   ICON_DIAL_5_BIN                         (void *)(resource_root + 0x0014d738)
#define   ICON_DIAL_6_BIN                         (void *)(resource_root + 0x00152138)
#define   ICON_DIAL_7_BIN                         (void *)(resource_root + 0x00156b38)
#define   ICON_DIAL_8_BIN                         (void *)(resource_root + 0x0015aef8)
#define   ICON_DIAL_9_BIN                         (void *)(resource_root + 0x0015f8f8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(resource_root + 0x001642f8)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(resource_root + 0x00168cf8)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(resource_root + 0x0016d6f8)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(resource_root + 0x001720f8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(resource_root + 0x00176af8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(resource_root + 0x0017b4f8)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(resource_root + 0x0017fef8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(resource_root + 0x001848f8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(resource_root + 0x00189538)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(resource_root + 0x0018df38)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x00192938)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(resource_root + 0x0019d978)
#define   ICON_FAIL_BIN                           (void *)(resource_root + 0x001a89b8)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(resource_root + 0x001b09f8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(resource_root + 0x001b9a38)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(resource_root + 0x001c2a78)
#define   ICON_FOLDER_BIN                         (void *)(resource_root + 0x001cbab8)
#define   ICON_HANGUP_BIN                         (void *)(resource_root + 0x001cbf78)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(resource_root + 0x001cf1b8)
#define   ICON_LOADING_BIN                        (void *)(resource_root + 0x001d23f8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(resource_root + 0x001d6db8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(resource_root + 0x001d9ff8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(resource_root + 0x001dd238)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(resource_root + 0x001e0478)
#define   ICON_MORE_OFF_BIN                       (void *)(resource_root + 0x001e36b8)
#define   ICON_MORE_ON_BIN                        (void *)(resource_root + 0x001e84f8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(resource_root + 0x001ed338)
#define   ICON_PHONE_OFF_BIN                      (void *)(resource_root + 0x001f2178)
#define   ICON_PHONE_ON_BIN                       (void *)(resource_root + 0x001f6fb8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(resource_root + 0x001fbdf8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(resource_root + 0x00200c38)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(resource_root + 0x00201e78)
#define   ICON_PROCESS_NODE_BIN                   (void *)(resource_root + 0x00201f78)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(resource_root + 0x002027b8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(resource_root + 0x00202ff8)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(resource_root + 0x0020df78)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(resource_root + 0x00218ef8)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(resource_root + 0x0022af38)
#define   ICON_RECORD_PLAY_BIN                    (void *)(resource_root + 0x0023cf78)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(resource_root + 0x0024efb8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(resource_root + 0x00250df8)
#define   ICON_RECORD_START_BIN                   (void *)(resource_root + 0x00262e38)
#define   ICON_RECORD_STOP_BIN                    (void *)(resource_root + 0x00274e78)
#define   ICON_SEEKBAR_BIN                        (void *)(resource_root + 0x00286eb8)
#define   ICON_SEEKBAR1_BIN                       (void *)(resource_root + 0x00288778)
#define   ICON_SEEKBAR2_BIN                       (void *)(resource_root + 0x00288ab8)
#define   ICON_SONG_BUDS_BIN                      (void *)(resource_root + 0x0028a378)
#define   ICON_SONG_LOCAL_BIN                     (void *)(resource_root + 0x0028abb8)
#define   ICON_SONG_NEXT_BIN                      (void *)(resource_root + 0x0028b3f8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(resource_root + 0x0028cdb8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(resource_root + 0x0028e738)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(resource_root + 0x00290778)
#define   ICON_SONG_PHONE_BIN                     (void *)(resource_root + 0x002927b8)
#define   ICON_SONG_PLAY_BIN                      (void *)(resource_root + 0x00292ff8)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(resource_root + 0x00295038)
#define   ICON_SONG_PREV_BIN                      (void *)(resource_root + 0x00297078)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(resource_root + 0x002989b8)
#define   ICON_SONG_SPK_BIN                       (void *)(resource_root + 0x0029a2f8)
#define   ICON_SUCCESS_BIN                        (void *)(resource_root + 0x0029ab38)
#define   ICON_SWITCH_OFF_BIN                     (void *)(resource_root + 0x002a2b78)
#define   ICON_SWITCH_ON_BIN                      (void *)(resource_root + 0x002a5a78)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(resource_root + 0x002a8978)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(resource_root + 0x002b19b8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(resource_root + 0x002ba9f8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(resource_root + 0x002c3a38)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(resource_root + 0x002c8278)
#define   ICON_TRASH_BIN                          (void *)(resource_root + 0x002ca2b8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(resource_root + 0x002cc2f8)
#define   ICON_UP_SLIDE_BIN                       (void *)(resource_root + 0x002ce338)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x002d9378)
#define   ICON_VOLUME_BAR_BIN                     (void *)(resource_root + 0x002d9bb8)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(resource_root + 0x002daaf8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(resource_root + 0x002dacb8)
#define   ICON_VOLUME_CALL_BIN                    (void *)(resource_root + 0x002dbbf8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(resource_root + 0x002dee38)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(resource_root + 0x002e2078)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(resource_root + 0x002e32b8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(resource_root + 0x002e44f8)
#define   ICON_VOLUME_UP_BIN                      (void *)(resource_root + 0x002e5738)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(resource_root + 0x002e6978)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(resource_root + 0x002e7bb8)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(resource_root + 0x002e8078)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(resource_root + 0x002e8178)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(resource_root + 0x002e90b8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(resource_root + 0x002e92f8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(resource_root + 0x0034dd78)
#define   WATCH_BASE_GREY_BIN                     (void *)(resource_root + 0x003b27f8)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(resource_root + 0x00417278)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(resource_root + 0x0047bcf8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(resource_root + 0x004ae278)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x004c45b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(resource_root + 0x004dd938)
#define   SIMKAI_SIZE32_BITS4_FONT_BIN            (void *)(resource_root + 0x009d95f8)

#else
#define   OVAL_BIN                                (void *)(0x0c000878)
#define   CLOCK_BIN                               (void *)(0x0c0010b8)
#define   ICON_ANSWER_BIN                         (void *)(0x0c065b38)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(0x0c068d78)
#define   ICON_BACK_BIN                           (void *)(0x0c06bfb8)
#define   ICON_BACKSPACE_BIN                      (void *)(0x0c06d1f8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(0x0c06f238)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(0x0c074078)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(0x0c078eb8)
#define   ICON_BUDS_OFF_BIN                       (void *)(0x0c07dcf8)
#define   ICON_BUDS_ON_BIN                        (void *)(0x0c082b38)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(0x0c087978)
#define   ICON_BUTTON_OFF_BIN                     (void *)(0x0c08c7b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(0x0c08e7f8)
#define   ICON_CALL_BIN                           (void *)(0x0c090838)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(0x0c0a3478)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(0x0c0ae4b8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(0x0c0b94f8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(0x0c0c4538)
#define   ICON_CALL_TOUCH_BIN                     (void *)(0x0c0cf578)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(0x0c0e21b8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(0x0c0e30f8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(0x0c0e32b8)
#define   ICON_CALLER_BIN                         (void *)(0x0c0e41f8)
#define   ICON_CALLER_LARGE_BIN                   (void *)(0x0c0ebc38)
#define   ICON_CANCEL_BIN                         (void *)(0x0c0febb8)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(0x0c1033f8)
#define   ICON_CONFIRM_BIN                        (void *)(0x0c107c38)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(0x0c10c478)
#define   ICON_CONTACTCS_BIN                      (void *)(0x0c110cb8)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(0x0c1238f8)
#define   ICON_DIAL_0_BIN                         (void *)(0x0c136538)
#define   ICON_DIAL_1_BIN                         (void *)(0x0c13af38)
#define   ICON_DIAL_2_BIN                         (void *)(0x0c13f938)
#define   ICON_DIAL_3_BIN                         (void *)(0x0c144338)
#define   ICON_DIAL_4_BIN                         (void *)(0x0c148d38)
#define   ICON_DIAL_5_BIN                         (void *)(0x0c14d738)
#define   ICON_DIAL_6_BIN                         (void *)(0x0c152138)
#define   ICON_DIAL_7_BIN                         (void *)(0x0c156b38)
#define   ICON_DIAL_8_BIN                         (void *)(0x0c15aef8)
#define   ICON_DIAL_9_BIN                         (void *)(0x0c15f8f8)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(0x0c1642f8)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(0x0c168cf8)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(0x0c16d6f8)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(0x0c1720f8)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(0x0c176af8)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(0x0c17b4f8)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(0x0c17fef8)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(0x0c1848f8)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(0x0c189538)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(0x0c18df38)
#define   ICON_DISCONNECT_BIN                     (void *)(0x0c192938)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(0x0c19d978)
#define   ICON_FAIL_BIN                           (void *)(0x0c1a89b8)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(0x0c1b09f8)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(0x0c1b9a38)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(0x0c1c2a78)
#define   ICON_FOLDER_BIN                         (void *)(0x0c1cbab8)
#define   ICON_HANGUP_BIN                         (void *)(0x0c1cbf78)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(0x0c1cf1b8)
#define   ICON_LOADING_BIN                        (void *)(0x0c1d23f8)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(0x0c1d6db8)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(0x0c1d9ff8)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(0x0c1dd238)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(0x0c1e0478)
#define   ICON_MORE_OFF_BIN                       (void *)(0x0c1e36b8)
#define   ICON_MORE_ON_BIN                        (void *)(0x0c1e84f8)
#define   ICON_MORE_TOUCH_BIN                     (void *)(0x0c1ed338)
#define   ICON_PHONE_OFF_BIN                      (void *)(0x0c1f2178)
#define   ICON_PHONE_ON_BIN                       (void *)(0x0c1f6fb8)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(0x0c1fbdf8)
#define   ICON_PROCESS_BAR_BIN                    (void *)(0x0c200c38)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(0x0c201e78)
#define   ICON_PROCESS_NODE_BIN                   (void *)(0x0c201f78)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(0x0c2027b8)
#define   ICON_RECORD_DELETE_BIN                  (void *)(0x0c202ff8)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(0x0c20df78)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(0x0c218ef8)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(0x0c22af38)
#define   ICON_RECORD_PLAY_BIN                    (void *)(0x0c23cf78)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(0x0c24efb8)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(0x0c250df8)
#define   ICON_RECORD_START_BIN                   (void *)(0x0c262e38)
#define   ICON_RECORD_STOP_BIN                    (void *)(0x0c274e78)
#define   ICON_SEEKBAR_BIN                        (void *)(0x0c286eb8)
#define   ICON_SEEKBAR1_BIN                       (void *)(0x0c288778)
#define   ICON_SEEKBAR2_BIN                       (void *)(0x0c288ab8)
#define   ICON_SONG_BUDS_BIN                      (void *)(0x0c28a378)
#define   ICON_SONG_LOCAL_BIN                     (void *)(0x0c28abb8)
#define   ICON_SONG_NEXT_BIN                      (void *)(0x0c28b3f8)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(0x0c28cdb8)
#define   ICON_SONG_PAUSE_BIN                     (void *)(0x0c28e738)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(0x0c290778)
#define   ICON_SONG_PHONE_BIN                     (void *)(0x0c2927b8)
#define   ICON_SONG_PLAY_BIN                      (void *)(0x0c292ff8)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(0x0c295038)
#define   ICON_SONG_PREV_BIN                      (void *)(0x0c297078)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(0x0c2989b8)
#define   ICON_SONG_SPK_BIN                       (void *)(0x0c29a2f8)
#define   ICON_SUCCESS_BIN                        (void *)(0x0c29ab38)
#define   ICON_SWITCH_OFF_BIN                     (void *)(0x0c2a2b78)
#define   ICON_SWITCH_ON_BIN                      (void *)(0x0c2a5a78)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(0x0c2a8978)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(0x0c2b19b8)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(0x0c2ba9f8)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(0x0c2c3a38)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(0x0c2c8278)
#define   ICON_TRASH_BIN                          (void *)(0x0c2ca2b8)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(0x0c2cc2f8)
#define   ICON_UP_SLIDE_BIN                       (void *)(0x0c2ce338)
#define   ICON_VOLUME_BIN                         (void *)(0x0c2d9378)
#define   ICON_VOLUME_BAR_BIN                     (void *)(0x0c2d9bb8)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(0x0c2daaf8)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(0x0c2dacb8)
#define   ICON_VOLUME_CALL_BIN                    (void *)(0x0c2dbbf8)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(0x0c2dee38)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(0x0c2e2078)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(0x0c2e32b8)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(0x0c2e44f8)
#define   ICON_VOLUME_UP_BIN                      (void *)(0x0c2e5738)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(0x0c2e6978)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(0x0c2e7bb8)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(0x0c2e8078)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(0x0c2e8178)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(0x0c2e90b8)
#define   WATCH_BASE_BLACK_BIN                    (void *)(0x0c2e92f8)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(0x0c34dd78)
#define   WATCH_BASE_GREY_BIN                     (void *)(0x0c3b27f8)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(0x0c417278)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(0x0c47bcf8)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(0x0c4ae278)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x0c4c45b8)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(0x0c4dd938)
#define   SIMKAI_SIZE32_BITS4_FONT_BIN            (void *)(0x0c9d95f8)

#endif
