#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   OVAL_BIN                                (void *)(resource_root + 0x000008f8)
#define   CLOCK_BIN                               (void *)(resource_root + 0x00001138)
#define   CLOCK_BASE_BIN                          (void *)(resource_root + 0x00065bb8)
#define   ICON_ANSWER_BIN                         (void *)(resource_root + 0x000ca638)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(resource_root + 0x000cd878)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x000d0ab8)
#define   ICON_BACKSPACE_BIN                      (void *)(resource_root + 0x000d1cf8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(resource_root + 0x000d3d38)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(resource_root + 0x000d8b78)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(resource_root + 0x000dd9b8)
#define   ICON_BUDS_OFF_BIN                       (void *)(resource_root + 0x000e27f8)
#define   ICON_BUDS_ON_BIN                        (void *)(resource_root + 0x000e7638)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(resource_root + 0x000ec478)
#define   ICON_BUTTON_OFF_BIN                     (void *)(resource_root + 0x000f12b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(resource_root + 0x000f32f8)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x000f5338)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(resource_root + 0x00107f78)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(resource_root + 0x00112fb8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(resource_root + 0x0011dff8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(resource_root + 0x00129038)
#define   ICON_CALL_TOUCH_BIN                     (void *)(resource_root + 0x00134078)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(resource_root + 0x00146cb8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(resource_root + 0x00147bf8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(resource_root + 0x00147db8)
#define   ICON_CALLER_BIN                         (void *)(resource_root + 0x00148cf8)
#define   ICON_CALLER_LARGE_BIN                   (void *)(resource_root + 0x00150738)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x001636b8)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(resource_root + 0x00167ef8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(resource_root + 0x0016c738)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(resource_root + 0x0016c978)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(resource_root + 0x0016cfb8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(resource_root + 0x0016d8f8)
#define   ICON_CONFIRM_BIN                        (void *)(resource_root + 0x0016ddb8)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(resource_root + 0x001725f8)
#define   ICON_CONTACTCS_BIN                      (void *)(resource_root + 0x00176e38)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(resource_root + 0x00189a78)
#define   ICON_DIAL_0_BIN                         (void *)(resource_root + 0x0019c6b8)
#define   ICON_DIAL_1_BIN                         (void *)(resource_root + 0x001a10b8)
#define   ICON_DIAL_2_BIN                         (void *)(resource_root + 0x001a5ab8)
#define   ICON_DIAL_3_BIN                         (void *)(resource_root + 0x001aa4b8)
#define   ICON_DIAL_4_BIN                         (void *)(resource_root + 0x001aeeb8)
#define   ICON_DIAL_5_BIN                         (void *)(resource_root + 0x001b38b8)
#define   ICON_DIAL_6_BIN                         (void *)(resource_root + 0x001b82b8)
#define   ICON_DIAL_7_BIN                         (void *)(resource_root + 0x001bccb8)
#define   ICON_DIAL_8_BIN                         (void *)(resource_root + 0x001c1078)
#define   ICON_DIAL_9_BIN                         (void *)(resource_root + 0x001c5a78)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(resource_root + 0x001ca478)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(resource_root + 0x001cee78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(resource_root + 0x001d3878)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(resource_root + 0x001d8278)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(resource_root + 0x001dcc78)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(resource_root + 0x001e1678)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(resource_root + 0x001e6078)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(resource_root + 0x001eaa78)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(resource_root + 0x001ef6b8)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(resource_root + 0x001f40b8)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x001f8ab8)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(resource_root + 0x00203af8)
#define   ICON_FAIL_BIN                           (void *)(resource_root + 0x0020eb38)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(resource_root + 0x00216b78)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(resource_root + 0x0021fbb8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(resource_root + 0x00228bf8)
#define   ICON_FOLDER_BIN                         (void *)(resource_root + 0x00231c38)
#define   ICON_HANGUP_BIN                         (void *)(resource_root + 0x002320f8)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(resource_root + 0x00235338)
#define   ICON_LOADING_BIN                        (void *)(resource_root + 0x00238578)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(resource_root + 0x0023cf38)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(resource_root + 0x00240178)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(resource_root + 0x002433b8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(resource_root + 0x002465f8)
#define   ICON_MORE_OFF_BIN                       (void *)(resource_root + 0x00249838)
#define   ICON_MORE_ON_BIN                        (void *)(resource_root + 0x0024e678)
#define   ICON_MORE_TOUCH_BIN                     (void *)(resource_root + 0x002534b8)
#define   ICON_PHONE_OFF_BIN                      (void *)(resource_root + 0x002582f8)
#define   ICON_PHONE_ON_BIN                       (void *)(resource_root + 0x0025d138)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(resource_root + 0x00261f78)
#define   ICON_PROCESS_BAR_BIN                    (void *)(resource_root + 0x00266db8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(resource_root + 0x00267ff8)
#define   ICON_PROCESS_NODE_BIN                   (void *)(resource_root + 0x002680f8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(resource_root + 0x00268938)
#define   ICON_RECORD_DELETE_BIN                  (void *)(resource_root + 0x00269178)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(resource_root + 0x002740f8)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(resource_root + 0x0027f078)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(resource_root + 0x002910b8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(resource_root + 0x002a30f8)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(resource_root + 0x002b5138)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(resource_root + 0x002b6f78)
#define   ICON_RECORD_START_BIN                   (void *)(resource_root + 0x002c8fb8)
#define   ICON_RECORD_STOP_BIN                    (void *)(resource_root + 0x002daff8)
#define   ICON_SEEKBAR_BIN                        (void *)(resource_root + 0x002ed038)
#define   ICON_SEEKBAR1_BIN                       (void *)(resource_root + 0x002ee8f8)
#define   ICON_SEEKBAR2_BIN                       (void *)(resource_root + 0x002eec38)
#define   ICON_SONG_BUDS_BIN                      (void *)(resource_root + 0x002f04f8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(resource_root + 0x002f0d38)
#define   ICON_SONG_NEXT_BIN                      (void *)(resource_root + 0x002f1578)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(resource_root + 0x002f2f38)
#define   ICON_SONG_PAUSE_BIN                     (void *)(resource_root + 0x002f48b8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(resource_root + 0x002f68f8)
#define   ICON_SONG_PHONE_BIN                     (void *)(resource_root + 0x002f8938)
#define   ICON_SONG_PLAY_BIN                      (void *)(resource_root + 0x002f9178)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(resource_root + 0x002fb1b8)
#define   ICON_SONG_PREV_BIN                      (void *)(resource_root + 0x002fd1f8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(resource_root + 0x002feb38)
#define   ICON_SONG_SPK_BIN                       (void *)(resource_root + 0x00300478)
#define   ICON_SUCCESS_BIN                        (void *)(resource_root + 0x00300cb8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(resource_root + 0x00308cf8)
#define   ICON_SWITCH_ON_BIN                      (void *)(resource_root + 0x0030bbf8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(resource_root + 0x0030eaf8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(resource_root + 0x00317b38)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(resource_root + 0x00320b78)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(resource_root + 0x00329bb8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(resource_root + 0x0032e3f8)
#define   ICON_TRASH_BIN                          (void *)(resource_root + 0x00330438)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(resource_root + 0x00332478)
#define   ICON_UP_SLIDE_BIN                       (void *)(resource_root + 0x003344b8)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x0033f4f8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(resource_root + 0x0033fd38)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(resource_root + 0x00340c78)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(resource_root + 0x00340e38)
#define   ICON_VOLUME_CALL_BIN                    (void *)(resource_root + 0x00341d78)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(resource_root + 0x00344fb8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(resource_root + 0x003481f8)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(resource_root + 0x00349438)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(resource_root + 0x0034a678)
#define   ICON_VOLUME_UP_BIN                      (void *)(resource_root + 0x0034b8b8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(resource_root + 0x0034caf8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(resource_root + 0x0034dd38)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(resource_root + 0x0034e1f8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(resource_root + 0x0034e2f8)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(resource_root + 0x0034f238)
#define   WATCH_BASE_BLACK_BIN                    (void *)(resource_root + 0x0034f478)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(resource_root + 0x003b3ef8)
#define   WATCH_BASE_GREY_BIN                     (void *)(resource_root + 0x00418978)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(resource_root + 0x0047d3f8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(resource_root + 0x004e1e78)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(resource_root + 0x005143f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x0052a738)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(resource_root + 0x00543ab8)
#define   SIMKAI_SIZE32_BITS4_FONT_BIN            (void *)(resource_root + 0x00a3f778)

#else
#define   OVAL_BIN                                (void *)(0x0c0008f8)
#define   CLOCK_BIN                               (void *)(0x0c001138)
#define   CLOCK_BASE_BIN                          (void *)(0x0c065bb8)
#define   ICON_ANSWER_BIN                         (void *)(0x0c0ca638)
#define   ICON_ANSWER_TOUCH_BIN                   (void *)(0x0c0cd878)
#define   ICON_BACK_BIN                           (void *)(0x0c0d0ab8)
#define   ICON_BACKSPACE_BIN                      (void *)(0x0c0d1cf8)
#define   ICON_BLUETOOTH_OFF_BIN                  (void *)(0x0c0d3d38)
#define   ICON_BLUETOOTH_ON_BIN                   (void *)(0x0c0d8b78)
#define   ICON_BLUETOOTH_TOUCH_BIN                (void *)(0x0c0dd9b8)
#define   ICON_BUDS_OFF_BIN                       (void *)(0x0c0e27f8)
#define   ICON_BUDS_ON_BIN                        (void *)(0x0c0e7638)
#define   ICON_BUDS_TOUCH_BIN                     (void *)(0x0c0ec478)
#define   ICON_BUTTON_OFF_BIN                     (void *)(0x0c0f12b8)
#define   ICON_BUTTON_ON_BIN                      (void *)(0x0c0f32f8)
#define   ICON_CALL_BIN                           (void *)(0x0c0f5338)
#define   ICON_CALL_CONTACTS_BIN                  (void *)(0x0c107f78)
#define   ICON_CALL_CONTACTS_TOUCH_BIN            (void *)(0x0c112fb8)
#define   ICON_CALL_HISTORY_BIN                   (void *)(0x0c11dff8)
#define   ICON_CALL_HISTORY_TOUCH_BIN             (void *)(0x0c129038)
#define   ICON_CALL_TOUCH_BIN                     (void *)(0x0c134078)
#define   ICON_CALL_VOLUME_BAR_BIN                (void *)(0x0c146cb8)
#define   ICON_CALL_VOLUME_BAR_1_BIN              (void *)(0x0c147bf8)
#define   ICON_CALL_VOLUME_BAR_2_BIN              (void *)(0x0c147db8)
#define   ICON_CALLER_BIN                         (void *)(0x0c148cf8)
#define   ICON_CALLER_LARGE_BIN                   (void *)(0x0c150738)
#define   ICON_CANCEL_BIN                         (void *)(0x0c1636b8)
#define   ICON_CANCEL_TOUCH_BIN                   (void *)(0x0c167ef8)
#define   ICON_CLOCK_HAND_DOT_BIN                 (void *)(0x0c16c738)
#define   ICON_CLOCK_HOUR_HAND_BIN                (void *)(0x0c16c978)
#define   ICON_CLOCK_MINUTE_HAND_BIN              (void *)(0x0c16cfb8)
#define   ICON_CLOCK_SECOND_HAND_BIN              (void *)(0x0c16d8f8)
#define   ICON_CONFIRM_BIN                        (void *)(0x0c16ddb8)
#define   ICON_CONFIRM_TOUCH_BIN                  (void *)(0x0c1725f8)
#define   ICON_CONTACTCS_BIN                      (void *)(0x0c176e38)
#define   ICON_CONTACTCS_TOUCH_BIN                (void *)(0x0c189a78)
#define   ICON_DIAL_0_BIN                         (void *)(0x0c19c6b8)
#define   ICON_DIAL_1_BIN                         (void *)(0x0c1a10b8)
#define   ICON_DIAL_2_BIN                         (void *)(0x0c1a5ab8)
#define   ICON_DIAL_3_BIN                         (void *)(0x0c1aa4b8)
#define   ICON_DIAL_4_BIN                         (void *)(0x0c1aeeb8)
#define   ICON_DIAL_5_BIN                         (void *)(0x0c1b38b8)
#define   ICON_DIAL_6_BIN                         (void *)(0x0c1b82b8)
#define   ICON_DIAL_7_BIN                         (void *)(0x0c1bccb8)
#define   ICON_DIAL_8_BIN                         (void *)(0x0c1c1078)
#define   ICON_DIAL_9_BIN                         (void *)(0x0c1c5a78)
#define   ICON_DIAL_TOUCH_0_BIN                   (void *)(0x0c1ca478)
#define   ICON_DIAL_TOUCH_1_BIN                   (void *)(0x0c1cee78)
#define   ICON_DIAL_TOUCH_2_BIN                   (void *)(0x0c1d3878)
#define   ICON_DIAL_TOUCH_3_BIN                   (void *)(0x0c1d8278)
#define   ICON_DIAL_TOUCH_4_BIN                   (void *)(0x0c1dcc78)
#define   ICON_DIAL_TOUCH_5_BIN                   (void *)(0x0c1e1678)
#define   ICON_DIAL_TOUCH_6_BIN                   (void *)(0x0c1e6078)
#define   ICON_DIAL_TOUCH_7_BIN                   (void *)(0x0c1eaa78)
#define   ICON_DIAL_TOUCH_8_BIN                   (void *)(0x0c1ef6b8)
#define   ICON_DIAL_TOUCH_9_BIN                   (void *)(0x0c1f40b8)
#define   ICON_DISCONNECT_BIN                     (void *)(0x0c1f8ab8)
#define   ICON_DISCONNECT_TOUCH_BIN               (void *)(0x0c203af8)
#define   ICON_FAIL_BIN                           (void *)(0x0c20eb38)
#define   ICON_FILES_BASE_BLUE_BIN                (void *)(0x0c216b78)
#define   ICON_FILES_BASE_DARK_BIN                (void *)(0x0c21fbb8)
#define   ICON_FILES_BASE_RED_BIN                 (void *)(0x0c228bf8)
#define   ICON_FOLDER_BIN                         (void *)(0x0c231c38)
#define   ICON_HANGUP_BIN                         (void *)(0x0c2320f8)
#define   ICON_HANGUP_TOUCH_BIN                   (void *)(0x0c235338)
#define   ICON_LOADING_BIN                        (void *)(0x0c238578)
#define   ICON_MIC_MUTE_OFF_BIN                   (void *)(0x0c23cf38)
#define   ICON_MIC_MUTE_OFF_TOUCH_BIN             (void *)(0x0c240178)
#define   ICON_MIC_MUTE_ON_BIN                    (void *)(0x0c2433b8)
#define   ICON_MIC_MUTE_ON_TOUCH_BIN              (void *)(0x0c2465f8)
#define   ICON_MORE_OFF_BIN                       (void *)(0x0c249838)
#define   ICON_MORE_ON_BIN                        (void *)(0x0c24e678)
#define   ICON_MORE_TOUCH_BIN                     (void *)(0x0c2534b8)
#define   ICON_PHONE_OFF_BIN                      (void *)(0x0c2582f8)
#define   ICON_PHONE_ON_BIN                       (void *)(0x0c25d138)
#define   ICON_PHONE_TOUCH_BIN                    (void *)(0x0c261f78)
#define   ICON_PROCESS_BAR_BIN                    (void *)(0x0c266db8)
#define   ICON_PROCESS_BAR_1_BIN                  (void *)(0x0c267ff8)
#define   ICON_PROCESS_NODE_BIN                   (void *)(0x0c2680f8)
#define   ICON_PROCESS_NODE_TOUCH_BIN             (void *)(0x0c268938)
#define   ICON_RECORD_DELETE_BIN                  (void *)(0x0c269178)
#define   ICON_RECORD_DELETE_TOUCH_BIN            (void *)(0x0c2740f8)
#define   ICON_RECORD_PAUSE_BIN                   (void *)(0x0c27f078)
#define   ICON_RECORD_PAUSE_TOUCH_BIN             (void *)(0x0c2910b8)
#define   ICON_RECORD_PLAY_BIN                    (void *)(0x0c2a30f8)
#define   ICON_RECORD_PLAY_BAR_BIN                (void *)(0x0c2b5138)
#define   ICON_RECORD_PLAY_TOUCH_BIN              (void *)(0x0c2b6f78)
#define   ICON_RECORD_START_BIN                   (void *)(0x0c2c8fb8)
#define   ICON_RECORD_STOP_BIN                    (void *)(0x0c2daff8)
#define   ICON_SEEKBAR_BIN                        (void *)(0x0c2ed038)
#define   ICON_SEEKBAR1_BIN                       (void *)(0x0c2ee8f8)
#define   ICON_SEEKBAR2_BIN                       (void *)(0x0c2eec38)
#define   ICON_SONG_BUDS_BIN                      (void *)(0x0c2f04f8)
#define   ICON_SONG_LOCAL_BIN                     (void *)(0x0c2f0d38)
#define   ICON_SONG_NEXT_BIN                      (void *)(0x0c2f1578)
#define   ICON_SONG_NEXT_TOUCH_BIN                (void *)(0x0c2f2f38)
#define   ICON_SONG_PAUSE_BIN                     (void *)(0x0c2f48b8)
#define   ICON_SONG_PAUSE_TOUCH_BIN               (void *)(0x0c2f68f8)
#define   ICON_SONG_PHONE_BIN                     (void *)(0x0c2f8938)
#define   ICON_SONG_PLAY_BIN                      (void *)(0x0c2f9178)
#define   ICON_SONG_PLAY_TOUCH_BIN                (void *)(0x0c2fb1b8)
#define   ICON_SONG_PREV_BIN                      (void *)(0x0c2fd1f8)
#define   ICON_SONG_PREV_TOUCH_BIN                (void *)(0x0c2feb38)
#define   ICON_SONG_SPK_BIN                       (void *)(0x0c300478)
#define   ICON_SUCCESS_BIN                        (void *)(0x0c300cb8)
#define   ICON_SWITCH_OFF_BIN                     (void *)(0x0c308cf8)
#define   ICON_SWITCH_ON_BIN                      (void *)(0x0c30bbf8)
#define   ICON_TEXT_BASE_BLUE_BIN                 (void *)(0x0c30eaf8)
#define   ICON_TEXT_BASE_DARK_BIN                 (void *)(0x0c317b38)
#define   ICON_TEXT_BASE_RED_BIN                  (void *)(0x0c320b78)
#define   ICON_TEXT_BASE_SHORT_BIN                (void *)(0x0c329bb8)
#define   ICON_TOUCH_BACKSPACE_BIN                (void *)(0x0c32e3f8)
#define   ICON_TRASH_BIN                          (void *)(0x0c330438)
#define   ICON_TRASH_TOUCH_BIN                    (void *)(0x0c332478)
#define   ICON_UP_SLIDE_BIN                       (void *)(0x0c3344b8)
#define   ICON_VOLUME_BIN                         (void *)(0x0c33f4f8)
#define   ICON_VOLUME_BAR_BIN                     (void *)(0x0c33fd38)
#define   ICON_VOLUME_BAR_1_BIN                   (void *)(0x0c340c78)
#define   ICON_VOLUME_BAR_2_BIN                   (void *)(0x0c340e38)
#define   ICON_VOLUME_CALL_BIN                    (void *)(0x0c341d78)
#define   ICON_VOLUME_CALL_TOUCH_BIN              (void *)(0x0c344fb8)
#define   ICON_VOLUME_DOWN_BIN                    (void *)(0x0c3481f8)
#define   ICON_VOLUME_DOWN_TOUCH_BIN              (void *)(0x0c349438)
#define   ICON_VOLUME_TOUCH_BIN                   (void *)(0x0c34a678)
#define   ICON_VOLUME_UP_BIN                      (void *)(0x0c34b8b8)
#define   ICON_VOLUME_UP_TOUCH_BIN                (void *)(0x0c34caf8)
#define   RECORD_FILES_ICON_FOLDER_BIN            (void *)(0x0c34dd38)
#define   RECORD_PLAY_BAR1_BIN                    (void *)(0x0c34e1f8)
#define   RECORD_PLAY_BAR2_BIN                    (void *)(0x0c34e2f8)
#define   RECORD_PLAY_BAR_DOT_BIN                 (void *)(0x0c34f238)
#define   WATCH_BASE_BLACK_BIN                    (void *)(0x0c34f478)
#define   WATCH_BASE_BLACK_LIGHT_BIN              (void *)(0x0c3b3ef8)
#define   WATCH_BASE_GREY_BIN                     (void *)(0x0c418978)
#define   WATCH_BASE_GREY_70_ALPHA_BIN            (void *)(0x0c47d3f8)
#define   WATCH_BASE_GREY_90ALPHA_HALF_BIN        (void *)(0x0c4e1e78)
#define   WATCH_BASE_MASK_BLACK_BIN               (void *)(0x0c5143f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x0c52a738)
#define   SIMKAI_SIZE32_BITS1_FONT_BIN            (void *)(0x0c543ab8)
#define   SIMKAI_SIZE32_BITS4_FONT_BIN            (void *)(0x0ca3f778)

#endif
