# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]
print(CPPPATH)
group = DefineGroup('realgui/test', src, depend = ['CONFIG_REALTEK_BUILD_AUTO_TEST'], CPPPATH = CPPPATH)

Return('group')
