# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]
print(CPPPATH)

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_240_240_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_240_240_DEMO']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_240_240_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
