# for module compiling

import os
from building import *
import menu_config

# get current directory
cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)
parent_dir = os.path.dirname(cwd)

src = Split("""
""")

include_path = []
libs = ['']
libpath = ['']


if GetDepend(['CONFIG_REALTEK_H264BSD']) :
    src += Glob(cwd + '/src/*.c')
    include_path += [cwd,
            cwd + '/inc',]



group = DefineGroup('realgui/3rd/h264bsd', src, depend = ['CONFIG_REALTEK_H264BSD'], CPPPATH = include_path, DEFINE = ['H264_BSD_ENABLE'])


Return('group')