# for module compiling

import os
from building import *
import menu_config

# get current directory
cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)
parent_dir = os.path.dirname(cwd)

src = Split("""
""")

path = []


src += Glob(cwd + '/src/*.c')
src += Glob(cwd + '/port/*.c')

path += [cwd, 
         cwd + '/src',
         cwd + '/port',
         cwd + '/inc']

print(path)


group = DefineGroup('realgui/3rd/h264bsd', src, depend = [], CPPPATH = path)


Return('group')