#if defined _HONEYGUI_SIMULATOR_
extern unsigned char *resource_root;

#define   HARMONYOS_SANS_BIN                      (void *)(resource_root + 0x000000b8)
#define   HARMONYOS_SANS_BOLD_BIN                 (void *)(resource_root + 0x000029b8)
#define   HARMONYOS_SIZE28_BITS1_FONT_BIN         (void *)(resource_root + 0x00005238)
#define   HARMONYOS_SIZE32_BITS1_FONT_BIN         (void *)(resource_root + 0x0000f478)
#define   HARMONYOS_SIZE56_BITS1_FONT_BIN         (void *)(resource_root + 0x002b6738)
#define   ARROW_LEFT_BIN                          (void *)(resource_root + 0x002d8d78)
#define   ARROW_RIGHT_BIN                         (void *)(resource_root + 0x002d90f8)
#define   BATTERY_BIN                             (void *)(resource_root + 0x002d94b8)
#define   LED0_OFF_BIN                            (void *)(resource_root + 0x002d9878)
#define   LED0_ON_BIN                             (void *)(resource_root + 0x002d9eb8)
#define   LED1_OFF_BIN                            (void *)(resource_root + 0x002da538)
#define   LED1_ON_BIN                             (void *)(resource_root + 0x002da9f8)
#define   LED2_OFF_BIN                            (void *)(resource_root + 0x002daeb8)
#define   LED2_ON_BIN                             (void *)(resource_root + 0x002db4b8)
#define   LED3_OFF_BIN                            (void *)(resource_root + 0x002dbab8)
#define   LED3_ON_BIN                             (void *)(resource_root + 0x002dbf38)
#define   LED4_OFF_BIN                            (void *)(resource_root + 0x002dc3b8)
#define   LED4_ON_BIN                             (void *)(resource_root + 0x002dc9b8)
#define   LED5_OFF_BIN                            (void *)(resource_root + 0x002dcfb8)
#define   LED5_ON_BIN                             (void *)(resource_root + 0x002dd7f8)
#define   LEFTBOTTOMGLOOMV1_BIN                   (void *)(resource_root + 0x002de038)
#define   LEFTGLOWV2_BIN                          (void *)(resource_root + 0x002e44b8)
#define   LEFTLINEV1_BIN                          (void *)(resource_root + 0x002f5c78)
#define   LEFTWING2V2_BIN                         (void *)(resource_root + 0x002f8cb8)
#define   LEFTWINGNEEDLEV2_BIN                    (void *)(resource_root + 0x002fe938)
#define   LEFTWINGV2_BIN                          (void *)(resource_root + 0x00300838)
#define   MAP_BIN                                 (void *)(resource_root + 0x0030c638)
#define   MAPFADING_BIN                           (void *)(resource_root + 0x003334f8)
#define   OFFICON_PRESS_BIN                       (void *)(resource_root + 0x0035fa38)
#define   OFFICON_RELEASE_BIN                     (void *)(resource_root + 0x0035fef8)
#define   RIGHTBOTTOMGLOOMV1_BIN                  (void *)(resource_root + 0x003603b8)
#define   RIGHTGLOWV2_BIN                         (void *)(resource_root + 0x00366838)
#define   RIGHTLINEV1_BIN                         (void *)(resource_root + 0x003780b8)
#define   RIGHTWING2V2_BIN                        (void *)(resource_root + 0x0037b0f8)
#define   RIGHTWINGNEEDLEV2_BIN                   (void *)(resource_root + 0x00380cb8)
#define   RIGHTWINGV2_BIN                         (void *)(resource_root + 0x00382bf8)
#define   STARTENGINE_BIN                         (void *)(resource_root + 0x0038ea78)
#define   STARTENGINEGLOOM_BIN                    (void *)(resource_root + 0x0039b0b8)
#define   START_ENGINE_PRESS_BIN                  (void *)(resource_root + 0x003d5ff8)
#define   START_ENGINE_RELEASE_BIN                (void *)(resource_root + 0x003d9538)
#define   SWITCHICON_PRESS_BIN                    (void *)(resource_root + 0x003dcef8)
#define   SWITCHICON_RELEASE_BIN                  (void *)(resource_root + 0x003dd2f8)
#define   TURNLEFT_OFF_BIN                        (void *)(resource_root + 0x003dd6f8)
#define   TURNLEFT_ON_BIN                         (void *)(resource_root + 0x003dd8f8)
#define   TURNRIGHT_OFF_BIN                       (void *)(resource_root + 0x003ddaf8)
#define   TURNRIGHT_ON_BIN                        (void *)(resource_root + 0x003ddcb8)
#define   ARROW_DIRECT_BIN                        (void *)(resource_root + 0x003dde78)
#define   BOARDERV2_BIN                           (void *)(resource_root + 0x003de1b8)
#define   BT_BIN                                  (void *)(resource_root + 0x003de8f8)
#define   DAIL_POINTER_BIN                        (void *)(resource_root + 0x003dea38)
#define   DAIL_POWER_BIN                          (void *)(resource_root + 0x003deb38)
#define   DAIL_SPEED_BIN                          (void *)(resource_root + 0x003f00b8)
#define   DIVIDING_LINE_BIN                       (void *)(resource_root + 0x00401678)
#define   MAP_0_BIN                               (void *)(resource_root + 0x004016b8)
#define   MAP_1_BIN                               (void *)(resource_root + 0x0041cb78)
#define   MAP_10_BIN                              (void *)(resource_root + 0x00438ff8)
#define   MAP_11_BIN                              (void *)(resource_root + 0x004549b8)
#define   MAP_12_BIN                              (void *)(resource_root + 0x0046fc78)
#define   MAP_2_BIN                               (void *)(resource_root + 0x0048a678)
#define   MAP_3_BIN                               (void *)(resource_root + 0x004a7738)
#define   MAP_4_BIN                               (void *)(resource_root + 0x004c44b8)
#define   MAP_5_BIN                               (void *)(resource_root + 0x004e0738)
#define   MAP_6_BIN                               (void *)(resource_root + 0x004fd1b8)
#define   MAP_7_BIN                               (void *)(resource_root + 0x0051a438)
#define   MAP_8_BIN                               (void *)(resource_root + 0x005376f8)
#define   MAP_9_BIN                               (void *)(resource_root + 0x00554138)
#define   MESSAGE_BG_BIN                          (void *)(resource_root + 0x005704b8)
#define   TEL_ACCPET_ICON_BIN                     (void *)(resource_root + 0x0058c5b8)
#define   TEL_BG_BIN                              (void *)(resource_root + 0x0058cab8)
#define   TEL_REJECT_ICON_BIN                     (void *)(resource_root + 0x0058d0b8)
#define   WIFI_BIN                                (void *)(resource_root + 0x0058d5b8)

#else
#define   HARMONYOS_SANS_BIN                      (void *)(0x044000b8)
#define   HARMONYOS_SANS_BOLD_BIN                 (void *)(0x044029b8)
#define   HARMONYOS_SIZE28_BITS1_FONT_BIN         (void *)(0x04405238)
#define   HARMONYOS_SIZE32_BITS1_FONT_BIN         (void *)(0x0440f478)
#define   HARMONYOS_SIZE56_BITS1_FONT_BIN         (void *)(0x046b6738)
#define   ARROW_LEFT_BIN                          (void *)(0x046d8d78)
#define   ARROW_RIGHT_BIN                         (void *)(0x046d90f8)
#define   BATTERY_BIN                             (void *)(0x046d94b8)
#define   LED0_OFF_BIN                            (void *)(0x046d9878)
#define   LED0_ON_BIN                             (void *)(0x046d9eb8)
#define   LED1_OFF_BIN                            (void *)(0x046da538)
#define   LED1_ON_BIN                             (void *)(0x046da9f8)
#define   LED2_OFF_BIN                            (void *)(0x046daeb8)
#define   LED2_ON_BIN                             (void *)(0x046db4b8)
#define   LED3_OFF_BIN                            (void *)(0x046dbab8)
#define   LED3_ON_BIN                             (void *)(0x046dbf38)
#define   LED4_OFF_BIN                            (void *)(0x046dc3b8)
#define   LED4_ON_BIN                             (void *)(0x046dc9b8)
#define   LED5_OFF_BIN                            (void *)(0x046dcfb8)
#define   LED5_ON_BIN                             (void *)(0x046dd7f8)
#define   LEFTBOTTOMGLOOMV1_BIN                   (void *)(0x046de038)
#define   LEFTGLOWV2_BIN                          (void *)(0x046e44b8)
#define   LEFTLINEV1_BIN                          (void *)(0x046f5c78)
#define   LEFTWING2V2_BIN                         (void *)(0x046f8cb8)
#define   LEFTWINGNEEDLEV2_BIN                    (void *)(0x046fe938)
#define   LEFTWINGV2_BIN                          (void *)(0x04700838)
#define   MAP_BIN                                 (void *)(0x0470c638)
#define   MAPFADING_BIN                           (void *)(0x047334f8)
#define   OFFICON_PRESS_BIN                       (void *)(0x0475fa38)
#define   OFFICON_RELEASE_BIN                     (void *)(0x0475fef8)
#define   RIGHTBOTTOMGLOOMV1_BIN                  (void *)(0x047603b8)
#define   RIGHTGLOWV2_BIN                         (void *)(0x04766838)
#define   RIGHTLINEV1_BIN                         (void *)(0x047780b8)
#define   RIGHTWING2V2_BIN                        (void *)(0x0477b0f8)
#define   RIGHTWINGNEEDLEV2_BIN                   (void *)(0x04780cb8)
#define   RIGHTWINGV2_BIN                         (void *)(0x04782bf8)
#define   STARTENGINE_BIN                         (void *)(0x0478ea78)
#define   STARTENGINEGLOOM_BIN                    (void *)(0x0479b0b8)
#define   START_ENGINE_PRESS_BIN                  (void *)(0x047d5ff8)
#define   START_ENGINE_RELEASE_BIN                (void *)(0x047d9538)
#define   SWITCHICON_PRESS_BIN                    (void *)(0x047dcef8)
#define   SWITCHICON_RELEASE_BIN                  (void *)(0x047dd2f8)
#define   TURNLEFT_OFF_BIN                        (void *)(0x047dd6f8)
#define   TURNLEFT_ON_BIN                         (void *)(0x047dd8f8)
#define   TURNRIGHT_OFF_BIN                       (void *)(0x047ddaf8)
#define   TURNRIGHT_ON_BIN                        (void *)(0x047ddcb8)
#define   ARROW_DIRECT_BIN                        (void *)(0x047dde78)
#define   BOARDERV2_BIN                           (void *)(0x047de1b8)
#define   BT_BIN                                  (void *)(0x047de8f8)
#define   DAIL_POINTER_BIN                        (void *)(0x047dea38)
#define   DAIL_POWER_BIN                          (void *)(0x047deb38)
#define   DAIL_SPEED_BIN                          (void *)(0x047f00b8)
#define   DIVIDING_LINE_BIN                       (void *)(0x04801678)
#define   MAP_0_BIN                               (void *)(0x048016b8)
#define   MAP_1_BIN                               (void *)(0x0481cb78)
#define   MAP_10_BIN                              (void *)(0x04838ff8)
#define   MAP_11_BIN                              (void *)(0x048549b8)
#define   MAP_12_BIN                              (void *)(0x0486fc78)
#define   MAP_2_BIN                               (void *)(0x0488a678)
#define   MAP_3_BIN                               (void *)(0x048a7738)
#define   MAP_4_BIN                               (void *)(0x048c44b8)
#define   MAP_5_BIN                               (void *)(0x048e0738)
#define   MAP_6_BIN                               (void *)(0x048fd1b8)
#define   MAP_7_BIN                               (void *)(0x0491a438)
#define   MAP_8_BIN                               (void *)(0x049376f8)
#define   MAP_9_BIN                               (void *)(0x04954138)
#define   MESSAGE_BG_BIN                          (void *)(0x049704b8)
#define   TEL_ACCPET_ICON_BIN                     (void *)(0x0498c5b8)
#define   TEL_BG_BIN                              (void *)(0x0498cab8)
#define   TEL_REJECT_ICON_BIN                     (void *)(0x0498d0b8)
#define   WIFI_BIN                                (void *)(0x0498d5b8)

#endif
