/*
 * Copyright (c) 2026, Realtek Semiconductor Corporation
 *
 * SPDX-License-Identifier: MIT
 */

#if defined _HONEYGUI_SIMULATOR_
extern unsigned char *resource_root;

#define   HARMONYOS_SANS_BIN                      (void *)(resource_root + 0x000000b8)
#define   HARMONYOS_SANS_BOLD_BIN                 (void *)(resource_root + 0x000029b8)
#define   HARMONYOS_SIZE28_BITS1_FONT_BIN         (void *)(resource_root + 0x00005238)
#define   HARMONYOS_SIZE32_BITS1_FONT_BIN         (void *)(resource_root + 0x0000f478)
#define   HARMONYOS_SIZE56_BITS1_FONT_BIN         (void *)(resource_root + 0x002b6738)
#define   ARROW_LEFT_BIN                          (void *)(resource_root + 0x002d8db8)
#define   ARROW_RIGHT_BIN                         (void *)(resource_root + 0x002d9138)
#define   BATTERY_BIN                             (void *)(resource_root + 0x002d94f8)
#define   LED0_OFF_BIN                            (void *)(resource_root + 0x002d98b8)
#define   LED0_ON_BIN                             (void *)(resource_root + 0x002d9ef8)
#define   LED1_OFF_BIN                            (void *)(resource_root + 0x002da578)
#define   LED1_ON_BIN                             (void *)(resource_root + 0x002daa38)
#define   LED2_OFF_BIN                            (void *)(resource_root + 0x002daef8)
#define   LED2_ON_BIN                             (void *)(resource_root + 0x002db4f8)
#define   LED3_OFF_BIN                            (void *)(resource_root + 0x002dbaf8)
#define   LED3_ON_BIN                             (void *)(resource_root + 0x002dbf78)
#define   LED4_OFF_BIN                            (void *)(resource_root + 0x002dc3f8)
#define   LED4_ON_BIN                             (void *)(resource_root + 0x002dc9f8)
#define   LED5_OFF_BIN                            (void *)(resource_root + 0x002dcff8)
#define   LED5_ON_BIN                             (void *)(resource_root + 0x002dd838)
#define   LEFTBOTTOMGLOOMV1_BIN                   (void *)(resource_root + 0x002de078)
#define   LEFTGLOWV2_BIN                          (void *)(resource_root + 0x002e44f8)
#define   LEFTLINEV1_BIN                          (void *)(resource_root + 0x002f5cb8)
#define   LEFTWING2V2_BIN                         (void *)(resource_root + 0x002f8cf8)
#define   LEFTWINGNEEDLEV2_BIN                    (void *)(resource_root + 0x002fe978)
#define   LEFTWINGV2_BIN                          (void *)(resource_root + 0x00300878)
#define   MAP_BIN                                 (void *)(resource_root + 0x0030c678)
#define   MAPFADING_BIN                           (void *)(resource_root + 0x00333538)
#define   OFFICON_PRESS_BIN                       (void *)(resource_root + 0x0035fa78)
#define   OFFICON_RELEASE_BIN                     (void *)(resource_root + 0x0035ff38)
#define   RIGHTBOTTOMGLOOMV1_BIN                  (void *)(resource_root + 0x003603f8)
#define   RIGHTGLOWV2_BIN                         (void *)(resource_root + 0x00366878)
#define   RIGHTLINEV1_BIN                         (void *)(resource_root + 0x003780f8)
#define   RIGHTWING2V2_BIN                        (void *)(resource_root + 0x0037b138)
#define   RIGHTWINGNEEDLEV2_BIN                   (void *)(resource_root + 0x00380cf8)
#define   RIGHTWINGV2_BIN                         (void *)(resource_root + 0x00382c38)
#define   STARTENGINE_BIN                         (void *)(resource_root + 0x0038eab8)
#define   STARTENGINEGLOOM_BIN                    (void *)(resource_root + 0x0039b0f8)
#define   START_ENGINE_PRESS_BIN                  (void *)(resource_root + 0x003d6038)
#define   START_ENGINE_RELEASE_BIN                (void *)(resource_root + 0x003d9578)
#define   SWITCHICON_PRESS_BIN                    (void *)(resource_root + 0x003dcf38)
#define   SWITCHICON_RELEASE_BIN                  (void *)(resource_root + 0x003dd338)
#define   TURNLEFT_OFF_BIN                        (void *)(resource_root + 0x003dd738)
#define   TURNLEFT_ON_BIN                         (void *)(resource_root + 0x003dd938)
#define   TURNRIGHT_OFF_BIN                       (void *)(resource_root + 0x003ddb38)
#define   TURNRIGHT_ON_BIN                        (void *)(resource_root + 0x003ddcf8)
#define   ARROW_DIRECT_BIN                        (void *)(resource_root + 0x003ddeb8)
#define   BOARDERV2_BIN                           (void *)(resource_root + 0x003de1f8)
#define   BT_BIN                                  (void *)(resource_root + 0x003de938)
#define   DAIL_POINTER_BIN                        (void *)(resource_root + 0x003dea78)
#define   DAIL_POWER_BIN                          (void *)(resource_root + 0x003deb78)
#define   DAIL_SPEED_BIN                          (void *)(resource_root + 0x003f00f8)
#define   DIVIDING_LINE_BIN                       (void *)(resource_root + 0x004016b8)
#define   MAP_0_BIN                               (void *)(resource_root + 0x004016f8)
#define   MAP_1_BIN                               (void *)(resource_root + 0x0041cbb8)
#define   MAP_10_BIN                              (void *)(resource_root + 0x00439038)
#define   MAP_11_BIN                              (void *)(resource_root + 0x004549f8)
#define   MAP_12_BIN                              (void *)(resource_root + 0x0046fcb8)
#define   MAP_2_BIN                               (void *)(resource_root + 0x0048a6b8)
#define   MAP_3_BIN                               (void *)(resource_root + 0x004a7778)
#define   MAP_4_BIN                               (void *)(resource_root + 0x004c44f8)
#define   MAP_5_BIN                               (void *)(resource_root + 0x004e0778)
#define   MAP_6_BIN                               (void *)(resource_root + 0x004fd1f8)
#define   MAP_7_BIN                               (void *)(resource_root + 0x0051a478)
#define   MAP_8_BIN                               (void *)(resource_root + 0x00537738)
#define   MAP_9_BIN                               (void *)(resource_root + 0x00554178)
#define   MESSAGE_BG_BIN                          (void *)(resource_root + 0x005704f8)
#define   NAVI_C1_BIN                             (void *)(resource_root + 0x0058c5f8)
#define   NAVI_C2_BIN                             (void *)(resource_root + 0x005a48b8)
#define   NAVI_C3_BIN                             (void *)(resource_root + 0x005bcb78)
#define   NAVI_C4_BIN                             (void *)(resource_root + 0x005d4e38)
#define   TEL_ACCPET_ICON_BIN                     (void *)(resource_root + 0x005ed0f8)
#define   TEL_BG_BIN                              (void *)(resource_root + 0x005ed5f8)
#define   TEL_REJECT_ICON_BIN                     (void *)(resource_root + 0x005edbf8)
#define   WIFI_BIN                                (void *)(resource_root + 0x005ee0f8)

#else
#define   HARMONYOS_SANS_BIN                      (void *)(0x044000b8)
#define   HARMONYOS_SANS_BOLD_BIN                 (void *)(0x044029b8)
#define   HARMONYOS_SIZE28_BITS1_FONT_BIN         (void *)(0x04405238)
#define   HARMONYOS_SIZE32_BITS1_FONT_BIN         (void *)(0x0440f478)
#define   HARMONYOS_SIZE56_BITS1_FONT_BIN         (void *)(0x046b6738)
#define   ARROW_LEFT_BIN                          (void *)(0x046d8db8)
#define   ARROW_RIGHT_BIN                         (void *)(0x046d9138)
#define   BATTERY_BIN                             (void *)(0x046d94f8)
#define   LED0_OFF_BIN                            (void *)(0x046d98b8)
#define   LED0_ON_BIN                             (void *)(0x046d9ef8)
#define   LED1_OFF_BIN                            (void *)(0x046da578)
#define   LED1_ON_BIN                             (void *)(0x046daa38)
#define   LED2_OFF_BIN                            (void *)(0x046daef8)
#define   LED2_ON_BIN                             (void *)(0x046db4f8)
#define   LED3_OFF_BIN                            (void *)(0x046dbaf8)
#define   LED3_ON_BIN                             (void *)(0x046dbf78)
#define   LED4_OFF_BIN                            (void *)(0x046dc3f8)
#define   LED4_ON_BIN                             (void *)(0x046dc9f8)
#define   LED5_OFF_BIN                            (void *)(0x046dcff8)
#define   LED5_ON_BIN                             (void *)(0x046dd838)
#define   LEFTBOTTOMGLOOMV1_BIN                   (void *)(0x046de078)
#define   LEFTGLOWV2_BIN                          (void *)(0x046e44f8)
#define   LEFTLINEV1_BIN                          (void *)(0x046f5cb8)
#define   LEFTWING2V2_BIN                         (void *)(0x046f8cf8)
#define   LEFTWINGNEEDLEV2_BIN                    (void *)(0x046fe978)
#define   LEFTWINGV2_BIN                          (void *)(0x04700878)
#define   MAP_BIN                                 (void *)(0x0470c678)
#define   MAPFADING_BIN                           (void *)(0x04733538)
#define   OFFICON_PRESS_BIN                       (void *)(0x0475fa78)
#define   OFFICON_RELEASE_BIN                     (void *)(0x0475ff38)
#define   RIGHTBOTTOMGLOOMV1_BIN                  (void *)(0x047603f8)
#define   RIGHTGLOWV2_BIN                         (void *)(0x04766878)
#define   RIGHTLINEV1_BIN                         (void *)(0x047780f8)
#define   RIGHTWING2V2_BIN                        (void *)(0x0477b138)
#define   RIGHTWINGNEEDLEV2_BIN                   (void *)(0x04780cf8)
#define   RIGHTWINGV2_BIN                         (void *)(0x04782c38)
#define   STARTENGINE_BIN                         (void *)(0x0478eab8)
#define   STARTENGINEGLOOM_BIN                    (void *)(0x0479b0f8)
#define   START_ENGINE_PRESS_BIN                  (void *)(0x047d6038)
#define   START_ENGINE_RELEASE_BIN                (void *)(0x047d9578)
#define   SWITCHICON_PRESS_BIN                    (void *)(0x047dcf38)
#define   SWITCHICON_RELEASE_BIN                  (void *)(0x047dd338)
#define   TURNLEFT_OFF_BIN                        (void *)(0x047dd738)
#define   TURNLEFT_ON_BIN                         (void *)(0x047dd938)
#define   TURNRIGHT_OFF_BIN                       (void *)(0x047ddb38)
#define   TURNRIGHT_ON_BIN                        (void *)(0x047ddcf8)
#define   ARROW_DIRECT_BIN                        (void *)(0x047ddeb8)
#define   BOARDERV2_BIN                           (void *)(0x047de1f8)
#define   BT_BIN                                  (void *)(0x047de938)
#define   DAIL_POINTER_BIN                        (void *)(0x047dea78)
#define   DAIL_POWER_BIN                          (void *)(0x047deb78)
#define   DAIL_SPEED_BIN                          (void *)(0x047f00f8)
#define   DIVIDING_LINE_BIN                       (void *)(0x048016b8)
#define   MAP_0_BIN                               (void *)(0x048016f8)
#define   MAP_1_BIN                               (void *)(0x0481cbb8)
#define   MAP_10_BIN                              (void *)(0x04839038)
#define   MAP_11_BIN                              (void *)(0x048549f8)
#define   MAP_12_BIN                              (void *)(0x0486fcb8)
#define   MAP_2_BIN                               (void *)(0x0488a6b8)
#define   MAP_3_BIN                               (void *)(0x048a7778)
#define   MAP_4_BIN                               (void *)(0x048c44f8)
#define   MAP_5_BIN                               (void *)(0x048e0778)
#define   MAP_6_BIN                               (void *)(0x048fd1f8)
#define   MAP_7_BIN                               (void *)(0x0491a478)
#define   MAP_8_BIN                               (void *)(0x04937738)
#define   MAP_9_BIN                               (void *)(0x04954178)
#define   MESSAGE_BG_BIN                          (void *)(0x049704f8)
#define   NAVI_C1_BIN                             (void *)(0x0498c5f8)
#define   NAVI_C2_BIN                             (void *)(0x049a48b8)
#define   NAVI_C3_BIN                             (void *)(0x049bcb78)
#define   NAVI_C4_BIN                             (void *)(0x049d4e38)
#define   TEL_ACCPET_ICON_BIN                     (void *)(0x049ed0f8)
#define   TEL_BG_BIN                              (void *)(0x049ed5f8)
#define   TEL_REJECT_ICON_BIN                     (void *)(0x049edbf8)
#define   WIFI_BIN                                (void *)(0x049ee0f8)

#endif
