
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_LETTER_SHELL'):
    CPPDEFINES += ['ENABLE_RTK_GUI_CONSOLE']

group = DefineGroup('realgui/3rd', src, depend = ['CONFIG_REALTEK_BUILD_LETTER_SHELL'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
