# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")
CPPDEFINES = []
CPPPATH = [cwd]


if GetDepend('CONFIG_REALTEK_BUILD_GUI_410_502_LVGL_DEMO'):
    src += Glob('*.c')
    src += Glob('./fonts/*.c')
    src += Glob('./images/*.c')

    CPPPATH += [cwd + '/fonts']
    CPPPATH += [cwd + '/images']
    CPPPATH += [cwd + '/root_image_lvgl']
    print(CPPPATH)

    CPPDEFINES += ['ENABLE_RTK_GUI_410_502_LVGL_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_410_502_LVGL_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
