# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Glob("*.cpp")


CPPPATH = [cwd]
group = DefineGroup('realgui/3rd/box2d', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
