# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

objs = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HEIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_EXAMPLE_TEXT_WIDGET'):
    src += Glob('*.c')

    objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')

