# HoneyGUI building script
from building import *
from SCons.Script import Flatten
import os
import menu_config

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_240_240_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_240_240_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=240']
    CPPDEFINES += ['DRV_LCD_HEIGHT=240']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

    if hasattr(menu_config, 'ARCH') and menu_config.ARCH == 'win32':
        from honeygui import *

        print("Target arch is win32, attempting to add prebuilt binary object...")
        BIN_SUBDIR = os.path.join(cwd, 'root_image')
        BIN_FILE = os.path.join(BIN_SUBDIR, 'root_0x859000.bin')
        OBJ_FILE = os.path.join(BIN_SUBDIR, 'root_0x859000_bin.o')
        result_node = add_prebuilt_binary_object(BIN_FILE, OBJ_FILE)
        if result_node:
            additional_objs = []
            additional_objs.append(result_node)
            print(additional_objs)
            src = Flatten(src + additional_objs)

objs = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_240_240_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
