# RTK building script for GuiEngine

import os

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd, cwd + '/rtos']

src += Glob('rtos/*.c')


# CPPDEFINES = ['TEST_DEFINE']
# group = DefineGroup('vg_lite', src, depend = ['MODULE_VG_LITE'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

group = DefineGroup('vg_lite', src, depend = ['MODULE_VG_LITE'], CPPPATH = CPPPATH)


Return('group')
