# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd, os.path.join(cwd, 'root_image')]
src = Glob('*.c') + Glob('*.cpp')

if GetDepend(['CONFIG_REALTEK_BUILD_EXAMPLE_STREAM_WIDGET']):
    CPPDEFINES = ['DRV_LCD_WIDTH=460']
    CPPDEFINES += ['DRV_LCD_HEIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    CPPDEFINES += ['DRV_LCD_CORNER_RADIUS=0']
    objs = DefineGroup('example/widget', src, depend = [''], CPPPATH = inc, CPPDEFINES = CPPDEFINES)
    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
else:
    objs = []

Return('objs')
