# building script for HoneyGUI

from building import *

Import('env')

cwd = GetCurrentDir()
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image']
src = Split("""
""")

objs = []

CPPDEFINES = []

if GetDepend('CONFIG_REALTEK_BUILD_EXAMPLE_STREAM_WIDGET'):

    src += ['example_gui_stream.c']
    CPPDEFINES = ['DRV_LCD_WIDTH=460']
    CPPDEFINES += ['DRV_LCD_HEIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    CPPDEFINES += ['DRV_LCD_CORNER_RADIUS=0']

objs = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
