#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: MIT
#
"""Shared helpers for the HoneyGUI CI build scripts.

Build inputs are complete, checked-in .config files. CI selects one file,
copies it to win32_sim/.config, and builds without parsing Kconfig.gui.
"""

import argparse
import codecs
import datetime
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


# ---------------------------------------------------------------- platform ---

IS_WINDOWS = sys.platform == "win32"
CMAKE_GENERATOR = "MinGW Makefiles" if IS_WINDOWS else "Unix Makefiles"
SCONS_COMMAND = "scons.exe" if IS_WINDOWS else "scons"

# Builds always go through "cmake --build", which drives whichever tool the
# generator needs (mingw32-make / make). Nothing here should invoke make itself.


def fix_console_encoding():
    """Force UTF-8 on the Windows console so build output does not crash us."""
    if IS_WINDOWS:
        for name in ("stdout", "stderr"):
            stream = getattr(sys, name)
            if hasattr(stream, "reconfigure"):
                stream.reconfigure(encoding="utf-8", errors="replace")
            elif hasattr(stream, "buffer"):
                setattr(sys, name, codecs.getwriter("utf-8")(
                    stream.buffer, "replace"))


# ------------------------------------------------------------------- paths ---

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
SIMULATOR_DIR = PROJECT_ROOT / "win32_sim"
EXAMPLE_DIR = PROJECT_ROOT / "example"
LIB_DIR = PROJECT_ROOT / "lib"
BUILD_ROOT = PROJECT_ROOT / ".ci-build"
CONFIG_ROOT = SCRIPT_DIR / "configs"
APPLICATION_CONFIG_DIR = CONFIG_ROOT / "application"
WIDGET_CONFIG_DIR = CONFIG_ROOT / "widget"

# Generated by menuconfig / SCons / CMake in win32_sim; snapshotted and restored
# around a run so a test sweep does not leave the developer's config mangled.
CONFIG_FILES = (
    ".config",
    ".config.old",
    "cconfig.h",
    "config.cmake",
    "menu_config.py",
)

DEMO_CONFIGS = (
    ("REALTEK_BUILD_EXAMPLE_IMAGE_WIDGET", "Image Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_SVG_WIDGET", "SVG Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_GIF_WIDGET", "GIF Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_TEXT_WIDGET", "Text Widget Demo", "widget"),
    ("REALTEK_BUILD_REAL_DOG_3D", "3D Dog Demo", "widget"),
    ("REALTEK_BUILD_REAL_EARTH_3D", "3D Earth Demo", "widget"),
    ("REALTEK_BUILD_REAL_DONUT_3D", "3D Donut Demo", "widget"),
    ("REALTEK_BUILD_REAL_PIKACHU_GLTF_3D",
     "3D Pikachu GLTF Demo", "widget"),
    ("REALTEK_BUILD_REAL_FLAG_GLTF_3D", "3D Flag GLTF Demo", "widget"),
    ("REALTEK_BUILD_REAL_ROBOT_GLTF_3D", "3D Robot GLTF Demo", "widget"),
    ("REALTEK_BUILD_REAL_VIEW", "View Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_LIST_WIDGET", "List Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_CARD_LIST_WIDGET",
     "Card List Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_MENU_CELLULAR_WIDGET",
     "Menu Cellular Widget Demo", "widget"),
    ("REALTEK_BUILD_REAL_CANVAS", "Canvas Demo", "widget"),
    ("REALTEK_BUILD_REAL_LITE_ARC", "Geometry ARC Demo", "widget"),
    ("REALTEK_BUILD_REAL_LITE_RECT", "Geometry RECT Demo", "widget"),
    ("REALTEK_BUILD_REAL_LITE_CIRCLE", "Geometry CIRCLE Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_QBCODE_WIDGET", "QRCode Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_GLASS_EFFECT_WIDGET",
     "Glass Effect Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_VIDEO_WIDGET", "Video Widget Demo", "widget"),
    ("REALTEK_BUILD_EXAMPLE_LITE_VIDEO_WIDGET",
     "Lite Video Unified Widget Demo (MSV1 + Cinepak)", "widget"),
    ("REALTEK_BUILD_EXAMPLE_STREAM_WIDGET",
     "Stream Widget Demo (live RAW video stream)", "widget"),
    ("REALTEK_BUILD_REAL_BOX2D", "Box2D Demo", "widget"),
    ("REALTEK_BUILD_GUI_410_502_DEMO", "GUI Demo 410x502", "application"),
    ("REALTEK_BUILD_GUI_466_466_DEMO", "GUI Demo 466x466", "application"),
    ("REALTEK_BUILD_GUI_240_240_DEMO", "GUI Demo 240x240", "application"),
    ("REALTEK_BUILD_GUI_800_480_DEMO", "GUI Demo 800x480", "application"),
    ("REALTEK_BUILD_HML_DESIGNER",
     "HML Designer Application", "application"),
    ("REALTEK_BUILD_PARTICLE_DEMO", "Particle System Demo", "widget"),
)

# These Kconfig choices intentionally have no build descriptions or configs.
UNSUPPORTED_DEMOS = (
    ("REALTEK_BUILD_TEST", "GUI Test"),
    ("REALTEK_BUILD_HONEYGUI_AUTO_TEST", "GUI Auto Test"),
)


# --------------------------------------------------------- static configs ---

def _config_filename(name):
    return ".config_{}".format(name.lower())


def demo_config_path(symbol, category):
    directories = {
        "application": APPLICATION_CONFIG_DIR,
        "widget": WIDGET_CONFIG_DIR,
    }
    try:
        directory = directories[category]
    except KeyError:
        raise ValueError("Unknown demo category: {}".format(category))
    return directory / _config_filename(symbol)


def install_config(source):
    """Copy one complete static config into the simulator build directory."""
    if not source.is_file():
        raise RuntimeError("Static config is missing: {}".format(source))
    config_path = SIMULATOR_DIR / ".config"
    shutil.copyfile(str(source), str(config_path))
    return config_path


def _build_files():
    """Cache of (path, text) for every build description under example/."""
    if not hasattr(_build_files, "cache"):
        cache = []
        for name in ("SConscript", "CMakeLists.txt"):
            for path in EXAMPLE_DIR.rglob(name):
                cache.append((path, path.read_text(encoding="ascii",
                                                   errors="ignore")))
        _build_files.cache = cache
    return _build_files.cache


def describe_demo(symbol):
    """Which build systems support this demo, and which example/ area owns it.

    category is the first path component below example/ -- "widget" or
    "application" -- taken from whichever build description mentions the
    symbol. It is None when no build description references it at all.
    """
    needle = "CONFIG_{}".format(symbol)
    scons = cmake = False
    category = None
    for path, text in _build_files():
        if needle not in text:
            continue
        if path.name == "SConscript":
            scons = True
        else:
            cmake = True
        if category is None:
            rel = path.relative_to(EXAMPLE_DIR).parts
            if len(rel) > 1:
                category = rel[0]
    return {"scons": scons, "cmake": cmake, "category": category}


def write_config(symbol, category):
    """Install the complete static config for one demo."""
    return install_config(demo_config_path(symbol, category))


def enabled_widgets(config_path=None):
    """Names of the widgets enabled in a .config, for logging."""
    path = config_path or (SIMULATOR_DIR / ".config")
    prefix = "CONFIG_REALTEK_GUI_WIDGET_"
    out = []
    for line in path.read_text(encoding="ascii", errors="ignore").splitlines():
        if line.startswith(prefix) and line.endswith("=y"):
            name = line[len(prefix):-2]
            if not name.startswith("SET_"):
                out.append(name.lower())
    return sorted(out)


def _config_lines(path, errors):
    if not path.is_file():
        errors.append("Missing static config: {}".format(path))
        return set()
    try:
        return set(path.read_text(encoding="ascii").splitlines())
    except UnicodeDecodeError:
        errors.append("Static config is not ASCII: {}".format(path))
        return set()


def validate_static_configs():
    """Return errors for missing, stale, or internally inconsistent configs."""
    errors = []
    expected_paths = set()
    demo_symbols = {symbol for symbol, _, _ in DEMO_CONFIGS}
    demo_symbols.update(symbol for symbol, _ in UNSUPPORTED_DEMOS)
    for symbol, _, owner in DEMO_CONFIGS:
        path = demo_config_path(symbol, owner)
        expected_paths.add(path)
        lines = _config_lines(path, errors)
        if not lines:
            continue

        if "CONFIG_REALTEK_HONEYGUI=y" not in lines:
            errors.append(
                "{} does not enable REALTEK_HONEYGUI".format(path))
        selected = {
            candidate for candidate in demo_symbols
            if "CONFIG_{}=y".format(candidate) in lines
        }
        if selected != {symbol}:
            errors.append(
                "{} selects demos {}, expected {}".format(
                    path, sorted(selected), symbol))

    actual_paths = set(CONFIG_ROOT.rglob(".config_*")) \
        if CONFIG_ROOT.is_dir() else set()
    for path in sorted(actual_paths - expected_paths):
        errors.append("Unexpected static config: {}".format(path))

    return errors


def validate_environment(needs_scons=True, needs_cmake=True):
    """Return missing prerequisites before a long build matrix starts."""
    errors = []
    if sys.version_info < (3, 7):
        errors.append("Python 3.7 or newer is required: {}".format(
            sys.executable))
    if needs_scons and shutil.which(SCONS_COMMAND) is None:
        errors.append("{} is not available on PATH".format(SCONS_COMMAND))
    if needs_cmake:
        if shutil.which("cmake") is None:
            errors.append("cmake is not available on PATH")
        if IS_WINDOWS and shutil.which("mingw32-make") is None:
            errors.append("mingw32-make is not available on PATH")
    return errors


# ------------------------------------------------------------------ config ---

def snapshot_config_files():
    return {p: (p.read_bytes() if p.exists() else None)
            for p in (SIMULATOR_DIR / n for n in CONFIG_FILES)}


def restore_config_files(snapshot):
    for path, content in snapshot.items():
        if content is None:
            if path.exists():
                path.unlink()
        else:
            path.write_bytes(content)


# ------------------------------------------------------------------- builds ---

def run_command(command, cwd):
    return subprocess.run(
        command,
        cwd=str(cwd),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="ignore",
    )


def make_build_dir(name, parent=None):
    """Create a fresh build directory that cannot reuse a stale CMake cache."""
    root = BUILD_ROOT if parent is None else BUILD_ROOT / parent
    root.mkdir(parents=True, exist_ok=True)
    return Path(tempfile.mkdtemp(
        prefix="{}-".format(name.lower()), dir=str(root)))


def _scons_clean():
    subprocess.run([SCONS_COMMAND, "-c"], cwd=str(SIMULATOR_DIR),
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def build_scons(jobs):
    """SCons builds in-tree, so clean before and after to isolate each demo."""
    _scons_clean()
    result = run_command(
        [SCONS_COMMAND, "-j{}".format(jobs)], SIMULATOR_DIR)
    _scons_clean()
    return result


def build_cmake(name, jobs):
    build_dir = make_build_dir(name)
    try:
        configure = run_command(
            ["cmake", "-G", CMAKE_GENERATOR,
             "-S", str(SIMULATOR_DIR), "-B", str(build_dir)],
            PROJECT_ROOT,
        )
        if configure.returncode != 0:
            return configure
        return run_command(
            ["cmake", "--build", str(build_dir), "--parallel", str(jobs)],
            PROJECT_ROOT,
        )
    finally:
        # Windows scanners can hold build artefacts briefly. Cleanup is best
        # effort, while the next build remains isolated in a fresh directory.
        shutil.rmtree(str(build_dir), ignore_errors=True)


# ------------------------------------------------------------------ report ---

class Report:
    """Collects (label, name, status, output) rows and prints the verdict."""

    def __init__(self, title):
        self.title = title
        self.rows = []
        self.start = datetime.datetime.now()

    def add(self, label, name, status, output=""):
        self.rows.append((label, name, status, output))

    def ok(self, label, name):
        self.add(label, name, "SUCCESS")

    def fail(self, label, name, output):
        self.add(label, name, "FAILED", output)

    def skip(self, label, name, output):
        self.add(label, name, "SKIPPED", output)

    def finish(self, log_name="build_errors.log"):
        print("\n" + "=" * 70)
        print("SUMMARY: {}".format(self.title))
        print("=" * 70)

        failed, skipped = [], []
        for label, name, status, output in self.rows:
            if status == "SUCCESS":
                symbol = "[OK]"
            elif status == "SKIPPED":
                symbol = "[SKIP]"
                skipped.append((label, name, output))
            else:
                symbol = "[FAIL]"
                failed.append((label, name, output))
            print("{} {:<8} {}: {}".format(symbol, label, name, status))

        passed = sum(1 for r in self.rows if r[2] == "SUCCESS")
        print("\nTotal: {} passed, {} failed, {} skipped  (duration {})".format(
            passed, len(failed), len(skipped),
            datetime.datetime.now() - self.start))

        if failed:
            log_path = SCRIPT_DIR / log_name
            with log_path.open("w", encoding="utf-8") as log:
                for label, name, output in failed:
                    heading = "{} - {}".format(label, name)
                    print("\n{}:\n{}".format(heading, (output or "")[:300]))
                    log.write("\n{}\n{}\n{}\n".format(
                        "=" * 60, heading, "=" * 60))
                    log.write((output or "") + "\n")
            print("\nDetailed errors: {}".format(log_path))

        print("\n" + "=" * 70)
        print("OVERALL RESULT")
        print("=" * 70)
        if not self.rows:
            print("Result: NO TESTS")
            return 1
        print("Result: {}".format("FAILED" if failed else "SUCCESS"))
        return 1 if failed else 0


# ------------------------------------------------------------ demo driver ---

def demo_arg_parser(description):
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 8,
                        help="parallel build jobs")
    return parser


def build_demos(category, build_system, jobs):
    """Build every demo owned by example/<category> with one build system.

    category      "widget" or "application"
    build_system  "scons" or "cmake"
    """
    fix_console_encoding()
    label = {"scons": "SCons", "cmake": "CMake"}[build_system]
    title = "{} demos via {}".format(category, label)

    config_errors = validate_static_configs()
    if config_errors:
        print("[FAIL] Static configuration validation:\n{}".format(
            "\n".join(config_errors)))
        return 1

    report = Report(title)
    for _, display in UNSUPPORTED_DEMOS:
        report.skip(label, display, "No build description or static config")
        print("[SKIP] {}: no build description or static config".format(
            display))

    snapshot = snapshot_config_files()
    try:
        for symbol, display, owner in DEMO_CONFIGS:
            if owner != category:
                continue

            info = describe_demo(symbol)
            if info["category"] != owner:
                report.fail(
                    label, display,
                    "Expected {} build description, found {}".format(
                        owner, info["category"]))
                print("[FAIL] {}: build description category mismatch".format(
                    display))
                continue

            if not info[build_system]:
                report.fail(label, display,
                            "Missing {} build description".format(label))
                print("[FAIL] {}: missing {} description".format(display, label))
                continue

            source = demo_config_path(symbol, owner)
            write_config(symbol, owner)
            print("=" * 70)
            print("Building {} [{}]".format(display, label))
            print("Config:  {}".format(source.relative_to(PROJECT_ROOT)))
            print("Widgets: {}".format(", ".join(enabled_widgets())))
            print("=" * 70)

            try:
                if build_system == "scons":
                    result = build_scons(jobs)
                else:
                    result = build_cmake(symbol, jobs)
                output, code = result.stdout or "", result.returncode
            except OSError as error:
                output, code = str(error), 1

            if code == 0:
                report.ok(label, display)
                print("[OK] {}\n".format(display))
            else:
                report.fail(label, display, output)
                print("[FAIL] {}\n{}\n".format(display, output[-1500:]))
    finally:
        if build_system == "scons":
            try:
                _scons_clean()
            except OSError:
                pass
        restore_config_files(snapshot)
        shutil.rmtree(str(BUILD_ROOT), ignore_errors=True)

    return report.finish("build_errors_{}_{}.log".format(category,
                                                         build_system))


def main_for(category, build_system):
    """Entry point body shared by the four demo scripts."""
    args = demo_arg_parser(
        "Build the {} demos with {}".format(category, build_system)).parse_args()
    try:
        return build_demos(category, build_system, args.jobs)
    except KeyboardInterrupt:
        print("\nInterrupted")
        return 1
