/**
 * @file app_hml_designer.c
 * @brief HML Designer Application
 *
 * This application loads UI from HML files generated by HoneyGUI Designer.
 * It demonstrates how to use the HML loader to create GUI from romfs.
 */

#include "guidef.h"
#include "gui_img.h"
#include "gui_win.h"
#include "gui_text.h"
#include "gui_obj.h"
#include "gui_vfs.h"
#include "gui_server.h"
#include "gui_components_init.h"
#include "loader/hml_loader.h"
#include <string.h>
#include <stdio.h>

// External romfs root (generated by designer)
extern const struct romfs_dirent app_romfs_root;

/*============================================================================*
 *                              Callbacks
 *============================================================================*/

static void on_button_click(gui_obj_t *obj)
{
    gui_log("Button clicked: %s\n", obj->name ? obj->name : "unknown");
}

static void on_button_long_press(gui_obj_t *obj)
{
    gui_log("Button long pressed: %s\n", obj->name ? obj->name : "unknown");
}

/*============================================================================*
 *                              App Init
 *============================================================================*/

static int app_init(void)
{
    gui_log("=== HML Designer App ===\n");

    gui_vfs_mount_romfs("/rom", &app_romfs_root, 0);

    // Register callbacks
    hml_register_callback("on_button_click", on_button_click);
    hml_register_callback("on_button_long_press", on_button_long_press);
    gui_log("[OK] Callbacks registered\n");

    // Load HML from romfs
    gui_obj_t *ui = hml_load(gui_obj_get_root(), "/rom/ui/main/NewProjectMain.hml");

    if (ui)
    {
        gui_log("[OK] HML loaded successfully\n");
    }
    else
    {
        gui_log("[ERROR] Failed to load HML\n");

        // Fallback: show error message
        gui_text_t *error_text = gui_text_create(gui_obj_get_root(), "error", 10, 10, 460, 50);
        gui_color_t red = {.color.argb_full = 0xFFFF0000};
        gui_text_set(error_text, "Failed to load UI", GUI_FONT_SRC_BMP,
                     red, 17, 16);
    }

    return 0;
}

GUI_INIT_APP_EXPORT(app_init);
