/**
 * @file app_hml_designer.c
 * @brief HML Designer Application
 *
 * This application loads UI from HML files generated by HoneyGUI Designer.
 * It demonstrates how to use the HML loader to create GUI from romfs.
 */

#include "guidef.h"
#include "gui_img.h"
#include "gui_win.h"
#include "gui_text.h"
#include "gui_obj.h"
#include "gui_vfs.h"
#include "gui_server.h"
#include "gui_components_init.h"
#include "hml_loader.h"
#include <string.h>
#include <stdio.h>

// External romfs root (generated by designer)
extern const struct romfs_dirent app_romfs_root;

static char *get_main_hml_path(void)
{
    gui_vfs_file_t *fd = gui_vfs_open("/hml/project.json", 0);
    if (!fd) { return NULL; }

    gui_vfs_stat_t st;
    if (gui_vfs_stat("/hml/project.json", &st) < 0) { gui_vfs_close(fd); return NULL; }

    char *buf = gui_malloc(st.size + 1);
    if (!buf) { gui_vfs_close(fd); return NULL; }

    gui_vfs_read(fd, buf, st.size);
    buf[st.size] = 0;
    gui_vfs_close(fd);

    char *p = strstr(buf, "\"mainHmlFile\"");
    if (!p) { gui_free(buf); return NULL; }
    p = strchr(p, ':');
    if (!p) { gui_free(buf); return NULL; }
    p = strchr(p, '"');
    if (!p) { gui_free(buf); return NULL; }
    char *start = ++p;
    p = strchr(start, '"');
    if (!p) { gui_free(buf); return NULL; }

    size_t len = p - start;
    char *path = gui_malloc(len + 6);
    strcpy(path, "/hml/");
    strncat(path, start, len);

    // Replace .hml with .xml
    char *ext = strstr(path, ".hml");
    if (ext) { strcpy(ext, ".xml"); }

    gui_free(buf);
    return path;
}

/*============================================================================*
 *                              App Init
 *============================================================================*/

static int app_init(void)
{
    gui_log("=== HML Designer App ===\n");

#ifdef _HONEYGUI_SIMULATOR_
    gui_vfs_mount_posix("/hml", "./example/application/hml_designer/assets");
    // gui_vfs_mount_romfs("/hml", &app_romfs_root, 0);
#else
    gui_vfs_mount_romfs("/hml", (void *)0x704D1000, 0);
#endif

    // Scan and register all views
    hml_scan_views("/hml/ui");

    // Load HML from project.json
    char *hml_path = get_main_hml_path();
    if (!hml_path)
    {
        gui_log("[ERROR] Failed to read mainHmlFile from project.json\n");
        gui_text_t *error_text = gui_text_create(gui_obj_get_root(), "error", 10, 10, 460, 50);
        gui_color_t red = {.color.argb_full = 0xFFFF0000};
        gui_text_set(error_text, "Failed to read project.json", GUI_FONT_SRC_BMP, red, 17, 16);
        return -1;
    }

    gui_obj_t *ui = hml_load(gui_obj_get_root(), hml_path);
    gui_free(hml_path);

    if (ui)
    {
        gui_log("[OK] HML loaded successfully\n");
    }
    else
    {
        gui_log("[ERROR] Failed to load HML\n");

        // Fallback: show error message
        gui_text_t *error_text = gui_text_create(gui_obj_get_root(), "error", 10, 10, 460, 50);
        gui_color_t red = {.color.argb_full = 0xFFFF0000};
        gui_text_set(error_text, "Failed to load UI", GUI_FONT_SRC_BMP,
                     red, 17, 16);
    }

    return 0;
}

GUI_INIT_APP_EXPORT(app_init);
