# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd]

# Explicitly list only the C port sources.
# msvideo1.cpp is a ScummVM reference and must NOT be compiled.
src = ['msv1_decoder.c', 'gui_msv1.c']

if GetDepend(['']):
    objs = DefineGroup('widget', src, depend = [''], CPPPATH = inc)
else:
    objs = []

Return('objs')
