# Common header files installation for HoneyGUI library
# Usage: include(${CMAKE_CURRENT_SOURCE_DIR}/../install_headers.cmake)

set(REALGUI_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../realgui")

file(GLOB_RECURSE HEADER_FILES "${REALGUI_DIR}/gui_version.h")

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/widget/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/server/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/core/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/app/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/dc/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/input/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/engine/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/misc/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/3rd/nanovg/base/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/3rd/ezXML/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/3rd/gifdec/*.h")
list(APPEND HEADER_FILES ${TMP_HEADERS})

# Lite3D headers - conditionally included based on config
if(DEFINED CONFIG_REALTEK_BUILD_LITE3D AND CONFIG_REALTEK_BUILD_LITE3D)
    file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/3rd/Lite3D/widget/*.h")
    list(APPEND HEADER_FILES ${TMP_HEADERS})

endif()

# H264 decoder headers - conditionally included based on config
if(DEFINED CONFIG_REALTEK_H264_DECODER AND CONFIG_REALTEK_H264_DECODER)
    file(GLOB_RECURSE TMP_HEADERS "${REALGUI_DIR}/3rd/h264bsd/inc/*.h")
    list(APPEND HEADER_FILES ${TMP_HEADERS})
endif()

install(FILES ${HEADER_FILES} DESTINATION include)

# Box2D directory installation - conditionally included
if(DEFINED CONFIG_REALTEK_BUILD_GUI_BOX2D AND CONFIG_REALTEK_BUILD_GUI_BOX2D)
    install(DIRECTORY "${REALGUI_DIR}/3rd/box2d/include/box2d" DESTINATION include)
endif()
