# for module compiling
import os
Import('TOOL_ROOT')
Import('RTK_GUI_ENGINE')

from building import *

cwd = GetCurrentDir()


src = Split("""
""")

CPPDEFINES = []

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    CPPDEFINES += ['LV_LVGL_H_INCLUDE_SIMPLE']
    CPPDEFINES += ['LV_CONF_INCLUDE_SIMPLE']
    CPPDEFINES += ['LV_USE_DEMO_BENCHMARK']
    CPPDEFINES += ['LV_USE_DEMO_WIDGETS']
    CPPDEFINES += ['LV_KCONFIG_IGNORE']

path = [cwd]

config = ['../../win32_sim/menu_config.h']

DefineGroup('menuconfig', config, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

objs = []

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
