#if defined _WIN32
extern unsigned char *resource_root;

#define   CELLULAR_MENU_CARD_BIN                  (void *)(resource_root + 0x00000138)
#define   LIST_MENU_CARD_BIN                      (void *)(resource_root + 0x00001a38)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x00002c78)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x000066f8)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(resource_root + 0x0000d0b8)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(resource_root + 0x00041bb8)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(resource_root + 0x000516b8)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(resource_root + 0x00062378)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(resource_root + 0x00062e38)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(resource_root + 0x00063a78)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(resource_root + 0x00064938)
#define   ADD_WATCHFACE_BIN                       (void *)(resource_root + 0x000654b8)
#define   WATCHFACE_BIG_NUM_BIN                   (void *)(resource_root + 0x00068838)
#define   WATCHFACE_FLOW_BIN                      (void *)(resource_root + 0x0006cc38)
#define   WATCHFACE_SPORT_BIN                     (void *)(resource_root + 0x00078ff8)
#define   WATCHFACE_VIDEO_BIN                     (void *)(resource_root + 0x00081978)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(resource_root + 0x000909b8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(resource_root + 0x000934b8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(resource_root + 0x000954f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(resource_root + 0x000970b8)
#define   APP_COMPASS_ICON_BIN                    (void *)(resource_root + 0x000986f8)
#define   APP_CONTACTS_ICON_BIN                   (void *)(resource_root + 0x0009a2b8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(resource_root + 0x0009b8b8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(resource_root + 0x0009cf38)
#define   APP_HOME_ICON_BIN                       (void *)(resource_root + 0x0009eff8)
#define   APP_MAIL_ICON_BIN                       (void *)(resource_root + 0x000a0a38)
#define   APP_MAP_ICON_BIN                        (void *)(resource_root + 0x000a2478)
#define   APP_MESSAGE_ICON_BIN                    (void *)(resource_root + 0x000a5838)
#define   APP_MUSIC_ICON_BIN                      (void *)(resource_root + 0x000a6f38)
#define   APP_NEWS_ICON_BIN                       (void *)(resource_root + 0x000a8e38)
#define   APP_NOISE_ICON_BIN                      (void *)(resource_root + 0x000aa338)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(resource_root + 0x000acb78)
#define   APP_PHONE_ICON_BIN                      (void *)(resource_root + 0x000ae178)
#define   APP_PHOTO_ICON_BIN                      (void *)(resource_root + 0x000afa78)
#define   APP_PODCASTS_ICON_BIN                   (void *)(resource_root + 0x000b16f8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(resource_root + 0x000b3cf8)
#define   APP_SLEEP_ICON_BIN                      (void *)(resource_root + 0x000b52b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(resource_root + 0x000b68b8)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(resource_root + 0x000b80b8)
#define   APP_STORE_ICON_BIN                      (void *)(resource_root + 0x000b9eb8)
#define   APP_TIMERS_ICON_BIN                     (void *)(resource_root + 0x000be0f8)
#define   APP_WEATHER_ICON_BIN                    (void *)(resource_root + 0x000bfd78)
#define   APP_WORKOUT_ICON_BIN                    (void *)(resource_root + 0x000c2d38)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(resource_root + 0x000c4838)
#define   PAUSE_BIN                               (void *)(resource_root + 0x000c6bb8)
#define   PLAY_BIN                                (void *)(resource_root + 0x000c6ff8)
#define   RECTANGLE86_BIN                         (void *)(resource_root + 0x000c72f8)
#define   DELETE_ICON_BIN                         (void *)(resource_root + 0x000fe578)
#define   MUSIC_BROADCAST_ICON_BIN                (void *)(resource_root + 0x000feef8)
#define   MUSIC_CTR_ICON_BIN                      (void *)(resource_root + 0x00100978)
#define   MUSIC_HOMEPAGE_BIN                      (void *)(resource_root + 0x00102838)
#define   MUSIC_LIB_BIN                           (void *)(resource_root + 0x001045f8)
#define   MUSIC_NEXT_BIN                          (void *)(resource_root + 0x001079b8)
#define   MUSIC_PRE_BIN                           (void *)(resource_root + 0x00108378)
#define   CJSON_DATA_BIN                          (void *)(resource_root + 0x00108d38)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(resource_root + 0x00109078)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(resource_root + 0x0010cab8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(resource_root + 0x00110338)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(resource_root + 0x00113eb8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(resource_root + 0x001179f8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(resource_root + 0x0011b338)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(resource_root + 0x0011ecf8)
#define   HEART_BIN                               (void *)(resource_root + 0x001225b8)
#define   ICON_INFORMATION_BIN                    (void *)(resource_root + 0x001266f8)
#define   EARTH_420_336_416_MJPG                  (void *)(resource_root + 0x00126fb8)
#define   SCROLLBAR_BG_BIN                        (void *)(resource_root + 0x00223138)
#define   SCROLLBAR_L_BIN                         (void *)(resource_root + 0x002233b8)
#define   SCROLLBAR_M_BIN                         (void *)(resource_root + 0x002235f8)
#define   SCROLLBAR_S_BIN                         (void *)(resource_root + 0x00223778)
#define   STOPWATCH_BUTTON_BG_BIN                 (void *)(resource_root + 0x00223938)
#define   STOPWATCH_BUTTON_MARK_BIN               (void *)(resource_root + 0x00224db8)
#define   STOPWATCH_BUTTON_RESET_BIN              (void *)(resource_root + 0x002251f8)
#define   STOPWATCH_BUTTON_START_BIN              (void *)(resource_root + 0x00225978)
#define   STOPWATCH_BUTTON_STOP_BIN               (void *)(resource_root + 0x00225cb8)
#define   STOPWATCH_HAND_BIG_BIN                  (void *)(resource_root + 0x00225fb8)
#define   STOPWATCH_HAND_S_BIN                    (void *)(resource_root + 0x002273b8)
#define   STOPWATCH_MILSEC_CONTAINER_BIN          (void *)(resource_root + 0x00227738)
#define   STOPWATCH_MIN_CONTAINER_BIN             (void *)(resource_root + 0x00229fb8)
#define   STOPWATCH_SEC_CONTAINER_BIN             (void *)(resource_root + 0x0022d038)
#define   STOPWATCH_SEC_CONTAINER_BIG_BIN         (void *)(resource_root + 0x0022faf8)
#define   WIND_ARROW_BIN                          (void *)(resource_root + 0x0023f2f8)
#define   WIND_BLUR_BIN                           (void *)(resource_root + 0x0023f6f8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(resource_root + 0x0023fbf8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(resource_root + 0x002589b8)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(resource_root + 0x002701f8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(resource_root + 0x00287a38)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(resource_root + 0x00287e78)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(resource_root + 0x002883f8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(resource_root + 0x00288978)
#define   WEATHER_DIAL_BIN                        (void *)(resource_root + 0x00288f38)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(resource_root + 0x0029a2f8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(resource_root + 0x0029acf8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(resource_root + 0x0029b7f8)

#else
#define   CELLULAR_MENU_CARD_BIN                  (void *)(0x704d1538)
#define   LIST_MENU_CARD_BIN                      (void *)(0x704d2e38)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x704d4078)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x704d7af8)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(0x704de4b8)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(0x70512fb8)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(0x70522ab8)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(0x70533778)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(0x70534238)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(0x70534e78)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(0x70535d38)
#define   ADD_WATCHFACE_BIN                       (void *)(0x705368b8)
#define   WATCHFACE_BIG_NUM_BIN                   (void *)(0x70539c38)
#define   WATCHFACE_FLOW_BIN                      (void *)(0x7053e038)
#define   WATCHFACE_SPORT_BIN                     (void *)(0x7054a3f8)
#define   WATCHFACE_VIDEO_BIN                     (void *)(0x70552d78)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(0x70561db8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(0x705648b8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(0x705668f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(0x705684b8)
#define   APP_COMPASS_ICON_BIN                    (void *)(0x70569af8)
#define   APP_CONTACTS_ICON_BIN                   (void *)(0x7056b6b8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(0x7056ccb8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(0x7056e338)
#define   APP_HOME_ICON_BIN                       (void *)(0x705703f8)
#define   APP_MAIL_ICON_BIN                       (void *)(0x70571e38)
#define   APP_MAP_ICON_BIN                        (void *)(0x70573878)
#define   APP_MESSAGE_ICON_BIN                    (void *)(0x70576c38)
#define   APP_MUSIC_ICON_BIN                      (void *)(0x70578338)
#define   APP_NEWS_ICON_BIN                       (void *)(0x7057a238)
#define   APP_NOISE_ICON_BIN                      (void *)(0x7057b738)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(0x7057df78)
#define   APP_PHONE_ICON_BIN                      (void *)(0x7057f578)
#define   APP_PHOTO_ICON_BIN                      (void *)(0x70580e78)
#define   APP_PODCASTS_ICON_BIN                   (void *)(0x70582af8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(0x705850f8)
#define   APP_SLEEP_ICON_BIN                      (void *)(0x705866b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(0x70587cb8)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(0x705894b8)
#define   APP_STORE_ICON_BIN                      (void *)(0x7058b2b8)
#define   APP_TIMERS_ICON_BIN                     (void *)(0x7058f4f8)
#define   APP_WEATHER_ICON_BIN                    (void *)(0x70591178)
#define   APP_WORKOUT_ICON_BIN                    (void *)(0x70594138)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(0x70595c38)
#define   PAUSE_BIN                               (void *)(0x70597fb8)
#define   PLAY_BIN                                (void *)(0x705983f8)
#define   RECTANGLE86_BIN                         (void *)(0x705986f8)
#define   DELETE_ICON_BIN                         (void *)(0x705cf978)
#define   MUSIC_BROADCAST_ICON_BIN                (void *)(0x705d02f8)
#define   MUSIC_CTR_ICON_BIN                      (void *)(0x705d1d78)
#define   MUSIC_HOMEPAGE_BIN                      (void *)(0x705d3c38)
#define   MUSIC_LIB_BIN                           (void *)(0x705d59f8)
#define   MUSIC_NEXT_BIN                          (void *)(0x705d8db8)
#define   MUSIC_PRE_BIN                           (void *)(0x705d9778)
#define   CJSON_DATA_BIN                          (void *)(0x705da138)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(0x705da478)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(0x705ddeb8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(0x705e1738)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(0x705e52b8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(0x705e8df8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(0x705ec738)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(0x705f00f8)
#define   HEART_BIN                               (void *)(0x705f39b8)
#define   ICON_INFORMATION_BIN                    (void *)(0x705f7af8)
#define   EARTH_420_336_416_MJPG                  (void *)(0x705f83b8)
#define   SCROLLBAR_BG_BIN                        (void *)(0x706f4538)
#define   SCROLLBAR_L_BIN                         (void *)(0x706f47b8)
#define   SCROLLBAR_M_BIN                         (void *)(0x706f49f8)
#define   SCROLLBAR_S_BIN                         (void *)(0x706f4b78)
#define   STOPWATCH_BUTTON_BG_BIN                 (void *)(0x706f4d38)
#define   STOPWATCH_BUTTON_MARK_BIN               (void *)(0x706f61b8)
#define   STOPWATCH_BUTTON_RESET_BIN              (void *)(0x706f65f8)
#define   STOPWATCH_BUTTON_START_BIN              (void *)(0x706f6d78)
#define   STOPWATCH_BUTTON_STOP_BIN               (void *)(0x706f70b8)
#define   STOPWATCH_HAND_BIG_BIN                  (void *)(0x706f73b8)
#define   STOPWATCH_HAND_S_BIN                    (void *)(0x706f87b8)
#define   STOPWATCH_MILSEC_CONTAINER_BIN          (void *)(0x706f8b38)
#define   STOPWATCH_MIN_CONTAINER_BIN             (void *)(0x706fb3b8)
#define   STOPWATCH_SEC_CONTAINER_BIN             (void *)(0x706fe438)
#define   STOPWATCH_SEC_CONTAINER_BIG_BIN         (void *)(0x70700ef8)
#define   WIND_ARROW_BIN                          (void *)(0x707106f8)
#define   WIND_BLUR_BIN                           (void *)(0x70710af8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(0x70710ff8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(0x70729db8)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(0x707415f8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(0x70758e38)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(0x70759278)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(0x707597f8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(0x70759d78)
#define   WEATHER_DIAL_BIN                        (void *)(0x7075a338)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(0x7076b6f8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(0x7076c0f8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(0x7076cbf8)

#endif
