#if defined _WIN32
extern unsigned char *resource_root;

#define   UI_TEXT_0_BIN                           (void *)(resource_root + 0x000001b8)
#define   UI_TEXT_1_BIN                           (void *)(resource_root + 0x00000b38)
#define   UI_TEXT_2_BIN                           (void *)(resource_root + 0x00001138)
#define   UI_TEXT_3_BIN                           (void *)(resource_root + 0x000018b8)
#define   UI_TEXT_4_BIN                           (void *)(resource_root + 0x00002178)
#define   UI_TEXT_5_BIN                           (void *)(resource_root + 0x000029b8)
#define   UI_TEXT_6_BIN                           (void *)(resource_root + 0x00003178)
#define   UI_TEXT_7_BIN                           (void *)(resource_root + 0x00003af8)
#define   UI_TEXT_8_BIN                           (void *)(resource_root + 0x000040b8)
#define   UI_TEXT_9_BIN                           (void *)(resource_root + 0x00004b78)
#define   UI_TEXT_COLON_BIN                       (void *)(resource_root + 0x000054f8)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x000057b8)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x00007a78)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(resource_root + 0x0000e438)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(resource_root + 0x00042f38)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(resource_root + 0x00052a38)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(resource_root + 0x000636f8)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(resource_root + 0x000641b8)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(resource_root + 0x00064df8)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(resource_root + 0x00065cb8)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(resource_root + 0x000669b8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(resource_root + 0x000698b8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(resource_root + 0x0006c0f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(resource_root + 0x0006e7b8)
#define   APP_COMPASS_ICON_BIN                    (void *)(resource_root + 0x0006ff38)
#define   APP_CONTACTS_ICON_BIN                   (void *)(resource_root + 0x00071df8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(resource_root + 0x00073af8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(resource_root + 0x000753b8)
#define   APP_HOME_ICON_BIN                       (void *)(resource_root + 0x000781b8)
#define   APP_MAIL_ICON_BIN                       (void *)(resource_root + 0x00079eb8)
#define   APP_MAP_ICON_BIN                        (void *)(resource_root + 0x0007c338)
#define   APP_MESSAGE_ICON_BIN                    (void *)(resource_root + 0x000805b8)
#define   APP_MUSIC_ICON_BIN                      (void *)(resource_root + 0x00082578)
#define   APP_NEWS_ICON_BIN                       (void *)(resource_root + 0x000850f8)
#define   APP_NOISE_ICON_BIN                      (void *)(resource_root + 0x00086938)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(resource_root + 0x00089c78)
#define   APP_PHONE_ICON_BIN                      (void *)(resource_root + 0x0008b538)
#define   APP_PHOTO_ICON_BIN                      (void *)(resource_root + 0x0008d8b8)
#define   APP_PODCASTS_ICON_BIN                   (void *)(resource_root + 0x0008f8f8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(resource_root + 0x000928f8)
#define   APP_SLEEP_ICON_BIN                      (void *)(resource_root + 0x000940b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(resource_root + 0x00096178)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(resource_root + 0x00097a78)
#define   APP_STORE_ICON_BIN                      (void *)(resource_root + 0x0009a0b8)
#define   APP_TIMERS_ICON_BIN                     (void *)(resource_root + 0x0009fb78)
#define   APP_WEATHER_ICON_BIN                    (void *)(resource_root + 0x000a20b8)
#define   APP_WORKOUT_ICON_BIN                    (void *)(resource_root + 0x000a7838)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(resource_root + 0x000a9e38)
#define   CJSON_DATA_BIN                          (void *)(resource_root + 0x000acc38)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(resource_root + 0x000acf78)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(resource_root + 0x000b09b8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(resource_root + 0x000b4238)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(resource_root + 0x000b7db8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(resource_root + 0x000bb8f8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(resource_root + 0x000bf238)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(resource_root + 0x000c2bf8)
#define   HEART_BIN                               (void *)(resource_root + 0x000c64b8)
#define   ICON_INFORMATION_BIN                    (void *)(resource_root + 0x000ca5f8)
#define   LABUBU_MJPG                             (void *)(resource_root + 0x000caeb8)
#define   WIND_ARROW_BIN                          (void *)(resource_root + 0x000fd9b8)
#define   WIND_BLUR_BIN                           (void *)(resource_root + 0x000fddb8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(resource_root + 0x000fe2b8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(resource_root + 0x00117078)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(resource_root + 0x0012e8b8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(resource_root + 0x001460f8)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(resource_root + 0x00146538)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(resource_root + 0x00146ab8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(resource_root + 0x00147038)
#define   WEATHER_DIAL_BIN                        (void *)(resource_root + 0x001475f8)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(resource_root + 0x001589b8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(resource_root + 0x001593b8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(resource_root + 0x00159eb8)

#else
#define   UI_TEXT_0_BIN                           (void *)(0x704d15b8)
#define   UI_TEXT_1_BIN                           (void *)(0x704d1f38)
#define   UI_TEXT_2_BIN                           (void *)(0x704d2538)
#define   UI_TEXT_3_BIN                           (void *)(0x704d2cb8)
#define   UI_TEXT_4_BIN                           (void *)(0x704d3578)
#define   UI_TEXT_5_BIN                           (void *)(0x704d3db8)
#define   UI_TEXT_6_BIN                           (void *)(0x704d4578)
#define   UI_TEXT_7_BIN                           (void *)(0x704d4ef8)
#define   UI_TEXT_8_BIN                           (void *)(0x704d54b8)
#define   UI_TEXT_9_BIN                           (void *)(0x704d5f78)
#define   UI_TEXT_COLON_BIN                       (void *)(0x704d68f8)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x704d6bb8)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x704d8e78)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(0x704df838)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(0x70514338)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(0x70523e38)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(0x70534af8)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(0x705355b8)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(0x705361f8)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(0x705370b8)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(0x70537db8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(0x7053acb8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(0x7053d4f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(0x7053fbb8)
#define   APP_COMPASS_ICON_BIN                    (void *)(0x70541338)
#define   APP_CONTACTS_ICON_BIN                   (void *)(0x705431f8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(0x70544ef8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(0x705467b8)
#define   APP_HOME_ICON_BIN                       (void *)(0x705495b8)
#define   APP_MAIL_ICON_BIN                       (void *)(0x7054b2b8)
#define   APP_MAP_ICON_BIN                        (void *)(0x7054d738)
#define   APP_MESSAGE_ICON_BIN                    (void *)(0x705519b8)
#define   APP_MUSIC_ICON_BIN                      (void *)(0x70553978)
#define   APP_NEWS_ICON_BIN                       (void *)(0x705564f8)
#define   APP_NOISE_ICON_BIN                      (void *)(0x70557d38)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(0x7055b078)
#define   APP_PHONE_ICON_BIN                      (void *)(0x7055c938)
#define   APP_PHOTO_ICON_BIN                      (void *)(0x7055ecb8)
#define   APP_PODCASTS_ICON_BIN                   (void *)(0x70560cf8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(0x70563cf8)
#define   APP_SLEEP_ICON_BIN                      (void *)(0x705654b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(0x70567578)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(0x70568e78)
#define   APP_STORE_ICON_BIN                      (void *)(0x7056b4b8)
#define   APP_TIMERS_ICON_BIN                     (void *)(0x70570f78)
#define   APP_WEATHER_ICON_BIN                    (void *)(0x705734b8)
#define   APP_WORKOUT_ICON_BIN                    (void *)(0x70578c38)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(0x7057b238)
#define   CJSON_DATA_BIN                          (void *)(0x7057e038)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(0x7057e378)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(0x70581db8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(0x70585638)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(0x705891b8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(0x7058ccf8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(0x70590638)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(0x70593ff8)
#define   HEART_BIN                               (void *)(0x705978b8)
#define   ICON_INFORMATION_BIN                    (void *)(0x7059b9f8)
#define   LABUBU_MJPG                             (void *)(0x7059c2b8)
#define   WIND_ARROW_BIN                          (void *)(0x705cedb8)
#define   WIND_BLUR_BIN                           (void *)(0x705cf1b8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(0x705cf6b8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(0x705e8478)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(0x705ffcb8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(0x706174f8)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(0x70617938)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(0x70617eb8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(0x70618438)
#define   WEATHER_DIAL_BIN                        (void *)(0x706189f8)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(0x70629db8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(0x7062a7b8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(0x7062b2b8)

#endif
