#if defined _WIN32
extern unsigned char *resource_root;

#define   CELLULAR_MENU_CARD_BIN                  (void *)(resource_root + 0x00000138)
#define   LIST_MENU_CARD_BIN                      (void *)(resource_root + 0x00001a38)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x00002c78)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x000066f8)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(resource_root + 0x0000d0b8)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(resource_root + 0x00041bb8)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(resource_root + 0x000516b8)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(resource_root + 0x00062378)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(resource_root + 0x00062e38)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(resource_root + 0x00063a78)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(resource_root + 0x00064938)
#define   ADD_WATCHFACE_BIN                       (void *)(resource_root + 0x000654b8)
#define   WATCHFACE_BIG_NUM_BIN                   (void *)(resource_root + 0x00068838)
#define   WATCHFACE_FLOW_BIN                      (void *)(resource_root + 0x0006cc38)
#define   WATCHFACE_SPORT_BIN                     (void *)(resource_root + 0x00078ff8)
#define   WATCHFACE_VIDEO_BIN                     (void *)(resource_root + 0x00081978)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(resource_root + 0x000909b8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(resource_root + 0x000934b8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(resource_root + 0x000954f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(resource_root + 0x000970b8)
#define   APP_COMPASS_ICON_BIN                    (void *)(resource_root + 0x000986f8)
#define   APP_CONTACTS_ICON_BIN                   (void *)(resource_root + 0x0009a2b8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(resource_root + 0x0009b8b8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(resource_root + 0x0009cf38)
#define   APP_HOME_ICON_BIN                       (void *)(resource_root + 0x0009eff8)
#define   APP_MAIL_ICON_BIN                       (void *)(resource_root + 0x000a0a38)
#define   APP_MAP_ICON_BIN                        (void *)(resource_root + 0x000a2478)
#define   APP_MESSAGE_ICON_BIN                    (void *)(resource_root + 0x000a5838)
#define   APP_MUSIC_ICON_BIN                      (void *)(resource_root + 0x000a6f38)
#define   APP_NEWS_ICON_BIN                       (void *)(resource_root + 0x000a8e38)
#define   APP_NOISE_ICON_BIN                      (void *)(resource_root + 0x000aa338)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(resource_root + 0x000acb78)
#define   APP_PHONE_ICON_BIN                      (void *)(resource_root + 0x000ae178)
#define   APP_PHOTO_ICON_BIN                      (void *)(resource_root + 0x000afa78)
#define   APP_PODCASTS_ICON_BIN                   (void *)(resource_root + 0x000b16f8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(resource_root + 0x000b3cf8)
#define   APP_SLEEP_ICON_BIN                      (void *)(resource_root + 0x000b52b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(resource_root + 0x000b68b8)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(resource_root + 0x000b80b8)
#define   APP_STORE_ICON_BIN                      (void *)(resource_root + 0x000b9eb8)
#define   APP_TIMERS_ICON_BIN                     (void *)(resource_root + 0x000be0f8)
#define   APP_WEATHER_ICON_BIN                    (void *)(resource_root + 0x000bfd78)
#define   APP_WORKOUT_ICON_BIN                    (void *)(resource_root + 0x000c2d38)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(resource_root + 0x000c4838)
#define   CJSON_DATA_BIN                          (void *)(resource_root + 0x000c6b38)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(resource_root + 0x000c6e78)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(resource_root + 0x000ca8b8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(resource_root + 0x000ce138)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(resource_root + 0x000d1cb8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(resource_root + 0x000d57f8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(resource_root + 0x000d9138)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(resource_root + 0x000dcaf8)
#define   HEART_BIN                               (void *)(resource_root + 0x000e03b8)
#define   ICON_INFORMATION_BIN                    (void *)(resource_root + 0x000e44f8)
#define   EARTH_420_336_416_MJPG                  (void *)(resource_root + 0x000e4db8)
#define   SCROLLBAR_BG_BIN                        (void *)(resource_root + 0x001e0f38)
#define   SCROLLBAR_L_BIN                         (void *)(resource_root + 0x001e11b8)
#define   SCROLLBAR_M_BIN                         (void *)(resource_root + 0x001e13f8)
#define   SCROLLBAR_S_BIN                         (void *)(resource_root + 0x001e1578)
#define   STOPWATCH_BUTTON_BG_BIN                 (void *)(resource_root + 0x001e1738)
#define   STOPWATCH_BUTTON_MARK_BIN               (void *)(resource_root + 0x001e2bb8)
#define   STOPWATCH_BUTTON_RESET_BIN              (void *)(resource_root + 0x001e2ff8)
#define   STOPWATCH_BUTTON_START_BIN              (void *)(resource_root + 0x001e3778)
#define   STOPWATCH_BUTTON_STOP_BIN               (void *)(resource_root + 0x001e3ab8)
#define   STOPWATCH_HAND_BIG_BIN                  (void *)(resource_root + 0x001e3db8)
#define   STOPWATCH_HAND_S_BIN                    (void *)(resource_root + 0x001e51b8)
#define   STOPWATCH_MILSEC_CONTAINER_BIN          (void *)(resource_root + 0x001e5538)
#define   STOPWATCH_MIN_CONTAINER_BIN             (void *)(resource_root + 0x001e7db8)
#define   STOPWATCH_SEC_CONTAINER_BIN             (void *)(resource_root + 0x001eae38)
#define   STOPWATCH_SEC_CONTAINER_BIG_BIN         (void *)(resource_root + 0x001ed8f8)
#define   WIND_ARROW_BIN                          (void *)(resource_root + 0x001fd0f8)
#define   WIND_BLUR_BIN                           (void *)(resource_root + 0x001fd4f8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(resource_root + 0x001fd9f8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(resource_root + 0x002167b8)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(resource_root + 0x0022dff8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(resource_root + 0x00245838)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(resource_root + 0x00245c78)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(resource_root + 0x002461f8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(resource_root + 0x00246778)
#define   WEATHER_DIAL_BIN                        (void *)(resource_root + 0x00246d38)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(resource_root + 0x002580f8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(resource_root + 0x00258af8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(resource_root + 0x002595f8)

#else
#define   CELLULAR_MENU_CARD_BIN                  (void *)(0x704d1538)
#define   LIST_MENU_CARD_BIN                      (void *)(0x704d2e38)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x704d4078)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x704d7af8)
#define   ACTIVITY_APP_BG1_BIN                    (void *)(0x704de4b8)
#define   ACTIVITY_APP_BG2_BIN                    (void *)(0x70512fb8)
#define   ACTIVITY_APP_BG3_BIN                    (void *)(0x70522ab8)
#define   ACTIVITY_LEFT_CONTROL_BIN               (void *)(0x70533778)
#define   ACTIVITY_LEFT_CONTROL0_BIN              (void *)(0x70534238)
#define   ACTIVITY_RIGHT_CONTROL_BIN              (void *)(0x70534e78)
#define   ACTIVITY_RIGHT_CONTROL0_BIN             (void *)(0x70535d38)
#define   ADD_WATCHFACE_BIN                       (void *)(0x705368b8)
#define   WATCHFACE_BIG_NUM_BIN                   (void *)(0x70539c38)
#define   WATCHFACE_FLOW_BIN                      (void *)(0x7053e038)
#define   WATCHFACE_SPORT_BIN                     (void *)(0x7054a3f8)
#define   WATCHFACE_VIDEO_BIN                     (void *)(0x70552d78)
#define   APP_ACTIVITY_ICON_BIN                   (void *)(0x70561db8)
#define   APP_ALARM_CLOCK_ICON_BIN                (void *)(0x705648b8)
#define   APP_AUDIO_BOOKS_ICON_BIN                (void *)(0x705668f8)
#define   APP_CALENDAR_ICON_BIN                   (void *)(0x705684b8)
#define   APP_COMPASS_ICON_BIN                    (void *)(0x70569af8)
#define   APP_CONTACTS_ICON_BIN                   (void *)(0x7056b6b8)
#define   APP_CYCLE_TRACKING_ICON_BIN             (void *)(0x7056ccb8)
#define   APP_HEART_RATE_ICON_BIN                 (void *)(0x7056e338)
#define   APP_HOME_ICON_BIN                       (void *)(0x705703f8)
#define   APP_MAIL_ICON_BIN                       (void *)(0x70571e38)
#define   APP_MAP_ICON_BIN                        (void *)(0x70573878)
#define   APP_MESSAGE_ICON_BIN                    (void *)(0x70576c38)
#define   APP_MUSIC_ICON_BIN                      (void *)(0x70578338)
#define   APP_NEWS_ICON_BIN                       (void *)(0x7057a238)
#define   APP_NOISE_ICON_BIN                      (void *)(0x7057b738)
#define   APP_NOW_PLAYING_ICON_BIN                (void *)(0x7057df78)
#define   APP_PHONE_ICON_BIN                      (void *)(0x7057f578)
#define   APP_PHOTO_ICON_BIN                      (void *)(0x70580e78)
#define   APP_PODCASTS_ICON_BIN                   (void *)(0x70582af8)
#define   APP_REMINDERS_ICON_BIN                  (void *)(0x705850f8)
#define   APP_SLEEP_ICON_BIN                      (void *)(0x705866b8)
#define   APP_STOCKS_ICON_BIN                     (void *)(0x70587cb8)
#define   APP_STOPWATCH_ICON_BIN                  (void *)(0x705894b8)
#define   APP_STORE_ICON_BIN                      (void *)(0x7058b2b8)
#define   APP_TIMERS_ICON_BIN                     (void *)(0x7058f4f8)
#define   APP_WEATHER_ICON_BIN                    (void *)(0x70591178)
#define   APP_WORKOUT_ICON_BIN                    (void *)(0x70594138)
#define   APP_WORLD_CLOCK_ICON_BIN                (void *)(0x70595c38)
#define   CJSON_DATA_BIN                          (void *)(0x70597f38)
#define   SF_COMPACT_REGULAR_BIN                  (void *)(0x70598278)
#define   SF_COMPACT_TEXT_BOLD_BIN                (void *)(0x7059bcb8)
#define   SF_COMPACT_TEXT_LIGHT_BIN               (void *)(0x7059f538)
#define   SF_COMPACT_TEXT_LIGHT_ITALIC_BIN        (void *)(0x705a30b8)
#define   SF_COMPACT_TEXT_MEDIUM_BIN              (void *)(0x705a6bf8)
#define   SF_COMPACT_TEXT_MEDIUM_ITALIC_BIN       (void *)(0x705aa538)
#define   SF_COMPACT_TEXT_SEMIBOLD_BIN            (void *)(0x705adef8)
#define   HEART_BIN                               (void *)(0x705b17b8)
#define   ICON_INFORMATION_BIN                    (void *)(0x705b58f8)
#define   EARTH_420_336_416_MJPG                  (void *)(0x705b61b8)
#define   SCROLLBAR_BG_BIN                        (void *)(0x706b2338)
#define   SCROLLBAR_L_BIN                         (void *)(0x706b25b8)
#define   SCROLLBAR_M_BIN                         (void *)(0x706b27f8)
#define   SCROLLBAR_S_BIN                         (void *)(0x706b2978)
#define   STOPWATCH_BUTTON_BG_BIN                 (void *)(0x706b2b38)
#define   STOPWATCH_BUTTON_MARK_BIN               (void *)(0x706b3fb8)
#define   STOPWATCH_BUTTON_RESET_BIN              (void *)(0x706b43f8)
#define   STOPWATCH_BUTTON_START_BIN              (void *)(0x706b4b78)
#define   STOPWATCH_BUTTON_STOP_BIN               (void *)(0x706b4eb8)
#define   STOPWATCH_HAND_BIG_BIN                  (void *)(0x706b51b8)
#define   STOPWATCH_HAND_S_BIN                    (void *)(0x706b65b8)
#define   STOPWATCH_MILSEC_CONTAINER_BIN          (void *)(0x706b6938)
#define   STOPWATCH_MIN_CONTAINER_BIN             (void *)(0x706b91b8)
#define   STOPWATCH_SEC_CONTAINER_BIN             (void *)(0x706bc238)
#define   STOPWATCH_SEC_CONTAINER_BIG_BIN         (void *)(0x706becf8)
#define   WIND_ARROW_BIN                          (void *)(0x706ce4f8)
#define   WIND_BLUR_BIN                           (void *)(0x706ce8f8)
#define   WEATHER_BACKGROUND1_BIN                 (void *)(0x706cedf8)
#define   WEATHER_BACKGROUND2_BIN                 (void *)(0x706e7bb8)
#define   WEATHER_BACKGROUND3_BIN                 (void *)(0x706ff3f8)
#define   WEATHER_CONDITION_CLOUDY_BIN            (void *)(0x70716c38)
#define   WEATHER_CONDITION_PARTLY_CLOUDY_BIN     (void *)(0x70717078)
#define   WEATHER_CONDITION_SUNNY_BIN             (void *)(0x707175f8)
#define   WEATHER_CONDITION_WINDY_BIN             (void *)(0x70717b78)
#define   WEATHER_DIAL_BIN                        (void *)(0x70718138)
#define   WEATHER_LEFT_CONTROL_BIN                (void *)(0x707294f8)
#define   WEATHER_RIGHT_CONTROL_BIN               (void *)(0x70729ef8)
#define   WEATHER_SEPARATOR_BIN                   (void *)(0x7072a9f8)

#endif
