Import('TOOL_ROOT')

Import('SDK_ROOT')
from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []

# add the general drivers.
src = Split("""
""")
CPPDEFINES = []
if GetDepend(['USING_BR_TASK']):
    src += ['br_gap_init.c']
    src += ['br_gap_cb.c']
    src += ['app_linkback.c']
    src += ['app_bt_policy.c']
    src += ['app_mmi.c']
if GetDepend(['BR_PROFILE_SDP']):
    src += ['app_sdp.c']
    CPPDEFINES += ['RTK_BR_PROFILE_SDP']
if GetDepend(['BR_PROFILE_SPP']):
    src += ['app_spp.c']
    CPPDEFINES += ['RTK_BR_PROFILE_SPP']
if GetDepend(['BR_PROFILE_A2DP']):
    src += ['app_audio_policy.c']
    src += ['app_audio_route.c']
    src += ['app_a2dp.c']
    CPPDEFINES += ['RTK_BR_PROFILE_A2DP']
if GetDepend(['BR_PROFILE_AVRCP']):
    src += ['app_avrcp.c']
    CPPDEFINES += ['RTK_BR_PROFILE_AVRCP']
if GetDepend(['BR_PROFILE_PBAP']):
    src += ['app_pbap.c']
    CPPDEFINES += ['RTK_BR_PROFILE_PBAP']
if GetDepend(['BR_PROFILE_HFP']):
    src += ['app_hfp.c']
    CPPDEFINES += ['RTK_BR_PROFILE_HFP']


CPPPATH = [cwd]
CPPDEFINES += ['DEFINE_RTK_BT_TODO']
libs = ['']
libpath = [SDK_ROOT + '/bin/mdk']
libs += ['gap_utils']
libs += ['bt_mgr']
libs += ['console']
libs += ['audio']
libs += ['sysm']
libs += ['remote']

libs += ['hal_utils']

group = DefineGroup('bt_app', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = libs, LIBPATH = libpath)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')