Import('TOOL_ROOT')

Import('SDK_ROOT')
from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []

# add the general drivers.
src = Split("""
""")
if GetDepend(['RTK_BT_TASK']):
    src += ['bt_gap_init.c']
    src += ['bt_gap_cb.c']
if GetDepend(['BT_PROFILE_SDP']):
    src += ['app_sdp.c']
if GetDepend(['BT_PROFILE_SPP']):
    src += ['app_spp.c']
if GetDepend(['BT_PROFILE_A2DP']):
    src += ['app_a2dp.c']
if GetDepend(['BT_PROFILE_AVRCP']):
    src += ['app_avrcp.c']
if GetDepend(['BT_PROFILE_PBAP']):
    src += ['app_pbap.c']
if GetDepend(['BT_PROFILE_HFP']):
    src += ['app_hfp.c']


CPPPATH = [cwd]
CPPDEFINES = ['DEFINE_RTK_BT_TODO']
libs = ['']
libpath = [SDK_ROOT + '/bin/mdk']
libs += ['gap_utils']
libs += ['bt_mgr']
libs += ['console']
libs += ['audio']
libs += ['sysm']
libs += ['remote']

libs += ['hal_utils']

group = DefineGroup('bt_app', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = libs, LIBPATH = libpath)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')