Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['BSP_TOUCH_ZT2717']):
    src += ['touch_zt2717.c']

CPPPATH = [cwd]

group = DefineGroup('touch_driver', src, depend = ['BSP_USING_TOUCH'], CPPPATH = CPPPATH)

Return('group')