# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_280_456_DEMO'], CPPPATH = CPPPATH)

Return('group')
