# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('realgui/legacy', src, depend = ['CONFIG_REALTEK_BUILD_LEGACY_RTK_GUI'], CPPPATH = CPPPATH)

Return('group')
