from building import *
import os


src = []
inc = []
group = []

cwd = GetCurrentDir() # get current dir path


# check if .h or .hpp files exsit
def check_h_hpp_exsit(path):
    file_dirs = os.listdir(path)
    for file_dir in file_dirs:
        if os.path.splitext(file_dir)[1] in ['.h', '.hpp']:
            return True
    return False



inc = inc + [cwd]
for root, dirs, files in os.walk(cwd):
    for dir in dirs:
        current_path = os.path.join(root, dir)
        src = src + Glob(os.path.join(current_path,'*.cpp'))
        if check_h_hpp_exsit(current_path):
            inc = inc + [current_path]


LOCAL_CFLAGS = ' -std=c++14'

group = group + DefineGroup('LVGL-RLOTTIE', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_RLOTTIE'], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CFLAGS)


Return('group')
