# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]
CPPPATH += [cwd + '\\file_system_image']
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_448_368_DEMO_PAGE'], CPPPATH = CPPPATH)

Return('group')
