#if defined _WIN32
extern unsigned char resource_root[];

#define   BACKGROUND_BIN                          (void *)(resource_root + 0x000001b8)
#define   CAN_BIN                                 (void *)(resource_root + 0x00096df8)
#define   CANSKIN_BIN                             (void *)(resource_root + 0x0009ce38)
#define   CANSKIN_GREEN_BIN                       (void *)(resource_root + 0x000a2e78)
#define   CANSKIN_PURPLE_BIN                      (void *)(resource_root + 0x000a8eb8)
#define   CANSKIN_RED_BIN                         (void *)(resource_root + 0x000aeef8)
#define   CANSKIN_YELLOW_BIN                      (void *)(resource_root + 0x000b4f38)
#define   DROPLET_BIN                             (void *)(resource_root + 0x000baf78)
#define   FISH0_BIN                               (void *)(resource_root + 0x000bb2b8)
#define   FISH1_BIN                               (void *)(resource_root + 0x000bcaf8)
#define   FISH2_BIN                               (void *)(resource_root + 0x000be938)
#define   FISH3_BIN                               (void *)(resource_root + 0x000c14f8)
#define   FOREGROUND_BIN                          (void *)(resource_root + 0x000c4838)
#define   NUM0_BIN                                (void *)(resource_root + 0x0010a2f8)
#define   NUM1_BIN                                (void *)(resource_root + 0x0010b538)
#define   NUM2_BIN                                (void *)(resource_root + 0x0010c778)
#define   NUM3_BIN                                (void *)(resource_root + 0x0010d9b8)
#define   NUM4_BIN                                (void *)(resource_root + 0x0010ebf8)
#define   NUM5_BIN                                (void *)(resource_root + 0x0010fe38)
#define   NUM6_BIN                                (void *)(resource_root + 0x00111078)
#define   NUM7_BIN                                (void *)(resource_root + 0x001122b8)
#define   NUM8_BIN                                (void *)(resource_root + 0x001134f8)
#define   NUM9_BIN                                (void *)(resource_root + 0x00114738)
#define   WATERFACTOR_BIN                         (void *)(resource_root + 0x00115978)
#define   WATERFACTOR_BG_BIN                      (void *)(resource_root + 0x00115cb8)

#else
#define   BACKGROUND_BIN                          (void *)(0x0253e5b8)
#define   CAN_BIN                                 (void *)(0x025d51f8)
#define   CANSKIN_BIN                             (void *)(0x025db238)
#define   CANSKIN_GREEN_BIN                       (void *)(0x025e1278)
#define   CANSKIN_PURPLE_BIN                      (void *)(0x025e72b8)
#define   CANSKIN_RED_BIN                         (void *)(0x025ed2f8)
#define   CANSKIN_YELLOW_BIN                      (void *)(0x025f3338)
#define   DROPLET_BIN                             (void *)(0x025f9378)
#define   FISH0_BIN                               (void *)(0x025f96b8)
#define   FISH1_BIN                               (void *)(0x025faef8)
#define   FISH2_BIN                               (void *)(0x025fcd38)
#define   FISH3_BIN                               (void *)(0x025ff8f8)
#define   FOREGROUND_BIN                          (void *)(0x02602c38)
#define   NUM0_BIN                                (void *)(0x026486f8)
#define   NUM1_BIN                                (void *)(0x02649938)
#define   NUM2_BIN                                (void *)(0x0264ab78)
#define   NUM3_BIN                                (void *)(0x0264bdb8)
#define   NUM4_BIN                                (void *)(0x0264cff8)
#define   NUM5_BIN                                (void *)(0x0264e238)
#define   NUM6_BIN                                (void *)(0x0264f478)
#define   NUM7_BIN                                (void *)(0x026506b8)
#define   NUM8_BIN                                (void *)(0x026518f8)
#define   NUM9_BIN                                (void *)(0x02652b38)
#define   WATERFACTOR_BIN                         (void *)(0x02653d78)
#define   WATERFACTOR_BG_BIN                      (void *)(0x026540b8)

#endif
