#if defined _WIN32
extern unsigned char resource_root[];

#define   BACKGROUND_BIN                          (void *)(resource_root + 0x000001f8)
#define   CAN_BIN                                 (void *)(resource_root + 0x00096e38)
#define   CANSKIN_BIN                             (void *)(resource_root + 0x0009ce78)
#define   DROPLET_BIN                             (void *)(resource_root + 0x000a2eb8)
#define   FISH0_BIN                               (void *)(resource_root + 0x000a31f8)
#define   FISH1_BIN                               (void *)(resource_root + 0x000a4a38)
#define   FISH2_BIN                               (void *)(resource_root + 0x000a6878)
#define   FISH3_BIN                               (void *)(resource_root + 0x000a9438)
#define   FOREGROUND_BIN                          (void *)(resource_root + 0x000ac778)
#define   NUM0_BIN                                (void *)(resource_root + 0x000f2238)
#define   NUM1_BIN                                (void *)(resource_root + 0x000f3478)
#define   NUM2_BIN                                (void *)(resource_root + 0x000f46b8)
#define   NUM3_BIN                                (void *)(resource_root + 0x000f58f8)
#define   NUM4_BIN                                (void *)(resource_root + 0x000f6b38)
#define   NUM5_BIN                                (void *)(resource_root + 0x000f7d78)
#define   NUM6_BIN                                (void *)(resource_root + 0x000f8fb8)
#define   NUM7_BIN                                (void *)(resource_root + 0x000fa1f8)
#define   NUM8_BIN                                (void *)(resource_root + 0x000fb438)
#define   NUM9_BIN                                (void *)(resource_root + 0x000fc678)
#define   WATERFACTOR_BIN                         (void *)(resource_root + 0x000fd8b8)
#define   WATERFACTOR_BG_BIN                      (void *)(resource_root + 0x000fdbf8)
#define   BLUE_COLA_BIN                           (void *)(resource_root + 0x0014c6f8)
#define   GREEN_COLA_BIN                          (void *)(resource_root + 0x00151e38)
#define   ORANGE_COLA_BIN                         (void *)(resource_root + 0x00157578)
#define   PURPLE_COLA_BIN                         (void *)(resource_root + 0x0015ccb8)
#define   RED_BIN                                 (void *)(resource_root + 0x001623f8)
#define   RED_COLA_BIN                            (void *)(resource_root + 0x00167b38)
#define   YELLOW_COLA_BIN                         (void *)(resource_root + 0x0016d278)

#else
#define   BACKGROUND_BIN                          (void *)(0x0253e5f8)
#define   CAN_BIN                                 (void *)(0x025d5238)
#define   CANSKIN_BIN                             (void *)(0x025db278)
#define   DROPLET_BIN                             (void *)(0x025e12b8)
#define   FISH0_BIN                               (void *)(0x025e15f8)
#define   FISH1_BIN                               (void *)(0x025e2e38)
#define   FISH2_BIN                               (void *)(0x025e4c78)
#define   FISH3_BIN                               (void *)(0x025e7838)
#define   FOREGROUND_BIN                          (void *)(0x025eab78)
#define   NUM0_BIN                                (void *)(0x02630638)
#define   NUM1_BIN                                (void *)(0x02631878)
#define   NUM2_BIN                                (void *)(0x02632ab8)
#define   NUM3_BIN                                (void *)(0x02633cf8)
#define   NUM4_BIN                                (void *)(0x02634f38)
#define   NUM5_BIN                                (void *)(0x02636178)
#define   NUM6_BIN                                (void *)(0x026373b8)
#define   NUM7_BIN                                (void *)(0x026385f8)
#define   NUM8_BIN                                (void *)(0x02639838)
#define   NUM9_BIN                                (void *)(0x0263aa78)
#define   WATERFACTOR_BIN                         (void *)(0x0263bcb8)
#define   WATERFACTOR_BG_BIN                      (void *)(0x0263bff8)
#define   BLUE_COLA_BIN                           (void *)(0x0268aaf8)
#define   GREEN_COLA_BIN                          (void *)(0x02690238)
#define   ORANGE_COLA_BIN                         (void *)(0x02695978)
#define   PURPLE_COLA_BIN                         (void *)(0x0269b0b8)
#define   RED_BIN                                 (void *)(0x026a07f8)
#define   RED_COLA_BIN                            (void *)(0x026a5f38)
#define   YELLOW_COLA_BIN                         (void *)(0x026ab678)

#endif
