
Import('TOOL_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
""")

path = [cwd]
		

group = DefineGroup('MODULE_VG_LITE', src, depend = [''], CPPPATH = path)

Return('group')
