
from building import *

cwd = GetCurrentDir()
src = Split("""
""")


src = Glob('assets/*.c')


CPPPATH = [cwd,
           cwd + 'assets/']
CPPDEFINES = []




group = DefineGroup('lvgl_assets', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_V8'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
