#define   QUICKSAND_SEMIBOLD_TTF                  (void *)0x044000b4
#define   GBK_32_32_DOT_BIN                       (void *)0x04412f1c
#define   GBK_UNICODE_TABLE_BIN                   (void *)0x0472d13c
#define   TANGYUANTI_TTF                          (void *)0x0474d14c
#define   ACTIVITY_SVG                            (void *)0x04a0cbb4
#define   ALARM_SVG                               (void *)0x04a0dfd0
#define   CLOCK_BACKGROUND_SVG                    (void *)0x04a0eb8c
#define   CLOCK_SCALE_SVG                         (void *)0x04a10328
#define   CLOCK_SCALE_1_SVG                       (void *)0x04a12aac
#define   CONTACTS_SVG                            (void *)0x04a15a04
#define   FISH_SVG                                (void *)0x04a165fc
#define   HEARTRATE_SVG                           (void *)0x04a21dc4
#define   MESSAGE_SVG                             (void *)0x04a2291c
#define   MUSIC_SVG                               (void *)0x04a23394
#define   MUSIC_BIG_SVG                           (void *)0x04a23e60
#define   POINTER_HOUR_SVG                        (void *)0x04a245c0
#define   POINTER_HOUR_1_SVG                      (void *)0x04a24cdc
#define   POINTER_MINUTE_SVG                      (void *)0x04a25590
#define   POINTER_MINUTE_1_SVG                    (void *)0x04a25ca4
#define   POINTER_SECOND_SVG                      (void *)0x04a26580
#define   SETTING_SVG                             (void *)0x04a26cb0
#define   SLEEP_SVG                               (void *)0x04a274c4
#define   STEP_SVG                                (void *)0x04a27ebc
#define   TELEPHONE_SVG                           (void *)0x04a28e30
#define   TIME_SVG                                (void *)0x04a29980
#define   WAVE_HAIKEI_SVG                         (void *)0x04a2a1c4
#define   WEATHER_SVG                             (void *)0x04a2aa7c
#define   A1_SVG                                  (void *)0x04a2b95c
#define   A2_SVG                                  (void *)0x04a401a4
#define   A3_SVG                                  (void *)0x04a54b30
#define   A4_SVG                                  (void *)0x04a69648
#define   A5_SVG                                  (void *)0x04a7e2dc
#define   A6_SVG                                  (void *)0x04a930f0
#define   BACK_SVG                                (void *)0x04aa8078
#define   NEXT2_SVG                               (void *)0x04aa844c
#define   PALY2_SVG                               (void *)0x04aa8870
#define   PAUSE2_SVG                              (void *)0x04aa8ae0
#define   A1_BIN                                  (void *)0x04aa9034
#define   A2_BIN                                  (void *)0x04aaa3cc
#define   A3_BIN                                  (void *)0x04aab764
#define   A4_BIN                                  (void *)0x04aacafc
#define   A5_BIN                                  (void *)0x04aade94
#define   A6_BIN                                  (void *)0x04aaf22c
#define   C1_BIN                                  (void *)0x04ab05c4
#define   C2_BIN                                  (void *)0x04ad05d4
#define   C3_BIN                                  (void *)0x04af05e4
#define   C4_BIN                                  (void *)0x04b105f4
#define   C5_BIN                                  (void *)0x04b30604
#define   C6_BIN                                  (void *)0x04b50614
#define   CLOCK_BIN                               (void *)0x04b70628
#define   CRAB_LIME_BIN                           (void *)0x04b7a280
#define   EMAIL_BIN                               (void *)0x04b97a94
#define   MAP_BIN                                 (void *)0x04ba16e4
#define   RTL_ORIGIN_BIN                          (void *)0x04bab33c
#define   SLEEP_BIN                               (void *)0x04bc8b50
#define   SPORT_BIN                               (void *)0x04bd27a4
#define   WATCH_RED_BIN                           (void *)0x04bdc3fc
