#if defined _WIN32
extern unsigned char resource_root[];

#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(resource_root + 0x000004f8)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(resource_root + 0x0000a178)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(resource_root + 0x00039f38)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(resource_root + 0x000695f8)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(resource_root + 0x00098ef8)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(resource_root + 0x000c80b8)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(resource_root + 0x000f7778)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(resource_root + 0x001013f8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(resource_root + 0x001c17b8)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(resource_root + 0x001cb438)
#define   UI_TEXT_0_BIN                           (void *)(resource_root + 0x001cb6b8)
#define   UI_TEXT_1_BIN                           (void *)(resource_root + 0x001cd338)
#define   UI_TEXT_2_BIN                           (void *)(resource_root + 0x001ceb78)
#define   UI_TEXT_3_BIN                           (void *)(resource_root + 0x001d0878)
#define   UI_TEXT_4_BIN                           (void *)(resource_root + 0x001d25f8)
#define   UI_TEXT_5_BIN                           (void *)(resource_root + 0x001d44b8)
#define   UI_TEXT_6_BIN                           (void *)(resource_root + 0x001d6278)
#define   UI_TEXT_7_BIN                           (void *)(resource_root + 0x001d7ef8)
#define   UI_TEXT_8_BIN                           (void *)(resource_root + 0x001d9b38)
#define   UI_TEXT_9_BIN                           (void *)(resource_root + 0x001db8b8)
#define   UI_TEXT_COLON_BIN                       (void *)(resource_root + 0x001dd538)
#define   UI_TEXT_PERCENT_BIN                     (void *)(resource_root + 0x001ddbb8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(resource_root + 0x001e1078)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(resource_root + 0x001e21b8)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(resource_root + 0x001e30f8)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(resource_root + 0x001e4038)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(resource_root + 0x001e4f78)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(resource_root + 0x001e5db8)
#define   WATCHFACE_RING_BIN                      (void *)(resource_root + 0x002176f8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(resource_root + 0x002497f8)
#define   CONTROL_LTE_ON_BIN                      (void *)(resource_root + 0x0025f038)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(resource_root + 0x00274878)
#define   CONTROL_MUTE_ON_BIN                     (void *)(resource_root + 0x0028a0b8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(resource_root + 0x0029f8f8)
#define   CONTROL_PHONE_ON_BIN                    (void *)(resource_root + 0x002b5138)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(resource_root + 0x002ca978)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(resource_root + 0x002d0c38)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(resource_root + 0x002d6ef8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(resource_root + 0x002dd1b8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(resource_root + 0x003a61f8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(resource_root + 0x003b02f8)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(resource_root + 0x003b3c78)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(resource_root + 0x003b75f8)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(resource_root + 0x003baf78)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(resource_root + 0x003bfc38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(resource_root + 0x003c48f8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(resource_root + 0x003c95b8)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(resource_root + 0x003d1838)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(resource_root + 0x003d9ab8)
#define   GENERATE_IMAGE_LIST_PY                  (void *)(resource_root + 0x003e1d38)
#define   UI_ARROW_DOWN_BIN                       (void *)(resource_root + 0x003e2af8)
#define   UI_ARROW_UP_BIN                         (void *)(resource_root + 0x003e3b38)
#define   UI_BG_ICON_BIN                          (void *)(resource_root + 0x003e4b78)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(resource_root + 0x003ee7f8)
#define   UI_CARD_APP_BIN                         (void *)(resource_root + 0x0042a9b8)
#define   UI_CARD_APPVIEW_BIN                     (void *)(resource_root + 0x00460978)
#define   UI_CARD_CALENDAR_BIN                    (void *)(resource_root + 0x00476938)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x004ac8f8)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x004e64f8)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(resource_root + 0x0051c4b8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(resource_root + 0x00526138)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(resource_root + 0x0052fdb8)
#define   UI_IWATCH_ICON_BIN                      (void *)(resource_root + 0x00539a38)
#define   UI_LINE_STILL_BIN                       (void *)(resource_root + 0x0053a9b8)
#define   UI_MESSAGE_ICON_BIN                     (void *)(resource_root + 0x0053ae78)
#define   UI_PERSON_ICON_BIN                      (void *)(resource_root + 0x0053e178)
#define   W1SLICE1_BIN                            (void *)(resource_root + 0x0053e7f8)
#define   W2W_BIN                                 (void *)(resource_root + 0x006077f8)
#define   W3W_BIN                                 (void *)(resource_root + 0x006d07f8)
#define   W5BATTERY_BIN                           (void *)(resource_root + 0x00799838)
#define   W5W_BIN                                 (void *)(resource_root + 0x0079bdb8)
#define   WATCH_HOUR_HAND_BIN                     (void *)(resource_root + 0x00864df8)
#define   WATCH_MASK_BIN                          (void *)(resource_root + 0x00865cb8)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(resource_root + 0x00865f38)
#define   WATCH_SECOND_HAND_BIN                   (void *)(resource_root + 0x00867c38)

#else
#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(0x044004f8)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(0x0440a178)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(0x04439f38)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(0x044695f8)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(0x04498ef8)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(0x044c80b8)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(0x044f7778)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(0x045013f8)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(0x045c17b8)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(0x045cb438)
#define   UI_TEXT_0_BIN                           (void *)(0x045cb6b8)
#define   UI_TEXT_1_BIN                           (void *)(0x045cd338)
#define   UI_TEXT_2_BIN                           (void *)(0x045ceb78)
#define   UI_TEXT_3_BIN                           (void *)(0x045d0878)
#define   UI_TEXT_4_BIN                           (void *)(0x045d25f8)
#define   UI_TEXT_5_BIN                           (void *)(0x045d44b8)
#define   UI_TEXT_6_BIN                           (void *)(0x045d6278)
#define   UI_TEXT_7_BIN                           (void *)(0x045d7ef8)
#define   UI_TEXT_8_BIN                           (void *)(0x045d9b38)
#define   UI_TEXT_9_BIN                           (void *)(0x045db8b8)
#define   UI_TEXT_COLON_BIN                       (void *)(0x045dd538)
#define   UI_TEXT_PERCENT_BIN                     (void *)(0x045ddbb8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(0x045e1078)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(0x045e21b8)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(0x045e30f8)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(0x045e4038)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(0x045e4f78)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(0x045e5db8)
#define   WATCHFACE_RING_BIN                      (void *)(0x046176f8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(0x046497f8)
#define   CONTROL_LTE_ON_BIN                      (void *)(0x0465f038)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(0x04674878)
#define   CONTROL_MUTE_ON_BIN                     (void *)(0x0468a0b8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(0x0469f8f8)
#define   CONTROL_PHONE_ON_BIN                    (void *)(0x046b5138)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(0x046ca978)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(0x046d0c38)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(0x046d6ef8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(0x046dd1b8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(0x047a61f8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(0x047b02f8)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(0x047b3c78)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(0x047b75f8)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(0x047baf78)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(0x047bfc38)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(0x047c48f8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(0x047c95b8)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(0x047d1838)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(0x047d9ab8)
#define   GENERATE_IMAGE_LIST_PY                  (void *)(0x047e1d38)
#define   UI_ARROW_DOWN_BIN                       (void *)(0x047e2af8)
#define   UI_ARROW_UP_BIN                         (void *)(0x047e3b38)
#define   UI_BG_ICON_BIN                          (void *)(0x047e4b78)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(0x047ee7f8)
#define   UI_CARD_APP_BIN                         (void *)(0x0482a9b8)
#define   UI_CARD_APPVIEW_BIN                     (void *)(0x04860978)
#define   UI_CARD_CALENDAR_BIN                    (void *)(0x04876938)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x048ac8f8)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x048e64f8)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(0x0491c4b8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(0x04926138)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(0x0492fdb8)
#define   UI_IWATCH_ICON_BIN                      (void *)(0x04939a38)
#define   UI_LINE_STILL_BIN                       (void *)(0x0493a9b8)
#define   UI_MESSAGE_ICON_BIN                     (void *)(0x0493ae78)
#define   UI_PERSON_ICON_BIN                      (void *)(0x0493e178)
#define   W1SLICE1_BIN                            (void *)(0x0493e7f8)
#define   W2W_BIN                                 (void *)(0x04a077f8)
#define   W3W_BIN                                 (void *)(0x04ad07f8)
#define   W5BATTERY_BIN                           (void *)(0x04b99838)
#define   W5W_BIN                                 (void *)(0x04b9bdb8)
#define   WATCH_HOUR_HAND_BIN                     (void *)(0x04c64df8)
#define   WATCH_MASK_BIN                          (void *)(0x04c65cb8)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(0x04c65f38)
#define   WATCH_SECOND_HAND_BIN                   (void *)(0x04c67c38)

#endif
