#if defined _WIN32
extern unsigned char resource_root[];

#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(resource_root + 0x00000878)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(resource_root + 0x0000a4f8)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(resource_root + 0x0003a2b8)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(resource_root + 0x00069978)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(resource_root + 0x00099278)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(resource_root + 0x000c8438)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(resource_root + 0x000f7af8)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(resource_root + 0x00101778)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(resource_root + 0x001c1b38)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(resource_root + 0x001cb7b8)
#define   UI_TEXT_0_BIN                           (void *)(resource_root + 0x001cba38)
#define   UI_TEXT_1_BIN                           (void *)(resource_root + 0x001cd6b8)
#define   UI_TEXT_2_BIN                           (void *)(resource_root + 0x001ceef8)
#define   UI_TEXT_3_BIN                           (void *)(resource_root + 0x001d0bf8)
#define   UI_TEXT_4_BIN                           (void *)(resource_root + 0x001d2978)
#define   UI_TEXT_5_BIN                           (void *)(resource_root + 0x001d4838)
#define   UI_TEXT_6_BIN                           (void *)(resource_root + 0x001d65f8)
#define   UI_TEXT_7_BIN                           (void *)(resource_root + 0x001d8278)
#define   UI_TEXT_8_BIN                           (void *)(resource_root + 0x001d9eb8)
#define   UI_TEXT_9_BIN                           (void *)(resource_root + 0x001dbc38)
#define   UI_TEXT_COLON_BIN                       (void *)(resource_root + 0x001dd8b8)
#define   UI_TEXT_PERCENT_BIN                     (void *)(resource_root + 0x001ddf38)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(resource_root + 0x001e13f8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(resource_root + 0x001e2538)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(resource_root + 0x001e3478)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(resource_root + 0x001e43b8)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(resource_root + 0x001e52f8)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(resource_root + 0x001e6138)
#define   WATCHFACE_RING_BIN                      (void *)(resource_root + 0x00217a78)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN            (void *)(resource_root + 0x00249b78)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN             (void *)(resource_root + 0x0024d238)
#define   APP_MUSIC_BTN_LOOP_BIN                  (void *)(resource_root + 0x002508b8)
#define   APP_MUSIC_BTN_NEXT_BIN                  (void *)(resource_root + 0x002511f8)
#define   APP_MUSIC_BTN_PAUSE_BIN                 (void *)(resource_root + 0x00254e38)
#define   APP_MUSIC_BTN_PLAY_BIN                  (void *)(resource_root + 0x0025ad78)
#define   APP_MUSIC_BTN_PREV_BIN                  (void *)(resource_root + 0x00260cb8)
#define   APP_MUSIC_BTN_RND_BIN                   (void *)(resource_root + 0x002648f8)
#define   APP_MUSIC_CORNER_LEFT_BIN               (void *)(resource_root + 0x00265238)
#define   APP_MUSIC_CORNER_RIGHT_BIN              (void *)(resource_root + 0x00265778)
#define   APP_MUSIC_COVER_1_BIN                   (void *)(resource_root + 0x00265cb8)
#define   APP_MUSIC_COVER_2_BIN                   (void *)(resource_root + 0x00283e38)
#define   APP_MUSIC_COVER_3_BIN                   (void *)(resource_root + 0x002a1fb8)
#define   APP_MUSIC_ICN_CHART_BIN                 (void *)(resource_root + 0x002c0138)
#define   APP_MUSIC_ICN_CHAT_BIN                  (void *)(resource_root + 0x002c0a78)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN              (void *)(resource_root + 0x002c13b8)
#define   APP_MUSIC_ICN_HEART_BIN                 (void *)(resource_root + 0x002c1cf8)
#define   APP_MUSIC_ICN_SLIDER_BIN                (void *)(resource_root + 0x002c2638)
#define   APP_MUSIC_LIST_BORDER_BIN               (void *)(resource_root + 0x002c3bf8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN               (void *)(resource_root + 0x002c4d38)
#define   APP_MUSIC_WAVE_TOP_BIN                  (void *)(resource_root + 0x002cfff8)
#define   CAPSULE_MUTE_OFF_BIN                    (void *)(resource_root + 0x002db2b8)
#define   CAPSULE_MUTE_ON_BIN                     (void *)(resource_root + 0x002dbc78)
#define   CAPSULE_NOBOTHER_OFF_BIN                (void *)(resource_root + 0x002dc638)
#define   CAPSULE_NOBOTHER_ON_BIN                 (void *)(resource_root + 0x002dd678)
#define   CAPSULE_PHONE_OFF_BIN                   (void *)(resource_root + 0x002de6b8)
#define   CAPSULE_PHONE_ON_BIN                    (void *)(resource_root + 0x002df6f8)
#define   CLEAR_BG_BIN                            (void *)(resource_root + 0x002e0738)
#define   CONTROL_CAPSULE_BIN                     (void *)(resource_root + 0x002f84b8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(resource_root + 0x002fea38)
#define   CONTROL_LTE_ON_BIN                      (void *)(resource_root + 0x00314278)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(resource_root + 0x00329ab8)
#define   CONTROL_MUTE_ON_BIN                     (void *)(resource_root + 0x0033f2f8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(resource_root + 0x00354b38)
#define   CONTROL_PHONE_ON_BIN                    (void *)(resource_root + 0x0036a378)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(resource_root + 0x0037fbb8)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(resource_root + 0x003953f8)
#define   CONTROL_PAD_BIN                         (void *)(resource_root + 0x003aac38)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(resource_root + 0x003c0478)
#define   CONTROL_WIFI_ON_BIN                     (void *)(resource_root + 0x003d5cb8)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(resource_root + 0x003eb4f8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(resource_root + 0x003f17b8)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(resource_root + 0x003f7a78)
#define   FRUIT_NINJA_BG_BIN                      (void *)(resource_root + 0x003fdd38)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(resource_root + 0x004c6d78)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(resource_root + 0x004d0e78)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(resource_root + 0x004d47f8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(resource_root + 0x004d8178)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(resource_root + 0x004dbaf8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(resource_root + 0x004e07b8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(resource_root + 0x004e5478)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(resource_root + 0x004ea138)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(resource_root + 0x004f23b8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(resource_root + 0x004fa638)
#define   MENU_BAR_BG_BIN                         (void *)(resource_root + 0x00502878)
#define   MSG_TAB_BG_BIN                          (void *)(resource_root + 0x00536cb8)
#define   MUTE_OFF_ICON_BIN                       (void *)(resource_root + 0x00581ff8)
#define   MUTE_ON_ICON_BIN                        (void *)(resource_root + 0x005829b8)
#define   OPTION_BAR_BG_BIN                       (void *)(resource_root + 0x00583378)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(resource_root + 0x0059e938)
#define   OPTION_TAB_BG_BIN                       (void *)(resource_root + 0x005b9ef8)
#define   PATH02_BIN                              (void *)(resource_root + 0x005de778)
#define   PATH03_BIN                              (void *)(resource_root + 0x005deab8)
#define   PATH04_BIN                              (void *)(resource_root + 0x005defb8)
#define   PATH05_BIN                              (void *)(resource_root + 0x005df638)
#define   PATH06_BIN                              (void *)(resource_root + 0x005dfe38)
#define   PATH07_BIN                              (void *)(resource_root + 0x005e07b8)
#define   PATH08_BIN                              (void *)(resource_root + 0x005e12f8)
#define   PATH09_BIN                              (void *)(resource_root + 0x005e1fb8)
#define   PATH10_BIN                              (void *)(resource_root + 0x005e2df8)
#define   PATH11_BIN                              (void *)(resource_root + 0x005e3db8)
#define   PATH12_BIN                              (void *)(resource_root + 0x005e4f38)
#define   PATH13_BIN                              (void *)(resource_root + 0x005e6238)
#define   PATH14_BIN                              (void *)(resource_root + 0x005e76b8)
#define   PATH15_BIN                              (void *)(resource_root + 0x005e8cb8)
#define   PATH16_BIN                              (void *)(resource_root + 0x005ea478)
#define   PATH17_BIN                              (void *)(resource_root + 0x005ebdb8)
#define   PATH18_BIN                              (void *)(resource_root + 0x005ed878)
#define   UI_ARROW_DOWN_BIN                       (void *)(resource_root + 0x005ef4b8)
#define   UI_ARROW_UP_BIN                         (void *)(resource_root + 0x005f04f8)
#define   UI_BG_ICON_BIN                          (void *)(resource_root + 0x005f1538)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(resource_root + 0x005fb1b8)
#define   UI_CARD_APP_BIN                         (void *)(resource_root + 0x00637378)
#define   UI_CARD_APPVIEW_BIN                     (void *)(resource_root + 0x0066d338)
#define   UI_CARD_CALENDAR_BIN                    (void *)(resource_root + 0x006832f8)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x006b92b8)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x006f2eb8)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(resource_root + 0x00728e78)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(resource_root + 0x00732af8)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(resource_root + 0x0073c778)
#define   UI_IWATCH_ICON_BIN                      (void *)(resource_root + 0x007463f8)
#define   UI_LINE_STILL_BIN                       (void *)(resource_root + 0x00747378)
#define   UI_MESSAGE_ICON_BIN                     (void *)(resource_root + 0x00747838)
#define   UI_PERSON_ICON_BIN                      (void *)(resource_root + 0x0074ab38)
#define   W1SLICE1_BIN                            (void *)(resource_root + 0x0074b1b8)
#define   W2W_BIN                                 (void *)(resource_root + 0x008141b8)
#define   W3W_BIN                                 (void *)(resource_root + 0x008dd1b8)
#define   W5BATTERY_BIN                           (void *)(resource_root + 0x009a61f8)
#define   W5W_BIN                                 (void *)(resource_root + 0x009a8778)
#define   WATCH_HOUR_HAND_BIN                     (void *)(resource_root + 0x00a717b8)
#define   WATCH_MASK_BIN                          (void *)(resource_root + 0x00a72678)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(resource_root + 0x00a728f8)
#define   WATCH_SECOND_HAND_BIN                   (void *)(resource_root + 0x00a745f8)

#else
#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(0x0253ec78)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(0x025488f8)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(0x025786b8)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(0x025a7d78)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(0x025d7678)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(0x02606838)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(0x02635ef8)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(0x0263fb78)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(0x026fff38)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(0x02709bb8)
#define   UI_TEXT_0_BIN                           (void *)(0x02709e38)
#define   UI_TEXT_1_BIN                           (void *)(0x0270bab8)
#define   UI_TEXT_2_BIN                           (void *)(0x0270d2f8)
#define   UI_TEXT_3_BIN                           (void *)(0x0270eff8)
#define   UI_TEXT_4_BIN                           (void *)(0x02710d78)
#define   UI_TEXT_5_BIN                           (void *)(0x02712c38)
#define   UI_TEXT_6_BIN                           (void *)(0x027149f8)
#define   UI_TEXT_7_BIN                           (void *)(0x02716678)
#define   UI_TEXT_8_BIN                           (void *)(0x027182b8)
#define   UI_TEXT_9_BIN                           (void *)(0x0271a038)
#define   UI_TEXT_COLON_BIN                       (void *)(0x0271bcb8)
#define   UI_TEXT_PERCENT_BIN                     (void *)(0x0271c338)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(0x0271f7f8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(0x02720938)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(0x02721878)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(0x027227b8)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(0x027236f8)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(0x02724538)
#define   WATCHFACE_RING_BIN                      (void *)(0x02755e78)
#define   APP_MUSIC_BTN_LIST_PAUSE_BIN            (void *)(0x02787f78)
#define   APP_MUSIC_BTN_LIST_PLAY_BIN             (void *)(0x0278b638)
#define   APP_MUSIC_BTN_LOOP_BIN                  (void *)(0x0278ecb8)
#define   APP_MUSIC_BTN_NEXT_BIN                  (void *)(0x0278f5f8)
#define   APP_MUSIC_BTN_PAUSE_BIN                 (void *)(0x02793238)
#define   APP_MUSIC_BTN_PLAY_BIN                  (void *)(0x02799178)
#define   APP_MUSIC_BTN_PREV_BIN                  (void *)(0x0279f0b8)
#define   APP_MUSIC_BTN_RND_BIN                   (void *)(0x027a2cf8)
#define   APP_MUSIC_CORNER_LEFT_BIN               (void *)(0x027a3638)
#define   APP_MUSIC_CORNER_RIGHT_BIN              (void *)(0x027a3b78)
#define   APP_MUSIC_COVER_1_BIN                   (void *)(0x027a40b8)
#define   APP_MUSIC_COVER_2_BIN                   (void *)(0x027c2238)
#define   APP_MUSIC_COVER_3_BIN                   (void *)(0x027e03b8)
#define   APP_MUSIC_ICN_CHART_BIN                 (void *)(0x027fe538)
#define   APP_MUSIC_ICN_CHAT_BIN                  (void *)(0x027fee78)
#define   APP_MUSIC_ICN_DOWNLOAD_BIN              (void *)(0x027ff7b8)
#define   APP_MUSIC_ICN_HEART_BIN                 (void *)(0x028000f8)
#define   APP_MUSIC_ICN_SLIDER_BIN                (void *)(0x02800a38)
#define   APP_MUSIC_LIST_BORDER_BIN               (void *)(0x02801ff8)
#define   APP_MUSIC_WAVE_BOTTOM_BIN               (void *)(0x02803138)
#define   APP_MUSIC_WAVE_TOP_BIN                  (void *)(0x0280e3f8)
#define   CAPSULE_MUTE_OFF_BIN                    (void *)(0x028196b8)
#define   CAPSULE_MUTE_ON_BIN                     (void *)(0x0281a078)
#define   CAPSULE_NOBOTHER_OFF_BIN                (void *)(0x0281aa38)
#define   CAPSULE_NOBOTHER_ON_BIN                 (void *)(0x0281ba78)
#define   CAPSULE_PHONE_OFF_BIN                   (void *)(0x0281cab8)
#define   CAPSULE_PHONE_ON_BIN                    (void *)(0x0281daf8)
#define   CLEAR_BG_BIN                            (void *)(0x0281eb38)
#define   CONTROL_CAPSULE_BIN                     (void *)(0x028368b8)
#define   CONTROL_LTE_OFF_BIN                     (void *)(0x0283ce38)
#define   CONTROL_LTE_ON_BIN                      (void *)(0x02852678)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(0x02867eb8)
#define   CONTROL_MUTE_ON_BIN                     (void *)(0x0287d6f8)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(0x02892f38)
#define   CONTROL_PHONE_ON_BIN                    (void *)(0x028a8778)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(0x028bdfb8)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(0x028d37f8)
#define   CONTROL_PAD_BIN                         (void *)(0x028e9038)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(0x028fe878)
#define   CONTROL_WIFI_ON_BIN                     (void *)(0x029140b8)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(0x029298f8)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(0x0292fbb8)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(0x02935e78)
#define   FRUIT_NINJA_BG_BIN                      (void *)(0x0293c138)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(0x02a05178)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(0x02a0f278)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(0x02a12bf8)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(0x02a16578)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(0x02a19ef8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(0x02a1ebb8)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(0x02a23878)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(0x02a28538)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(0x02a307b8)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(0x02a38a38)
#define   MENU_BAR_BG_BIN                         (void *)(0x02a40c78)
#define   MSG_TAB_BG_BIN                          (void *)(0x02a750b8)
#define   MUTE_OFF_ICON_BIN                       (void *)(0x02ac03f8)
#define   MUTE_ON_ICON_BIN                        (void *)(0x02ac0db8)
#define   OPTION_BAR_BG_BIN                       (void *)(0x02ac1778)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(0x02adcd38)
#define   OPTION_TAB_BG_BIN                       (void *)(0x02af82f8)
#define   PATH02_BIN                              (void *)(0x02b1cb78)
#define   PATH03_BIN                              (void *)(0x02b1ceb8)
#define   PATH04_BIN                              (void *)(0x02b1d3b8)
#define   PATH05_BIN                              (void *)(0x02b1da38)
#define   PATH06_BIN                              (void *)(0x02b1e238)
#define   PATH07_BIN                              (void *)(0x02b1ebb8)
#define   PATH08_BIN                              (void *)(0x02b1f6f8)
#define   PATH09_BIN                              (void *)(0x02b203b8)
#define   PATH10_BIN                              (void *)(0x02b211f8)
#define   PATH11_BIN                              (void *)(0x02b221b8)
#define   PATH12_BIN                              (void *)(0x02b23338)
#define   PATH13_BIN                              (void *)(0x02b24638)
#define   PATH14_BIN                              (void *)(0x02b25ab8)
#define   PATH15_BIN                              (void *)(0x02b270b8)
#define   PATH16_BIN                              (void *)(0x02b28878)
#define   PATH17_BIN                              (void *)(0x02b2a1b8)
#define   PATH18_BIN                              (void *)(0x02b2bc78)
#define   UI_ARROW_DOWN_BIN                       (void *)(0x02b2d8b8)
#define   UI_ARROW_UP_BIN                         (void *)(0x02b2e8f8)
#define   UI_BG_ICON_BIN                          (void *)(0x02b2f938)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(0x02b395b8)
#define   UI_CARD_APP_BIN                         (void *)(0x02b75778)
#define   UI_CARD_APPVIEW_BIN                     (void *)(0x02bab738)
#define   UI_CARD_CALENDAR_BIN                    (void *)(0x02bc16f8)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x02bf76b8)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x02c312b8)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(0x02c67278)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(0x02c70ef8)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(0x02c7ab78)
#define   UI_IWATCH_ICON_BIN                      (void *)(0x02c847f8)
#define   UI_LINE_STILL_BIN                       (void *)(0x02c85778)
#define   UI_MESSAGE_ICON_BIN                     (void *)(0x02c85c38)
#define   UI_PERSON_ICON_BIN                      (void *)(0x02c88f38)
#define   W1SLICE1_BIN                            (void *)(0x02c895b8)
#define   W2W_BIN                                 (void *)(0x02d525b8)
#define   W3W_BIN                                 (void *)(0x02e1b5b8)
#define   W5BATTERY_BIN                           (void *)(0x02ee45f8)
#define   W5W_BIN                                 (void *)(0x02ee6b78)
#define   WATCH_HOUR_HAND_BIN                     (void *)(0x02fafbb8)
#define   WATCH_MASK_BIN                          (void *)(0x02fb0a78)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(0x02fb0cf8)
#define   WATCH_SECOND_HAND_BIN                   (void *)(0x02fb29f8)

#endif
