#if defined _WIN32
extern unsigned char resource_root[];

#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(resource_root + 0x00000738)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(resource_root + 0x0000a3b8)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(resource_root + 0x0003a178)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(resource_root + 0x00069838)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(resource_root + 0x00099138)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(resource_root + 0x000c82f8)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(resource_root + 0x000f79b8)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(resource_root + 0x00101638)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(resource_root + 0x001c19f8)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(resource_root + 0x001cb678)
#define   UI_TEXT_0_BIN                           (void *)(resource_root + 0x001cb8f8)
#define   UI_TEXT_1_BIN                           (void *)(resource_root + 0x001cd578)
#define   UI_TEXT_2_BIN                           (void *)(resource_root + 0x001cedb8)
#define   UI_TEXT_3_BIN                           (void *)(resource_root + 0x001d0ab8)
#define   UI_TEXT_4_BIN                           (void *)(resource_root + 0x001d2838)
#define   UI_TEXT_5_BIN                           (void *)(resource_root + 0x001d46f8)
#define   UI_TEXT_6_BIN                           (void *)(resource_root + 0x001d64b8)
#define   UI_TEXT_7_BIN                           (void *)(resource_root + 0x001d8138)
#define   UI_TEXT_8_BIN                           (void *)(resource_root + 0x001d9d78)
#define   UI_TEXT_9_BIN                           (void *)(resource_root + 0x001dbaf8)
#define   UI_TEXT_COLON_BIN                       (void *)(resource_root + 0x001dd778)
#define   UI_TEXT_PERCENT_BIN                     (void *)(resource_root + 0x001dddf8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(resource_root + 0x001e12b8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(resource_root + 0x001e23f8)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(resource_root + 0x001e3338)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(resource_root + 0x001e4278)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(resource_root + 0x001e51b8)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(resource_root + 0x001e5ff8)
#define   WATCHFACE_RING_BIN                      (void *)(resource_root + 0x00217938)
#define   CLEAR_BG_BIN                            (void *)(resource_root + 0x00249a38)
#define   CONTROL_LTE_OFF_BIN                     (void *)(resource_root + 0x002617b8)
#define   CONTROL_LTE_ON_BIN                      (void *)(resource_root + 0x00276ff8)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(resource_root + 0x0028c838)
#define   CONTROL_MUTE_ON_BIN                     (void *)(resource_root + 0x002a2078)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(resource_root + 0x002b78b8)
#define   CONTROL_PHONE_ON_BIN                    (void *)(resource_root + 0x002cd0f8)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(resource_root + 0x002e2938)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(resource_root + 0x002f8178)
#define   CONTROL_PAD_BIN                         (void *)(resource_root + 0x0030d9b8)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(resource_root + 0x003231f8)
#define   CONTROL_WIFI_ON_BIN                     (void *)(resource_root + 0x00338a38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(resource_root + 0x0034e278)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(resource_root + 0x00354538)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(resource_root + 0x0035a7f8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(resource_root + 0x00360ab8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(resource_root + 0x00429af8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(resource_root + 0x00433bf8)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(resource_root + 0x00437578)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(resource_root + 0x0043aef8)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(resource_root + 0x0043e878)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(resource_root + 0x00443538)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(resource_root + 0x004481f8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(resource_root + 0x0044ceb8)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(resource_root + 0x00455138)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(resource_root + 0x0045d3b8)
#define   GENERATE_IMAGE_LIST_PY                  (void *)(resource_root + 0x00465638)
#define   MENU_BAR_BG_BIN                         (void *)(resource_root + 0x004663f8)
#define   MSG_TAB_BG_BIN                          (void *)(resource_root + 0x0049a838)
#define   MUTE_OFF_ICON_BIN                       (void *)(resource_root + 0x004e5b78)
#define   MUTE_ON_ICON_BIN                        (void *)(resource_root + 0x004e6538)
#define   NOBOTHER_OFF_ICON_BIN                   (void *)(resource_root + 0x004e6ef8)
#define   NOBOTHER_ON_ICON_BIN                    (void *)(resource_root + 0x004e7f38)
#define   OPTION_BAR_BG_BIN                       (void *)(resource_root + 0x004e8f78)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(resource_root + 0x00504538)
#define   OPTION_TAB_BG_BIN                       (void *)(resource_root + 0x0051faf8)
#define   PATH02_BIN                              (void *)(resource_root + 0x00544378)
#define   PATH03_BIN                              (void *)(resource_root + 0x005446b8)
#define   PATH04_BIN                              (void *)(resource_root + 0x00544bb8)
#define   PATH05_BIN                              (void *)(resource_root + 0x00545238)
#define   PATH06_BIN                              (void *)(resource_root + 0x00545a38)
#define   PATH07_BIN                              (void *)(resource_root + 0x005463b8)
#define   PATH08_BIN                              (void *)(resource_root + 0x00546ef8)
#define   PATH09_BIN                              (void *)(resource_root + 0x00547bb8)
#define   PATH10_BIN                              (void *)(resource_root + 0x005489f8)
#define   PATH11_BIN                              (void *)(resource_root + 0x005499b8)
#define   PATH12_BIN                              (void *)(resource_root + 0x0054ab38)
#define   PATH13_BIN                              (void *)(resource_root + 0x0054be38)
#define   PATH14_BIN                              (void *)(resource_root + 0x0054d2b8)
#define   PATH15_BIN                              (void *)(resource_root + 0x0054e8b8)
#define   PATH16_BIN                              (void *)(resource_root + 0x00550078)
#define   PATH17_BIN                              (void *)(resource_root + 0x005519b8)
#define   PATH18_BIN                              (void *)(resource_root + 0x00553478)
#define   PHONE_OFF_ICON_BIN                      (void *)(resource_root + 0x005550b8)
#define   PHONE_ON_ICON_BIN                       (void *)(resource_root + 0x005560f8)
#define   UI_ARROW_DOWN_BIN                       (void *)(resource_root + 0x00557138)
#define   UI_ARROW_UP_BIN                         (void *)(resource_root + 0x00558178)
#define   UI_BG_ICON_BIN                          (void *)(resource_root + 0x005591b8)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(resource_root + 0x00562e38)
#define   UI_CARD_APP_BIN                         (void *)(resource_root + 0x0059eff8)
#define   UI_CARD_APPVIEW_BIN                     (void *)(resource_root + 0x005d4fb8)
#define   UI_CARD_CALENDAR_BIN                    (void *)(resource_root + 0x005eaf78)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(resource_root + 0x00620f38)
#define   UI_CARD_WEATHER_BIN                     (void *)(resource_root + 0x0065ab38)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(resource_root + 0x00690af8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(resource_root + 0x0069a778)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(resource_root + 0x006a43f8)
#define   UI_IWATCH_ICON_BIN                      (void *)(resource_root + 0x006ae078)
#define   UI_LINE_STILL_BIN                       (void *)(resource_root + 0x006aeff8)
#define   UI_MESSAGE_ICON_BIN                     (void *)(resource_root + 0x006af4b8)
#define   UI_PERSON_ICON_BIN                      (void *)(resource_root + 0x006b27b8)
#define   W1SLICE1_BIN                            (void *)(resource_root + 0x006b2e38)
#define   W2W_BIN                                 (void *)(resource_root + 0x0077be38)
#define   W3W_BIN                                 (void *)(resource_root + 0x00844e38)
#define   W5BATTERY_BIN                           (void *)(resource_root + 0x0090de78)
#define   W5W_BIN                                 (void *)(resource_root + 0x009103f8)
#define   WATCH_HOUR_HAND_BIN                     (void *)(resource_root + 0x009d9438)
#define   WATCH_MASK_BIN                          (void *)(resource_root + 0x009da2f8)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(resource_root + 0x009da578)
#define   WATCH_SECOND_HAND_BIN                   (void *)(resource_root + 0x009dc278)

#else
#define   UI_CLOCK_ACTIVITY_ICON_BIN              (void *)(0x0253eb38)
#define   UI_CLOCK_CARD_ALARM_BIN                 (void *)(0x025487b8)
#define   UI_CLOCK_CARD_COMPASS_BIN               (void *)(0x02578578)
#define   UI_CLOCK_CARD_MUSIC_BIN                 (void *)(0x025a7c38)
#define   UI_CLOCK_CARD_WEATHER_BIN               (void *)(0x025d7538)
#define   UI_CLOCK_CARD_WORKOUT_BIN               (void *)(0x026066f8)
#define   UI_CLOCK_COMPASS_DIAL_ICON_BIN          (void *)(0x02635db8)
#define   UI_CLOCK_FACE_MAIN_BIN                  (void *)(0x0263fa38)
#define   UI_CLOCK_HEARTRATE_ICON_BIN             (void *)(0x026ffdf8)
#define   UI_CLOCK_COMPASS_POINTER_ICON_BIN       (void *)(0x02709a78)
#define   UI_TEXT_0_BIN                           (void *)(0x02709cf8)
#define   UI_TEXT_1_BIN                           (void *)(0x0270b978)
#define   UI_TEXT_2_BIN                           (void *)(0x0270d1b8)
#define   UI_TEXT_3_BIN                           (void *)(0x0270eeb8)
#define   UI_TEXT_4_BIN                           (void *)(0x02710c38)
#define   UI_TEXT_5_BIN                           (void *)(0x02712af8)
#define   UI_TEXT_6_BIN                           (void *)(0x027148b8)
#define   UI_TEXT_7_BIN                           (void *)(0x02716538)
#define   UI_TEXT_8_BIN                           (void *)(0x02718178)
#define   UI_TEXT_9_BIN                           (void *)(0x02719ef8)
#define   UI_TEXT_COLON_BIN                       (void *)(0x0271bb78)
#define   UI_TEXT_PERCENT_BIN                     (void *)(0x0271c1f8)
#define   UI_WEATHER_CLOUDY_BIN                   (void *)(0x0271f6b8)
#define   UI_WEATHER_RAIN_L_BIN                   (void *)(0x027207f8)
#define   UI_WEATHER_RAIN_M_BIN                   (void *)(0x02721738)
#define   UI_WEATHER_RAIN_S_BIN                   (void *)(0x02722678)
#define   UI_WEATHER_SUNNY_BIN                    (void *)(0x027235b8)
#define   WATCHFACE_BUTTERFLY_BIN                 (void *)(0x027243f8)
#define   WATCHFACE_RING_BIN                      (void *)(0x02755d38)
#define   CLEAR_BG_BIN                            (void *)(0x02787e38)
#define   CONTROL_LTE_OFF_BIN                     (void *)(0x0279fbb8)
#define   CONTROL_LTE_ON_BIN                      (void *)(0x027b53f8)
#define   CONTROL_MUTE_OFF_BIN                    (void *)(0x027cac38)
#define   CONTROL_MUTE_ON_BIN                     (void *)(0x027e0478)
#define   CONTROL_PHONE_OFF_BIN                   (void *)(0x027f5cb8)
#define   CONTROL_PHONE_ON_BIN                    (void *)(0x0280b4f8)
#define   CONTROL_NOBOTHER_OFF_BIN                (void *)(0x02820d38)
#define   CONTROL_NOBOTHER_ON_BIN                 (void *)(0x02836578)
#define   CONTROL_PAD_BIN                         (void *)(0x0284bdb8)
#define   CONTROL_WIFI_OFF_BIN                    (void *)(0x028615f8)
#define   CONTROL_WIFI_ON_BIN                     (void *)(0x02876e38)
#define   FRUIT_NINJA_BANANA_BIN                  (void *)(0x0288c678)
#define   FRUIT_NINJA_BANANA_HALF_1_BIN           (void *)(0x02892938)
#define   FRUIT_NINJA_BANANA_HALF_2_BIN           (void *)(0x02898bf8)
#define   FRUIT_NINJA_BG_BIN                      (void *)(0x0289eeb8)
#define   FRUIT_NINJA_BOMB_BIN                    (void *)(0x02967ef8)
#define   FRUIT_NINJA_PEACH_BIN                   (void *)(0x02971ff8)
#define   FRUIT_NINJA_PEACH_HALF_1_BIN            (void *)(0x02975978)
#define   FRUIT_NINJA_PEACH_HALF_2_BIN            (void *)(0x029792f8)
#define   FRUIT_NINJA_STRAWBERRY_BIN              (void *)(0x0297cc78)
#define   FRUIT_NINJA_STRAWBERRY_HALF_1_BIN       (void *)(0x02981938)
#define   FRUIT_NINJA_STRAWBERRY_HALF_2_BIN       (void *)(0x029865f8)
#define   FRUIT_NINJA_WATERMELON_BIN              (void *)(0x0298b2b8)
#define   FRUIT_NINJA_WATERMELON_HALF_1_BIN       (void *)(0x02993538)
#define   FRUIT_NINJA_WATERMELON_HALF_2_BIN       (void *)(0x0299b7b8)
#define   GENERATE_IMAGE_LIST_PY                  (void *)(0x029a3a38)
#define   MENU_BAR_BG_BIN                         (void *)(0x029a47f8)
#define   MSG_TAB_BG_BIN                          (void *)(0x029d8c38)
#define   MUTE_OFF_ICON_BIN                       (void *)(0x02a23f78)
#define   MUTE_ON_ICON_BIN                        (void *)(0x02a24938)
#define   NOBOTHER_OFF_ICON_BIN                   (void *)(0x02a252f8)
#define   NOBOTHER_ON_ICON_BIN                    (void *)(0x02a26338)
#define   OPTION_BAR_BG_BIN                       (void *)(0x02a27378)
#define   OPTION_BAR_WHITE_BG_BIN                 (void *)(0x02a42938)
#define   OPTION_TAB_BG_BIN                       (void *)(0x02a5def8)
#define   PATH02_BIN                              (void *)(0x02a82778)
#define   PATH03_BIN                              (void *)(0x02a82ab8)
#define   PATH04_BIN                              (void *)(0x02a82fb8)
#define   PATH05_BIN                              (void *)(0x02a83638)
#define   PATH06_BIN                              (void *)(0x02a83e38)
#define   PATH07_BIN                              (void *)(0x02a847b8)
#define   PATH08_BIN                              (void *)(0x02a852f8)
#define   PATH09_BIN                              (void *)(0x02a85fb8)
#define   PATH10_BIN                              (void *)(0x02a86df8)
#define   PATH11_BIN                              (void *)(0x02a87db8)
#define   PATH12_BIN                              (void *)(0x02a88f38)
#define   PATH13_BIN                              (void *)(0x02a8a238)
#define   PATH14_BIN                              (void *)(0x02a8b6b8)
#define   PATH15_BIN                              (void *)(0x02a8ccb8)
#define   PATH16_BIN                              (void *)(0x02a8e478)
#define   PATH17_BIN                              (void *)(0x02a8fdb8)
#define   PATH18_BIN                              (void *)(0x02a91878)
#define   PHONE_OFF_ICON_BIN                      (void *)(0x02a934b8)
#define   PHONE_ON_ICON_BIN                       (void *)(0x02a944f8)
#define   UI_ARROW_DOWN_BIN                       (void *)(0x02a95538)
#define   UI_ARROW_UP_BIN                         (void *)(0x02a96578)
#define   UI_BG_ICON_BIN                          (void *)(0x02a975b8)
#define   UI_CARD_ACTIVITY_BIN                    (void *)(0x02aa1238)
#define   UI_CARD_APP_BIN                         (void *)(0x02add3f8)
#define   UI_CARD_APPVIEW_BIN                     (void *)(0x02b133b8)
#define   UI_CARD_CALENDAR_BIN                    (void *)(0x02b29378)
#define   UI_CARD_CLOCKCIRCLE_BIN                 (void *)(0x02b5f338)
#define   UI_CARD_WEATHER_BIN                     (void *)(0x02b98f38)
#define   UI_CLOCK_FRUIT_NINJA_ICON_BIN           (void *)(0x02bceef8)
#define   UI_CLOCK_MUSIC_ICON_BIN                 (void *)(0x02bd8b78)
#define   UI_CLOCK_BOX2D_RING_ICON_BIN            (void *)(0x02be27f8)
#define   UI_IWATCH_ICON_BIN                      (void *)(0x02bec478)
#define   UI_LINE_STILL_BIN                       (void *)(0x02bed3f8)
#define   UI_MESSAGE_ICON_BIN                     (void *)(0x02bed8b8)
#define   UI_PERSON_ICON_BIN                      (void *)(0x02bf0bb8)
#define   W1SLICE1_BIN                            (void *)(0x02bf1238)
#define   W2W_BIN                                 (void *)(0x02cba238)
#define   W3W_BIN                                 (void *)(0x02d83238)
#define   W5BATTERY_BIN                           (void *)(0x02e4c278)
#define   W5W_BIN                                 (void *)(0x02e4e7f8)
#define   WATCH_HOUR_HAND_BIN                     (void *)(0x02f17838)
#define   WATCH_MASK_BIN                          (void *)(0x02f186f8)
#define   WATCH_MINUTE_HAND_BIN                   (void *)(0x02f18978)
#define   WATCH_SECOND_HAND_BIN                   (void *)(0x02f1a678)

#endif
