
from building import *

cwd = GetCurrentDir()
src = Split("""
""")


src += [cwd + '/base/nanovg_port.c']
src += [cwd + '/base/nanovg.c']
src += [cwd + '/agge/math.cpp']
src += [cwd + '/agge/stroke.cpp']
src += [cwd + '/agge/stroke_features.cpp']
src += [cwd + '/agge/vector_rasterizer.cpp']
src += [cwd + '/agge/nanovg_agge.cpp']
src += [cwd + '/agge/nanovg_vertex.cpp']

path = [cwd,
        cwd + '/agge', 
        cwd + '/base']

objs = DefineGroup('realgui/3rd', src, depend = [''], CPPPATH = path)

Return('objs')
