#if defined _WIN32
extern unsigned char resource_root[1024 * 1024 * 20];

#define   ACTIVITY_BIN                            (void *)(resource_root + 0x000002f8)
#define   BLOODOXYGEN_BIN                         (void *)(resource_root + 0x000a1338)
#define   CLOCKN_BIN                              (void *)(resource_root + 0x00142378)
#define   CONTROLMENU_0_BIN                       (void *)(resource_root + 0x001e33b8)
#define   CONTROLMENU_1_BIN                       (void *)(resource_root + 0x002843f8)
#define   HEARTRATE_BIN                           (void *)(resource_root + 0x00325438)
#define   MESSAGE_BIN                             (void *)(resource_root + 0x003c6478)
#define   MUSIC_BIN                               (void *)(resource_root + 0x004674b8)
#define   QUICKCARD_BIN                           (void *)(resource_root + 0x005084f8)
#define   SLEEPN_BIN                              (void *)(resource_root + 0x005a9538)
#define   STRESS_BIN                              (void *)(resource_root + 0x0064a578)
#define   WEATHER_BIN                             (void *)(resource_root + 0x006eb5b8)
#define   ALARM_CLOCK_OFF_BIN                     (void *)(resource_root + 0x0078c5f8)
#define   ALARM_CLOCK_ON_BIN                      (void *)(resource_root + 0x0079c8f8)
#define   BRIGHT_OFF_BIN                          (void *)(resource_root + 0x007acbf8)
#define   BRIGHT_ON_BIN                           (void *)(resource_root + 0x007bcef8)
#define   C1_BIN                                  (void *)(resource_root + 0x007cd1f8)
#define   C2_BIN                                  (void *)(resource_root + 0x007ed238)
#define   C3_BIN                                  (void *)(resource_root + 0x0080d278)
#define   C4_BIN                                  (void *)(resource_root + 0x0082d2b8)
#define   C5_BIN                                  (void *)(resource_root + 0x0084d2f8)
#define   C6_BIN                                  (void *)(resource_root + 0x0086d338)
#define   CALL_OFF_BIN                            (void *)(resource_root + 0x0088d378)
#define   CALL_ON_BIN                             (void *)(resource_root + 0x0089d678)
#define   EMOTION_OFF_BIN                         (void *)(resource_root + 0x008ad978)
#define   EMOTION_ON_BIN                          (void *)(resource_root + 0x008bdc78)
#define   FLASHLIGHT_OFF_BIN                      (void *)(resource_root + 0x008cdf78)
#define   FLASHLIGHT_ON_BIN                       (void *)(resource_root + 0x008de278)
#define   HARMONYOS_SIZE24_BITS1_FONT_BIN         (void *)(resource_root + 0x008ee5b8)
#define   NO_DISTURB_OFF_BIN                      (void *)(resource_root + 0x00dce5b8)
#define   NO_DISTURB_ON_BIN                       (void *)(resource_root + 0x00dde8b8)
#define   NOTICE_OFF_BIN                          (void *)(resource_root + 0x00deebb8)
#define   NOTICE_ON_BIN                           (void *)(resource_root + 0x00dfeeb8)
#define   RING_OFF_BIN                            (void *)(resource_root + 0x00e0f1b8)
#define   RING_ON_BIN                             (void *)(resource_root + 0x00e1f4b8)
#define   SET_OFF_BIN                             (void *)(resource_root + 0x00e2f7b8)
#define   SET_ON_BIN                              (void *)(resource_root + 0x00e3fab8)
#define   SIGNAL_OFF_BIN                          (void *)(resource_root + 0x00e4fdb8)
#define   SIGNAL_ON_BIN                           (void *)(resource_root + 0x00e600b8)
#define   VIBRATE_OFF_BIN                         (void *)(resource_root + 0x00e703b8)
#define   VIBRATE_ON_BIN                          (void *)(resource_root + 0x00e806b8)
#define   WATCH_OFF_BIN                           (void *)(resource_root + 0x00e909b8)
#define   WATCH_ON_BIN                            (void *)(resource_root + 0x00ea0cb8)

#else
#define   ACTIVITY_BIN                            (void *)(0x044002f8)
#define   BLOODOXYGEN_BIN                         (void *)(0x044a1338)
#define   CLOCKN_BIN                              (void *)(0x04542378)
#define   CONTROLMENU_0_BIN                       (void *)(0x045e33b8)
#define   CONTROLMENU_1_BIN                       (void *)(0x046843f8)
#define   HEARTRATE_BIN                           (void *)(0x04725438)
#define   MESSAGE_BIN                             (void *)(0x047c6478)
#define   MUSIC_BIN                               (void *)(0x048674b8)
#define   QUICKCARD_BIN                           (void *)(0x049084f8)
#define   SLEEPN_BIN                              (void *)(0x049a9538)
#define   STRESS_BIN                              (void *)(0x04a4a578)
#define   WEATHER_BIN                             (void *)(0x04aeb5b8)
#define   ALARM_CLOCK_OFF_BIN                     (void *)(0x04b8c5f8)
#define   ALARM_CLOCK_ON_BIN                      (void *)(0x04b9c8f8)
#define   BRIGHT_OFF_BIN                          (void *)(0x04bacbf8)
#define   BRIGHT_ON_BIN                           (void *)(0x04bbcef8)
#define   C1_BIN                                  (void *)(0x04bcd1f8)
#define   C2_BIN                                  (void *)(0x04bed238)
#define   C3_BIN                                  (void *)(0x04c0d278)
#define   C4_BIN                                  (void *)(0x04c2d2b8)
#define   C5_BIN                                  (void *)(0x04c4d2f8)
#define   C6_BIN                                  (void *)(0x04c6d338)
#define   CALL_OFF_BIN                            (void *)(0x04c8d378)
#define   CALL_ON_BIN                             (void *)(0x04c9d678)
#define   EMOTION_OFF_BIN                         (void *)(0x04cad978)
#define   EMOTION_ON_BIN                          (void *)(0x04cbdc78)
#define   FLASHLIGHT_OFF_BIN                      (void *)(0x04ccdf78)
#define   FLASHLIGHT_ON_BIN                       (void *)(0x04cde278)
#define   HARMONYOS_SIZE24_BITS1_FONT_BIN         (void *)(0x04cee5b8)
#define   NO_DISTURB_OFF_BIN                      (void *)(0x051ce5b8)
#define   NO_DISTURB_ON_BIN                       (void *)(0x051de8b8)
#define   NOTICE_OFF_BIN                          (void *)(0x051eebb8)
#define   NOTICE_ON_BIN                           (void *)(0x051feeb8)
#define   RING_OFF_BIN                            (void *)(0x0520f1b8)
#define   RING_ON_BIN                             (void *)(0x0521f4b8)
#define   SET_OFF_BIN                             (void *)(0x0522f7b8)
#define   SET_ON_BIN                              (void *)(0x0523fab8)
#define   SIGNAL_OFF_BIN                          (void *)(0x0524fdb8)
#define   SIGNAL_ON_BIN                           (void *)(0x052600b8)
#define   VIBRATE_OFF_BIN                         (void *)(0x052703b8)
#define   VIBRATE_ON_BIN                          (void *)(0x052806b8)
#define   WATCH_OFF_BIN                           (void *)(0x052909b8)
#define   WATCH_ON_BIN                            (void *)(0x052a0cb8)

#endif
