# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd]

src = Glob('*.c') + Glob('*.cpp')

if GetDepend(['']):
    objs = DefineGroup('widget', src, depend = [''], CPPPATH = inc)
else:
    objs = []

Return('objs')
