#if defined _WIN32
extern unsigned char resource_root[];

#define   AURACAST_BIN                            (void *)(resource_root + 0x00000178)
#define   TABLE1_BLANK_BIN                        (void *)(resource_root + 0x0000a3b8)
#define   TABLE2_BLANK_BIN                        (void *)(resource_root + 0x0002f838)
#define   VOL_DEC_BIN                             (void *)(resource_root + 0x000532f8)
#define   VOL_DEC_BLUE_BIN                        (void *)(resource_root + 0x00056778)
#define   VOL_INC_BIN                             (void *)(resource_root + 0x00059bb8)
#define   VOL_INC_BLUE_BIN                        (void *)(resource_root + 0x0005d038)
#define   BACKGROUND_BIN                          (void *)(resource_root + 0x000604b8)
#define   BUTTON_BIN                              (void *)(resource_root + 0x0009c9f8)
#define   BUTTON_ON_BIN                           (void *)(resource_root + 0x000a1f78)
#define   CONN_BIN                                (void *)(resource_root + 0x000a74f8)
#define   CONN_BLUE_BIN                           (void *)(resource_root + 0x000aa978)
#define   DISC_BIN                                (void *)(resource_root + 0x000addb8)
#define   DISC_BLUE_BIN                           (void *)(resource_root + 0x000b1238)
#define   GBK_32_32_DOT_BIN                       (void *)(resource_root + 0x000b46b8)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(resource_root + 0x003ce8f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x003ee938)
#define   OVERLAP_BIN                             (void *)(resource_root + 0x00407c78)
#define   SCAN_BIN                                (void *)(resource_root + 0x00417338)
#define   SCAN_BLUE_BIN                           (void *)(resource_root + 0x0041a7b8)

#else
#define   AURACAST_BIN                            (void *)(0x0c000178)
#define   TABLE1_BLANK_BIN                        (void *)(0x0c00a3b8)
#define   TABLE2_BLANK_BIN                        (void *)(0x0c02f838)
#define   VOL_DEC_BIN                             (void *)(0x0c0532f8)
#define   VOL_DEC_BLUE_BIN                        (void *)(0x0c056778)
#define   VOL_INC_BIN                             (void *)(0x0c059bb8)
#define   VOL_INC_BLUE_BIN                        (void *)(0x0c05d038)
#define   BACKGROUND_BIN                          (void *)(0x0c0604b8)
#define   BUTTON_BIN                              (void *)(0x0c09c9f8)
#define   BUTTON_ON_BIN                           (void *)(0x0c0a1f78)
#define   CONN_BIN                                (void *)(0x0c0a74f8)
#define   CONN_BLUE_BIN                           (void *)(0x0c0aa978)
#define   DISC_BIN                                (void *)(0x0c0addb8)
#define   DISC_BLUE_BIN                           (void *)(0x0c0b1238)
#define   GBK_32_32_DOT_BIN                       (void *)(0x0c0b46b8)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(0x0c3ce8f8)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x0c3ee938)
#define   OVERLAP_BIN                             (void *)(0x0c407c78)
#define   SCAN_BIN                                (void *)(0x0c417338)
#define   SCAN_BLUE_BIN                           (void *)(0x0c41a7b8)

#endif
