#if defined _WIN32
extern unsigned char resource_root[];

#define   ARROW_BIN                               (void *)(resource_root + 0x000003b8)
#define   BAR0_BIN                                (void *)(resource_root + 0x000083f8)
#define   BAR1_BIN                                (void *)(resource_root + 0x0000ac38)
#define   BAR2_BIN                                (void *)(resource_root + 0x0000d478)
#define   BAR3_BIN                                (void *)(resource_root + 0x0000fcb8)
#define   BAR4_BIN                                (void *)(resource_root + 0x000124f8)
#define   BAT_CASE_BIN                            (void *)(resource_root + 0x00014d38)
#define   BAT_L_BIN                               (void *)(resource_root + 0x00015478)
#define   BAT_R_BIN                               (void *)(resource_root + 0x00015bb8)
#define   BLUETOOTH_OFF_BIN                       (void *)(resource_root + 0x000162f8)
#define   BLUETOOTH_ON_BIN                        (void *)(resource_root + 0x00016a38)
#define   CALL_ANSWER_BIN                         (void *)(resource_root + 0x00017178)
#define   CALL_ANSWER_HIGHLIGHT_BIN               (void *)(resource_root + 0x0001a3b8)
#define   CALL_REJECT_BIN                         (void *)(resource_root + 0x0001d5f8)
#define   CALL_REJECT_HIGHLIGHT_BIN               (void *)(resource_root + 0x00020838)
#define   CLOCK_SET_BIN                           (void *)(resource_root + 0x00023a78)
#define   CLOCK_SET_HIGHLIGHT_BIN                 (void *)(resource_root + 0x00028bb8)
#define   EQ_OFF_BIN                              (void *)(resource_root + 0x0002dcf8)
#define   EQ_ON_BIN                               (void *)(resource_root + 0x0002e5b8)
#define   FLASHLIGHT_BIN                          (void *)(resource_root + 0x0002ee78)
#define   FLASHLIGHT_HIGHLIGHT_BIN                (void *)(resource_root + 0x00034338)
#define   HARMONYOS_REGULAR_SIZE24_BITS1_FONT_BIN (void *)(resource_root + 0x00039838)
#define   HARMONYOS_REGULAR_SIZE28_BITS1_FONT_BIN (void *)(resource_root + 0x00225638)
#define   LISTEN_ANC_BIN                          (void *)(resource_root + 0x00503478)
#define   LISTEN_ANC_HIGHLIGHT_BIN                (void *)(resource_root + 0x00506fb8)
#define   LISTEN_APT_BIN                          (void *)(resource_root + 0x0050aaf8)
#define   LISTEN_APT_HIGHLIGHT_BIN                (void *)(resource_root + 0x0050e638)
#define   LISTEN_OFF_BIN                          (void *)(resource_root + 0x00512178)
#define   LISTEN_OFF_HIGHLIGHT_BIN                (void *)(resource_root + 0x00515cb8)
#define   MIC_MUTE_BIN                            (void *)(resource_root + 0x005197f8)
#define   MIC_MUTE_HIGHLIGHT_BIN                  (void *)(resource_root + 0x0051b438)
#define   MIC_UNMUTE_BIN                          (void *)(resource_root + 0x0051d078)
#define   MIC_UNMUTE_HIGHLIGHT_BIN                (void *)(resource_root + 0x0051ecb8)
#define   MUSIC_BACKWARD_BIN                      (void *)(resource_root + 0x005208f8)
#define   MUSIC_BACKWARD_HIGHLIGHT_BIN            (void *)(resource_root + 0x00523b38)
#define   MUSIC_FORWARD_BIN                       (void *)(resource_root + 0x00526d78)
#define   MUSIC_FORWARD_HIGHLIGHT_BIN             (void *)(resource_root + 0x00529fb8)
#define   MUSIC_PAUSE_BIN                         (void *)(resource_root + 0x0052d1f8)
#define   MUSIC_PLAY_BIN                          (void *)(resource_root + 0x00530438)
#define   OPTION_LEFT_BIN                         (void *)(resource_root + 0x00533678)
#define   OPTION_LEFT_HIGHLIGHT_BIN               (void *)(resource_root + 0x005368b8)
#define   OPTION_RIGHT_BIN                        (void *)(resource_root + 0x00539af8)
#define   OPTION_RIGHT_HIGHLIGHT_BIN              (void *)(resource_root + 0x0053cd38)
#define   OVERLAP_BIN                             (void *)(resource_root + 0x0053ff78)
#define   TWS_LEFT_BIN                            (void *)(resource_root + 0x0054f0f8)
#define   TWS_LEFT_HIGHLIGHT_BIN                  (void *)(resource_root + 0x00554ef8)
#define   TWS_RIGHT_BIN                           (void *)(resource_root + 0x0055acb8)
#define   TWS_RIGHT_HIGHLIGHT_BIN                 (void *)(resource_root + 0x00560ab8)
#define   VOLUME_DOWN_BIN                         (void *)(resource_root + 0x00566878)
#define   VOLUME_DOWN_HIGHLIGHT_BIN               (void *)(resource_root + 0x00569ab8)
#define   VOLUME_UP_BIN                           (void *)(resource_root + 0x0056ccf8)
#define   VOLUME_UP_HIGHLIGHT_BIN                 (void *)(resource_root + 0x0056ff38)
#define   WALLPAPER1_BIN                          (void *)(resource_root + 0x00573178)
#define   WALLPAPER2_BIN                          (void *)(resource_root + 0x005af438)
#define   WALLPAPER3_BIN                          (void *)(resource_root + 0x005eb6f8)

#else
#define   ARROW_BIN                               (void *)(0x00a003b8)
#define   BAR0_BIN                                (void *)(0x00a083f8)
#define   BAR1_BIN                                (void *)(0x00a0ac38)
#define   BAR2_BIN                                (void *)(0x00a0d478)
#define   BAR3_BIN                                (void *)(0x00a0fcb8)
#define   BAR4_BIN                                (void *)(0x00a124f8)
#define   BAT_CASE_BIN                            (void *)(0x00a14d38)
#define   BAT_L_BIN                               (void *)(0x00a15478)
#define   BAT_R_BIN                               (void *)(0x00a15bb8)
#define   BLUETOOTH_OFF_BIN                       (void *)(0x00a162f8)
#define   BLUETOOTH_ON_BIN                        (void *)(0x00a16a38)
#define   CALL_ANSWER_BIN                         (void *)(0x00a17178)
#define   CALL_ANSWER_HIGHLIGHT_BIN               (void *)(0x00a1a3b8)
#define   CALL_REJECT_BIN                         (void *)(0x00a1d5f8)
#define   CALL_REJECT_HIGHLIGHT_BIN               (void *)(0x00a20838)
#define   CLOCK_SET_BIN                           (void *)(0x00a23a78)
#define   CLOCK_SET_HIGHLIGHT_BIN                 (void *)(0x00a28bb8)
#define   EQ_OFF_BIN                              (void *)(0x00a2dcf8)
#define   EQ_ON_BIN                               (void *)(0x00a2e5b8)
#define   FLASHLIGHT_BIN                          (void *)(0x00a2ee78)
#define   FLASHLIGHT_HIGHLIGHT_BIN                (void *)(0x00a34338)
#define   HARMONYOS_REGULAR_SIZE24_BITS1_FONT_BIN (void *)(0x00a39838)
#define   HARMONYOS_REGULAR_SIZE28_BITS1_FONT_BIN (void *)(0x00c25638)
#define   LISTEN_ANC_BIN                          (void *)(0x00f03478)
#define   LISTEN_ANC_HIGHLIGHT_BIN                (void *)(0x00f06fb8)
#define   LISTEN_APT_BIN                          (void *)(0x00f0aaf8)
#define   LISTEN_APT_HIGHLIGHT_BIN                (void *)(0x00f0e638)
#define   LISTEN_OFF_BIN                          (void *)(0x00f12178)
#define   LISTEN_OFF_HIGHLIGHT_BIN                (void *)(0x00f15cb8)
#define   MIC_MUTE_BIN                            (void *)(0x00f197f8)
#define   MIC_MUTE_HIGHLIGHT_BIN                  (void *)(0x00f1b438)
#define   MIC_UNMUTE_BIN                          (void *)(0x00f1d078)
#define   MIC_UNMUTE_HIGHLIGHT_BIN                (void *)(0x00f1ecb8)
#define   MUSIC_BACKWARD_BIN                      (void *)(0x00f208f8)
#define   MUSIC_BACKWARD_HIGHLIGHT_BIN            (void *)(0x00f23b38)
#define   MUSIC_FORWARD_BIN                       (void *)(0x00f26d78)
#define   MUSIC_FORWARD_HIGHLIGHT_BIN             (void *)(0x00f29fb8)
#define   MUSIC_PAUSE_BIN                         (void *)(0x00f2d1f8)
#define   MUSIC_PLAY_BIN                          (void *)(0x00f30438)
#define   OPTION_LEFT_BIN                         (void *)(0x00f33678)
#define   OPTION_LEFT_HIGHLIGHT_BIN               (void *)(0x00f368b8)
#define   OPTION_RIGHT_BIN                        (void *)(0x00f39af8)
#define   OPTION_RIGHT_HIGHLIGHT_BIN              (void *)(0x00f3cd38)
#define   OVERLAP_BIN                             (void *)(0x00f3ff78)
#define   TWS_LEFT_BIN                            (void *)(0x00f4f0f8)
#define   TWS_LEFT_HIGHLIGHT_BIN                  (void *)(0x00f54ef8)
#define   TWS_RIGHT_BIN                           (void *)(0x00f5acb8)
#define   TWS_RIGHT_HIGHLIGHT_BIN                 (void *)(0x00f60ab8)
#define   VOLUME_DOWN_BIN                         (void *)(0x00f66878)
#define   VOLUME_DOWN_HIGHLIGHT_BIN               (void *)(0x00f69ab8)
#define   VOLUME_UP_BIN                           (void *)(0x00f6ccf8)
#define   VOLUME_UP_HIGHLIGHT_BIN                 (void *)(0x00f6ff38)
#define   WALLPAPER1_BIN                          (void *)(0x00f73178)
#define   WALLPAPER2_BIN                          (void *)(0x00faf438)
#define   WALLPAPER3_BIN                          (void *)(0x00feb6f8)

#endif
