#if defined _WIN32
extern unsigned char resource_root[];

#define   AURACAST_BIN                            (void *)(resource_root + 0x00000138)
#define   TABLE1_BLANK_BIN                        (void *)(resource_root + 0x0000a378)
#define   TABLE2_BLANK_BIN                        (void *)(resource_root + 0x0002f7f8)
#define   VOL_DEC_BIN                             (void *)(resource_root + 0x000532b8)
#define   VOL_DEC_BLUE_BIN                        (void *)(resource_root + 0x00056738)
#define   VOL_INC_BIN                             (void *)(resource_root + 0x00059b78)
#define   VOL_INC_BLUE_BIN                        (void *)(resource_root + 0x0005cff8)
#define   BUTTON_BIN                              (void *)(resource_root + 0x00060438)
#define   BUTTON_ON_BIN                           (void *)(resource_root + 0x000659b8)
#define   CONN_BIN                                (void *)(resource_root + 0x0006af38)
#define   CONN_BLUE_BIN                           (void *)(resource_root + 0x0006e3b8)
#define   DISC_BIN                                (void *)(resource_root + 0x000717f8)
#define   DISC_BLUE_BIN                           (void *)(resource_root + 0x00074c78)
#define   GBK_32_32_DOT_BIN                       (void *)(resource_root + 0x000780f8)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(resource_root + 0x00392338)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(resource_root + 0x003b2378)
#define   OVERLAP_BIN                             (void *)(resource_root + 0x003cb6b8)
#define   SCAN_BIN                                (void *)(resource_root + 0x003dad78)
#define   SCAN_BLUE_BIN                           (void *)(resource_root + 0x003de1f8)

#else
#define   AURACAST_BIN                            (void *)(0x0c000138)
#define   TABLE1_BLANK_BIN                        (void *)(0x0c00a378)
#define   TABLE2_BLANK_BIN                        (void *)(0x0c02f7f8)
#define   VOL_DEC_BIN                             (void *)(0x0c0532b8)
#define   VOL_DEC_BLUE_BIN                        (void *)(0x0c056738)
#define   VOL_INC_BIN                             (void *)(0x0c059b78)
#define   VOL_INC_BLUE_BIN                        (void *)(0x0c05cff8)
#define   BUTTON_BIN                              (void *)(0x0c060438)
#define   BUTTON_ON_BIN                           (void *)(0x0c0659b8)
#define   CONN_BIN                                (void *)(0x0c06af38)
#define   CONN_BLUE_BIN                           (void *)(0x0c06e3b8)
#define   DISC_BIN                                (void *)(0x0c0717f8)
#define   DISC_BLUE_BIN                           (void *)(0x0c074c78)
#define   GBK_32_32_DOT_BIN                       (void *)(0x0c0780f8)
#define   GBK_UNICODE_TABLE_BIN                   (void *)(0x0c392338)
#define   SIMKAI_SIZE24_BITS4_FONT_BIN            (void *)(0x0c3b2378)
#define   OVERLAP_BIN                             (void *)(0x0c3cb6b8)
#define   SCAN_BIN                                (void *)(0x0c3dad78)
#define   SCAN_BLUE_BIN                           (void *)(0x0c3de1f8)

#endif
