# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('gui_demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_454_454_BB2PLUS_WATCH'], CPPPATH = CPPPATH)

Return('group')
