from building import *

cwd = GetCurrentDir()
src = Split("""
""")



CPPPATH = [cwd]
CPPDEFINES = []



if GetDepend('CONFIG_REALTEK_BUILD_GUI_XML_DOM') or GetDepend('CONFIG_REALTEK_BUILD_SCRIPT_AS_A_APP'):

    src = Glob('*.c')


group = DefineGroup('realgui/dom', 
                   src, 
                   depend=['CONFIG_REALTEK_BUILD_GUI'],
                   CPPPATH=CPPPATH,
                   CPPDEFINES=CPPDEFINES)

Return('group')
