# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]
src = Split("""
""")

group = []
CPPDEFINES = ['DRV_LCD_WIDTH=480']
CPPDEFINES += ['DRV_LCD_HIGHT=480']
CPPDEFINES += ['DRV_PIXEL_BITS=16']

if GetDepend('CONFIG_REALTEK_BUILD_REAL_BASE'):
    src += ['app_ui_realgui_base.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
    
if GetDepend('CONFIG_REALTEK_BUILD_MULTI_APP'):
    src += ['multi_app/app_ui_app_0.c']
    src += ['multi_app/app_ui_app_1.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_3D'):
    src += ['app_ui_realgui_3d.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_PRISM_MIRROR_3D'):
    src += ['app_ui_realgui_3d_prism_mirror.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)   

if GetDepend('CONFIG_REALTEK_BUILD_REAL_PAINTENGINE'):
    src += ['app_ui_paintengine.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_NANOVG'):
    src += ['app_ui_nanovg.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_BOX2D'):
    src += ['app_ui_box2d.cpp']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    src += ['app_ui_lvgl.c']
    group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_DEMO_APP'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_V9'):
    src += ['app_ui_lvglv9.c']
    group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_LVGL_DEMO_APP'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_ARM2D_DEMO_APP'):
    src += ['app_ui_arm2d.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_BUILD_REAL_LITEGFX_DEMO'):
    src += ['app_ui_realgui_litegfx.c']
    group = DefineGroup('realgui/demo', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)
Return('group')

