# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_HONEYGUI']):
    src += ['ezxml.c']


CPPPATH = [cwd]

group = DefineGroup('realgui/3rd', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('group')
