from building import *

cwd = GetCurrentDir()
src = Split("""
""")
src += ['cwm_task.c']
path = [cwd]
libs = ['']
libpath = [cwd]

libs += Split('''
CWM_LIB_Keil
''')
	

group = DefineGroup('CWM', src, depend = ['MODULE_USING_CWM'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')

