# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
SrcRemove(src,'gui_scroll_wheel.c')
SrcRemove(src,'gui_bitmap.c')
SrcRemove(src,'gui_stb_img.c')

if not GetDepend(['CONFIG_REALTEK_BUILD_LVGL_GUI']):
    SrcRemove(src,'gui_lvgl.c')

if not GetDepend(['CONFIG_REALTEK_BUILD_PAINTER_ENGINE']):
    SrcRemove(src,'gui_px.c')

CPPPATH = [cwd]

objs = DefineGroup('realgui/widget', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
