# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += ['tlsf/tlsf.c']

CPPPATH = [cwd,cwd + '/tlsf']

group = DefineGroup('realgui/misc', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('group')
