# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Glob("*.cpp")


CPPPATH = [cwd]
objs = DefineGroup('realgui/3rd/box2d', src, depend = [''], CPPPATH = CPPPATH)

Return('objs')
