# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_TEST'], CPPPATH = CPPPATH)

Return('group')
