# RTK building script for GuiEngine

import os

from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)

src = Glob('*.c')
SrcRemove(src,'vg_lite_dump.c')
CPPPATH = [cwd]



group = DefineGroup('vg_lite', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))


Return('group')
