# RTK building script for GuiEngine

import os

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
src += Glob('rtos/*.c')
SrcRemove(src,'vg_lite_dump.c')
CPPPATH = [cwd]

group = DefineGroup('vg_lite', src, depend = ['MODULE_VG_LITE'], CPPPATH = CPPPATH)


Return('group')
