# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")
CPPDEFINES = []
src = Glob('*.c')
src += Glob('./gui_main/*.c')
src += Glob('./gui_watchface/*.c')
src += Glob('./gui_player/*.c')
src += Glob('./gui_contacts/*.c')
src += Glob('./gui_common/*.c')
src += Glob('./gui_call/*.c')
src += Glob('./gui_record/*.c')
src += Glob('./gui_menu/*.c') 
if GetDepend('CONFIG_REALTEK_BUILD_GUI_BOX2D'):
    src += Glob('./gui_menu/*.cpp') 
    CPPDEFINES += ['ENABLE_RTK_GUI_BOX2D']
src += Glob('./gui_benchmark/*.c') 
src += Glob('./gui_watchface_litegfx/*.c') 
CPPPATH = [cwd]
CPPPATH += [cwd + '\\gui_benchmark']
CPPPATH += [cwd + '\\gui_call']
CPPPATH += [cwd + '\\gui_common']
CPPPATH += [cwd + '\\gui_contacts']
CPPPATH += [cwd + '\\gui_player']
CPPPATH += [cwd + '\\gui_record']
CPPPATH += [cwd + '\\gui_watchface']
print(CPPPATH)


if GetDepend('CONFIG_REALTEK_BUILD_GUI_454_454_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_454_454_DEMO']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_454_454_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
