# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += Glob('./gui_main/*.c')
src += Glob('./gui_watchface/*.c')
src += Glob('./gui_player/*.c')
src += Glob('./gui_contacts/*.c')
src += Glob('./gui_common/*.c')
src += Glob('./gui_call/*.c')
src += Glob('./gui_record/*.c')
src += Glob('./gui_menu/*.c') 
src += Glob('./gui_watchface_litegfx/*.c') 
CPPPATH = [cwd]
CPPPATH += [cwd + '\\gui_common']
print(CPPPATH)

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_454_454_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_454_454_DEMO']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_454_454_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
