
from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]


CPPDEFINES = ['ENABLE_RTK_GUI_WEB']

group = DefineGroup('realgui/3rd', src, depend = ['CONFIG_REALTEK_BUILD_WEB'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
