# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_HONEYGUI_AUTO_TEST'):
    CPPDEFINES += ['ENABLE_RTK_AUTO_TEST']

CPPPATH = [cwd]
objs = DefineGroup('realgui/test', src, depend = ['CONFIG_REALTEK_BUILD_HONEYGUI_AUTO_TEST'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('objs')
