
from building import *


cwd     = GetCurrentDir()
objs = []
cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
list = os.listdir(cwd)

group = DefineGroup('database', src, depend = ['MODULE_USING_DATABASE'], CPPPATH = CPPPATH)

if GetDepend('MODULE_USING_DATABASE'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
