#if defined _HONEYGUI_SIMULATOR_
extern unsigned char *resource_root;

#define   BUTTON_BG_ELLIPSE_84_40_BIN             (void *)(resource_root + 0x000001b8)
#define   ICON_OTA_BIN                            (void *)(resource_root + 0x00000ef8)
#define   ICON_OTA_COMPLETE_BIN                   (void *)(resource_root + 0x000028f8)
#define   ICON_OTA_ERROR_BIN                      (void *)(resource_root + 0x00003138)
#define   ICON_OTA_SMALL_BIN                      (void *)(resource_root + 0x00003978)
#define   OTA_BG_BIN                              (void *)(resource_root + 0x00004178)
#define   OTA_BG_BIG_BIN                          (void *)(resource_root + 0x000189b8)
#define   OTA_BG_FAIL_BIN                         (void *)(resource_root + 0x0002d1f8)
#define   OTA_BG_SMALL_BIN                        (void *)(resource_root + 0x00040ab8)
#define   ICON_CALL_BIG_BIN                       (void *)(resource_root + 0x00055338)
#define   ICON_MUTE_BIN                           (void *)(resource_root + 0x000559b8)
#define   BATTERY_CHARGING_BG_BIN                 (void *)(resource_root + 0x000560f8)
#define   ICON_CHARGING_0_BIN                     (void *)(resource_root + 0x00075538)
#define   ICON_CHARGING_1_BIN                     (void *)(resource_root + 0x000758f8)
#define   ICON_CHARGING_2_BIN                     (void *)(resource_root + 0x00075cb8)
#define   ICON_CHARGING_3_BIN                     (void *)(resource_root + 0x00076078)
#define   ICON_CHARGING_4_BIN                     (void *)(resource_root + 0x00076438)
#define   ICON_CHARGING_5_BIN                     (void *)(resource_root + 0x000767f8)
#define   ICON_CHARGING_6_BIN                     (void *)(resource_root + 0x00076bb8)
#define   ICON_CHARGING_7_BIN                     (void *)(resource_root + 0x00076f78)
#define   ICON_CHARGING_BG_BIN                    (void *)(resource_root + 0x00077338)
#define   CAPTION_1_BIN                           (void *)(resource_root + 0x00077b78)
#define   CAPTION_2_BIN                           (void *)(resource_root + 0x00083df8)
#define   CAPTION_3_30_BIN                        (void *)(resource_root + 0x0008e878)
#define   CONTENT_1_BIN                           (void *)(resource_root + 0x00099ef8)
#define   HEADING_1_BIN                           (void *)(resource_root + 0x0009cb78)
#define   HEADING_2_BIN                           (void *)(resource_root + 0x000a27f8)
#define   ICON_ASC_BIN                            (void *)(resource_root + 0x000a5b78)
#define   ICON_HR_AUDIO_BIN                       (void *)(resource_root + 0x000a61f8)
#define   ICON_AURACAST_BIN                       (void *)(resource_root + 0x000a6878)
#define   ICON_AUTO_PLAY_PAUSE_BIN                (void *)(resource_root + 0x000a6ef8)
#define   ICON_BT_SOURCE_BIN                      (void *)(resource_root + 0x000a7578)
#define   ICON_EQ_BIN                             (void *)(resource_root + 0x000a7bf8)
#define   ICON_PLAYBACK_BIN                       (void *)(resource_root + 0x000a8278)
#define   ICON_SMART_TALK_BIN                     (void *)(resource_root + 0x000a88f8)
#define   ICON_SPATIAL_SOUND_BIN                  (void *)(resource_root + 0x000a8f78)
#define   ICON_VOICE_AWARE_BIN                    (void *)(resource_root + 0x000a95f8)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x000a9c78)
#define   ICON_24HOUR_TIME_BIN                    (void *)(resource_root + 0x000aa3f8)
#define   ICON_AUTODIMOFFSCREEN_BIN               (void *)(resource_root + 0x000aaa78)
#define   ICON_AUTOLOCKSCREEN_BIN                 (void *)(resource_root + 0x000ab0f8)
#define   ICON_BRIGHTNESS_BIN                     (void *)(resource_root + 0x000ab778)
#define   ICON_CASEBUTTON_BIN                     (void *)(resource_root + 0x000abdf8)
#define   ICON_CLOCK_SETTINGS_BIN                 (void *)(resource_root + 0x000ac478)
#define   ICON_CUSTOMIZE_INFOCENTER_BIN           (void *)(resource_root + 0x000acaf8)
#define   ICON_FACTORY_RESET_BIN                  (void *)(resource_root + 0x000ad178)
#define   ICON_ICON_WALLPAPER_BIN                 (void *)(resource_root + 0x000ad7f8)
#define   ICON_LANGUAGE_BIN                       (void *)(resource_root + 0x000ade78)
#define   ICON_LIGHTDARKMODE_BIN                  (void *)(resource_root + 0x000ae4f8)
#define   ICON_NOTIFICATION_BIN                   (void *)(resource_root + 0x000aeb78)
#define   ICON_PRODUCT_TIPS_BIN                   (void *)(resource_root + 0x000af1f8)
#define   ICON_QUICKWAKEUP_BIN                    (void *)(resource_root + 0x000af878)
#define   ICON_REORDER_BIN                        (void *)(resource_root + 0x000afef8)
#define   ICON_SUPPORT_BIN                        (void *)(resource_root + 0x000b0578)
#define   ICON_TX_MANAGER_BIN                     (void *)(resource_root + 0x000b0bf8)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x000b1278)
#define   ICON_FLASHLIGHT_BIN                     (void *)(resource_root + 0x000b1ab8)
#define   ICON_ICON_APP_BIN                       (void *)(resource_root + 0x000b2138)
#define   ICON_SILENTNOW_BIN                      (void *)(resource_root + 0x000b27b8)
#define   ICON_TIMER_BIN                          (void *)(resource_root + 0x000b2e38)
#define   ICON_VOLUME_UNIT_METER_BIN              (void *)(resource_root + 0x000b34b8)
#define   BUTTON_BG_ELLIPSE_240_48_BIN            (void *)(resource_root + 0x000b3c78)
#define   ICON_LOCK_TAB_BIN                       (void *)(resource_root + 0x000b69b8)
#define   ICON_UNLOCK_BIN                         (void *)(resource_root + 0x000b84f8)
#define   WALLPAPER_1_BIN                         (void *)(resource_root + 0x000b8838)
#define   WALLPAPER_1_DARK_BIN                    (void *)(resource_root + 0x000d7c78)
#define   WALLPAPER_1_LIGHT_BIN                   (void *)(resource_root + 0x000dccb8)
#define   WALLPAPER_2_BIN                         (void *)(resource_root + 0x000e1cf8)
#define   WALLPAPER_2_DARK_BIN                    (void *)(resource_root + 0x00101138)
#define   WALLPAPER_2_LIGHT_BIN                   (void *)(resource_root + 0x00106178)
#define   WALLPAPER_3_BIN                         (void *)(resource_root + 0x0010b1b8)
#define   WALLPAPER_3_DARK_BIN                    (void *)(resource_root + 0x0012a5f8)
#define   WALLPAPER_3_LIGHT_BIN                   (void *)(resource_root + 0x0012f638)
#define   WALLPAPER_4_BIN                         (void *)(resource_root + 0x00134678)
#define   WALLPAPER_4_DARK_BIN                    (void *)(resource_root + 0x00153ab8)
#define   WALLPAPER_4_LIGHT_BIN                   (void *)(resource_root + 0x00158af8)
#define   WALLPAPER_5_BIN                         (void *)(resource_root + 0x0015db38)
#define   WALLPAPER_5_DARK_BIN                    (void *)(resource_root + 0x0017cf78)
#define   WALLPAPER_5_LIGHT_BIN                   (void *)(resource_root + 0x00181fb8)
#define   MASK_BIN                                (void *)(resource_root + 0x00187078)
#define   MENU_AUDIO_BIN                          (void *)(resource_root + 0x0018bbb8)
#define   MENU_AUDIO_SCALE_BIN                    (void *)(resource_root + 0x0018c378)
#define   MENU_BUTTON_BG_BIN                      (void *)(resource_root + 0x0018cbf8)
#define   MENU_BUTTON_BG_SCALE_BIN                (void *)(resource_root + 0x0018e538)
#define   MENU_LISTNOTE_BG_BIN                    (void *)(resource_root + 0x00190c78)
#define   MENU_SETTINGS_BIN                       (void *)(resource_root + 0x00194bb8)
#define   MENU_SETTINGS_SCALE_BIN                 (void *)(resource_root + 0x00195378)
#define   MENU_TOOLS_BIN                          (void *)(resource_root + 0x00195b78)
#define   MENU_TOOLS_SCALE_BIN                    (void *)(resource_root + 0x00196338)
#define   JBL_BIN                                 (void *)(resource_root + 0x00196bb8)
#define   BUTTON_GET_START_BIN                    (void *)(resource_root + 0x0019cb78)
#define   ADD_BIN                                 (void *)(resource_root + 0x0019ff78)
#define   ICON_AURACAST_SMALL_BIN                 (void *)(resource_root + 0x001a03b8)
#define   ICON_CONNECT_BIN                        (void *)(resource_root + 0x001a0638)
#define   ICON_DELETE_BIN                         (void *)(resource_root + 0x001a0978)
#define   ICON_DISCONNECT_BIN                     (void *)(resource_root + 0x001a0cb8)
#define   ICON_HQ_BIN                             (void *)(resource_root + 0x001a0ff8)
#define   ICON_SELECTED_BIN                       (void *)(resource_root + 0x001a1338)
#define   BASS_BIN                                (void *)(resource_root + 0x001a15b8)
#define   BG_CIRCLE_40_BIN                        (void *)(resource_root + 0x001a3cb8)
#define   BUTTON_BG_CIRCLE_BIN                    (void *)(resource_root + 0x001a4338)
#define   BUTTON_BG_ELLIPSE_BIN                   (void *)(resource_root + 0x001a5b38)
#define   BUTTON_BG_ELLIPSE_134_66_BIN            (void *)(resource_root + 0x001a7d78)
#define   BUTTON_BG_ELLIPSE_148_88_BIN            (void *)(resource_root + 0x001aa038)
#define   BUTTON_BG_ELLIPSE_201_80_BIN            (void *)(resource_root + 0x001ad378)
#define   BUTTON_BG_ELLIPSE_240_80_BIN            (void *)(resource_root + 0x001b1278)
#define   BUTTON_BG_ELLIPSE_312_56_BIN            (void *)(resource_root + 0x001b5db8)
#define   BUTTON_BG_ELLIPSE_312_56_BOT_BIN        (void *)(resource_root + 0x001ba238)
#define   BUTTON_BG_ELLIPSE_312_56_MID_BIN        (void *)(resource_root + 0x001be6b8)
#define   BUTTON_BG_ELLIPSE_312_56_TOP_BIN        (void *)(resource_root + 0x001c2b38)
#define   BUTTON_BG_ELLIPSE_56_60_BIN             (void *)(resource_root + 0x001c6fb8)
#define   BUTTON_BG_ELLIPSE_60_64_BIN             (void *)(resource_root + 0x001c7d38)
#define   BUTTON_BG_ELLIPSE_64_40_BIN             (void *)(resource_root + 0x001c8c78)
#define   BUTTON_BG_ELLIPSE_90_68_BIN             (void *)(resource_root + 0x001c96b8)
#define   BUTTON_BG_RECT_BIN                      (void *)(resource_root + 0x001caef8)
#define   CLUB_BIN                                (void *)(resource_root + 0x001cc138)
#define   CONTROL_BG_BIN                          (void *)(resource_root + 0x001ce838)
#define   EXTRE_BASS_BIN                          (void *)(resource_root + 0x001d5078)
#define   ICON_AA_BIN                             (void *)(resource_root + 0x001d7778)
#define   ICON_ANC_BIN                            (void *)(resource_root + 0x001d80b8)
#define   ICON_ARROW_DOWN_BIN                     (void *)(resource_root + 0x001d8a38)
#define   ICON_ARROW_R_BIG_BIN                    (void *)(resource_root + 0x001d8b78)
#define   ICON_ARROW_UP_BIN                       (void *)(resource_root + 0x001d8cb8)
#define   ICON_CLICK_BIN                          (void *)(resource_root + 0x001d8df8)
#define   ICON_CLICK_DOUBLE_BIN                   (void *)(resource_root + 0x001d94f8)
#define   ICON_CLICK_TRIPLE_BIN                   (void *)(resource_root + 0x001d9bf8)
#define   ICON_DARK_BIN                           (void *)(resource_root + 0x001da2f8)
#define   ICON_DONE_BIN                           (void *)(resource_root + 0x001da978)
#define   ICON_FLASHLIGHT_OFF_BIN                 (void *)(resource_root + 0x001db078)
#define   ICON_FLASHLIGHT_ON_BIN                  (void *)(resource_root + 0x001db4f8)
#define   ICON_HEAD_TRACKING_BIN                  (void *)(resource_root + 0x001db7f8)
#define   ICON_L_BIN                              (void *)(resource_root + 0x001dbdb8)
#define   ICON_LIGHT_BIN                          (void *)(resource_root + 0x001dc578)
#define   ICON_MAIL_BIN                           (void *)(resource_root + 0x001dcbf8)
#define   ICON_R_BIN                              (void *)(resource_root + 0x001dcd78)
#define   ICON_RESET_BIG_BIN                      (void *)(resource_root + 0x001dd538)
#define   ICON_SETTINGS_BIN                       (void *)(resource_root + 0x001ddb38)
#define   ICON_SS_OFF_BIN                         (void *)(resource_root + 0x001dddb8)
#define   ICON_SS_ON_BIN                          (void *)(resource_root + 0x001de378)
#define   ICON_TT_BIN                             (void *)(resource_root + 0x001de938)
#define   JAZZ_BIN                                (void *)(resource_root + 0x001df278)
#define   MASK_320_14_BIN                         (void *)(resource_root + 0x001e1978)
#define   MASK_320_40_BIN                         (void *)(resource_root + 0x001e2b38)
#define   MASK_320_82_BIN                         (void *)(resource_root + 0x001e5d78)
#define   MASK_FADE_BOTTOM_BIN                    (void *)(resource_root + 0x001ec438)
#define   MASK_FADE_TOP_BIN                       (void *)(resource_root + 0x001ef9b8)
#define   PAGE_INDICATOR_BIN                      (void *)(resource_root + 0x001f2f38)
#define   PAUSE_BIN                               (void *)(resource_root + 0x001f2f78)
#define   PAUSE_SMALL_BIN                         (void *)(resource_root + 0x001f3538)
#define   PLAY_BIN                                (void *)(resource_root + 0x001f3738)
#define   PLAY_SMALL_BIN                          (void *)(resource_root + 0x001f3e38)
#define   PAGE_INDICATOR_HEART_BIN                (void *)(resource_root + 0x001f40f8)
#define   TIP_2_FG_DARK_BIN                       (void *)(resource_root + 0x001f4178)
#define   TIP_2_FG_LIGHT_BIN                      (void *)(resource_root + 0x001f91b8)
#define   TIP_3_FG_DARK_BIN                       (void *)(resource_root + 0x001fe1f8)
#define   TIP_3_FG_LIGHT_BIN                      (void *)(resource_root + 0x00205a38)
#define   TIP_4_FG_DARK_BIN                       (void *)(resource_root + 0x0020d278)
#define   TIP_4_FG_LIGHT_BIN                      (void *)(resource_root + 0x00214ab8)
#define   TIP_5_FG_DARK_BIN                       (void *)(resource_root + 0x0021c2f8)
#define   TIP_5_FG_LIGHT_BIN                      (void *)(resource_root + 0x00221938)
#define   PROGRESSBAR_1_BIN                       (void *)(resource_root + 0x00226f78)
#define   PROGRESSBAR_10_BIN                      (void *)(resource_root + 0x002270b8)
#define   PROGRESSBAR_11_BIN                      (void *)(resource_root + 0x00227ab8)
#define   PROGRESSBAR_12_BIN                      (void *)(resource_root + 0x002285b8)
#define   PROGRESSBAR_13_BIN                      (void *)(resource_root + 0x002291b8)
#define   PROGRESSBAR_14_BIN                      (void *)(resource_root + 0x00229eb8)
#define   PROGRESSBAR_15_BIN                      (void *)(resource_root + 0x0022acb8)
#define   PROGRESSBAR_16_BIN                      (void *)(resource_root + 0x0022bbb8)
#define   PROGRESSBAR_2_BIN                       (void *)(resource_root + 0x0022cbb8)
#define   PROGRESSBAR_3_BIN                       (void *)(resource_root + 0x0022cdf8)
#define   PROGRESSBAR_4_BIN                       (void *)(resource_root + 0x0022d138)
#define   PROGRESSBAR_5_BIN                       (void *)(resource_root + 0x0022d578)
#define   PROGRESSBAR_6_BIN                       (void *)(resource_root + 0x0022dab8)
#define   PROGRESSBAR_7_BIN                       (void *)(resource_root + 0x0022e0f8)
#define   PROGRESSBAR_8_BIN                       (void *)(resource_root + 0x0022e7f8)
#define   PROGRESSBAR_9_BIN                       (void *)(resource_root + 0x0022eff8)
#define   QRCODE_BIN                              (void *)(resource_root + 0x0022f8f8)
#define   SECTION_BAR_1_BIN                       (void *)(resource_root + 0x00238c38)
#define   SECTION_BAR_2_BIN                       (void *)(resource_root + 0x00239cb8)
#define   SECTION_BAR_3_BIN                       (void *)(resource_root + 0x0023ad38)
#define   SELECTOR_BG_BIN                         (void *)(resource_root + 0x0023bdb8)
#define   SELECTOR_CIRCLE_BIN                     (void *)(resource_root + 0x0023c078)
#define   ICON_BELL_BOT_BIN                       (void *)(resource_root + 0x0023c178)
#define   ICON_BELL_TOP_BIN                       (void *)(resource_root + 0x0023c1f8)
#define   ICON_CANCEL_BIN                         (void *)(resource_root + 0x0023c3b8)
#define   ICON_SILENT_BIN                         (void *)(resource_root + 0x0023c578)
#define   ICON_SILENT_CIRCLE_BIN                  (void *)(resource_root + 0x0023c838)
#define   ICON_SILENT_CIRCLE_SMALL_BIN            (void *)(resource_root + 0x0023ccb8)
#define   ICON_SILENT_SMALL_BIN                   (void *)(resource_root + 0x0023cfb8)
#define   SKIP_LAST_BIN                           (void *)(resource_root + 0x0023d178)
#define   SKIP_NEXT_BIN                           (void *)(resource_root + 0x0023d5f8)
#define   SMART_TALK_15S_BIN                      (void *)(resource_root + 0x0023da78)
#define   SMART_TALK_20S_BIN                      (void *)(resource_root + 0x0023e5f8)
#define   SMART_TALK_5S_BIN                       (void *)(resource_root + 0x0023f178)
#define   SPATIAL_SOUND_GAME_BIN                  (void *)(resource_root + 0x0023fcf8)
#define   SPATIAL_SOUND_MOVIE_BIN                 (void *)(resource_root + 0x00240638)
#define   SPATIAL_SOUND_MUSIC_BIN                 (void *)(resource_root + 0x00240f78)
#define   STRENGTH_BAR_BIN                        (void *)(resource_root + 0x002418b8)
#define   STUDIO_BIN                              (void *)(resource_root + 0x00241a78)
#define   SUB_BIN                                 (void *)(resource_root + 0x00244178)
#define   SWITCH_L_BIN                            (void *)(resource_root + 0x00244278)
#define   SWITCH_R_BIN                            (void *)(resource_root + 0x002444f8)
#define   TIME_FORMAT_12_BIN                      (void *)(resource_root + 0x002447b8)
#define   TIME_FORMAT_24_BIN                      (void *)(resource_root + 0x00244e78)
#define   ICON_BELL_PART_1_BIN                    (void *)(resource_root + 0x002459f8)
#define   ICON_BELL_PART_2_BIN                    (void *)(resource_root + 0x00245c38)
#define   ICON_CANCEL_BIG_BIN                     (void *)(resource_root + 0x00245cf8)
#define   PROGRESS_CIRCLE_0_BIN                   (void *)(resource_root + 0x00245ff8)
#define   PROGRESS_CIRCLE_1_BIN                   (void *)(resource_root + 0x002462f8)
#define   PROGRESS_CIRCLE_10_BIN                  (void *)(resource_root + 0x00246638)
#define   PROGRESS_CIRCLE_11_BIN                  (void *)(resource_root + 0x00246938)
#define   PROGRESS_CIRCLE_12_BIN                  (void *)(resource_root + 0x00246c38)
#define   PROGRESS_CIRCLE_13_BIN                  (void *)(resource_root + 0x00246f38)
#define   PROGRESS_CIRCLE_14_BIN                  (void *)(resource_root + 0x00247238)
#define   PROGRESS_CIRCLE_15_BIN                  (void *)(resource_root + 0x00247538)
#define   PROGRESS_CIRCLE_16_BIN                  (void *)(resource_root + 0x00247838)
#define   PROGRESS_CIRCLE_17_BIN                  (void *)(resource_root + 0x00247b38)
#define   PROGRESS_CIRCLE_18_BIN                  (void *)(resource_root + 0x00247e38)
#define   PROGRESS_CIRCLE_19_BIN                  (void *)(resource_root + 0x00248138)
#define   PROGRESS_CIRCLE_2_BIN                   (void *)(resource_root + 0x00248438)
#define   PROGRESS_CIRCLE_20_BIN                  (void *)(resource_root + 0x00248778)
#define   PROGRESS_CIRCLE_21_BIN                  (void *)(resource_root + 0x00248a78)
#define   PROGRESS_CIRCLE_22_BIN                  (void *)(resource_root + 0x00248d78)
#define   PROGRESS_CIRCLE_23_BIN                  (void *)(resource_root + 0x00249078)
#define   PROGRESS_CIRCLE_24_BIN                  (void *)(resource_root + 0x00249378)
#define   PROGRESS_CIRCLE_25_BIN                  (void *)(resource_root + 0x00249678)
#define   PROGRESS_CIRCLE_26_BIN                  (void *)(resource_root + 0x002499b8)
#define   PROGRESS_CIRCLE_27_BIN                  (void *)(resource_root + 0x00249cf8)
#define   PROGRESS_CIRCLE_28_BIN                  (void *)(resource_root + 0x00249ff8)
#define   PROGRESS_CIRCLE_29_BIN                  (void *)(resource_root + 0x0024a2f8)
#define   PROGRESS_CIRCLE_3_BIN                   (void *)(resource_root + 0x0024a5f8)
#define   PROGRESS_CIRCLE_30_BIN                  (void *)(resource_root + 0x0024a8f8)
#define   PROGRESS_CIRCLE_31_BIN                  (void *)(resource_root + 0x0024abf8)
#define   PROGRESS_CIRCLE_32_BIN                  (void *)(resource_root + 0x0024aef8)
#define   PROGRESS_CIRCLE_33_BIN                  (void *)(resource_root + 0x0024b1f8)
#define   PROGRESS_CIRCLE_34_BIN                  (void *)(resource_root + 0x0024b4f8)
#define   PROGRESS_CIRCLE_35_BIN                  (void *)(resource_root + 0x0024b7f8)
#define   PROGRESS_CIRCLE_36_BIN                  (void *)(resource_root + 0x0024baf8)
#define   PROGRESS_CIRCLE_37_BIN                  (void *)(resource_root + 0x0024bdf8)
#define   PROGRESS_CIRCLE_38_BIN                  (void *)(resource_root + 0x0024c0f8)
#define   PROGRESS_CIRCLE_39_BIN                  (void *)(resource_root + 0x0024c3f8)
#define   PROGRESS_CIRCLE_4_BIN                   (void *)(resource_root + 0x0024c6f8)
#define   PROGRESS_CIRCLE_40_BIN                  (void *)(resource_root + 0x0024c9f8)
#define   PROGRESS_CIRCLE_41_BIN                  (void *)(resource_root + 0x0024ccf8)
#define   PROGRESS_CIRCLE_42_BIN                  (void *)(resource_root + 0x0024cff8)
#define   PROGRESS_CIRCLE_43_BIN                  (void *)(resource_root + 0x0024d2f8)
#define   PROGRESS_CIRCLE_44_BIN                  (void *)(resource_root + 0x0024d5f8)
#define   PROGRESS_CIRCLE_45_BIN                  (void *)(resource_root + 0x0024d8f8)
#define   PROGRESS_CIRCLE_46_BIN                  (void *)(resource_root + 0x0024dbf8)
#define   PROGRESS_CIRCLE_47_BIN                  (void *)(resource_root + 0x0024def8)
#define   PROGRESS_CIRCLE_48_BIN                  (void *)(resource_root + 0x0024e1f8)
#define   PROGRESS_CIRCLE_49_BIN                  (void *)(resource_root + 0x0024e4f8)
#define   PROGRESS_CIRCLE_5_BIN                   (void *)(resource_root + 0x0024e7f8)
#define   PROGRESS_CIRCLE_6_BIN                   (void *)(resource_root + 0x0024eaf8)
#define   PROGRESS_CIRCLE_7_BIN                   (void *)(resource_root + 0x0024edf8)
#define   PROGRESS_CIRCLE_8_BIN                   (void *)(resource_root + 0x0024f0f8)
#define   PROGRESS_CIRCLE_9_BIN                   (void *)(resource_root + 0x0024f3f8)
#define   TIMER_PAUSE_BIN                         (void *)(resource_root + 0x0024f6f8)
#define   TIMER_PLAY_BIN                          (void *)(resource_root + 0x0024f9b8)
#define   TIMER_PLAY_BIG_BIN                      (void *)(resource_root + 0x0024fb78)
#define   TIMER_RESET_BIN                         (void *)(resource_root + 0x0024fe38)
#define   TOGGLE_BIN                              (void *)(resource_root + 0x00250178)
#define   TOGGLE_BG_BIN                           (void *)(resource_root + 0x002505b8)
#define   VOCAL_BIN                               (void *)(resource_root + 0x00250ff8)
#define   SCROLLBAR_BG_BIN                        (void *)(resource_root + 0x002536f8)
#define   SCROLLBAR_L_BIN                         (void *)(resource_root + 0x00253978)
#define   SCROLLBAR_M_BIN                         (void *)(resource_root + 0x00253b78)
#define   SCROLLBAR_S_BIN                         (void *)(resource_root + 0x00253cf8)
#define   BUTTON_BG_ELLIPSE_142_64_BIN            (void *)(resource_root + 0x00253f38)
#define   BUTTON_BG_ELLIPSE_194_68_BIN            (void *)(resource_root + 0x002562f8)
#define   BUTTON_BG_ELLIPSE_296_68_BIN            (void *)(resource_root + 0x002596b8)
#define   ICON_ARROW_R_BIN                        (void *)(resource_root + 0x0025e578)
#define   ICON_BT_CONNECT_BIN                     (void *)(resource_root + 0x0025e638)
#define   ICON_BT_DISCONNECT_BIN                  (void *)(resource_root + 0x0025e6f8)
#define   ICON_CALL_BIN                           (void *)(resource_root + 0x0025e7f8)
#define   ICON_CALL_MEDIUM_BIN                    (void *)(resource_root + 0x0025e938)
#define   ICON_CHARGING_SMALL_BIN                 (void *)(resource_root + 0x0025ec78)
#define   ICON_CUSTOMIZE_INFOCENTER_SMALL_BIN     (void *)(resource_root + 0x0025ecf8)
#define   ICON_HEADBAND_BIN                       (void *)(resource_root + 0x0025eef8)
#define   ICON_HEADBAND_SMALL_BIN                 (void *)(resource_root + 0x0025f178)
#define   ICON_IS_FAVORITE_BIN                    (void *)(resource_root + 0x0025f278)
#define   ICON_MESSAGE_BIN                        (void *)(resource_root + 0x0025f5b8)
#define   ICON_MESSAGE_SMALL_BIN                  (void *)(resource_root + 0x0025fc38)
#define   ICON_NOT_FAVORITE_BIN                   (void *)(resource_root + 0x0025fdb8)
#define   ICON_TIMER_MEDIUM_BIN                   (void *)(resource_root + 0x002600f8)
#define   ICON_TIMER_SMALL_BIN                    (void *)(resource_root + 0x00260338)
#define   ICON_TX_INNER_BIN                       (void *)(resource_root + 0x00260478)
#define   ICON_TX_INNER_SMALL_BIN                 (void *)(resource_root + 0x00260538)
#define   ICON_TX_OUTER_BIN                       (void *)(resource_root + 0x002605b8)
#define   ICON_TX_OUTER_SMALL_BIN                 (void *)(resource_root + 0x00260738)
#define   STATUSBAR_HOME_BG_BIN                   (void *)(resource_root + 0x00260838)

#else
#define   BUTTON_BG_ELLIPSE_84_40_BIN             (void *)(0x009501b8)
#define   ICON_OTA_BIN                            (void *)(0x00950ef8)
#define   ICON_OTA_COMPLETE_BIN                   (void *)(0x009528f8)
#define   ICON_OTA_ERROR_BIN                      (void *)(0x00953138)
#define   ICON_OTA_SMALL_BIN                      (void *)(0x00953978)
#define   OTA_BG_BIN                              (void *)(0x00954178)
#define   OTA_BG_BIG_BIN                          (void *)(0x009689b8)
#define   OTA_BG_FAIL_BIN                         (void *)(0x0097d1f8)
#define   OTA_BG_SMALL_BIN                        (void *)(0x00990ab8)
#define   ICON_CALL_BIG_BIN                       (void *)(0x009a5338)
#define   ICON_MUTE_BIN                           (void *)(0x009a59b8)
#define   BATTERY_CHARGING_BG_BIN                 (void *)(0x009a60f8)
#define   ICON_CHARGING_0_BIN                     (void *)(0x009c5538)
#define   ICON_CHARGING_1_BIN                     (void *)(0x009c58f8)
#define   ICON_CHARGING_2_BIN                     (void *)(0x009c5cb8)
#define   ICON_CHARGING_3_BIN                     (void *)(0x009c6078)
#define   ICON_CHARGING_4_BIN                     (void *)(0x009c6438)
#define   ICON_CHARGING_5_BIN                     (void *)(0x009c67f8)
#define   ICON_CHARGING_6_BIN                     (void *)(0x009c6bb8)
#define   ICON_CHARGING_7_BIN                     (void *)(0x009c6f78)
#define   ICON_CHARGING_BG_BIN                    (void *)(0x009c7338)
#define   CAPTION_1_BIN                           (void *)(0x009c7b78)
#define   CAPTION_2_BIN                           (void *)(0x009d3df8)
#define   CAPTION_3_30_BIN                        (void *)(0x009de878)
#define   CONTENT_1_BIN                           (void *)(0x009e9ef8)
#define   HEADING_1_BIN                           (void *)(0x009ecb78)
#define   HEADING_2_BIN                           (void *)(0x009f27f8)
#define   ICON_ASC_BIN                            (void *)(0x009f5b78)
#define   ICON_HR_AUDIO_BIN                       (void *)(0x009f61f8)
#define   ICON_AURACAST_BIN                       (void *)(0x009f6878)
#define   ICON_AUTO_PLAY_PAUSE_BIN                (void *)(0x009f6ef8)
#define   ICON_BT_SOURCE_BIN                      (void *)(0x009f7578)
#define   ICON_EQ_BIN                             (void *)(0x009f7bf8)
#define   ICON_PLAYBACK_BIN                       (void *)(0x009f8278)
#define   ICON_SMART_TALK_BIN                     (void *)(0x009f88f8)
#define   ICON_SPATIAL_SOUND_BIN                  (void *)(0x009f8f78)
#define   ICON_VOICE_AWARE_BIN                    (void *)(0x009f95f8)
#define   ICON_VOLUME_BIN                         (void *)(0x009f9c78)
#define   ICON_24HOUR_TIME_BIN                    (void *)(0x009fa3f8)
#define   ICON_AUTODIMOFFSCREEN_BIN               (void *)(0x009faa78)
#define   ICON_AUTOLOCKSCREEN_BIN                 (void *)(0x009fb0f8)
#define   ICON_BRIGHTNESS_BIN                     (void *)(0x009fb778)
#define   ICON_CASEBUTTON_BIN                     (void *)(0x009fbdf8)
#define   ICON_CLOCK_SETTINGS_BIN                 (void *)(0x009fc478)
#define   ICON_CUSTOMIZE_INFOCENTER_BIN           (void *)(0x009fcaf8)
#define   ICON_FACTORY_RESET_BIN                  (void *)(0x009fd178)
#define   ICON_ICON_WALLPAPER_BIN                 (void *)(0x009fd7f8)
#define   ICON_LANGUAGE_BIN                       (void *)(0x009fde78)
#define   ICON_LIGHTDARKMODE_BIN                  (void *)(0x009fe4f8)
#define   ICON_NOTIFICATION_BIN                   (void *)(0x009feb78)
#define   ICON_PRODUCT_TIPS_BIN                   (void *)(0x009ff1f8)
#define   ICON_QUICKWAKEUP_BIN                    (void *)(0x009ff878)
#define   ICON_REORDER_BIN                        (void *)(0x009ffef8)
#define   ICON_SUPPORT_BIN                        (void *)(0x00a00578)
#define   ICON_TX_MANAGER_BIN                     (void *)(0x00a00bf8)
#define   ICON_BACK_BIN                           (void *)(0x00a01278)
#define   ICON_FLASHLIGHT_BIN                     (void *)(0x00a01ab8)
#define   ICON_ICON_APP_BIN                       (void *)(0x00a02138)
#define   ICON_SILENTNOW_BIN                      (void *)(0x00a027b8)
#define   ICON_TIMER_BIN                          (void *)(0x00a02e38)
#define   ICON_VOLUME_UNIT_METER_BIN              (void *)(0x00a034b8)
#define   BUTTON_BG_ELLIPSE_240_48_BIN            (void *)(0x00a03c78)
#define   ICON_LOCK_TAB_BIN                       (void *)(0x00a069b8)
#define   ICON_UNLOCK_BIN                         (void *)(0x00a084f8)
#define   WALLPAPER_1_BIN                         (void *)(0x00a08838)
#define   WALLPAPER_1_DARK_BIN                    (void *)(0x00a27c78)
#define   WALLPAPER_1_LIGHT_BIN                   (void *)(0x00a2ccb8)
#define   WALLPAPER_2_BIN                         (void *)(0x00a31cf8)
#define   WALLPAPER_2_DARK_BIN                    (void *)(0x00a51138)
#define   WALLPAPER_2_LIGHT_BIN                   (void *)(0x00a56178)
#define   WALLPAPER_3_BIN                         (void *)(0x00a5b1b8)
#define   WALLPAPER_3_DARK_BIN                    (void *)(0x00a7a5f8)
#define   WALLPAPER_3_LIGHT_BIN                   (void *)(0x00a7f638)
#define   WALLPAPER_4_BIN                         (void *)(0x00a84678)
#define   WALLPAPER_4_DARK_BIN                    (void *)(0x00aa3ab8)
#define   WALLPAPER_4_LIGHT_BIN                   (void *)(0x00aa8af8)
#define   WALLPAPER_5_BIN                         (void *)(0x00aadb38)
#define   WALLPAPER_5_DARK_BIN                    (void *)(0x00accf78)
#define   WALLPAPER_5_LIGHT_BIN                   (void *)(0x00ad1fb8)
#define   MASK_BIN                                (void *)(0x00ad7078)
#define   MENU_AUDIO_BIN                          (void *)(0x00adbbb8)
#define   MENU_AUDIO_SCALE_BIN                    (void *)(0x00adc378)
#define   MENU_BUTTON_BG_BIN                      (void *)(0x00adcbf8)
#define   MENU_BUTTON_BG_SCALE_BIN                (void *)(0x00ade538)
#define   MENU_LISTNOTE_BG_BIN                    (void *)(0x00ae0c78)
#define   MENU_SETTINGS_BIN                       (void *)(0x00ae4bb8)
#define   MENU_SETTINGS_SCALE_BIN                 (void *)(0x00ae5378)
#define   MENU_TOOLS_BIN                          (void *)(0x00ae5b78)
#define   MENU_TOOLS_SCALE_BIN                    (void *)(0x00ae6338)
#define   JBL_BIN                                 (void *)(0x00ae6bb8)
#define   BUTTON_GET_START_BIN                    (void *)(0x00aecb78)
#define   ADD_BIN                                 (void *)(0x00aeff78)
#define   ICON_AURACAST_SMALL_BIN                 (void *)(0x00af03b8)
#define   ICON_CONNECT_BIN                        (void *)(0x00af0638)
#define   ICON_DELETE_BIN                         (void *)(0x00af0978)
#define   ICON_DISCONNECT_BIN                     (void *)(0x00af0cb8)
#define   ICON_HQ_BIN                             (void *)(0x00af0ff8)
#define   ICON_SELECTED_BIN                       (void *)(0x00af1338)
#define   BASS_BIN                                (void *)(0x00af15b8)
#define   BG_CIRCLE_40_BIN                        (void *)(0x00af3cb8)
#define   BUTTON_BG_CIRCLE_BIN                    (void *)(0x00af4338)
#define   BUTTON_BG_ELLIPSE_BIN                   (void *)(0x00af5b38)
#define   BUTTON_BG_ELLIPSE_134_66_BIN            (void *)(0x00af7d78)
#define   BUTTON_BG_ELLIPSE_148_88_BIN            (void *)(0x00afa038)
#define   BUTTON_BG_ELLIPSE_201_80_BIN            (void *)(0x00afd378)
#define   BUTTON_BG_ELLIPSE_240_80_BIN            (void *)(0x00b01278)
#define   BUTTON_BG_ELLIPSE_312_56_BIN            (void *)(0x00b05db8)
#define   BUTTON_BG_ELLIPSE_312_56_BOT_BIN        (void *)(0x00b0a238)
#define   BUTTON_BG_ELLIPSE_312_56_MID_BIN        (void *)(0x00b0e6b8)
#define   BUTTON_BG_ELLIPSE_312_56_TOP_BIN        (void *)(0x00b12b38)
#define   BUTTON_BG_ELLIPSE_56_60_BIN             (void *)(0x00b16fb8)
#define   BUTTON_BG_ELLIPSE_60_64_BIN             (void *)(0x00b17d38)
#define   BUTTON_BG_ELLIPSE_64_40_BIN             (void *)(0x00b18c78)
#define   BUTTON_BG_ELLIPSE_90_68_BIN             (void *)(0x00b196b8)
#define   BUTTON_BG_RECT_BIN                      (void *)(0x00b1aef8)
#define   CLUB_BIN                                (void *)(0x00b1c138)
#define   CONTROL_BG_BIN                          (void *)(0x00b1e838)
#define   EXTRE_BASS_BIN                          (void *)(0x00b25078)
#define   ICON_AA_BIN                             (void *)(0x00b27778)
#define   ICON_ANC_BIN                            (void *)(0x00b280b8)
#define   ICON_ARROW_DOWN_BIN                     (void *)(0x00b28a38)
#define   ICON_ARROW_R_BIG_BIN                    (void *)(0x00b28b78)
#define   ICON_ARROW_UP_BIN                       (void *)(0x00b28cb8)
#define   ICON_CLICK_BIN                          (void *)(0x00b28df8)
#define   ICON_CLICK_DOUBLE_BIN                   (void *)(0x00b294f8)
#define   ICON_CLICK_TRIPLE_BIN                   (void *)(0x00b29bf8)
#define   ICON_DARK_BIN                           (void *)(0x00b2a2f8)
#define   ICON_DONE_BIN                           (void *)(0x00b2a978)
#define   ICON_FLASHLIGHT_OFF_BIN                 (void *)(0x00b2b078)
#define   ICON_FLASHLIGHT_ON_BIN                  (void *)(0x00b2b4f8)
#define   ICON_HEAD_TRACKING_BIN                  (void *)(0x00b2b7f8)
#define   ICON_L_BIN                              (void *)(0x00b2bdb8)
#define   ICON_LIGHT_BIN                          (void *)(0x00b2c578)
#define   ICON_MAIL_BIN                           (void *)(0x00b2cbf8)
#define   ICON_R_BIN                              (void *)(0x00b2cd78)
#define   ICON_RESET_BIG_BIN                      (void *)(0x00b2d538)
#define   ICON_SETTINGS_BIN                       (void *)(0x00b2db38)
#define   ICON_SS_OFF_BIN                         (void *)(0x00b2ddb8)
#define   ICON_SS_ON_BIN                          (void *)(0x00b2e378)
#define   ICON_TT_BIN                             (void *)(0x00b2e938)
#define   JAZZ_BIN                                (void *)(0x00b2f278)
#define   MASK_320_14_BIN                         (void *)(0x00b31978)
#define   MASK_320_40_BIN                         (void *)(0x00b32b38)
#define   MASK_320_82_BIN                         (void *)(0x00b35d78)
#define   MASK_FADE_BOTTOM_BIN                    (void *)(0x00b3c438)
#define   MASK_FADE_TOP_BIN                       (void *)(0x00b3f9b8)
#define   PAGE_INDICATOR_BIN                      (void *)(0x00b42f38)
#define   PAUSE_BIN                               (void *)(0x00b42f78)
#define   PAUSE_SMALL_BIN                         (void *)(0x00b43538)
#define   PLAY_BIN                                (void *)(0x00b43738)
#define   PLAY_SMALL_BIN                          (void *)(0x00b43e38)
#define   PAGE_INDICATOR_HEART_BIN                (void *)(0x00b440f8)
#define   TIP_2_FG_DARK_BIN                       (void *)(0x00b44178)
#define   TIP_2_FG_LIGHT_BIN                      (void *)(0x00b491b8)
#define   TIP_3_FG_DARK_BIN                       (void *)(0x00b4e1f8)
#define   TIP_3_FG_LIGHT_BIN                      (void *)(0x00b55a38)
#define   TIP_4_FG_DARK_BIN                       (void *)(0x00b5d278)
#define   TIP_4_FG_LIGHT_BIN                      (void *)(0x00b64ab8)
#define   TIP_5_FG_DARK_BIN                       (void *)(0x00b6c2f8)
#define   TIP_5_FG_LIGHT_BIN                      (void *)(0x00b71938)
#define   PROGRESSBAR_1_BIN                       (void *)(0x00b76f78)
#define   PROGRESSBAR_10_BIN                      (void *)(0x00b770b8)
#define   PROGRESSBAR_11_BIN                      (void *)(0x00b77ab8)
#define   PROGRESSBAR_12_BIN                      (void *)(0x00b785b8)
#define   PROGRESSBAR_13_BIN                      (void *)(0x00b791b8)
#define   PROGRESSBAR_14_BIN                      (void *)(0x00b79eb8)
#define   PROGRESSBAR_15_BIN                      (void *)(0x00b7acb8)
#define   PROGRESSBAR_16_BIN                      (void *)(0x00b7bbb8)
#define   PROGRESSBAR_2_BIN                       (void *)(0x00b7cbb8)
#define   PROGRESSBAR_3_BIN                       (void *)(0x00b7cdf8)
#define   PROGRESSBAR_4_BIN                       (void *)(0x00b7d138)
#define   PROGRESSBAR_5_BIN                       (void *)(0x00b7d578)
#define   PROGRESSBAR_6_BIN                       (void *)(0x00b7dab8)
#define   PROGRESSBAR_7_BIN                       (void *)(0x00b7e0f8)
#define   PROGRESSBAR_8_BIN                       (void *)(0x00b7e7f8)
#define   PROGRESSBAR_9_BIN                       (void *)(0x00b7eff8)
#define   QRCODE_BIN                              (void *)(0x00b7f8f8)
#define   SECTION_BAR_1_BIN                       (void *)(0x00b88c38)
#define   SECTION_BAR_2_BIN                       (void *)(0x00b89cb8)
#define   SECTION_BAR_3_BIN                       (void *)(0x00b8ad38)
#define   SELECTOR_BG_BIN                         (void *)(0x00b8bdb8)
#define   SELECTOR_CIRCLE_BIN                     (void *)(0x00b8c078)
#define   ICON_BELL_BOT_BIN                       (void *)(0x00b8c178)
#define   ICON_BELL_TOP_BIN                       (void *)(0x00b8c1f8)
#define   ICON_CANCEL_BIN                         (void *)(0x00b8c3b8)
#define   ICON_SILENT_BIN                         (void *)(0x00b8c578)
#define   ICON_SILENT_CIRCLE_BIN                  (void *)(0x00b8c838)
#define   ICON_SILENT_CIRCLE_SMALL_BIN            (void *)(0x00b8ccb8)
#define   ICON_SILENT_SMALL_BIN                   (void *)(0x00b8cfb8)
#define   SKIP_LAST_BIN                           (void *)(0x00b8d178)
#define   SKIP_NEXT_BIN                           (void *)(0x00b8d5f8)
#define   SMART_TALK_15S_BIN                      (void *)(0x00b8da78)
#define   SMART_TALK_20S_BIN                      (void *)(0x00b8e5f8)
#define   SMART_TALK_5S_BIN                       (void *)(0x00b8f178)
#define   SPATIAL_SOUND_GAME_BIN                  (void *)(0x00b8fcf8)
#define   SPATIAL_SOUND_MOVIE_BIN                 (void *)(0x00b90638)
#define   SPATIAL_SOUND_MUSIC_BIN                 (void *)(0x00b90f78)
#define   STRENGTH_BAR_BIN                        (void *)(0x00b918b8)
#define   STUDIO_BIN                              (void *)(0x00b91a78)
#define   SUB_BIN                                 (void *)(0x00b94178)
#define   SWITCH_L_BIN                            (void *)(0x00b94278)
#define   SWITCH_R_BIN                            (void *)(0x00b944f8)
#define   TIME_FORMAT_12_BIN                      (void *)(0x00b947b8)
#define   TIME_FORMAT_24_BIN                      (void *)(0x00b94e78)
#define   ICON_BELL_PART_1_BIN                    (void *)(0x00b959f8)
#define   ICON_BELL_PART_2_BIN                    (void *)(0x00b95c38)
#define   ICON_CANCEL_BIG_BIN                     (void *)(0x00b95cf8)
#define   PROGRESS_CIRCLE_0_BIN                   (void *)(0x00b95ff8)
#define   PROGRESS_CIRCLE_1_BIN                   (void *)(0x00b962f8)
#define   PROGRESS_CIRCLE_10_BIN                  (void *)(0x00b96638)
#define   PROGRESS_CIRCLE_11_BIN                  (void *)(0x00b96938)
#define   PROGRESS_CIRCLE_12_BIN                  (void *)(0x00b96c38)
#define   PROGRESS_CIRCLE_13_BIN                  (void *)(0x00b96f38)
#define   PROGRESS_CIRCLE_14_BIN                  (void *)(0x00b97238)
#define   PROGRESS_CIRCLE_15_BIN                  (void *)(0x00b97538)
#define   PROGRESS_CIRCLE_16_BIN                  (void *)(0x00b97838)
#define   PROGRESS_CIRCLE_17_BIN                  (void *)(0x00b97b38)
#define   PROGRESS_CIRCLE_18_BIN                  (void *)(0x00b97e38)
#define   PROGRESS_CIRCLE_19_BIN                  (void *)(0x00b98138)
#define   PROGRESS_CIRCLE_2_BIN                   (void *)(0x00b98438)
#define   PROGRESS_CIRCLE_20_BIN                  (void *)(0x00b98778)
#define   PROGRESS_CIRCLE_21_BIN                  (void *)(0x00b98a78)
#define   PROGRESS_CIRCLE_22_BIN                  (void *)(0x00b98d78)
#define   PROGRESS_CIRCLE_23_BIN                  (void *)(0x00b99078)
#define   PROGRESS_CIRCLE_24_BIN                  (void *)(0x00b99378)
#define   PROGRESS_CIRCLE_25_BIN                  (void *)(0x00b99678)
#define   PROGRESS_CIRCLE_26_BIN                  (void *)(0x00b999b8)
#define   PROGRESS_CIRCLE_27_BIN                  (void *)(0x00b99cf8)
#define   PROGRESS_CIRCLE_28_BIN                  (void *)(0x00b99ff8)
#define   PROGRESS_CIRCLE_29_BIN                  (void *)(0x00b9a2f8)
#define   PROGRESS_CIRCLE_3_BIN                   (void *)(0x00b9a5f8)
#define   PROGRESS_CIRCLE_30_BIN                  (void *)(0x00b9a8f8)
#define   PROGRESS_CIRCLE_31_BIN                  (void *)(0x00b9abf8)
#define   PROGRESS_CIRCLE_32_BIN                  (void *)(0x00b9aef8)
#define   PROGRESS_CIRCLE_33_BIN                  (void *)(0x00b9b1f8)
#define   PROGRESS_CIRCLE_34_BIN                  (void *)(0x00b9b4f8)
#define   PROGRESS_CIRCLE_35_BIN                  (void *)(0x00b9b7f8)
#define   PROGRESS_CIRCLE_36_BIN                  (void *)(0x00b9baf8)
#define   PROGRESS_CIRCLE_37_BIN                  (void *)(0x00b9bdf8)
#define   PROGRESS_CIRCLE_38_BIN                  (void *)(0x00b9c0f8)
#define   PROGRESS_CIRCLE_39_BIN                  (void *)(0x00b9c3f8)
#define   PROGRESS_CIRCLE_4_BIN                   (void *)(0x00b9c6f8)
#define   PROGRESS_CIRCLE_40_BIN                  (void *)(0x00b9c9f8)
#define   PROGRESS_CIRCLE_41_BIN                  (void *)(0x00b9ccf8)
#define   PROGRESS_CIRCLE_42_BIN                  (void *)(0x00b9cff8)
#define   PROGRESS_CIRCLE_43_BIN                  (void *)(0x00b9d2f8)
#define   PROGRESS_CIRCLE_44_BIN                  (void *)(0x00b9d5f8)
#define   PROGRESS_CIRCLE_45_BIN                  (void *)(0x00b9d8f8)
#define   PROGRESS_CIRCLE_46_BIN                  (void *)(0x00b9dbf8)
#define   PROGRESS_CIRCLE_47_BIN                  (void *)(0x00b9def8)
#define   PROGRESS_CIRCLE_48_BIN                  (void *)(0x00b9e1f8)
#define   PROGRESS_CIRCLE_49_BIN                  (void *)(0x00b9e4f8)
#define   PROGRESS_CIRCLE_5_BIN                   (void *)(0x00b9e7f8)
#define   PROGRESS_CIRCLE_6_BIN                   (void *)(0x00b9eaf8)
#define   PROGRESS_CIRCLE_7_BIN                   (void *)(0x00b9edf8)
#define   PROGRESS_CIRCLE_8_BIN                   (void *)(0x00b9f0f8)
#define   PROGRESS_CIRCLE_9_BIN                   (void *)(0x00b9f3f8)
#define   TIMER_PAUSE_BIN                         (void *)(0x00b9f6f8)
#define   TIMER_PLAY_BIN                          (void *)(0x00b9f9b8)
#define   TIMER_PLAY_BIG_BIN                      (void *)(0x00b9fb78)
#define   TIMER_RESET_BIN                         (void *)(0x00b9fe38)
#define   TOGGLE_BIN                              (void *)(0x00ba0178)
#define   TOGGLE_BG_BIN                           (void *)(0x00ba05b8)
#define   VOCAL_BIN                               (void *)(0x00ba0ff8)
#define   SCROLLBAR_BG_BIN                        (void *)(0x00ba36f8)
#define   SCROLLBAR_L_BIN                         (void *)(0x00ba3978)
#define   SCROLLBAR_M_BIN                         (void *)(0x00ba3b78)
#define   SCROLLBAR_S_BIN                         (void *)(0x00ba3cf8)
#define   BUTTON_BG_ELLIPSE_142_64_BIN            (void *)(0x00ba3f38)
#define   BUTTON_BG_ELLIPSE_194_68_BIN            (void *)(0x00ba62f8)
#define   BUTTON_BG_ELLIPSE_296_68_BIN            (void *)(0x00ba96b8)
#define   ICON_ARROW_R_BIN                        (void *)(0x00bae578)
#define   ICON_BT_CONNECT_BIN                     (void *)(0x00bae638)
#define   ICON_BT_DISCONNECT_BIN                  (void *)(0x00bae6f8)
#define   ICON_CALL_BIN                           (void *)(0x00bae7f8)
#define   ICON_CALL_MEDIUM_BIN                    (void *)(0x00bae938)
#define   ICON_CHARGING_SMALL_BIN                 (void *)(0x00baec78)
#define   ICON_CUSTOMIZE_INFOCENTER_SMALL_BIN     (void *)(0x00baecf8)
#define   ICON_HEADBAND_BIN                       (void *)(0x00baeef8)
#define   ICON_HEADBAND_SMALL_BIN                 (void *)(0x00baf178)
#define   ICON_IS_FAVORITE_BIN                    (void *)(0x00baf278)
#define   ICON_MESSAGE_BIN                        (void *)(0x00baf5b8)
#define   ICON_MESSAGE_SMALL_BIN                  (void *)(0x00bafc38)
#define   ICON_NOT_FAVORITE_BIN                   (void *)(0x00bafdb8)
#define   ICON_TIMER_MEDIUM_BIN                   (void *)(0x00bb00f8)
#define   ICON_TIMER_SMALL_BIN                    (void *)(0x00bb0338)
#define   ICON_TX_INNER_BIN                       (void *)(0x00bb0478)
#define   ICON_TX_INNER_SMALL_BIN                 (void *)(0x00bb0538)
#define   ICON_TX_OUTER_BIN                       (void *)(0x00bb05b8)
#define   ICON_TX_OUTER_SMALL_BIN                 (void *)(0x00bb0738)
#define   STATUSBAR_HOME_BG_BIN                   (void *)(0x00bb0838)

#endif
