#if defined _WIN32
extern unsigned char *resource_root;

#define   BATTERY_CHARGING_BG_BIN                 (void *)(resource_root + 0x000001b8)
#define   BATTERY_CHARGING_BG_NEW_BIN             (void *)(resource_root + 0x0001f5f8)
#define   BATTERY_CHARGING_MID_BG_BIN             (void *)(resource_root + 0x0002f038)
#define   BATTERY_CHARGING_TOP_BG_BIN             (void *)(resource_root + 0x00034878)
#define   ICON_CHARGING_0_BIN                     (void *)(resource_root + 0x000442b8)
#define   ICON_CHARGING_1_BIN                     (void *)(resource_root + 0x00044678)
#define   ICON_CHARGING_2_BIN                     (void *)(resource_root + 0x00044a38)
#define   ICON_CHARGING_3_BIN                     (void *)(resource_root + 0x00044df8)
#define   ICON_CHARGING_4_BIN                     (void *)(resource_root + 0x000451b8)
#define   ICON_CHARGING_5_BIN                     (void *)(resource_root + 0x00045578)
#define   ICON_CHARGING_6_BIN                     (void *)(resource_root + 0x00045938)
#define   ICON_CHARGING_7_BIN                     (void *)(resource_root + 0x00045cf8)
#define   ICON_CHARGING_BG_BIN                    (void *)(resource_root + 0x000460b8)
#define   CLOCK3_VECTOR_BIN                       (void *)(resource_root + 0x000468f8)
#define   CLOCK3_CENTER_BIN                       (void *)(resource_root + 0x00056338)
#define   CLOCK3_HOUR_BIN                         (void *)(resource_root + 0x00056678)
#define   CLOCK3_MIN_BIN                          (void *)(resource_root + 0x000577b8)
#define   CLOCK4_VECTOR_BIN                       (void *)(resource_root + 0x00058b78)
#define   CAPTION_1_BIN                           (void *)(resource_root + 0x00062838)
#define   CAPTION_2_BIN                           (void *)(resource_root + 0x0006eab8)
#define   CONTENT_1_BIN                           (void *)(resource_root + 0x00079538)
#define   HEADING_1_BIN                           (void *)(resource_root + 0x0007c1b8)
#define   HEADING_2_BIN                           (void *)(resource_root + 0x00081e38)
#define   ICON_ASC_BIN                            (void *)(resource_root + 0x000851b8)
#define   ICON_AURACAST_BIN                       (void *)(resource_root + 0x00085838)
#define   ICON_AUTO_PLAY_PAUSE_BIN                (void *)(resource_root + 0x00085eb8)
#define   ICON_BT_SOURCE_BIN                      (void *)(resource_root + 0x00086538)
#define   ICON_EARTIP_BIN                         (void *)(resource_root + 0x00086bb8)
#define   ICON_EQ_BIN                             (void *)(resource_root + 0x00087238)
#define   ICON_PLAYBACK_BIN                       (void *)(resource_root + 0x000878b8)
#define   ICON_SMART_TALK_BIN                     (void *)(resource_root + 0x00087f38)
#define   ICON_SPATIAL_SOUND_BIN                  (void *)(resource_root + 0x000885b8)
#define   ICON_VOICE_AWARE_BIN                    (void *)(resource_root + 0x00088c38)
#define   ICON_VOLUME_BIN                         (void *)(resource_root + 0x000892b8)
#define   ICON_24HOUR_TIME_BIN                    (void *)(resource_root + 0x00089a38)
#define   ICON_AUTODIMOFFSCREEN_BIN               (void *)(resource_root + 0x0008a0b8)
#define   ICON_AUTOLOCKSCREEN_BIN                 (void *)(resource_root + 0x0008a738)
#define   ICON_BRIGHTNESS_BIN                     (void *)(resource_root + 0x0008adb8)
#define   ICON_CASEBUTTON_BIN                     (void *)(resource_root + 0x0008b438)
#define   ICON_CUSTOMIZE_INFOCENTER_BIN           (void *)(resource_root + 0x0008bab8)
#define   ICON_FACTORY_RESET_BIN                  (void *)(resource_root + 0x0008c138)
#define   ICON_ICON_WALLPAPER_BIN                 (void *)(resource_root + 0x0008c7b8)
#define   ICON_LANGUAGE_BIN                       (void *)(resource_root + 0x0008ce38)
#define   ICON_LIGHTDARKMODE_BIN                  (void *)(resource_root + 0x0008d4b8)
#define   ICON_MESSAGE_BIN                        (void *)(resource_root + 0x0008db38)
#define   ICON_PRODUCT_TIPS_BIN                   (void *)(resource_root + 0x0008e1b8)
#define   ICON_QUICKWAKEUP_BIN                    (void *)(resource_root + 0x0008e838)
#define   ICON_REORDER_BIN                        (void *)(resource_root + 0x0008eeb8)
#define   ICON_SUPPORT_BIN                        (void *)(resource_root + 0x0008f538)
#define   ICON_BACK_BIN                           (void *)(resource_root + 0x0008fbb8)
#define   MASK_BIN                                (void *)(resource_root + 0x000903b8)
#define   ICON_FINDMYBUDS_BIN                     (void *)(resource_root + 0x00094f38)
#define   ICON_FLASHLIGHT_BIN                     (void *)(resource_root + 0x000955b8)
#define   ICON_ICON_APP_BIN                       (void *)(resource_root + 0x00095c38)
#define   ICON_TIMER_BIN                          (void *)(resource_root + 0x000962b8)
#define   DEFAULT_BIN                             (void *)(resource_root + 0x00096978)
#define   ICON_TOUCH_BIN                          (void *)(resource_root + 0x0009b5b8)
#define   ICON_UNLOCK_BIN                         (void *)(resource_root + 0x0009baf8)
#define   LOCK_SCROLLBAR_BG_BIN                   (void *)(resource_root + 0x0009c038)
#define   TAB_BG_BIN                              (void *)(resource_root + 0x000a1a78)
#define   TAP_BIN                                 (void *)(resource_root + 0x000a33b8)
#define   MENU_AUDIO_BIN                          (void *)(resource_root + 0x000a8078)
#define   MENU_AUDIO_SCALE_BIN                    (void *)(resource_root + 0x000a8838)
#define   MENU_BUTTON_BG_BIN                      (void *)(resource_root + 0x000a90b8)
#define   MENU_BUTTON_BG_SCALE_BIN                (void *)(resource_root + 0x000aa9f8)
#define   MENU_SETTINGS_BIN                       (void *)(resource_root + 0x000ad138)
#define   MENU_SETTINGS_SCALE_BIN                 (void *)(resource_root + 0x000ad8f8)
#define   MENU_TOOLS_BIN                          (void *)(resource_root + 0x000ae0f8)
#define   MENU_TOOLS_SCALE_BIN                    (void *)(resource_root + 0x000ae8b8)
#define   ADD_BIN                                 (void *)(resource_root + 0x000af378)
#define   BASS_BIN                                (void *)(resource_root + 0x000af738)
#define   BUTTON_BG_CIRCLE_BIN                    (void *)(resource_root + 0x000b1e38)
#define   BUTTON_BG_ELLIPSE_BIN                   (void *)(resource_root + 0x000b3638)
#define   BUTTON_BG_ELLIPSE_148_88_BIN            (void *)(resource_root + 0x000b5878)
#define   BUTTON_BG_ELLIPSE_90_68_BIN             (void *)(resource_root + 0x000b8bb8)
#define   CLUB_BIN                                (void *)(resource_root + 0x000ba3b8)
#define   CONTROL_BG_BIN                          (void *)(resource_root + 0x000bcab8)
#define   EXTRE_BASS_BIN                          (void *)(resource_root + 0x000c32f8)
#define   ICON_AA_BIN                             (void *)(resource_root + 0x000c59f8)
#define   ICON_ANC_BIN                            (void *)(resource_root + 0x000c6338)
#define   ICON_DARK_BIN                           (void *)(resource_root + 0x000c6cb8)
#define   ICON_LIGHT_BIN                          (void *)(resource_root + 0x000c7338)
#define   ICON_MAIL_BIN                           (void *)(resource_root + 0x000c79b8)
#define   ICON_TT_BIN                             (void *)(resource_root + 0x000c7b38)
#define   JAZZ_BIN                                (void *)(resource_root + 0x000c8478)
#define   PAGE_INDICATOR_BIN                      (void *)(resource_root + 0x000cab78)
#define   PAUSE_BIN                               (void *)(resource_root + 0x000cabb8)
#define   PLAY_BIN                                (void *)(resource_root + 0x000cb138)
#define   PROGRESSBAR_1_BIN                       (void *)(resource_root + 0x000cb838)
#define   PROGRESSBAR_10_BIN                      (void *)(resource_root + 0x000cc8b8)
#define   PROGRESSBAR_2_BIN                       (void *)(resource_root + 0x000cd938)
#define   PROGRESSBAR_3_BIN                       (void *)(resource_root + 0x000ce9b8)
#define   PROGRESSBAR_4_BIN                       (void *)(resource_root + 0x000cfa38)
#define   PROGRESSBAR_5_BIN                       (void *)(resource_root + 0x000d0ab8)
#define   PROGRESSBAR_6_BIN                       (void *)(resource_root + 0x000d1b38)
#define   PROGRESSBAR_7_BIN                       (void *)(resource_root + 0x000d2bb8)
#define   PROGRESSBAR_8_BIN                       (void *)(resource_root + 0x000d3c38)
#define   PROGRESSBAR_9_BIN                       (void *)(resource_root + 0x000d4cb8)
#define   PROGRESSBAR_BG_BIN                      (void *)(resource_root + 0x000d5d38)
#define   SKIP_LAST_BIN                           (void *)(resource_root + 0x000d6db8)
#define   SKIP_NEXT_BIN                           (void *)(resource_root + 0x000d7238)
#define   STUDIO_BIN                              (void *)(resource_root + 0x000d76b8)
#define   SUB_BIN                                 (void *)(resource_root + 0x000d9db8)
#define   SWITCH_L_BIN                            (void *)(resource_root + 0x000d9eb8)
#define   SWITCH_R_BIN                            (void *)(resource_root + 0x000da138)
#define   TOGGLE_BIN                              (void *)(resource_root + 0x000da3f8)
#define   TOGGLE_BG_BIN                           (void *)(resource_root + 0x000da838)
#define   VOCAL_BIN                               (void *)(resource_root + 0x000db278)
#define   SCREEN_BG_BIN                           (void *)(resource_root + 0x000dd978)
#define   BARN_INNER_BIN                          (void *)(resource_root + 0x000ed4b8)
#define   BARN_INNER_BIG_BIN                      (void *)(resource_root + 0x000ed578)
#define   BARN_OUTER_BIN                          (void *)(resource_root + 0x000ed678)
#define   BARN_OUTER_BIG_BIN                      (void *)(resource_root + 0x000ed7b8)
#define   BATTERY_STATUS_BG_BIN                   (void *)(resource_root + 0x000ed9b8)
#define   BLUETOOTH_BIN                           (void *)(resource_root + 0x000f0a38)
#define   EARPLUG_BIG_L_BIN                       (void *)(resource_root + 0x000f0af8)
#define   EARPLUG_BIG_R_BIN                       (void *)(resource_root + 0x000f0c78)
#define   EARPLUG_L_BIN                           (void *)(resource_root + 0x000f0db8)
#define   EARPLUG_R_BIN                           (void *)(resource_root + 0x000f0e78)
#define   ICON_ARRAW_R_BIN                        (void *)(resource_root + 0x000f0f38)
#define   ICON_IS_FAVORITE_BIN                    (void *)(resource_root + 0x000f0ff8)
#define   ICON_MESSAGE_SMALL_BIN                  (void *)(resource_root + 0x000f1338)
#define   ICON_NOT_FAVORITE_BIN                   (void *)(resource_root + 0x000f14b8)
#define   STATUSBAR_HOME_BG_BIN                   (void *)(resource_root + 0x000f17f8)
#define   WALLPAPER_BIN                           (void *)(resource_root + 0x000f1cb8)

#else
#define   BATTERY_CHARGING_BG_BIN                 (void *)(0x009501b8)
#define   BATTERY_CHARGING_BG_NEW_BIN             (void *)(0x0096f5f8)
#define   BATTERY_CHARGING_MID_BG_BIN             (void *)(0x0097f038)
#define   BATTERY_CHARGING_TOP_BG_BIN             (void *)(0x00984878)
#define   ICON_CHARGING_0_BIN                     (void *)(0x009942b8)
#define   ICON_CHARGING_1_BIN                     (void *)(0x00994678)
#define   ICON_CHARGING_2_BIN                     (void *)(0x00994a38)
#define   ICON_CHARGING_3_BIN                     (void *)(0x00994df8)
#define   ICON_CHARGING_4_BIN                     (void *)(0x009951b8)
#define   ICON_CHARGING_5_BIN                     (void *)(0x00995578)
#define   ICON_CHARGING_6_BIN                     (void *)(0x00995938)
#define   ICON_CHARGING_7_BIN                     (void *)(0x00995cf8)
#define   ICON_CHARGING_BG_BIN                    (void *)(0x009960b8)
#define   CLOCK3_VECTOR_BIN                       (void *)(0x009968f8)
#define   CLOCK3_CENTER_BIN                       (void *)(0x009a6338)
#define   CLOCK3_HOUR_BIN                         (void *)(0x009a6678)
#define   CLOCK3_MIN_BIN                          (void *)(0x009a77b8)
#define   CLOCK4_VECTOR_BIN                       (void *)(0x009a8b78)
#define   CAPTION_1_BIN                           (void *)(0x009b2838)
#define   CAPTION_2_BIN                           (void *)(0x009beab8)
#define   CONTENT_1_BIN                           (void *)(0x009c9538)
#define   HEADING_1_BIN                           (void *)(0x009cc1b8)
#define   HEADING_2_BIN                           (void *)(0x009d1e38)
#define   ICON_ASC_BIN                            (void *)(0x009d51b8)
#define   ICON_AURACAST_BIN                       (void *)(0x009d5838)
#define   ICON_AUTO_PLAY_PAUSE_BIN                (void *)(0x009d5eb8)
#define   ICON_BT_SOURCE_BIN                      (void *)(0x009d6538)
#define   ICON_EARTIP_BIN                         (void *)(0x009d6bb8)
#define   ICON_EQ_BIN                             (void *)(0x009d7238)
#define   ICON_PLAYBACK_BIN                       (void *)(0x009d78b8)
#define   ICON_SMART_TALK_BIN                     (void *)(0x009d7f38)
#define   ICON_SPATIAL_SOUND_BIN                  (void *)(0x009d85b8)
#define   ICON_VOICE_AWARE_BIN                    (void *)(0x009d8c38)
#define   ICON_VOLUME_BIN                         (void *)(0x009d92b8)
#define   ICON_24HOUR_TIME_BIN                    (void *)(0x009d9a38)
#define   ICON_AUTODIMOFFSCREEN_BIN               (void *)(0x009da0b8)
#define   ICON_AUTOLOCKSCREEN_BIN                 (void *)(0x009da738)
#define   ICON_BRIGHTNESS_BIN                     (void *)(0x009dadb8)
#define   ICON_CASEBUTTON_BIN                     (void *)(0x009db438)
#define   ICON_CUSTOMIZE_INFOCENTER_BIN           (void *)(0x009dbab8)
#define   ICON_FACTORY_RESET_BIN                  (void *)(0x009dc138)
#define   ICON_ICON_WALLPAPER_BIN                 (void *)(0x009dc7b8)
#define   ICON_LANGUAGE_BIN                       (void *)(0x009dce38)
#define   ICON_LIGHTDARKMODE_BIN                  (void *)(0x009dd4b8)
#define   ICON_MESSAGE_BIN                        (void *)(0x009ddb38)
#define   ICON_PRODUCT_TIPS_BIN                   (void *)(0x009de1b8)
#define   ICON_QUICKWAKEUP_BIN                    (void *)(0x009de838)
#define   ICON_REORDER_BIN                        (void *)(0x009deeb8)
#define   ICON_SUPPORT_BIN                        (void *)(0x009df538)
#define   ICON_BACK_BIN                           (void *)(0x009dfbb8)
#define   MASK_BIN                                (void *)(0x009e03b8)
#define   ICON_FINDMYBUDS_BIN                     (void *)(0x009e4f38)
#define   ICON_FLASHLIGHT_BIN                     (void *)(0x009e55b8)
#define   ICON_ICON_APP_BIN                       (void *)(0x009e5c38)
#define   ICON_TIMER_BIN                          (void *)(0x009e62b8)
#define   DEFAULT_BIN                             (void *)(0x009e6978)
#define   ICON_TOUCH_BIN                          (void *)(0x009eb5b8)
#define   ICON_UNLOCK_BIN                         (void *)(0x009ebaf8)
#define   LOCK_SCROLLBAR_BG_BIN                   (void *)(0x009ec038)
#define   TAB_BG_BIN                              (void *)(0x009f1a78)
#define   TAP_BIN                                 (void *)(0x009f33b8)
#define   MENU_AUDIO_BIN                          (void *)(0x009f8078)
#define   MENU_AUDIO_SCALE_BIN                    (void *)(0x009f8838)
#define   MENU_BUTTON_BG_BIN                      (void *)(0x009f90b8)
#define   MENU_BUTTON_BG_SCALE_BIN                (void *)(0x009fa9f8)
#define   MENU_SETTINGS_BIN                       (void *)(0x009fd138)
#define   MENU_SETTINGS_SCALE_BIN                 (void *)(0x009fd8f8)
#define   MENU_TOOLS_BIN                          (void *)(0x009fe0f8)
#define   MENU_TOOLS_SCALE_BIN                    (void *)(0x009fe8b8)
#define   ADD_BIN                                 (void *)(0x009ff378)
#define   BASS_BIN                                (void *)(0x009ff738)
#define   BUTTON_BG_CIRCLE_BIN                    (void *)(0x00a01e38)
#define   BUTTON_BG_ELLIPSE_BIN                   (void *)(0x00a03638)
#define   BUTTON_BG_ELLIPSE_148_88_BIN            (void *)(0x00a05878)
#define   BUTTON_BG_ELLIPSE_90_68_BIN             (void *)(0x00a08bb8)
#define   CLUB_BIN                                (void *)(0x00a0a3b8)
#define   CONTROL_BG_BIN                          (void *)(0x00a0cab8)
#define   EXTRE_BASS_BIN                          (void *)(0x00a132f8)
#define   ICON_AA_BIN                             (void *)(0x00a159f8)
#define   ICON_ANC_BIN                            (void *)(0x00a16338)
#define   ICON_DARK_BIN                           (void *)(0x00a16cb8)
#define   ICON_LIGHT_BIN                          (void *)(0x00a17338)
#define   ICON_MAIL_BIN                           (void *)(0x00a179b8)
#define   ICON_TT_BIN                             (void *)(0x00a17b38)
#define   JAZZ_BIN                                (void *)(0x00a18478)
#define   PAGE_INDICATOR_BIN                      (void *)(0x00a1ab78)
#define   PAUSE_BIN                               (void *)(0x00a1abb8)
#define   PLAY_BIN                                (void *)(0x00a1b138)
#define   PROGRESSBAR_1_BIN                       (void *)(0x00a1b838)
#define   PROGRESSBAR_10_BIN                      (void *)(0x00a1c8b8)
#define   PROGRESSBAR_2_BIN                       (void *)(0x00a1d938)
#define   PROGRESSBAR_3_BIN                       (void *)(0x00a1e9b8)
#define   PROGRESSBAR_4_BIN                       (void *)(0x00a1fa38)
#define   PROGRESSBAR_5_BIN                       (void *)(0x00a20ab8)
#define   PROGRESSBAR_6_BIN                       (void *)(0x00a21b38)
#define   PROGRESSBAR_7_BIN                       (void *)(0x00a22bb8)
#define   PROGRESSBAR_8_BIN                       (void *)(0x00a23c38)
#define   PROGRESSBAR_9_BIN                       (void *)(0x00a24cb8)
#define   PROGRESSBAR_BG_BIN                      (void *)(0x00a25d38)
#define   SKIP_LAST_BIN                           (void *)(0x00a26db8)
#define   SKIP_NEXT_BIN                           (void *)(0x00a27238)
#define   STUDIO_BIN                              (void *)(0x00a276b8)
#define   SUB_BIN                                 (void *)(0x00a29db8)
#define   SWITCH_L_BIN                            (void *)(0x00a29eb8)
#define   SWITCH_R_BIN                            (void *)(0x00a2a138)
#define   TOGGLE_BIN                              (void *)(0x00a2a3f8)
#define   TOGGLE_BG_BIN                           (void *)(0x00a2a838)
#define   VOCAL_BIN                               (void *)(0x00a2b278)
#define   SCREEN_BG_BIN                           (void *)(0x00a2d978)
#define   BARN_INNER_BIN                          (void *)(0x00a3d4b8)
#define   BARN_INNER_BIG_BIN                      (void *)(0x00a3d578)
#define   BARN_OUTER_BIN                          (void *)(0x00a3d678)
#define   BARN_OUTER_BIG_BIN                      (void *)(0x00a3d7b8)
#define   BATTERY_STATUS_BG_BIN                   (void *)(0x00a3d9b8)
#define   BLUETOOTH_BIN                           (void *)(0x00a40a38)
#define   EARPLUG_BIG_L_BIN                       (void *)(0x00a40af8)
#define   EARPLUG_BIG_R_BIN                       (void *)(0x00a40c78)
#define   EARPLUG_L_BIN                           (void *)(0x00a40db8)
#define   EARPLUG_R_BIN                           (void *)(0x00a40e78)
#define   ICON_ARRAW_R_BIN                        (void *)(0x00a40f38)
#define   ICON_IS_FAVORITE_BIN                    (void *)(0x00a40ff8)
#define   ICON_MESSAGE_SMALL_BIN                  (void *)(0x00a41338)
#define   ICON_NOT_FAVORITE_BIN                   (void *)(0x00a414b8)
#define   STATUSBAR_HOME_BG_BIN                   (void *)(0x00a417f8)
#define   WALLPAPER_BIN                           (void *)(0x00a41cb8)

#endif
