# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

objs = DefineGroup('realgui/engine', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('objs')
