# RTK building script for GuiEngine

import os

from building import *

cwd = GetCurrentDir()

src = Glob('*.c')
CPPPATH = [cwd]


group = DefineGroup('vg_lite', src, depend = [''], CPPPATH = CPPPATH)


Return('group')
