
SET(CMAKE_SYSTEM_NAME Generic)


SET(CMAKE_SYSTEM_PROCESSOR arm)


SET(CMAKE_C_COMPILER arm-none-eabi-gcc)
SET(CMAKE_CXX_COMPILER arm-none-eabi-g++)

SET(CMAKE_C_FLAGS "-mcpu=cortex-m3 -mthumb" CACHE STRING "" FORCE)
SET(CMAKE_CXX_FLAGS "-mcpu=cortex-m3 -mthumb" CACHE STRING "" FORCE)
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -specs=nosys.specs")


SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


