# for module compiling
import os
Import('TOOL_ROOT')
Import('RTK_GUI_ENGINE')

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd, 
           RTK_GUI_ENGINE + '/example/root_image/']



#src = Glob('*.c')
src = ['main.c']
if GetDepend('CONFIG_REALTEK_BUILD_LETTER_SHELL'):
    src += ['test_cmd.c']

CPPDEFINES = ['GUI_WIN32_SIM']

if GetDepend('CONFIG_REALTEK_BUILD_LVGL_GUI'):
    CPPDEFINES += ['LV_KCONFIG_IGNORE']
    CPPDEFINES += ['LV_LVGL_H_INCLUDE_SIMPLE']
    CPPDEFINES += ['LV_USE_DEMO_BENCHMARK']
    CPPDEFINES += ['LV_USE_DEMO_WIDGETS']

objs = DefineGroup('rtk_gui', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
