# for module compiling
import os
Import('TOOL_ROOT')
Import('RTK_GUI_ENGINE')

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd,
           RTK_GUI_ENGINE + '/example/root_image/']



#src = Glob('*.c')
src = ['main.c']
src += ['version.o']


CPPDEFINES = ['GUI_WIN32_SIM']


objs = DefineGroup('rtk_gui', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
