#building script for HoneyGUI Widget

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


CPPPATH = [cwd]

objs = DefineGroup('realgui/widget', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
