# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]

objs = DefineGroup('realgui/widget', src, depend = [''], CPPPATH = CPPPATH)

Return('objs')
