# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()
inc = [cwd]
src = Glob('*.c')

CPPDEFINES = []

if not GetDepend(['CONFIG_REALTEK_BUILD_AUDIO']):
    SrcRemove(src, ['gui_port_audio.c'])

objs = DefineGroup('rtk_gui', src, depend = [], CPPPATH = inc, CPPDEFINES = CPPDEFINES)
list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
