/* Generated by mkromfs. Edit with caution. */
#include "romfs/hg_romfs.h"

static const uint8_t _romfs_root_app_data_file_txt[] =
{
    0x41, 0x70, 0x70, 0x20, 0x64, 0x61, 0x74, 0x61, 0x0a
};

static const struct romfs_dirent _romfs_root_app_data[] =
{
    {ROMFS_DIRENT_FILE, "file.txt", (uint8_t *)_romfs_root_app_data_file_txt, sizeof(_romfs_root_app_data_file_txt) / sizeof(_romfs_root_app_data_file_txt[0])}
};

static const struct romfs_dirent _romfs_root_app[] =
{
    {ROMFS_DIRENT_DIR, "data", (uint8_t *)_romfs_root_app_data, sizeof(_romfs_root_app_data) / sizeof(_romfs_root_app_data[0])}
};

static const uint8_t _romfs_root_test_txt[] =
{
    0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x52, 0x4f, 0x4d, 0x46, 0x53, 0x0a
};

static const struct romfs_dirent _romfs_root[] =
{
    {ROMFS_DIRENT_DIR, "app", (uint8_t *)_romfs_root_app, sizeof(_romfs_root_app) / sizeof(_romfs_root_app[0])},
    {ROMFS_DIRENT_FILE, "test.txt", (uint8_t *)_romfs_root_test_txt, sizeof(_romfs_root_test_txt) / sizeof(_romfs_root_test_txt[0])}
};

const struct romfs_dirent hg_romfs_root =
{
    ROMFS_DIRENT_DIR, "/", (uint8_t *)_romfs_root, sizeof(_romfs_root) / sizeof(_romfs_root[0])
};
