# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
src   = Glob('*.c')
CPPPATH = [cwd]
list = os.listdir(cwd)

SrcRemove(src,'ctr_drbg.c')
SrcRemove(src,'ccm.c')
SrcRemove(src,'aes.c')
SrcRemove(src,'md5.c')
SrcRemove(src,'sha1.c')
SrcRemove(src,'sha256.c')

group = DefineGroup('tuya_ble_sdk', src, depend = ['TUYA_BLE_SDK'], CPPPATH = CPPPATH)

if GetDepend('TUYA_BLE_SDK'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))


Return('group')
