# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += Glob('./*.cpp') 


CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_hongkong']

CPPDEFINES = []
if GetDepend('CONFIG_REALTEK_BUILD_GUI_410_502_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_410_502_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=410']
    CPPDEFINES += ['DRV_LCD_HIGHT=502']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']
    
group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_410_502_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
