# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')

CPPPATH = [cwd]

objs = DefineGroup('realgui/3rd/Lite3D', src, depend = ['CONFIG_REALTEK_BUILD_LITE3D'], CPPPATH = CPPPATH)

Return('objs')
