# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
src += ['../Lite3D_port_gui.c']

CPPPATH = [cwd]

group = DefineGroup('realgui/3rd/Lite3D', src, depend = ['CONFIG_REALTEK_BUILD_LITE3D'], CPPPATH = CPPPATH)

Return('group')
