
SET(CMAKE_SYSTEM_NAME Generic)


SET(CMAKE_SYSTEM_PROCESSOR arm)


SET(CMAKE_C_COMPILER armcc)
SET(CMAKE_CXX_COMPILER armcc)

# Compiler flags for Cortex-M3 with ARMCC
set(CMAKE_C_FLAGS "--c99 -c --cpu Cortex-M3 --li -g -O2 --fpu=FPv5-SP --gnu --bss_threshold=0 --diag_suppress=177" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "--cpu Cortex-M3 -c --cpp --c++11" CACHE STRING "" FORCE)

# Linker flags (ARMCC uses different syntax)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} --no_startup --scatter=scatterfile.sct" CACHE STRING "" FORCE)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY) 
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_COMPILER_WORKS ON CACHE BOOL "")
set(CMAKE_CXX_COMPILER_WORKS ON CACHE BOOL "")
set(CMAKE_C_COMPILER_FORCED ON CACHE BOOL "")
set(CMAKE_CXX_COMPILER_FORCED ON CACHE BOOL "")

