#
# Copyright (c) 2026, Realtek Semiconductor Corporation
#
# SPDX-License-Identifier: MIT
#

set(CONFIG_REALTEK_HONEYGUI y)
# CONFIG_REALTEK_BUILD_LETTER_SHELL is not set
set(CONFIG_REALTEK_H264_DECODER y)
set(CONFIG_REALTEK_GUI_WIDGET_OBJ y)
set(CONFIG_REALTEK_GUI_WIDGET_IMG y)
set(CONFIG_REALTEK_GUI_WIDGET_WIN y)
set(CONFIG_REALTEK_GUI_WIDGET_TEXT y)
set(CONFIG_REALTEK_GUI_WIDGET_VIEW y)
set(CONFIG_REALTEK_GUI_WIDGET_CANVAS y)
set(CONFIG_REALTEK_GUI_WIDGET_GEOMETRY y)
set(CONFIG_REALTEK_GUI_WIDGET_LIST y)
set(CONFIG_REALTEK_GUI_WIDGET_SVG y)
set(CONFIG_REALTEK_GUI_WIDGET_GIF y)
set(CONFIG_REALTEK_GUI_WIDGET_GLASS y)
set(CONFIG_REALTEK_GUI_WIDGET_LOTTIE y)
set(CONFIG_REALTEK_GUI_WIDGET_VIDEO y)
set(CONFIG_REALTEK_GUI_WIDGET_LITE_VIDEO y)
set(CONFIG_REALTEK_GUI_WIDGET_STREAM y)
set(CONFIG_REALTEK_GUI_WIDGET_QBCODE y)
set(CONFIG_REALTEK_GUI_WIDGET_SOCCER y)
set(CONFIG_REALTEK_GUI_WIDGET_CARD_LIST y)
set(CONFIG_REALTEK_GUI_WIDGET_MENU_CELLULAR y)
