# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
list = os.listdir(cwd)
src = Split("""""")
CPPPATH = [cwd]

CPPDEFINES = ['ENABLE_RTK_GUI']

if GetDepend('BUILD_USING_RTK_GUI_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_DEMO']
if GetDepend('BUILD_USING_RTK_GUI_OS_HEAP'):
    CPPDEFINES += ['ENABLE_RTK_GUI_OS_HEAP']
if GetDepend('BUILD_USING_RTK_GUI_FONT_STB'):
    CPPDEFINES += ['ENABLE_RTK_GUI_FONT_STB']
if GetDepend('BUILD_USING_RTK_GUI_FONT_FREETYPE'):
    CPPDEFINES += ['ENABLE_RTK_GUI_FONT_FREETYPE']
if GetDepend('BUILD_USING_RTK_GUI_FONT_RTK_MEM'):
    CPPDEFINES += ['ENABLE_RTK_GUI_FONT_RTK_MEM']
if GetDepend('BUILD_USING_RTK_GUI_FONT_TTF_SVG'):
    CPPDEFINES += ['ENABLE_RTK_GUI_FONT_TTF_SVG']
if GetDepend('BUILD_USING_SCRIPT_AS_A_APP'):
    CPPDEFINES += ['ENABLE_RTK_GUI_SCRIPT_AS_A_APP']
if GetDepend('BUILD_USING_VG_LITE'):
    CPPDEFINES += ['RTK_MODULE_VG_LITE']
if GetDepend('BUILD_USING_RTK_PPE'):
    CPPDEFINES += ['RTK_MODULE_RTK_PPE']

group = DefineGroup('rtk_gui', src, depend = ['BUILD_USING_RTK_GUI'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('BUILD_USING_RTK_GUI'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            if not os.path.isfile(os.path.join(path, 'SConstruct')):
                group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
