# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
list = os.listdir(cwd)
src = Split("""""")
CPPPATH = [cwd]

CPPDEFINES = ['RTK_BUILD_USING_RTK_GUI']

group = DefineGroup('bt_app', src, depend = ['BUILD_USING_RTK_GUI'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('BUILD_USING_RTK_GUI'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            if not os.path.isfile(os.path.join(path, 'SConstruct')):
                group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
