# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
src = []
CPPPATH = [cwd]
libs = []
libpath = []
list = os.listdir(cwd)
CPPDEFINES = ['CUSTOMIZED_TUYA_BLE_CONFIG_FILE=<custom_tuya_ble_config.h>']
CPPDEFINES += ['RTK_TUYA_BLE_SDK']

group = DefineGroup('tuya_ble_sdk', src, depend = ['TUYA_BLE_SDK'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES, LIBS = libs, LIBPATH = libpath)

if GetDepend('TUYA_BLE_SDK'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
