Import('TOOL_ROOT')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

src += ['drv_dlps.c']
src += ['drv_flash.c']
src += ['drv_rtc.c']

CPPDEFINES = ['BSP_HAL_DRIVER']

if GetDepend(['BSP_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['BSP_USING_UART']):
    src += ['drv_uart.c']

if GetDepend('BSP_USING_I2C1') or GetDepend('BSP_USING_I2C2') or GetDepend('BSP_USING_I2C3') or GetDepend('BSP_USING_I2C4'):
        src += ['drv_i2c.c']

if GetDepend(['RT_USING_ADC']):
    src += Glob('drv_adc.c')

if GetDepend(['RT_USING_DAC']):
    src += Glob('drv_dac.c')

if GetDepend('BSP_USING_LCD'):
    src += ['drv_lcd.c']
    CPPDEFINES += ['BSP_USING_LCD']

if GetDepend('MODULE_VG_LITE'):
    src += ['drv_gpu.c']

if GetDepend(['BSP_USING_SDIO']):
    src += ['drv_sdio.c']

if GetDepend(['BSP_USING_USBD']):
    src += ['drv_usbd.c']

if GetDepend(['BSP_USING_USBH']):
    src += ['drv_usbh.c']
	
if GetDepend(['BSP_USING_TOUCH']):
    src += ['drv_touch.c']
    src += ['drv_gpio.c']
    CPPDEFINES += ['BSP_USING_TOUCH']

path =  [cwd]


group = DefineGroup('hal_drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
