
from building import *

cwd = GetCurrentDir()

src = Glob('*.c')

CPPPATH = [cwd]


group = DefineGroup('realgui/minimp3', src, depend = ['CONFIG_REALTEK_HONEYGUI'], CPPPATH = CPPPATH)

Return('group')
