# for module compiling
import os
Import('TOOL_ROOT')
Import('WEARABLE_ROOT')

from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

CPPDEFINES = ['LV_KCONFIG_IGNORE']
CPPDEFINES += ['LV_LVGL_H_INCLUDE_SIMPLE']



src = ['main.c']
src += ['sdl_init.c']

objs = DefineGroup('rtk_gui', src, depend = ['MODULE_USING_PORT_FOR_LVGL'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)


list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
