# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]
print(CPPPATH)
group = DefineGroup('gui_demo', src, depend = ['BUILD_USING_RTK_GUI_320_385_DEMO'], CPPPATH = CPPPATH)

Return('group')
