# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]
print(CPPPATH)

CPPDEFINES = []

if GetDepend('CONFIG_REALTEK_BUILD_GUI_240_320_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_240_320_BEE3DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=240']
    CPPDEFINES += ['DRV_LCD_HIGHT=320']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_240_320_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
