# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")
inc = []

if GetDepend('CONFIG_REALTEK_BUILD_LITE3D'):
    src += Glob('*.c')
    inc = [cwd]


objs = DefineGroup('realgui/widget', src, depend = ['CONFIG_REALTEK_BUILD_LITE3D'], CPPPATH = inc)

Return('objs')
