# building script for HoneyGUI

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPDEFINES = []
CPPPATH = [cwd]
CPPPATH += [cwd + '\\root_image_800_480']

if GetDepend('CONFIG_REALTEK_BUILD_GUI_800_480_DEMO'):
    CPPDEFINES += ['ENABLE_RTK_GUI_800_480_DEMO']
    CPPDEFINES += ['DRV_LCD_WIDTH=800']
    CPPDEFINES += ['DRV_LCD_HIGHT=480']
    CPPDEFINES += ['DRV_PIXEL_BITS=16']

group = DefineGroup('realgui/demo', src, depend = ['CONFIG_REALTEK_BUILD_GUI_800_480_DEMO'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')
