# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_BUILD_SCRIPT_AS_A_APP']):
    src += Glob('./*.c')
    src += Glob('./js_ui/*.c')

CPPPATH = [cwd]

group = DefineGroup('rtk_gui', src, depend = ['CONFIG_REALTEK_BUILD_GUI'], CPPPATH = CPPPATH)

Return('group')
