# for module compiling
import os
from building import *


objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

src = Split("""""")
src += Glob(cwd + '/*.c')

path = [cwd]

objs = DefineGroup('realgui/3rd/Arm2d', src, depend = [], CPPPATH = path)


Return('objs')
