# for module compiling
import os
import sys

from building import *

cwd = GetCurrentDir()

inc = [cwd]
inc += [os.path.join(cwd, 'Library/Include')]
inc += [os.path.join(cwd, 'platform')]
inc += [os.path.join(cwd, 'platform/math')]

src = Glob('*.c')
src += Glob('*.cpp')
src += Glob('Library/Source/*.c')
src += Glob('platform/math/*.c')


if GetDepend(['CONFIG_REALTEK_BUILD_GUI_USE_ARM2D']):
    objs = DefineGroup('3rd', src, depend = [''], CPPPATH = inc)
    list = os.listdir(cwd)
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
else:
    objs = []

Return('objs')
