# for module compiling
import os
Import('PLATFORM')
from building import *


objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

src = Split("""""")
src += Glob(cwd + '/*.c')

path = [cwd]

objs = DefineGroup('realgui/3rd/Arm2d', src, depend = [], CPPPATH = path)


for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
